### ISSUE TITLE
conda package always requires importlib-metadata but setup.py seems to indicate its only needed for py37

### ISSUE THREAD

**Issue by ErikRtvl** [zauberzeug/nicegui#1002]
### Description

First of all, the NiceGUI package seems really nice so we want to give it a try!

But: I am trying to install the conda-forge package for NiceGUI and it fails (in my/our environment) on the importlib-metadata dependency. If I look at the requirements in pyproject.toml, it seems the importlib-metadata package is only required for NiceGUI when the python version is 3.7, am I correct?

However, as the conda package requires python>=3.8, I seems that the importlib-metadata requirement is obsolete anyway. Can it be removed? Of course, I may be missing something.

I guess that the idea "the less dependencies, the better" does apply in this case as it makes installation easier for users. In our case, we have an organisation-wide list of packages&versions that we build software/tools upon so that others can rely on the tools working for their environment. It just so happens that the importlib-metadata requirement is running behind a bit because of some other package that requires a relatively old version....

Thanks for checking this issue and the great work on NiceGUI!

**Comment by rodja** [comment]
Thanks for spotting this. I've updated the requirements in the [nicegui-feedstock](https://github.com/conda-forge/nicegui-feedstock/blob/main/recipe/meta.yaml) and the fix will be available with the next release 1.2.18.
