### ISSUE TITLE
How to use the hover effect in Tailwind CSS

### ISSUE THREAD

**Issue by CrystalWindSnake** [zauberzeug/nicegui#1008]
### Description

I want to set a hover effect in a row, but there is no effect at all in the end. Is it that `nicegui`'s `Tailwind CSS` cannot use hover? If it's regular css, how should I set it up?

```python
from nicegui import ui,Tailwind

styles = Tailwind().width('10').height('10').border_width('4').border_style('solid').border_color('blue-400')
row = ui.row().classes('hover:bg-red').tailwind(styles)

ui.run()
```

**Comment by falkoschindler** [comment]
Hi @CrystalWindSnake!
The problem is that "bg-red" is a Quasar class and not Tailwind. But the "hover:" prefix only works with Tailwind classes.
Using "hover:" in combination with a [Tailwind color](https://tailwindcss.com/docs/background-color) like `classes('hover:bg-red-400')` works as expected.

**Comment by CrystalWindSnake** [comment]
> Hi @CrystalWindSnake! The problem is that "bg-red" is a Quasar class and not Tailwind. But the "hover:" prefix only works with Tailwind classes. Using "hover:" in combination with a [Tailwind color](https://tailwindcss.com/docs/background-color) like `classes('hover:bg-red-400')` works as expected.

my problem has been resolved, thank you for your reply.
