### ISSUE TITLE
menu_and_tabs example outdated

### ISSUE THREAD

**Issue by xec-abailey** [zauberzeug/nicegui#1013]
@falkoschindler Sorry, pasted the wrong link. Should be https://github.com/zauberzeug/nicegui/blob/main/examples/menu_and_tabs/main.py 

I will fix my https://github.com/zauberzeug/nicegui/issues/251#issuecomment-1540306075

_Originally posted by @rafo in https://github.com/zauberzeug/nicegui/issues/251#issuecomment-1540464986_

Per above, menu and tabs panel example is outdated and thus confusing when comparing to documentation that uses the QTabPanels implementation.

**Comment by falkoschindler** [comment]
Thanks for fixing this outdated example, @xec-abailey!
I reviewed and merged it into main.
