### ISSUE TITLE
mermaid element shows syntax error when updated content begins with a line break

### ISSUE THREAD

**Issue by jsharer** [zauberzeug/nicegui#1031]
### Description

I am creating an interactive mermaid diagram editor. I use a single mermaid element, and update its content from the value in a textarea element on the same page. For some chart types, the mermaid.min.js component treats leading line breaks as a syntax error. These chart types include:

- gantt
- classDiagram
- journey
- c4

nicegui already attempts to overcome this problem, but the attempt only works when first constructing the mermaid element.

### Expected Behavior
The mermaid element should prevent syntax errors associated with leading line breaks when the element is updated.

### Actual Behavior
The mermaid element allows syntax errors associated with leading line breaks when the element is updated.

### Analysis
This is from mermaid.py; comments are mine.
```py
    def on_content_change(self, content: str) -> None:
        self._props[self.CONTENT_PROP] = content.strip() # line breaks removed from content saved as content property
        self.run_method('update', content) # original content passed to component's update method; ignored on initial load
```
This is from mermaid.js; comments are mine.
```js
export default {
  template: `<div></div>`,
  mounted() {
    this.update(this.content); // initial load; line breaks previously removed from content
  },
  methods: {
    update(content) {  // line breaks may not have been removed
      mermaid.render("mermaid" + this.$el.id, content, (svg) => (this.$el.innerHTML = svg));
    },
  },
  props: {
    content: String,
  },
};

```

File demonstrating the issue is attached.
[main_mermaid.py.txt](https://github.com/zauberzeug/nicegui/files/11750884/main_mermaid.py.txt)

**Comment by falkoschindler** [comment]
As you precisely analyzed, we should call `run_method('update', ...)` with the stripped content.
Commit [2ab9d68](https://github.com/zauberzeug/nicegui/commit/2ab9d68c926464b47fc255efcb755768410b730a) should fix this bug. 🙂
Thanks again for your contribution, @jsharer!
