### ISSUE TITLE
ui.button 'icon' keyword argument is considered unexpected

### ISSUE THREAD

**Issue by Mayorc1978** [zauberzeug/nicegui#1034]
### Description

I'm just testing the examples, and this is the second time I face this error, and it doesn't make any sense.

```python
with ui.page_sticky(position='bottom-right', x_offset=20, y_offset=20):
    ui.button(on_click=footer.toggle, icon='contact_support').props('fab')
```
Gives me this error:
```
Traceback (most recent call last):
  File "H:\AI\nicegui\examples\menu_and_tabs\main.py", line 18, in <module>
    ui.button(on_click=footer.toggle, icon='contact_support').props('fab')
TypeError: Button.__init__() got an unexpected keyword argument 'icon'
```
The error makes no sense cause if I ctrl+click in VSCODE I get to:

```python
class Button(TextElement, DisableableElement, BackgroundColorElement):

    def __init__(self,
                 text: str = '', *,
                 on_click: Optional[Callable[..., Any]] = None,
                 color: Optional[str] = 'primary',
                 icon: Optional[str] = None,
                 ) -> None:
```
And **icon** is a possible keyword argument, so why does it gives me an error. It doesn't make sense.
So I tried using **color** keyword argument and gives me no error. So only **icon** is problematic, but I don't have any explanation.

For the moment I removed it in my test to bypass the issue and don't get any error, and to achieve same result i added the icon to the props call writing : `ui.button(on_click=footer.toggle).props('fab icon=contact_support')`

Do you have any idea what are the reasons for this strange behavior?

**Comment by falkoschindler** [comment]
Hi @Mayorc1978!
It looks like VSCode uses a different Python version for code analysis than what is used for running the app.
Can you make sure you're using the latest version 1.2.20?

```py
from nicegui import __version__
print(__version__)
```

**Comment by Mayorc1978** [comment]
> ```python
> print(__version__)
> ```

```
from nicegui import __version__
print(__version__)
1.2.20
```
This is the output while running it through debug console inside VSCODE.
I get the same result if I do it in the powershell:
```
(NiceGui_py3_10)  Jinxius   menu_and_tabs   main ≡  +4 ~3    python
Python 3.10.11 | packaged by Anaconda, Inc. | (main, May 16 2023, 00:55:32) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from nicegui import __version__
>>> print(__version__)
1.2.20
```
```
File "H:\AI\nicegui\examples\menu_and_tabs\main.py", line 18, in <module>
    ui.button(on_click=footer.toggle, icon='contact_support').props('fab')
TypeError: Button.__init__() got an unexpected keyword argument 'icon'
```

**Comment by rodja** [comment]
@Mayorc1978 that looks super strange. Have you installed with pip or conda? With conda-forge there where some build issues which prevented proper releasing the last few versions. With the yesterday released 1.2.21 these issues should be fixed. Could you remove/reinstall the latest version an try again?

**Comment by Mayorc1978** [comment]
> 
Installed 1.2.20 with pip.

I will try the new version asap.

**Comment by falkoschindler** [comment]
I'll close this card for now. But feel free to re-open it in case you have new information.
