### ISSUE TITLE
Shift + Alphabet letter seems to be problematic when using keyboard handler

### ISSUE THREAD

**Issue by Mayorc1978** [zauberzeug/nicegui#1051]
### Description

When using keyboard handler:
```python
async def handle_key(e: KeyEventArguments):
    if e.modifiers.ctrl and e.action.keydown:
        if e.key == "v":
            pil_image = ImageGrab.grabclipboard() # This works fine
    elif e.modifiers.shift and e.action.keydown:
        if e.key == "v":
            pil_image = ImageGrab.grabclipboard() # Can't break on this

```

Also tried with this version too:
```python
async def handle_key(e: KeyEventArguments):
    if e.key == "v" and e.action.keyup:
        print(e.modifiers)
        if e.modifiers.ctrl:
            print("Control+V was pressed") # Breaks on this!
	elif e.modifiers.shift:
            print("Shift+V was pressed") # Doesn't break on this!
```

Results of print(e.modifiers):
1st Time (with ctrl):
KeyboardModifiers(alt=False, ctrl=True, meta=False, shift=False)

2nd Time (with shift):
Nothing printed!!

Minimal buggy test code:

```python
from nicegui import app, ui
from nicegui.events import KeyEventArguments

async def handle_key(e: KeyEventArguments):
    if e.key == "v" and e.action.keyup:
        print(e.modifiers)
        if e.modifiers.ctrl:
            print("Control+V was pressed") # Breaks on this!
        elif e.modifiers.shift:
            print("Shift+V was pressed") # Doesn't break on this!
    if e.key.arrow_right and e.action.keyup:
        if e.modifiers.shift:
            print("Shift+Right Arrow was pressed") # Breaks on this! Maybe special case cause not a "letter".
            
keyboard = ui.keyboard(active=True, on_key=handle_key)

ui.run(favicon='🚀',title = "Test keyboard", native=True, window_size=(800, 600), fullscreen=False)

```
I've tested with other combinations of "letter" keys + shift and they don't work.
Ctrl+Shift+letter combination doesn't work either and it doesnt even break in the first case like if just "Control+V was pressed".
So it's like Shift key is messing things up.

Edit: "**Alt**" modifier instead works without any problem.
At this point I don't know if this was the intended behaviour, but the only explanation for this is **Shift** is considered a modifier only for keys that are not alphabet letters, and so to catch a Shift+V key i should check the key like this:
`if e.key == "V"`

**Comment by falkoschindler** [comment]
Hi @Mayorc1978!
I think what you're describing is intended behavior. We basically forward the JavaScript key name as it is sent from the client. The shift key transforms letters like "a" into uppercase letters like "A" and numbers like "1" into symbols like "!" (depending on the keyboard layout, of course). [Here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key#result) you can experiment with JavaScript key events.

**Comment by Mayorc1978** [comment]
Thanks. I'm closing this, then.
