### ISSUE TITLE
After modifying the options for radio, the interface does not update correctly

### ISSUE THREAD

**Issue by CrystalWindSnake** [zauberzeug/nicegui#1073]
### Description

```python
r = ui.radio([10, 20, 30], value=10)


def onclick():
    print(r.value) # is right,eq 10
    r.options = [30, 20, 10]
    r.update()
    print(r.value) # is right,eq 10


ui.button("change", on_click=onclick)
```
after clicking the button, option 30 was selected on the interface. This is not expected as option 10 should still be selected.

**Comment by falkoschindler** [comment]
Thanks for spotting this, @CrystalWindSnake!
Because NiceGUI's choice elements use an index internally, the value changes to whatever new option has the same index. We should probably update the index to the option with the same value.

**Comment by CrystalWindSnake** [comment]
> Thanks for spotting this, @CrystalWindSnake! Because NiceGUI's choice elements use an index internally, the value changes to whatever new option has the same index. We should probably update the index to the option with the same value.

It's possible that other similar components may also have this issue, such as `Toggle`.

**Comment by falkoschindler** [comment]
Ok, commit [50bec3a](https://github.com/zauberzeug/nicegui/commit/50bec3a1d37a5773ab9301d421889633647cb5ea) should fix this issue for `ui.radio`, `ui.select` and `ui.toggle`. 🙂

**Comment by CrystalWindSnake** [comment]
very nice！！！！🙂
