### ISSUE TITLE
How to achieve the lazy input effect in q-slider?

### ISSUE THREAD

**Issue by CrystalWindSnake** [zauberzeug/nicegui#1074]
### Description

I hope to achieve the lazy output effect in slider, just like the effect on the official website of Quasar. How can I do it? I hope to get some help. Thank you.

This is the link to the quasar official website.
[slider lazy-input](https://quasar.dev/vue-components/slider#lazy-input)

**Comment by falkoschindler** [comment]
That would be a great feature, @CrystalWindSnake!
I couldn't find a quick solution, yet. But maybe - as a workaround - you can make use of the `change` event which is fired whenever the slider is released?

**Comment by CrystalWindSnake** [comment]
> That would be a great feature, @CrystalWindSnake! I couldn't find a quick solution, yet. But maybe - as a workaround - you can make use of the `change` event which is fired whenever the slider is released?

Thank you for the solution you provided, which can solve my problem.
