### ISSUE TITLE
Slack Notification GitHub Action Failing Due to Missing Webhook URL

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#1084]
### Discussed in https://github.com/zauberzeug/nicegui/discussions/1068

<div type='discussions-op-text'>

<sup>Originally posted by **michangelis** June 24, 2023</sup>
### Question

Hello,

I encountered an issue while contributing to the repository. It seems the GitHub action Gamesight/slack-workflow-status@master is failing due to a missing Slack webhook URL.

Here is the error message I received:

```
Error: Error: Input required and not supplied: slack_webhook_url
Error: Input required and not supplied: slack_webhook_url
```

As an external contributor, I do not have the necessary permissions to add the SLACK_WEBHOOK_URL secret to the repository's settings. The secret appears to be necessary for the GitHub action to send notifications to Slack.

Could you please look into this issue? I believe that adding the SLACK_WEBHOOK_URL secret to the repository's settings should resolve it.

Please let me know if there's anything else I can provide to assist in resolving this.

</div>

**Comment by rodja** [comment]
Can we maybe only run the Slack step if the SLACK_WEBHOOK_URL is defined?

**Comment by michangelis** [comment]
yes that was my original thought and i tried updating the test.yml file to handle the case where the Slack webhook secret is not defined like this 
`slack:
    needs:
      - test
    if: always() # also execute when test fails
    runs-on: ubuntu-latest
    steps:
      - name: Determine if we need to notify
        uses: Jimdo/should-i-notify-action@main
        id: should_notify
        with:
          needs_context: ${{ toJson(needs) }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check if secret exists
        id: check_secret
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_ROBOTICS_CI_WEBHOOK }}
        run: |
          if [[ -z "$SLACK_WEBHOOK" ]]; then
            echo "slack_webhook_exists=false" >> $GITHUB_ENV
          else
            echo "slack_webhook_exists=true" >> $GITHUB_ENV
          fi
      - name: Slack workflow notification
        if: steps.should_notify.outputs.should_send_message == 'yes' && env.slack_webhook_exists == 'true'
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK_ROBOTICS_CI_WEBHOOK }}
          channel: "robotik-ci"
          name: "NiceGUI"`

**Comment by falkoschindler** [comment]
@rodja The code changes from @michangelis' comment https://github.com/zauberzeug/nicegui/issues/1084#issuecomment-1607318047 are part of his PR #1087.

**Comment by rodja** [comment]
@michangelis can you create a separate pull request for the slack fix? That way your contribution will be tracked in the repo and we can discuss the carousel from #1087 distinced from this.

**Comment by michangelis** [comment]
sure thing

**Comment by michangelis** [comment]
@rodja i opened a new PL as you recommended addressing the specific issue so it can be tracked in the repo. Here is the link https://github.com/zauberzeug/nicegui/pull/1105

**Comment by rodja** [comment]
Wonderful. I just merged your code. Thanks for contributing!
