### ISSUE TITLE
clearing value of ui.input() does not work on 2nd try

### ISSUE THREAD

**Issue by eshyun** [zauberzeug/nicegui#1088]
### Description

Code to reproduce:
```python
from nicegui import ui

prompt = ui.input().on('keypress.enter', lambda: prompt.set_value(None))

ui.run(port=8889)
``` 
1. Enter some text and just press 'Enter' key, then the value of prompt element will be delete on the first try
2. Enter any text again and press 'Enter' key again to find that nothing happens, leaving the input value intact.

Alternatively, the official demo at [Input Styling](https://nicegui.io/documentation/input#styling) can be used to reproduce the issue. Just click 'delete' icon more than twice from the 3rd example.

This issue is new in version 1.2.22. Everything is okay in version 1.2.21 and older.

**Comment by falkoschindler** [comment]
Thanks for reporting this bug, @eshyun!
Luckily, there's already a fix (see https://github.com/zauberzeug/nicegui/issues/1071) that will be released with version 1.2.23 shortly. 🙂

**Comment by falkoschindler** [comment]
@eshyun, by the way: I love your short and precise bug report! That's a great starting point for further investigating the problem.

And another thought about your key event: "keypress" is [depricated](https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event). So you better use "keydown" or "keyup".

**Comment by eshyun** [comment]
@falkoschindler , thanks for fixing the bug so quickly.

Regarding the deprecation of `keypress`, I've tried to work around a issue with keydown/keyup event. In CJK IME, especially Korean, keydown event does not properly handle the last composing character, and thus, when I press Enter key it triggers keydown event twice. Alt sequence might be the similar issue in the western world. This is not the case with keypress event. One workaround is to use isComing flag along with keydown event, however, it's a lot more complicated.
Thanks for bringing this up anyway. I honestly didn't know that it's been deprecated as I'm not from frontend world.

**Comment by tjongsma** [comment]
@falkoschindler, I'm currently having the exact same problem with ui.editor. editor.set_value(None) works once and then after that not anymore. Any suggestions for this one?

**Comment by falkoschindler** [comment]
Thanks for letting us know, @tjongsma!
I created issue #3217 for tracking this bug.
