### ISSUE TITLE
element.run_method('focus') not working

### ISSUE THREAD

**Issue by CatamountJack** [zauberzeug/nicegui#1092]
### Description

Calling `.run_method('focus')` on an element stopped working with v1.2.22; worked fine with 1.2.21.

Example:

```python
from nicegui import ui

button = ui.button(on_click=lambda: input1.run_method('focus'))
input1 = ui.input().on('keydown.enter', lambda: input2.run_method('focus'))
input2 = ui.input().on('keydown.enter', lambda: input1.run_method('focus'))

ui.run()
```

In the example when you press a button, the focus should move to the first input and when you press Enter on either of the input fields the focus should change to the other.  (I don't know whether it's specific to `'focus'` or an issue with `.run_method()` itself, I did not try on other potential methods.)

**Comment by cj** [comment]
I just ran into this same issue.

**Comment by cj** [comment]
In the browser, the error points to this line https://github.com/zauberzeug/nicegui/blob/main/nicegui/templates/index.html#L181, saying the method does not exist.

**Comment by rodja** [comment]
I created pull request #1093 to tackle the issue. Currently there is only a unit test to reproduce the error. I can verify the test runs fine with 1.2.21. @falkoschindler can you have a look at this and extend the PR?

**Comment by cj** [comment]
@rodja thank you for fixing that! Question, `await ui.run_javascript(f"getElement({element.id}).getNativeElement()")` still does not work. Should I open a new ticket for that, or is there a new way to update the server?

**Comment by cj** [comment]
This is what was returned with `getElement` on an input for version `1.2.21`:
<img width="484" alt="image" src="https://github.com/zauberzeug/nicegui/assets/1819/347de27f-af3a-461d-af71-4b61cacf6508">

**Comment by cj** [comment]
It looks like this did the trick:

```python
        await ui.run_javascript(
            f"""
            const e = getElement({element.id})
            return new Promise((resolve) => {{
                e.$nextTick(() => resolve('done'))
                e.$emit("update:value", e._.data.inputValue)
            }});
            """,
        )
```
