### ISSUE TITLE
refresh function of the refreshable cannot accept parameters

### ISSUE THREAD

**Issue by CrystalWindSnake** [zauberzeug/nicegui#1096]
### Description

in many cases, we need to pass data while refreshing a container. If variables are always defined globally, the code becomes difficult to maintain.

```python
from nicegui import ui

def onclick():
    # 显示表格
    box.refresh(1)

ui.button("加载excel", on_click=onclick)

@ui.refreshable
def box(num=0):
    if num > 0:
        ui.label(f"num is :{num}")

box()

ui.run()
```

error:
```shell
    box.refresh(1)
TypeError: refreshable.refresh() takes 1 positional argument but 2 were given
```

**Comment by falkoschindler** [comment]
That's a good idea, @CrystalWindSnake!
I experimented with `ui.refreshable` on the [refresh-with-args branch](https://github.com/zauberzeug/nicegui/tree/refresh-with-args). But the pytests are still failing, because there is a problem with our event handlers:
```py
@ui.refreshable
def time_ui():
    ui.label(time.time())

time_ui()
ui.button('Refresh', on_click=time_ui.refresh)
```
Now that `time_ui.refresh` accepts arguments, the click handler passes `ClickEventArguments` to `refresh`, which uses them to call `time_ui`. But `time_ui` itself doesn't accept arguments. So I'll have to dig a bit deeper.

**Comment by falkoschindler** [comment]
Idea: Let `RefreshableTarget.run` check if `args[0]` is of type `EventArguments`. If so, only pass it to `func` if the function expects a positional argument of type `EventArguments`.

**Comment by falkoschindler** [comment]
I think I found a rather elegant solution:

1. By allowing only keyword arguments in `refreshable.refresh` the implementation gets extremely simple and transparent. The provided arguments simply update the `target.kwargs`. I don't think there is a need for positional arguments here.

2. By checking the parameter `kind` in events.py, we can ignore `args` or `kwargs` parameters of the event `handler`, which are usually not expected to be filled with event arguments.

These to changes allow to use keyword arguments for `refreshable.refresh` very flexibly:

```py
@ui.refreshable
def some_ui(*, number: int):
    with ui.card():
        ui.label(f'{number=}')
        ui.label(time.time())

some_ui(number=0)
n = ui.number()
ui.button('Refresh', on_click=lambda: some_ui.refresh(number=n.value))
ui.button('Refresh', on_click=lambda: some_ui.refresh())
ui.button('Refresh', on_click=some_ui.refresh)
```

**Comment by falkoschindler** [comment]
I just removed the restriction to keyword arguments only. This felt awkward when writing the documentation.
If you pass `args`, they replace `target.args`.
If you pass `kwargs`, they update `target.kwargs`.

**Comment by rodja** [comment]
Wonderful!!!

**Comment by CrystalWindSnake** [comment]
Excellent!!!
