### ISSUE TITLE
DOM Placement of Header, Footer, & Drawer Elements

### ISSUE THREAD

**Issue by ProbablyBrian** [zauberzeug/nicegui#1097]
### Description

When using the ui.header, ui.left_drawer, or ui.right_drawer elements, they are placed at the end of the DOM.  For users utilizing a screen reader, this places these elements in unexpected, unusual places in the page.  Minimum example:

```python
from nicegui import ui

with ui.header():
    ui.label("This is in the header.")
with ui.left_drawer():
    ui.label("This is in the left drawer.")
with ui.right_drawer():
    ui.label("This is in the right drawer.")
with ui.footer():
    ui.label("This is in the footer")

ui.label("This is presumed to be in the body.")

ui.run()
```

On the resulting page, the main content is followed by the header, left drawer, right drawer, and then footer.  From the perspective of a screen reader, the flow of content they experience is different from that of visually scanning the page from top to bottom.  Ideally, it would go header > left drawer > main content > right drawer > footer.

Fixing this is pretty simple, however I wonder if something more permanent can be done in these elements directly so that the layout for screen reader users is correct by default.  Minimal working solution in the above example:

```python
from nicegui import ui

with ui.header() as header:
    header.move(target_container=None, target_index=0)
    ui.label("This is in the header.")
with ui.left_drawer() as left_drawer:
    left_drawer.move(target_container=None, target_index=1)
    ui.label("This is in the left drawer.")
with ui.right_drawer():
    ui.label("This is in the right drawer.")
with ui.footer():
    ui.label("This is in the footer")

ui.label("This is presumed to be in the body.")

ui.run()
```

This ensures both that the header content is encountered first and that the main content is between the left drawer and right drawer in the DOM which is where it visually resides.  Header > left drawer > main content > right drawer > footer.

For thoroughness, it doesn't matter what order the header, footer, drawers, and other content are defined in the script, they always have the main -> header -> right drawer -> footer order by default.

**Comment by ProbablyBrian** [comment]
I think that the default configuration should be accessible, though I'm unsure if I want to remove freedom of choice from the developer by enforcement.  In that spirit, perhaps a "sticky" keyword argument determines whether to enforce the positioning in the DOM for these elements or not.  Set to True by default, it'd provide guardrails against accidental degradation of accessible design but still be a discoverable, documented override for developers who know they need that flexibility.

**Comment by falkoschindler** [comment]
Ok, we decided to place the elements as you suggested (header, left, content, right, footer) by default, without adding another parameter. The case that a developer wants to change the order will be rare. And if so, he/she can use the `.move()` method. We will add a note about the unusual DOM placement in the documentation of `ui.header` and `ui.left_drawer`.

**Comment by ProbablyBrian** [comment]
I think that's a solid approach. I agree manual modification is rare for these elements since they render properly on the page regardless of their DOM positioning. Glad to see this change!

**Comment by falkoschindler** [comment]
Commit [02cf959](https://github.com/zauberzeug/nicegui/commit/02cf959945404e247749994cc4b98ae213fd3acf) should solve this issue.
In order to get the desired order independent of the order of creation, I move
- the header to index 0,
- the left drawer to the index of the main page container,
- the right drawer to the index of the main page container + 1, and
- the footer to index -1, i.e. all the way to the end.
