### ISSUE TITLE
Provide sophisticated page structures through QLayout etc.

### ISSUE THREAD

**Issue by rodja** [zauberzeug/nicegui#110]
@hroemer showed in #101 how a possible integration of [Quasar Layouts](https://v1.quasar.dev/layout/layout#introduction) could be done. In this issue we want to explore the nicest possible NiceGUI API.

**Comment by rodja** [comment]
Fixed with #128

**Comment by abulka** [comment]
Looks like the parameters etc. in the above example have since been changed. See current doco https://nicegui.io/documentation#page_layout 

P.S. Hoping for a [splitter](https://quasar.dev/vue-components/splitter) component one day - that would really up the game in terms of sophistication. Especially being able to do multiple splitters etc.

**Comment by rodja** [comment]
@abulka thanks for the update! Implementing the `q-splitter` should be fairly easy. Would you like to be a contributor? We will help you on your way to create this pull-request.

**Comment by abulka** [comment]
I'm just a few days into NiceGui and Quasar but getting the hang of things. I've build the Quasar spltter demo in javascript and its quite a smooth component. I've cloned the nicegui repo and run the tests, which all pass on my Mac M1 except `tests/test_scene.py FFF`.

How would I start with this feature - I looked at an existing component e.g. `expansion` and there is a short test, and a startlingly short implementation `nicegui/elements/expansion.py`.

**Comment by rodja** [comment]
Congratulations @abulka. That's awesome. Your approach is exactly right. I just added more detailed instructions on how to add new elements to our [CONTRIBUTING.md](https://github.com/zauberzeug/nicegui/blob/main/CONTRIBUTING.md#new-elements).

**Comment by abulka** [comment]
Thanks for the instructions - that's useful.

Understanding how NiceGUI and Quasar slots work (and relate to each other) seems fundamental to implementing any new component, and what I'm currently figuring out.  In the absence of an existing thread on implementing Splitter, I'm thinking out loud in a thread on the NiceGUI discord: https://discord.com/channels/1089836369431498784/1090826214270324818/1090868038234013726
