### ISSUE TITLE
button click event includes multiple threading.Thread will report "RuntimeError: no running event loop" if calls ui.x function in the subthread

### ISSUE THREAD

**Issue by ads262743698** [zauberzeug/nicegui#1107]
### Description

I am trying to develop a autotest platfrom, when someone clicks the start_button, will run the self.run_test_seq function.
```py
start_button = ui.button('开始测试',
                                        on_click=lambda cur_button=station, station_name=station: 
                                        self.run_test_seq(cur_button, '{}'.format(station_name))).style('font-size:150%').props('color=black')
```

The self.run_test_seq function includes 2 Threads, thread1 is update_button, thread2 is run_seq(long time function).
```py
            t1 = thread_with_trace(target=self.update_button, kwargs={'button': cur_button.sender,
                                                                                                            'button_text': '停止测试',})
            t1.start()
            self.thread_list.append(t1)
            t2 = thread_with_trace(target=self.run_seq, kwargs={'station_name': station_name,
                                                                                                 'cur_button': cur_button,})
            t2.start()
```

If calls ui.dialog() or other ui.x function in subthread(thread1 or thread2), it reports "RuntimeError: no running event loop".
```py
def run_seq(self, station_name, cur_button):
        task = asyncio.current_task()
        log.info('3 task - {}'.format(task))
        with ui.dialog() as dialog, ui.card():
            ui.label('debug').classes('text-center')
            ui.button('关闭', on_click=lambda: dialog.close()).style('width:100%')

        async def show():
            log.info('kozhu debug...')
            result = await dialog
            log.info('result - {}'.format(result))

        log.info('kozhu debug 1')
        asyncio.ensure_future(show())

        self.tc.log_box = self.station_log_box[station_name]
```

Here is the full log.
```
Exception in thread Thread-2 (run_seq):
Traceback (most recent call last):
  File "C:\Users\zhudeqiang\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "D:\kozhu\product_tool\framework\framework.py", line 49, in __run
    self.__run_backup()
  File "C:\Users\zhudeqiang\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "D:\kozhu\product_tool\framework\framework.py", line 401, in run_seq
    task = asyncio.current_task()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zhudeqiang\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 38, in current_task
    loop = events.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
```

**Comment by rodja** [comment]
Generally, it's not recommended to manually manage threads in an asynchronous application unless you understand the implications. NiceGUI (and the underlying FastAPI) are async frameworks where io-bound or cpu-bound tasks should be "awaited". See https://fastapi.tiangolo.com/async/ for a good in-depth explanation.
There are also some in-depth examples like [ffmepg](https://github.com/zauberzeug/nicegui/blob/main/examples/ffmpeg_extract_images/main.py), [opencv webcam](https://github.com/zauberzeug/nicegui/blob/main/examples/opencv_webcam/main.py), [progress](https://github.com/zauberzeug/nicegui/blob/main/examples/progress/main.py) and the [script executor](https://github.com/zauberzeug/nicegui/blob/main/examples/script_executor/main.py) which could be helpful for you in finding an alternative to your currently used threading.

**Comment by ads262743698** [comment]
> Generally, it's not recommended to manually manage threads in an asynchronous application unless you understand the implications. NiceGUI (and the underlying FastAPI) are async frameworks where io-bound or cpu-bound tasks should be "awaited". See https://fastapi.tiangolo.com/async/ for a good in-depth explanation. There are also some in-depth examples like [ffmepg](https://github.com/zauberzeug/nicegui/blob/main/examples/ffmpeg_extract_images/main.py), [opencv webcam](https://github.com/zauberzeug/nicegui/blob/main/examples/opencv_webcam/main.py), [progress](https://github.com/zauberzeug/nicegui/blob/main/examples/progress/main.py) and the [script executor](https://github.com/zauberzeug/nicegui/blob/main/examples/script_executor/main.py) which could be helpful for you in finding an alternative to your currently used threading.

Thanks Rodja, I am using await to fix this requirement.
await asyncio.get_running_loop().run_in_executor(None, self.update_start_btn, start_btn, '停止测试', 'orange')
await asyncio.get_running_loop().run_in_executor(None, self.run_steps, log_box, steps, start_btn)

**Comment by ads262743698** [comment]
> Generally, it's not recommended to manually manage threads in an asynchronous application unless you understand the implications. NiceGUI (and the underlying FastAPI) are async frameworks where io-bound or cpu-bound tasks should be "awaited". See https://fastapi.tiangolo.com/async/ for a good in-depth explanation. There are also some in-depth examples like [ffmepg](https://github.com/zauberzeug/nicegui/blob/main/examples/ffmpeg_extract_images/main.py), [opencv webcam](https://github.com/zauberzeug/nicegui/blob/main/examples/opencv_webcam/main.py), [progress](https://github.com/zauberzeug/nicegui/blob/main/examples/progress/main.py) and the [script executor](https://github.com/zauberzeug/nicegui/blob/main/examples/script_executor/main.py) which could be helpful for you in finding an alternative to your currently used threading.

Another question, is it possible to call ui.diag() in self.run_steps function? It seems there is no running loop in self.run_steps.
await asyncio.get_running_loop().run_in_executor(None, self.run_steps, log_box, steps, start_btn)

**Comment by rodja** [comment]
> `await asyncio.get_running_loop().run_in_executor(None, self.run_steps, log_box, steps, start_btn)`

If the `run_steps` method is cpu bound instead of io bound, you need to [use a ProcessPoolExecutor](https://github.com/zauberzeug/nicegui/blob/c63828ef2c7b8f464b7fff43784a3f8b7802f6a0/examples/opencv_webcam/main.py#L41).

> is it possible to call `ui.dialog()` in `self.run_steps` function?

No. The ui calls can only happen on the main thread. You can split `run_steps` into separate functions where each can be awaited. Between these calls you can then make `ui` modifications. Another way would be to use Pythons [multiprocessing tools like Queue and Pipe](https://docs.python.org/3/library/multiprocessing.html#exchanging-objects-between-processes) for communication between the main program and your started subprocess. But thats quite advanced and often not necessary.
