### ISSUE TITLE
Possibility to use other Vue components?

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#111]
Hello,

I know NiceGUI works by utilizing Quasar framework Vue components and it has Vue application under the hood, communicating with Python over websocket.
Is it possible to use other Vue components, for example, [SyncFusion](https://www.syncfusion.com/products/communitylicense)?
I know this is an advanced topic, and I do not expect it to be done soon, but I would appreciate an example on wrapping custom Vue component with explanation of low level interaction mechanism.

**Comment by rodja** [comment]
Thanks for the idea, @me21. It should be possible. Let's use this issue as an addition to #90 to provide such an example.

**Comment by falkoschindler** [comment]
@me21 I added a new example ["custom_vue_component"](https://github.com/zauberzeug/nicegui/tree/main/examples/custom_vue_component). It shows a rather primitive component that receives two props and emits an event. The python code contains the typical separation between NiceGUI element `Counter` and JustPy view `CounterView`.

I'm still learning the low-level interactions of Vue and JustPy, so you might find a more detailed explanation at https://justpy.io/tutorial/custom_components/. But this example is basically all you need to integrate a Vue component with NiceGUI. Other examples are the `colors`, `interactive_image`, `joystick`, `keyboard`, `log` and `scene` elements.

**Comment by rodja** [comment]
With the release of NiceGUI 1.0 we improved and simplified the use of custom Vue components a lot. See https://github.com/zauberzeug/nicegui/blob/main/examples/custom_vue_component/main.py

**Comment by PranitModak** [comment]
Is there a way to integrate vue-flow ( https://github.com/bcakmakoglu/vue-flow ) into this ? I would really love that integration and more so if we can execute nodes from the UI somehow. @rodja

**Comment by rodja** [comment]
@PranitModak looks interesting! Could you create a separate feature request? We can discuss all the details in one place and find contributors.

**Comment by PranitModak** [comment]
@rodja  sure.
Have created this discussion to track its development. #1113
