### ISSUE TITLE
Improve javascript execution

### ISSUE THREAD

**Issue by rodja** [zauberzeug/nicegui#112]
I think we have two issues with the current javascript execution, which I put into one issue because of their interlocking:

### 1: unintuitive naming
We have two separate calls: `ui.run_javascript` to just execute and `ui.await_javascript` to get the value back. Both are awaitable. So the distinction is not self explaining. And writing `my_value = await ui.await_javascript(...)` is not nice.

I suggest we merge both features into a single `ui.run_javascript` call. It always returns the data from the executed javascript which can also be `None`.

### 2: silent ignore before page is ready

Calling `ui.run_javascript` before the page is ready is silently ignored. We could raise an Exception in this cases. But I'd rather make the javascript execute directly after page creation.

**Comment by rodja** [comment]
In 18b390cd I made `ui.run_javascript` waiting for the page to become ready. This worked well for scenarios like when a value_changed is triggered for a selection: https://github.com/zauberzeug/nicegui/blob/18b390cd56d226dbe35b6daeedf6325a82eca89c/tests/test_javascript.py#L24-L26

But on an async page, this could easily create a deadlock:

```python
@ui.page('/')
    async def page():
        ui.label('before js')
        await ui.run_javascript('document.title = "A New Title"')
        ui.label('after js')
```

Therefore I changed the behaviour to raise an exception if javascript is requested to execute before the page is ready.

**Comment by rodja** [comment]
The code to run JavaScript immediately after page is finished is not very nice. Due to the page handler we need to make internal objects available to the outside. See the map example: https://github.com/zauberzeug/nicegui/blob/ac5f8fdd8481a07e993cd985d728a38c7ec34b82/examples/map/main.py#L7-L21

Maybe the page builder could also be a generator. All code after `yield` is executed after the page is ready. A similar technique is used in [fixures from pytest](https://docs.pytest.org/en/6.2.x/fixture.html#teardown-cleanup-aka-fixture-finalization): the tear down code is executed after the `yield` statement.

**Comment by rodja** [comment]
I found a way to use the `yield` keyword and created pull request #114. With this the example becomes much nicer: https://github.com/zauberzeug/nicegui/blob/c27ad191a488060434eac08e73b1681e97a5eee1/examples/map/main.py#L8-L21

**Comment by MLaurenceFournier** [comment]
For anyone brought here by a search engine and wasting time on this...

I think the new way to wait for the page to be ready before executing a script is now (I'm using version 1.4.26) to call `await ui.context.client.connected()` instead of `yield` as describe in the documentation:

https://nicegui.io/documentation/page#page
