### ISSUE TITLE
Can't change visibility of a tab once it's been created

### ISSUE THREAD

**Issue by juledwar** [zauberzeug/nicegui#1127]
### Description

```py
with ui.tabs() as tabs:
    ui.tab('foo')
    bar = ui.tab('bar')

bar.set_visibility(False)
```

The `set_visibility` call does nothing, nor does using `bind_visibility_from`.

**Comment by rodja** [comment]
True. That's because the quasar implementation of `ui.tab` does not have a visibility prop: https://quasar.dev/vue-components/tabs#qtab-api. It only supports enable/disable. It is a good example where our line of inheritance is inconsistent with Quasar: in NiceGUI the visibility functions are implemented for all elements, which reduced code complexity but produces this inconsistency in `ui.tab`.
@falkoschindler can/should we fix this in the upcoming 1.3?

**Comment by juledwar** [comment]
I can work with enabled/disabled so it's not the end of the world for me. If you can fix it, great, if not, maybe override in the `ui.tab` method to throw an exception so users aren't left in the dark?

Cheers.

**Comment by juledwar** [comment]
Well I spoke too soon - enable/disable has the exact same problem :cry:

**Comment by falkoschindler** [comment]
@juledwar I just checked your example code and it works as expected:

<img width="181" alt="Screenshot 2023-07-06 at 14 35 58" src="https://github.com/zauberzeug/nicegui/assets/5767091/4c89a90e-1062-445b-8106-010e8472c230">

Disabling the "bar" tab works as well:

<img width="161" alt="Screenshot 2023-07-06 at 14 36 49" src="https://github.com/zauberzeug/nicegui/assets/5767091/02d8d7bc-e5dc-45fb-a4c7-5d4c3f5489ca">

Can you check once again what is happening on your side? The tab should get the class "hidden" which causes the element to disappear.

**Comment by falkoschindler** [comment]
I'll close this issue since hiding and disabling tabs seem to work as expected.
Feel free to re-open it if you have new information.

**Comment by juledwar** [comment]
(Apologies for the delay in replying, this totally went under my radar)

Woa, that was definitely not working before and now it is. Did something change in a recent release or upstream library? Either way, thanks for confirming.

**Comment by falkoschindler** [comment]
@juledwar No, we didn't touch the visibility mechanism for a while. But in 1.3 we updated Quasar and other third-party dependencies. So theoretically there might have been bugs that got fixed.
Anyway, I'm glad it's working now. 🙂
