### ISSUE TITLE
ui.html() does not work as expected

### ISSUE THREAD

**Issue by JS-Aibel** [zauberzeug/nicegui#1129]
### Description

The following code does not render as expected.
NiceGUI Version: 1.2.24. 
Browser: Edge

**Code**
```
ui.html('<h1>Heading 1</h1>')

ui.html('''<ul>
    <li>Coffee</li>
    <li>Tea</li>
    <li>Milk</li>
    </ul>''')
```

**Rendered**
![image](https://github.com/zauberzeug/nicegui/assets/100705556/891f1991-9a19-4db8-8b0e-ffdea1023a76)

**Expected**
![image](https://github.com/zauberzeug/nicegui/assets/100705556/f75a21c9-0100-4005-b5fa-28b3a3d4c33c)

**Comment by falkoschindler** [comment]
Hi, @JS-Aibel!

This is indeed confusing, but let me explain:
NiceGUI uses Tailwind by default. This involves some style definitions to reset the default appearance of various HTML elements. See https://tailwindcss.com/docs/preflight for more information.

You can either remove Tailwind support altogether using `ui.run(tailwind=False)`, or add custom style definitions for `h1`, `ul` etc. using `ui.add_head_html`.
