### ISSUE TITLE
Margin-Bottom doesnt work with ui.column

### ISSUE THREAD

**Issue by RiyanParvez** [zauberzeug/nicegui#1144]
### Description

Title.
messageColumn.style('position: absolute; top: 90px; left: 350px;margin-bottom:130px;')

**Comment by rodja** [comment]
What do you expect to happen @RiyanParvez? How would the `margin-bottom` manifest in the layout? Could you please provide a [minimal, executable code snippet reproducing the problem](https://en.wikipedia.org/wiki/Minimal_reproducible_example). This will allow us to identify and fix it more efficiently.

**Comment by falkoschindler** [comment]
I'll close this issue since the problem description is very unclear.
Feel free to re-open it once you have new information for us.
