### ISSUE TITLE
Issue with ui.select using options list and value binding

### ISSUE THREAD

**Issue by Viish** [zauberzeug/nicegui#1145]
### Description

Hi,

I try to use a ui.select with options list and value binding, but if the value isn't part of the options list (or dict) it doesn't show up:
```py
ui.select(label=_('Name'), with_input=True, options=options).bind_value(model, 'name')
```
I have to manually add the bound value to the options list to ensure the default value will be shown.

Best regards,

**Comment by Viish** [comment]
Forgot to add I have a workaround:

```
options = {}
copy = options.copy()
copy[model.name] = model.name
select = ui.select(label=_('Name'), with_input=True, options=copy).bind_value(model, 'name')
select.options = options
select.update()
```

**Comment by falkoschindler** [comment]
Hi @Viish,
If I understand correctly, you expect the `ui.select` to take whatever value it is set to. E.g. the following button should set the select's value to "Dave":

```py
s = ui.select(['Alice', 'Bob', 'Charlie'], with_input=True)
ui.button('Click', on_click=lambda: s.set_value('Dave'))
```

I think this is not how `ui.select` works. Currently it can only hold values from its options.
See feature request https://github.com/zauberzeug/nicegui/discussions/1045 for adding a "freetext" mode.

**Comment by Viish** [comment]
Thanks for your comment, indeed the freetext option is what I seek to do.
