### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by Smug246** [zauberzeug/nicegui#1155]
### Description

i might sound stupid saying this but here goes. So here is the code i use to add a label with the home icon:
```py
from nicegui import ui

ui.button('Hello world!', icon='home')

ui.run()
```
This works absolutely fine and gives me this:
![image](https://github.com/zauberzeug/nicegui/assets/99215486/882963cf-c411-463d-9bf3-b8b87775f697)

However when i try to change the icon to a different home photo it as shown below:
```py
from nicegui import ui

ui.button('Hello world!', icon='home app logo')

ui.run()
```
It gives me this:
![image](https://github.com/zauberzeug/nicegui/assets/99215486/92d4bd8e-b127-4431-902a-3985be900c04)
When it should give me this:
![image](https://github.com/zauberzeug/nicegui/assets/99215486/696cb314-1882-40e9-9869-b3fb6ad55e2c)
How can i fix this?

**Comment by duane-impulse** [comment]
try underscores instead of spaces: 'home_app_logo'

**Comment by Smug246** [comment]
@duane-impulse i forgot to mention but i did also try different combinations with _ and - in between but they didnt work

**Comment by rodja** [comment]
It looks like the material icon font had quite some missing icons in the past: https://github.com/google/material-design-icons/issues/1304. We will release NiceGUI 1.3.0 shortly which should have the latest material font. Hopefully we can try and verify this today.

**Comment by rodja** [comment]
> @duane-impulse i forgot to mention but i did also try different combinations with _ and - in between but they didnt work

Btw. It must be written

**Comment by Smug246** [comment]
np thanks

**Comment by falkoschindler** [comment]
I just tried to use this icon on the "v1.3" branch. But it turns out "home_app_logo" is _not_ a Google Material icon, but a symbol:

```html
<span class="material-symbols-outlined">
home_app_logo
</span>
```

Currently we only support icons. I already thought about supporting additional icon packs (see https://quasar.dev/start/umd#installation). But this would raise the question how the API would look like, i.e. how to allow the user to choose between icons, symbols, rounded symbols etc.

**Comment by Smug246** [comment]
idk maybe like give it a prefix in the icon arg so like symbol_home_app_logo. so just check for the prefix and if its there, do the logic to retrieve the corresponding symbol. probably a lot better way to do that

**Comment by BadBadBoss** [comment]
what is yoru discord?
