### ISSUE TITLE
Aggrid Cell Editor : coldef , cell editor :  agNumberCellEditor not working

### ISSUE THREAD

**Issue by srinath-sankaragallu** [zauberzeug/nicegui#1156]
### Description

```py
from nicegui import ui

ui.aggrid({
    'columnDefs': [
        {'headerName': 'Name', 'field': 'name', 'filter': 'agTextColumnFilter', 'floatingFilter': True,'editable': True,  'cellEditor': 'agSelectCellEditor', "cellEditorParams" : {"values" :  ['English', 'Spanish', 'French', 'Portuguese', '(other)']}},
        {'headerName': 'Age', 'field': 'age', 'cellDataType': 'number',  'editable': True, 'cellEditorPopup': True, "cellEditor": "agNumberCellEditor", 'filter': 'agNumberColumnFilter', 'floatingFilter': True},
    ],
    'rowData': [
        {'name': 'Alice', 'age': 18},
        {'name': 'Bob', 'age': 21},
        {'name': 'Carol', 'age': 42},
    ],
}).classes('max-h-40')

ui.run(native=True)
```

agNumberCellEditor : not working, but agSelectCellEditor is working , after seeing the aggrid min.js i am able to see agSelectCellEditor  but not agNumberCellEditor found any where

**Comment by falkoschindler** [comment]
@srinath-sankaragallu I'm not sure if I understand the problem. Both editors seem to be working:
![Screenshot 2023-07-17 at 16 55 02](https://github.com/zauberzeug/nicegui/assets/5767091/a1df5642-5905-44d1-aee4-3640d2b75c38)
![Screenshot 2023-07-17 at 16 55 07](https://github.com/zauberzeug/nicegui/assets/5767091/de7bdbe1-448c-43e1-a04f-df358fb4e673)

**Comment by srinath-sankaragallu** [comment]
Working fine in the higher version thank you
