### ISSUE TITLE
ui.download() problem with parameter injection (same observations using ui.link and ui.open )

### ISSUE THREAD

**Issue by Derf000** [zauberzeug/nicegui#1158]
### Description

Hi,

Using ui.download() (ui.open and ui.link) with parameter injection provide "strange" results.

Provided file : sample.zip -> unzip to get sample.gpx 

**Demo code** (ui_download_t01.py):

```python

from typing import Optional
from nicegui import app, ui

@ui.page('/')
@ui.page('/{_:path}') # IF COMMENTED HERE : ui.download / ui.open and ui.link 'works' "as expected"
async def main_page(param: Optional[str] = None):
  with ui.row() :
      ui.label(f'Download ({param=})')
      ui.label(f'Folder : dl_dir')
  ui.button('Gpx_Download', on_click=lambda: ui.download('/download/sample.gpx'))
  ui.button('Gpx_Open', on_click=lambda: ui.open('/download/sample.gpx'))
  ui.link('Right-click and Save as this Gpx_link', '/download/sample.gpx', new_tab = True)

app.add_static_files('/download', "dl_dir")
ui.run(port=8182)
```
```bash
# Local Directory Structure :
# ui_dl_test
# ├── dl_dir
# │   ├── sample.gpx  -> size is ~ 5kb
# └── ui_download_t01.py

mkdir -p ~/ui_dl_test/dl_dir
unzip sample.zip # to get sample.gpx : gpx files are 'variants' of xml files
mv sample.gpx ~/ui_dl_test/dl_dir/
cd ~/ui_dl_test/
vi ui_download_t01.py
```

**Expected**
- The downloaded file must be identical to the 'source' file.
- The open page shows only file contents
- the new tab shows only file contents

- original file size : ~5kb
- download file size : ~16kb

If you comment:
```python 
#@ui.page('/{_:path}')
```
All (ui.donwload, ui.open and ui.link) works as expected.

(Windows10/WSL : python 3.9.0 (in venv) / nicegui 1.2.29)
```
[sample.zip](https://github.com/zauberzeug/nicegui/files/12025598/sample.zip)

**Comment by Derf000** [comment]
Hi,
just for information : 
same comments with  v 1.2.31

**Comment by rodja** [comment]
With `@ui.page('/{_:path}')` you register a route for all paths. This includes `/download/...`. But in FastAPI [order matters](https://fastapi.tiangolo.com/tutorial/path-params/?h=order#order-matters). Try adding the static files before registering the page builder.

**Comment by Derf000** [comment]
👍 THANK YOU for the clarification on the decorators and the importance of the order in the declaration of paths.
