### ISSUE TITLE
component props values have to be enclosed in double quotes?

### ISSUE THREAD

**Issue by CrystalWindSnake** [zauberzeug/nicegui#1161]
### Description

```python

# that ok
def onchange(arg):
    print(ok_input.value)

ok_input = ui.input(on_change=onchange).props('debounce="1000"')


# not debounce effect
def on_not_ok_change(arg):
    print(not_ok_input.value)

not_ok_input = ui.input(on_change=on_not_ok_change).props("debounce='1000'")
```

Is this a bug?

**Comment by falkoschindler** [comment]
Nice catch, @CrystalWindSnake!
I think you're right and you need to use double quotes. Here is a minimal reproduction:
```py
ui.input().props('bg-color="red"')
ui.input().props("bg-color='red'")
```
Here is the regex that parses the prop string:
https://github.com/zauberzeug/nicegui/blob/01246d2a8cad130b19d213e48c5086e90f05fb84/nicegui/element.py#L23 It is the result of a cooperation with ChatGPT and I'm not sure if we can easily support single quotes as well.

But note that you usually don't need to use any quotes. They are only required if the value contains whitespace:
```py
ui.input().props("bg-color=red")
```

**Comment by CrystalWindSnake** [comment]
@falkoschindler Thanks a lot for the quick response. It seems that this issue does not have a significant impact.
