### ISSUE TITLE
ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by dyipon** [zauberzeug/nicegui#1167]
### Description

Hi,

I just upgraded to 1.3.1, but cannot start nicegui, i get the next messages:
<img width="826" alt="image" src="https://github.com/zauberzeug/nicegui/assets/35313394/6601c2e8-fa28-4e88-90fa-ddf89d19d1f5">

quick fix: installing numpy package via pip. (but this was not necessary before this release)

**Comment by rodja** [comment]
Oh yes. So sorry. We are about to fix that in 1.3.2 which will be released shortly.

**Comment by falkoschindler** [comment]
Ok, in https://github.com/zauberzeug/nicegui/commit/3b81379878cc1f13106bad8fa181430d4104a7c5 and https://github.com/zauberzeug/nicegui/commit/96da04ccf3c14b49125868f8b25f7a04e1f7eb73 I removed the NumPy dependency. Now it is only needed for development when running pytests or in combination with matplotlib.
