### ISSUE TITLE
Log sometime repeats text

### ISSUE THREAD

**Issue by BrianLandry** [zauberzeug/nicegui#1173]
### Description

I am experiencing a weird duplicated output from a log element created within a function. 

Example:

```python
from nicegui import ui

log_works = ui.log().classes("h-64 w-full")

def test():
    log_works.push("a")
    log_works.push("b")
    log_works.push("c")
    log_repeated = ui.log().classes("h-64 w-full")
    log_repeated.push("a")
    log_repeated.push("b")
    log_repeated.push("c")


ui.button("test", on_click=test)
ui.run()
```

log_works output:

```
a
b
c
```

log_repeated output:

```
a
b
c
a
b
c
```

Weirdly, if only a single push is performed I don't see this behavior:

```python
from nicegui import ui

log_works = ui.log().classes("h-64 w-full")

def test():
    log_works.push("a")
    log_repeated = ui.log().classes("h-64 w-full")
    log_repeated.push("a")


ui.button("test", on_click=test)
ui.run()
```

log_works output:

```
a
```

log_repeated output:

```
a
```

**Comment by falkoschindler** [comment]
Thanks for reporting this issue, @BrianLandry!
The code example should really help to hunt this bug. 🐞

**Comment by falkoschindler** [comment]
Commit [baf5902](https://github.com/zauberzeug/nicegui/commit/baf59020d2a42343e4b277ae6dc1c53fd92ebc0a) should fix this issue.

By checking for _equality_ of the current `total_count` and the target `total_count`, we missed the case where the frontend is already ahead by two or more pushs.
