### ISSUE TITLE
AttributeError: module 'nicegui.ui' has no attribute 'scroll_area'

### ISSUE THREAD

**Issue by martxo** [zauberzeug/nicegui#1174]
### Description

AttributeError: module 'nicegui.ui' has no attribute 'scroll_area'。？？？

```py
from nicegui import ui

with ui.row():
    with ui.card().classes('w-32 h-32'):
        with ui.scroll_area():
            ui.label('I scroll. ' * 20)
    with ui.card().classes('w-32 h-32'):
        ui.label('I will not scroll. ' * 10)

ui.run()
```

**Comment by falkoschindler** [comment]
@martxo Can you, please, make sure you have the latest NiceGUI version installed?
`ui.scroll_area` has been released in version 1.3.0.

**Comment by martxo** [comment]
Oh, I feel very sorry and embarrassed. I'm a Python beginner, and I installed NiceGUI following the tutorial using "pip show nicegui", thinking it was the latest version. Now I've checked and realized that it installed Version: 1.2.24 by default. But now I have resolved the issue. Thank you for taking the time to help me!

**Comment by falkoschindler** [comment]
No worries. Glad it works! 🙂
