### ISSUE TITLE
Deprecation Warning notice

### ISSUE THREAD

**Issue by frankenstein91** [zauberzeug/nicegui#1187]
### Description

seeing a warning at first run of my code
```
<path removed>.venv/lib/python3.11/site-packages/vbuild/__init__.py:230: DeprecationWarning: invalid escape sequence '\*'
  css = re.sub(re.compile("/\*.*?\*/", re.DOTALL), "", css)
```

I used `poetry run python logBook.py -h` to run.

https://github.com/frankenstein91/PicardLog/blob/747c26f19957a2a9c58037af77b79971e3d1b013/logBook.py

**What do you expect to happen?** No DeprecationWarning at runtime

**Comment by falkoschindler** [comment]
Now that https://github.com/manatlan/vbuild/issues/10 is closed, I upgraded to vbuild 0.8.2. This should fix this deprecation warning.
