### ISSUE TITLE
The logs are not displayed in real time in the loop

### ISSUE THREAD

**Issue by Devil-Ryu** [zauberzeug/nicegui#1194]
### Description

```python
from nicegui import ui
import time

def start_loop():
    for i in range(5):
        print("before push")
        time.sleep(2)
        log.push('> sleeped 2s')
        label.set_text("push times: {}".format(i+1))
        print("after push")

label = ui.label("push times: ")
log = ui.log(5)
ui.button("start", on_click=start_loop)

ui.run(host='127.0.0.1', port=9991)
```
expected output:
`"> sleeped 2s"` displayed in the view per 2s

actual output:
after 10s, 5 records  `"> sleeped 2s"`  display at the same time

**Comment by rodja** [comment]
try 

```py
async def start_loop():
    for i in range(5):
        print("before push")
        await asyncio.sleep(2)
        log.push('> sleeped 2s')
        label.set_text("push times: {}".format(i+1))
        print("after push")
```

NiceGUI (and the underlying FastAPI) are async frameworks. That means, no io-bound or cpu-bound tasks should be directly executed on the main thread but rather be "awaited". See https://fastapi.tiangolo.com/async/ for a good in-depth explanation. There are also some interesting examples like [ffmepg](https://github.com/zauberzeug/nicegui/blob/main/examples/ffmpeg_extract_images/main.py), [opencv webcam](https://github.com/zauberzeug/nicegui/blob/main/examples/opencv_webcam/main.py), [search-as-you-type](https://github.com/zauberzeug/nicegui/blob/6950a664f09889bb47fbe29ebe96690cbed89be1/examples/search_as_you_type/main.py), [progress](https://github.com/zauberzeug/nicegui/blob/main/examples/progress/main.py) and the [script executor](https://github.com/zauberzeug/nicegui/blob/main/examples/script_executor/main.py) which could be helpful.

**Comment by Devil-Ryu** [comment]
It works, thanks!!!
