### ISSUE TITLE
After packaging the program, the window keeps popping up

### ISSUE THREAD

**Issue by Devil-Ryu** [zauberzeug/nicegui#1207]
### Description

After packaging the program, the window keeps popping up, even closing the terminal does not work
this is main.py
```py
from nicegui import app, ui

app.native.window_args['resizable'] = False
app.native.start_args['debug'] = True

ui.input("input").tailwind.background_color('blue-100')
ui.textarea("")
ui.label('app running in native mode')
ui.button('enlarge', on_click=lambda: app.native.main_window.resize(1000, 700))

# ui.run(native=True, window_size=(400, 300), fullscreen=False)
ui.run(host='127.0.0.1', port=51001, reload=False)
```
this is build.py
```python
import os
import subprocess
from pathlib import Path
import nicegui

cmd = [
    'python',
    '-m', 'PyInstaller',
    'main.py', # your main file with ui.run()
    '--name', 'myapp1', # name of your app
    # '--onefile',
    #'--windowed', # prevent console appearing, only use with ui.run(native=True, ...)
    '--add-data', f'{Path(nicegui.__file__).parent}{os.pathsep}nicegui'
]
subprocess.call(cmd)
```
it's runs this:
![image](https://github.com/zauberzeug/nicegui/assets/46808006/8f1ebcad-86c6-4d62-8fe5-34bd89cb4990)

help😭

**Comment by falkoschindler** [comment]
@Devil-Ryu I'm wondering, _which_ window is popping up? You're not running in native mode, so there shouldn't be any other window than the browser.

**Comment by Devil-Ryu** [comment]
@falkoschindler Sorry, my description is wrong, the browser window keeps popping up，It can also be seen from the background process that new processes are constantly being created（because the process cannot be closed after the demonstration, I will not post screenshots here😭）

**Comment by falkoschindler** [comment]
Can you further reduce your code to (almost) a bare [hello world example](https://nicegui.io/#installation)?

And can you try the same packaged app on a different machine?
Or package the code on a different machine and then try running it on yours?
(I'm having some doubts about your Windows installation... https://github.com/zauberzeug/nicegui/issues/1205 😉)

**Comment by falkoschindler** [comment]
I'll close this issue for now. Feel free to re-open it if you have new information for us.

**Comment by rodja** [comment]
There is a possible solution in #1490.
