### ISSUE TITLE
Help with stopping persistence (probably simple)

### ISSUE THREAD

**Issue by MosheMendel18** [zauberzeug/nicegui#1221]
### Description

The ui no longer responds to ui changes.

Here's what my code currently looks like. Even though all the nicegui code is commented out, `ui.run()` still calls the same code as before, and the counter doesn't reset.

```py
from nicegui import ui
# {other non nicegui code}
# with ui.button('My Devices', on_click=lambda: badge.set_text(int(badge.text) + 1)):
#     badge = ui.badge(len(dN), color='red').props('floating')

# from jinja2 import Template
# temp = Template("""
# ui.mermaid('''
# stateDiagram-v2
#     {{g}} --> {{dev}};
# ''')
# """)
# exec(temp.render(g=dN[gw_index],dev=dN[0].replace(" ","_"))) 
ui.run()
```

I've tried closing the script, running other nicegui code, and running `del(ui)`, but nothing has worked yet. Any advice? 
![image](https://github.com/zauberzeug/nicegui/assets/136655032/f5d959ec-37ef-4299-9428-53bc49741b99)

**Comment by rodja** [comment]
Strange. When I start the script with the code above everything works as expected (browser opening a blank page). You said you tried closing the script. Have you killed the process and started it again?

**Comment by MosheMendel18** [comment]
I'm not sure. How do I do that? 

I tried using ctrl+c, but that didn't seem to work. I tried closing the browsers too, but still my old code leaves a shadow.

**Comment by rodja** [comment]
ctrl+c does not work? That's bad. Are you running Windows? Maybe something like https://github.com/zauberzeug/nicegui/pull/922 could help? Else, try closing the terminal, killing the process with the Task Manager or as a last resort reboot your system.

**Comment by MosheMendel18** [comment]
Ok, closing command prompt worked. Thank you.

I had tried #922 before (or someone's version of the same idea that I saw in a different issue) and it hadn't worked for me, but I'm wondering if some other handler (not based on ctrl+c) could stop the ui during execution (or otherwise allow it to be rebuilt during execution without restarting it). Do you know of any? If not, that's fine, and I'll close the issue. Really appreciate the help regardless.

**Comment by rodja** [comment]
On Mac/Linux I sometimes use ctrl+z to send a process into background. It can then be killed with the command `kill -9 %%`. The `%%` means: pid of last process I send to background.

**Comment by MosheMendel18** [comment]
Can both parts of that be done programmatically?

**Comment by rodja** [comment]
You mean from within the NiceGUI app? What is the purpose? Do you want to programatically shutdown NiceGUI? Have you seen https://nicegui.io/documentation#shutdown

**Comment by MosheMendel18** [comment]
That looks really helpful actually. I can use it to remake the page (since some of the graphics aren't changing on reload anyways). Thank you!
