### ISSUE TITLE
Example script_executor 

### ISSUE THREAD

**Issue by v479038280** [zauberzeug/nicegui#1240]
### Description

It seems that the example does not work 
![微信截图_20230724114809](https://github.com/zauberzeug/nicegui/assets/25096045/887ccc64-1a38-4710-a71c-17fb8783c5d5)

I'm using Python 3.11.4

**Comment by rodja** [comment]
It works fine for me (Mac with Python 3.11). What OS are you on? And is there any console log output?

**Comment by v479038280** [comment]
> It works fine for me (Mac with Python 3.11). What OS are you on? And is there any console log output?

here is the console outpus , nothing wrong,  I'm using windows10
![微信截图_20230721100643](https://github.com/zauberzeug/nicegui/assets/25096045/2b8bc46f-8477-49e3-b897-6509654553af)

**Comment by falkoschindler** [comment]
What do you see if you run `python3 hello.py` in the console?

**Comment by v479038280** [comment]
> What do you see if you run `python3 hello.py` in the console?

The result is same.
![微信截图_20230725065918](https://github.com/zauberzeug/nicegui/assets/25096045/59135f81-35b7-422c-8858-3350187dffdc)

**Comment by rodja** [comment]
We use `python3` in the run_command calls. But you use simply `python`. Is `python3` working for you? Otherwise you need to change the example and remove the `3`.

**Comment by v479038280** [comment]
> We use `python3` in the run_command calls. But you use simply `python`. Is `python3` working for you? Otherwise you need to change the example and remove the `3`.

ui.button("python hello.py", on_click=lambda: run_command("python hello.py")).props(
    "no-caps"
)
ui.button("python slow.py", on_click=lambda: run_command("python slow.py")).props(
    "no-caps"
)
I change python3 to python ,it works

```
with ui.row().classes("items-center"):
    ui.button(
        'python hello.py "<message>"',
        on_click=lambda: run_command(f'python hello.py "{message.value}"'),
    ).props("no-caps")
    message = ui.input("message", value="NiceGUI")

# NOTE: On Windows reload must be disabled to make asyncio.create_subprocess_exec work (see https://github.com/zauberzeug/nicegui/issues/486)
ui.run(reload=platform.system() != "Windows")
```

**Comment by rodja** [comment]
That's great. It seems we can not rely on the existence of `python3` command. Maybe we need to probe for the right command at startup? Or take the python bin with which the app has been started?

**Comment by v479038280** [comment]
> That's great. It seems we can not rely on the existence of `python3` command. Maybe we need to probe for the right command at startup? Or take the python bin with which the app has been started?

I just ran these examples to see how it looks , and haven't looked throuth  his code, this kind of bug is not actually a bug

**Comment by rodja** [comment]
> this kind of bug is not actually a bug

True. But it is very inconvenient. I would love to see it fixed.

**Comment by falkoschindler** [comment]
I'd vote for leaving it as it is. It is just an example and a look into the code would have unveiled the issue.
It is strange though, that the system didn't yield an error message shown in the dialog.
Anyway, that's why I asked for the output of `python3 hello.py` (which hasn't been answered).

**Comment by v479038280** [comment]
> 

I'm using python3.11.4,but I didnot install the python2,so I didn't need to use python3,I didn't notice that this is why it didn't work,
