### ISSUE TITLE
Improve favicon API

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#125]
In https://github.com/zauberzeug/nicegui/issues/123 @ezio416 noticed that it is rather tricky to change the favicon. Besides specifying the name of the icon file you need explicitly serve the file. But there is also a STATIC_DIRECTORY environment variable which is apparently ineffective.

We would like to tidy up the API as follows:

- [x] The `favicon` argument of `ui.run` and `ui.page` specifies the path of the local file relative to the main script.
- [x] The icon is automatically served by NiceGUI (at which route?).
- [x] Review

**Comment by falkoschindler** [comment]
In https://github.com/zauberzeug/nicegui/commit/ff53a438d97110814283b2fb662d2fe364d452b2 I updated the favicon implementation as follows:

- The favicon (on page and `ui.run`) defines the relative local filepath and is now `None` by default.
- The `PageBuilder` stores the favicon (the relative filepath).
- The `Page` converts the `favicon` into a URL path starting with "_favicon". If `favicon` is `None`, the default "favicon.ico" is set. JustPy will add the prefix "/static/".
- A new function `create_favicon_routes()` creates individual routes for each favicon. This function is called on startup. It matches the favicon URLs created by the `Page` instance.

**Comment by rodja** [comment]
Hm.... now we can not use urls anymore as a favicon. Maybe that is ok? Or should we have a fallback, if no file at the path can be found?
Also I wonder why we use a complicated rule for prefixing the favicon path. Can we not just use `/favicon.ico`?

**Comment by falkoschindler** [comment]
Ah, I forgot supporting URLs. It's now fixed.

The favicon path is a bit complicated because JustPy prefixes it with `static/` and I didn't want to interfere with user-defined paths. And the `Page` currently doesn't know its route, so it can't generate a favicon path like `<path_to_page>/favicon.ico`. Or would a relative path work?
