### ISSUE TITLE
Copyright notices for JS libraries & licensing of Highcharts

### ISSUE THREAD

**Issue by firai** [zauberzeug/nicegui#1286]
### Description

- JS libraries are being bundled with NiceGui, but the repo seems to be missing respective copyright/license notices for the various libraries. Since most of the libraries are MIT-licensed, I understand that the copyright and license notices are required.
- NiceGui is MIT-licensed, but I understand that Highcharts is only free for non-commercial, testing or demonstration use[^1][^2]. Since the Highcharts sources are being bundled with NiceGui, it seems like the Readme and/or docs should point out the difference in licensing and point the user to Highchart's licensing descriptions linked to above or the [license notice in their repo](https://github.com/highcharts/highcharts/blob/master/license.txt).

[^1]: https://www.highcharts.com/blog/download/
[^2]: https://www.jsdelivr.com/package/npm/highcharts#id-license

**Comment by rodja** [comment]
We already have the [npm.py](https://github.com/zauberzeug/nicegui/blob/main/npm.py) which fetches the libs according to [npm.json](https://github.com/zauberzeug/nicegui/blob/main/npm.json). Maybe we can add the licence links to the json and let the py script build the Dependencies.md?

**Comment by falkoschindler** [comment]
PR #1747 adds license links to Dependencies.md. This should resolve this issue for now.
