### ISSUE TITLE
`tailwind` cannot be used in `with` statements

### ISSUE THREAD

**Issue by ShizuhaAki** [zauberzeug/nicegui#1294]
### Description

When I use
```python3
with ui.row().tailwind.padding('20'):
    pass
```

The following error is produced by Pylint:

```
Context manager 'Tailwind' doesn't implement __enter__ and __exit__.
```

The terminal reported:

```
Traceback (most recent call last):
  File "/home/lily/Code/mwb/mwb/main.py", line 40, in <module>
    main()
  File "/home/lily/Code/mwb/mwb/main.py", line 33, in main
    auth.build()
  File "/home/lily/Code/mwb/mwb/auth.py", line 7, in build
    with ui.row().tailwind.padding('20'):
TypeError: 'Tailwind' object does not support the context manager protocol

```

Is this intended behavior or a bug?

**Comment by falkoschindler** [comment]
Hi @ShizuhaAki,
This is expected. With `.tailwind` you get a `Tailwind` object which has methods like `.padding` to manipulate the Tailwind styling. Every such method follows the builder pattern, thus returns the very same `Tailwind` object. If you want to do something with the original `Element`, like _entering_ its context with a `with` expression, you can use the `.element` property:
```py
with ui.row().tailwind.padding('20').element:
    pass
```
This might not be the most intuitive NiceGUI feature, but we couldn't find a better solution for the Tailwind API (see #362).
