### ISSUE TITLE
Enable accessing websocket instance in generator-style pages

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#130]
Could you please provide access to websocket instance in generator-style pages? Because `on_page_ready` handler has websocket optional argument, whereas generator-style page can't access websocket after the page is ready (after `yield`).

By the way, a bigger picture: this is needed to redirect user to a login page when he's not authenticated. I execute `await ui.run_javascript('window.location.replace("/login")', respond=False)` in the page ready handler. The usual way to do it would be to return RedirectResponse, but page build functions do not allow this. It's not a major issue, we could perform a redirect using Javascript, but I don't know whether you like it or not. If not, then probably you could allow to return Response objects from page build functions. Or allow to supply a subclass of Page class to `ui.page` decorator - then I could override `Page._route_function` in subclass.
But so far running Javascript to redirect is fine for me - the job is done.

**Comment by rodja** [comment]
Have you seen the authentication example?

https://github.com/zauberzeug/nicegui/blob/d2a08b99e1ee078591bc1e784bb924b468671d2b/examples/authentication/main.py#L31-L36

The decorated page function already receives the request object. In the example we simply render the content according to the session. So there is no redirect needed.

Adding a socket parameter should not be to hard. Maybe similar to the request:

https://github.com/zauberzeug/nicegui/blob/d2a08b99e1ee078591bc1e784bb924b468671d2b/nicegui/routes.py#L53-L54

It would be great if you could provide a short pull request to honor your contribution to NiceGUI :-)

**Comment by me21** [comment]
Gladly.
But the trick with the socket parameter is that it's not yet open before yield 😃 
I'll have to think a bit...

**Comment by rodja** [comment]
You are right. It must be implemented here:

https://github.com/zauberzeug/nicegui/blob/d2a08b99e1ee078591bc1e784bb924b468671d2b/nicegui/page.py#L83-L99

 Maybe instead of `__anext__`/`next` you could use `asend(msg.websocket)`/`send(msg.websocket)` to provide the web socket for the yield statement. Then the page generator looks like

```python
@ui.page('/')
def main(request: Request):
    ui.label(f'request: {request}')
    websocket = yield
    ui.label(f'socket: {websocket}')
```

**Comment by me21** [comment]
Another idea: the second yield could mark the start of `on_disconnect` lifecycle phase. So that everything would be in page builder function:
```
on_connect code
websocket = yield
on_page_ready code
yield
on_disconnect code
```

On another hand, it's more for fun than adding real value.

**Comment by rodja** [comment]
Thanks for your pull request, @me21. I just updated tests and documentation. And instead of directly returning the websocket I wrapped it into a PageEvent class. This way we are able to extend the yield-response without breaking the API in the future.
