### ISSUE TITLE
Dialog isn't modal like mentioned in the docs

### ISSUE THREAD

**Issue by cheak1974** [zauberzeug/nicegui#132]
Hi Everybody,

is there a possibility to make the dialog really modal?

The API Reference claims that it is modal but the dialog can be closed at any time by clicking onto an area outside the dialog. This is not really what I call modal. The dialog should stay open until the user was using the dedicated method to close the dialog (by calling the the .close() method, e.g. bound to a button).

Maybe you consider to add an "is_modal" modifier to the constructor of the dialog class (with default value set to "False" to keep the original behaviour) and suppress the closing of the dialog by clicking somewhere.

**Comment by falkoschindler** [comment]
Quasar's "persistent" prop might be what you're looking for:

> Description: User cannot dismiss Dialog if clicking outside of it or hitting ESC key; Also, an app route change won't dismiss it

https://quasar.dev/vue-components/dialog

So the modified example would look like this:

```python
from nicegui import ui

with ui.dialog().props('persistent') as dialog, ui.card():
    ui.label('Hello world!')
    ui.button('Close', on_click=dialog.close)

ui.button('Open a dialog', on_click=dialog.open)

ui.run()
```

Actually, I wasn't aware that "modal" dialogs are supposed to stay open when clicking in the background. We should update the documentation.

**Comment by cheak1974** [comment]
Hi Falko,
thanks for caring. Your help is very much appreciated. I tried your proposal with the Quasar prop "persistent". Unfortunately it did not solve the problem.

I am just playing around at this point and have a "hamburger menu" which is showing a menu as a dialog like this:

```
from nicegui import ui

def nav_menu():

    menu = ui.dialog()
    menu.props('persistent')    # Quasar Prop for showing the Dialog really modal.
    btn_width = '200px'         # Width of the buttons inside of the menu

    with menu:
        with ui.card().style('position:fixed; top:60px; right:20px;'):
            ui.button('Home', on_click=lambda e: ui.open('/', e.socket)).props('color="secondary" icon-right="home"').style(f'width: {btn_width}')
            ui.button('Go to Start', on_click=lambda e: ui.open('/start', e.socket)).props('color="secondary" icon-right="mail"').style(f'width: {btn_width}')
            ui.button('Impressum', on_click=lambda e: ui.open('/impressum', e.socket)).props('color="secondary" icon-right="phone"').style(f'width: {btn_width}')
            ui.button('Close', on_click=menu.close).props('color="secondary" icon-right="close"').style(f'width: {btn_width}')
            ui.html('<a href="http://www.google.de" target="_blank">Visit Google</a>')

    menu.open()

```

This is called from the View of some routes inside the Site Structure with:
`nav_btn = ui.button(on_click=app.nav.nav_menu).props('round color="amber" text-color="black" icon=menu').style('position:fixed; z-index:2; top:10px; right:20px;')`

When I do this the dialog will show up, but it is still closable when I click onto an area outside of the card inside the nav menu.

BTW:  Yes, a modal dialog is defined as a dialog that the user can not evade. It has to be answered.

**Comment by cheak1974** [comment]
Hi Falko,

I am not that experienced in Quasar, so your help is very much appreciated and yes, the "persistent" prop did the trick.

I think that not only me could find this feature useful so maybe it is a good idea to mention this in the API reference as you proposed. Indeed a "modal" dialog is one the user of the UI can not evade and he has to be interact with before anything else can happen. 
https://en.wikipedia.org/wiki/Modal_window

Thank you very much.
Chris
