### ISSUE TITLE
Column width setting in ui.aggrid is not working

### ISSUE THREAD

**Issue by CrystalWindSnake** [zauberzeug/nicegui#1336]
### Description

```python

ui.aggrid(
    {
        "defaultColDef": {
            "width": 20,
        },
        "columnDefs": [
            {"field": "a"},
            {"field": "b"},
        ],
        "rowData": [{"a": 1, "b": 2}],
    }
)

ui.run()
```

The column width of the table is automatically set to fit.

**Comment by falkoschindler** [comment]
You're right, @CrystalWindSnake: `ui.aggrid` automatically scales all columns to fit the overall grid width:
https://github.com/zauberzeug/nicegui/blob/e083e3f06aa13ebe4b5d457b9587dc7d7a047e26/nicegui/elements/aggrid.js#L11

This seemed to be a useful default behavior, but might lead to confusion when a fixed width is desired. Should we remove this line? Or should we extend the documentation?

For now you can add the following property to the `columnDefs` or `defaultColDef`:
```py
            "suppressSizeToFit": True,
```

**Comment by CrystalWindSnake** [comment]
@falkoschindler Thanks for your help
