### ISSUE TITLE
Slow response and crash when loading large files on the page

### ISSUE THREAD

**Issue by txhy2018** [zauberzeug/nicegui#1352]
### Description

I loaded a JSON file on the page and wanted to display it on the page. The JSON file is 5Mb in size, and when loaded, it will show that it is still loading, as if it is stuck. After a few minutes, the webpage crashes and hangs directly. Error code: FACILITY_VISUALCPP/ERROR_MOD_NOT_FOUND. I hope Nicegui can solve this caching and response speed issue when loading large files or displays. Thank you

**Comment by rodja** [comment]
How are you loading the file? How is it displayed? Eg. `ui.table`, `ui.download`? Can you provide a minimal working example to reproduce the error?

**Comment by txhy2018** [comment]
At present, the program correlation of the project is relatively complex, making it difficult to extract a code demo, so let's talk about the data situation. The following is a sample JSON file, where a3 is a list. The code type below does not display all the elements. The list actually contains 256000 floating point elements, and the file is approximately 5Mb.


```json

{"input": {"data": ["项点1"], "param1": 2.0, "param2": 15}, "output": {"a1": 17.0, "a2": ["项点1"], 


"a3":[2.3451, 3.2111, ....],



 "a4": 2.0, "a5": [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]}, "plot": {}}

```

**Comment by txhy2018** [comment]
At present, when clicking to enter the page, the JSON will be loaded as a global dictionary variable for the entire program. It has two main functions: (1) displaying it on the page through ui. markdown, and (2) clicking the download button to export the JSON. (Reminder: When using small data, all functions are normal)

**Comment by rodja** [comment]
Are you loading the JSON in an async manner? NiceGUI (and the underlying FastAPI) are async frameworks. That means, no io-bound or cpu-bound tasks should be directly executed on the main thread but rather be "awaited". See https://fastapi.tiangolo.com/async/ for a good in-depth explanation. There are also some interesting examples like [ffmepg](https://github.com/zauberzeug/nicegui/blob/main/examples/ffmpeg_extract_images/main.py), [opencv webcam](https://github.com/zauberzeug/nicegui/blob/main/examples/opencv_webcam/main.py), [search-as-you-type](https://github.com/zauberzeug/nicegui/blob/6950a664f09889bb47fbe29ebe96690cbed89be1/examples/search_as_you_type/main.py), [progress](https://github.com/zauberzeug/nicegui/blob/main/examples/progress/main.py) and the [script executor](https://github.com/zauberzeug/nicegui/blob/main/examples/script_executor/main.py) which could be helpful.

**Comment by falkoschindler** [comment]
Here is an example with a 5MB JSON that works on my machine:

```py
N = 200_000
json_str = json.dumps({f'key{i}': f'value{i}' for i in range(N)}, indent=4)
ui.button('Show JSON', on_click=lambda: ui.markdown(f'''
    JSON (length: {len(json_str) / 1024 / 1024:.2f} MB):
    ```json
    {json_str}
    ```
'''))
```

**Comment by txhy2018** [comment]
My calculation results are displayed on the page in JSON format combined with ui.markdown. Previously, the page was loaded abnormally, but now after commenting out the following code, the page can respond to backend functions normally and run to obtain results, and can support ui.upload to download the JSON results. At present, the problem lies in the ui. markdown, which may be due to the large amount of data causing the crash

```python
# ui.markdown(f'''```json\n{download_content}\n```''').style("margin-left:10%;width:80%;font-size:15px")

```

**Comment by txhy2018** [comment]
I suddenly came up with a method to display a large amount of JSON content to ui. markdown, which means omitting a part of a field with large content, such as "result": [1,2,3,4,5,..., 1000000000], but currently I don't know how to implement this idea in ui. markdown

**Comment by falkoschindler** [comment]
@txhy2018 Have you tried my example from https://github.com/zauberzeug/nicegui/issues/1352#issuecomment-1667520607?

**Comment by txhy2018** [comment]
@falkoschindler No, it's stuck，Here is the original JSON content

```json

{
  "input": {
    "data": [],
    "param1": 2.0,
    "param2": 15
  },
  "output": {
    "a1": 17.0,
    "a2": [],
    "a3": 2.0,
    "a4": 2.0,
    "a5": [     # Provide an example where the a5 field contains 256000 elements, some of which are double omitted
      2.0,
      2.0,
      2.0,
      2.0,
      2.0,
      2.0,
      2.0,
      2.0,
      2.0,
      2.0,
      ....
      2.0
    ]
  },
  "plot": {}
}

```

**Comment by falkoschindler** [comment]
@txhy2018 Again: What is the result of the code example from https://github.com/zauberzeug/nicegui/issues/1352#issuecomment-1667520607? Does it crash?

**Comment by falkoschindler** [comment]
I'll close this issue for now. Feel free to reopen it if you have new information.
