### ISSUE TITLE
tree prop 'default-expand-all' 

### ISSUE THREAD

**Issue by frwkl** [zauberzeug/nicegui#1385]
### Description

Hello at all. Thx for that awesome work. I use nicegui for a lot  of little tools. Now i have updated from Version 1.2.2 to 1.3.8. And the trees element don't  expand all at render time. I use the prop 'default-expand-all' .

```py
from nicegui import ui
sProps = 'icon=menu dense default-expand-all no-connectors text-color=primary selected-color=green-10'

ui.tree([
    {'id': 'numbers', 'children': [{'id': '1'}, {'id': '2'}]},
    {'id': 'letters', 'children': [{'id': 'A'}, {'id': 'B'}]},
], label_key='id', on_select=lambda e: ui.notify(e.value)).props(sProps)

ui.tree([
    {'id': 'numbers', 'children': [{'id': '1'}, {'id': '2'}]},
    {'id': 'letters', 'children': [{'id': 'A'}, {'id': 'B'}]},
], label_key='id', on_select=lambda e: ui.notify(e.value)).props('default-expand-all')
ui.run()
```

Is there a new way to do the job ?

![image](https://github.com/zauberzeug/nicegui/assets/7351875/110f256e-0aec-40a9-97bf-5f43fc91ebef)

**Comment by falkoschindler** [comment]
Thanks for reporting this bug, @frwkl!
It looks like there is a JavaScript error when rendering a `ui.tree` with the "default-expand-all" prop being set.

Minimal example:
```py
ui.tree([]).props('default-expand-all')
```

> TypeError: Cannot read properties of undefined (reading 'emit')

I'll look into it.

**Comment by falkoschindler** [comment]
Oh, I see! The default expansion triggers an "update:expanded" event on the client. But this happens during the first rendering, when the socket is not yet created. Therefore the line `window.socket.emit("event", data)` crashes.

Maybe we should simply skip emitting an event if there is no socket. 🤔

**Comment by falkoschindler** [comment]
I still haven't found a solution to avoid getting in a wrong state... Maybe someone can have a look into it?

**Comment by frwkl** [comment]
Thanks for the idea @signup2k 
For me it does what it should.

**Comment by falkoschindler** [comment]
Thanks for the workaround, @signup2k! This is a great idea!
I also thought about closing this issue. But I created PR https://github.com/zauberzeug/nicegui/pull/1704 to add a warning about this prop, so that other users don't run into the same problem. Furthermore, it adds a new parameter `default_expand_all` which basically applies the workaround directly. So the buggy prop isn't needed anymore.

**Comment by ariahrism** [comment]
@falkoschindler 
The documentation and docstring is outdated on `default_expand_all` which doesn't seem to exist anymore.
https://nicegui.io/documentation/tree#tree

https://github.com/zauberzeug/nicegui/blob/9b4e46da9f7e87111376b5840a4197fa2b0adde5/nicegui/elements/tree.py#L38C9-L38C95

Unless the parameter was omitted by mistake on line 21?

**Comment by falkoschindler** [comment]
Oh, you're right, @ariahrism!
I removed it in commit [ae73837](https://github.com/zauberzeug/nicegui/commit/ae73837672f3571185814f4b8fae4a6336ba0dfd).
