### ISSUE TITLE
Add tests for Python 3.11

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#139]
Since Python 3.11 has been released yesterday, we should run automated tests for it as well. I guess we need to upgrade some packages, hopefully without loosing Python 3.7, which is still officially supported until June 2023.

**Comment by falkoschindler** [comment]
Looks like there is no NumPy version supporting both Python 3.7 and 3.11: https://github.com/numpy/numpy/releases 😕

**Comment by falkoschindler** [comment]
The question is: Why did my test https://github.com/zauberzeug/nicegui/actions/runs/3314053234/jobs/5472833427 try to build wheels for NumPy 1.21.1? Numpy 1.23.2 would come [with wheels](https://github.com/numpy/numpy/issues/22097#issuecomment-1215060081). Something is depending on an old version.

**Comment by rodja** [comment]
Maybe we need to add numpy to pyproject.toml. Then we could define different numpy versions for different python versions as shown here: https://github.com/python-poetry/poetry/issues/5378#issuecomment-1100291542

**Comment by rodja** [comment]
Ok, not numpy. But matplotlib needs different versions. I found a poetry.lock configuration where Python 3.7 is handled special. And from Python 3.8 onwards we can use the latest matplotlib (which then uses the newer numpy versions).
