### ISSUE TITLE
Get path/route from page object?

### ISSUE THREAD

**Issue by florianwittkamp** [zauberzeug/nicegui#14]
Hello,

thanks for providing nicegui as open source project!

I run in the following question using nicegui: Is there any way to get the path/route of a page object?

I can set up a new page with the path `/other_page` as follows:
```python
from nicegui import ui

with ui.page('/other_page') as otherPage:
      (...)
```
However, I found now way to get the path `/other_page`  from the page-object `otherPage `.
In this example the path/route is obvious, however, in my side project things are a bit more nested and it would by nice to only pass the page object itself. 

Do you have any hint?

Would it be possible to add the constructor argument `route` as a class member to the [page class](https://github.com/zauberzeug/nicegui/blob/main/nicegui/elements/page.py)?

Thanks!

**Comment by falkoschindler** [comment]
Hi Florian, thanks for your contribution!
That's a good idea to add a class member `page.route`. This way we can now also allow passing page instances to `ui.link`.
The new feature is released in version 0.7.7.
