### ISSUE TITLE
Documentation page scrolls when closing a dialog

### ISSUE THREAD

**Issue by rodja** [zauberzeug/nicegui#1404]
### Discussed in https://github.com/zauberzeug/nicegui/discussions/1401

<div type='discussions-op-text'>

<sup>Originally posted by **v479038280** August 12, 2023</sup>
Each time close a dialog, the page always slides，is it necessary?
![GIF 2023-08-12 11-23-28](https://github.com/zauberzeug/nicegui/assets/25096045/382c418b-ffc2-4392-8cfb-62f987e7337b)
</div>

**Comment by falkoschindler** [comment]
Reproduction:

```py
ui.add_head_html('<style>html {scroll-behavior: smooth} </style>')

with ui.dialog() as dialog, ui.card():
    ui.button('Close', on_click=dialog.close)

ui.button('Open a dialog', on_click=dialog.open).classes('mt-[1000px]')
```
