### ISSUE TITLE
NiceGUI website slow on Safari (mobile and desktop) even for simple dropdown interaction

### ISSUE THREAD

**Issue by qingant** [zauberzeug/nicegui#1412]
### Description

https://github.com/zauberzeug/nicegui/assets/219657/477550f1-fe19-4256-b299-4fab032fcbe4

**Comment by rodja** [comment]
Yes. Thanks for creating this issue @qingant. We hope to fix that in the next release by changing the internal server configurations.

**Comment by rodja** [comment]
@qingant It should be much better now. Basically our machines have now activated swap space which strikes a good balance between costs and performance (before we sometimes had 100 % memory utilization which is really really bad).

**Comment by rodja** [comment]
Can you confirm @qingant ?

**Comment by qingant** [comment]
@rodja 
thanks. seems no better.

actually it's slow even when I run the website on my laptop .


https://github.com/zauberzeug/nicegui/assets/219657/58000088-7226-4d7a-b3e1-2223521620a

**Comment by rodja** [comment]
It's fast for me, but china had quite a spike two hours ago on the the website. Still... it should be optimized. Even if I do not know how at the moment. I'll do more experiments!

**Comment by rodja** [comment]
@qingant we have NiceGUI servers running in Hongkong, Mumbai and Singapore. Can you share where you are located? How fast is your ping to the nicegui.io website?

```bash
ping nicegui.io
```

**Comment by qingant** [comment]
hi @rodja 

```
(base) ➜  ~ ping nicegui.io
PING nicegui.io (149.248.211.128): 56 data bytes
64 bytes from 149.248.211.128: icmp_seq=0 ttl=52 time=129.356 ms
64 bytes from 149.248.211.128: icmp_seq=1 ttl=52 time=130.943 ms
```

I am located in Xi'an , almost middle of China. the roundtrip looks good. Actually, I tried to host the website on my local. it's still slow on my Safari (good on Chrome). So I assume it's about performance issue on Safari instead of network issue.

**Comment by Dronakurl** [comment]
I have a similar problem but with my own application: on mobile, the website freezes when switching tabs.  It works fine on a desktop. I will provide a minimal example as soon as I can.

**Comment by falkoschindler** [comment]
@Dronakurl A minimal example would be very helpful. Looking forward to it! 🙂

**Comment by falkoschindler** [comment]
I'll close this issue since it has been stale for several weeks now.
Feel free to open a new ticket if the problem persists. If so, we should distinguish between the performance of nicegui.io (which might be caused by our fly.io hosting) and the performance of other NiceGUI apps (i.e. NiceGUI's performance itself).

**Comment by Dronakurl** [comment]
I tried to reproduce it, but did not succeed. Right call to close it.

Falko Schindler ***@***.***> schrieb am Di. 24. Okt. 2023 um
07:47:
