### ISSUE TITLE
Error while running ./docker.sh up app.

### ISSUE THREAD

**Issue by Suraj1089** [zauberzeug/nicegui#1456]
### Description

**Issue Description:**

I'm facing an issue while trying to set up the `nicegui` library using Docker with the new version of Docker Compose. The provided `docker.sh` script uses `docker-compose`, which has been replaced by `docker compose` in the new version.

**Steps to Reproduce:**

1. Clone the repository.
2. Run `./docker.sh up app`.

**Expected Behavior:**

The development container should start successfully.

**Actual Behavior:**

The script fails because it uses `docker-compose` instead of `docker compose`.

**Additional Information:**

- Docker version: Docker version 24.0.5, build ced0996
- Docker Compose version: Docker Compose version v2.20.2
- Operating System: Fedora Linux 38 (Workstation Edition)

**Error Message:**

```
$ ./docker.sh up app
./docker.sh: line 39: docker-compose: command not found
```

I believe updating the `docker.sh` script to use the new `docker compose` command would resolve this issue.

---

**Comment by rodja** [comment]
Thanks for reportin @Suraj1089. That update was long overdue!
