### ISSUE TITLE
'page doesn't exist' with on_air param

### ISSUE THREAD

**Issue by Smug246** [zauberzeug/nicegui#1464]
### Description

so when i use the on_air=True param and try to use the link it just says that page doesnt exist. is this a bug or am i doing something wrong.

```python
from nicegui import ui, app
from fastapi.responses import RedirectResponse

@ui.page('/')
def test():
    ui.label('testing')
    if not app.storage.user.get('authenticated', False):
        return RedirectResponse('/login')

@ui.page('/login')
def login():
    async def try_login():
        pass
        # login logic

    ui.query('body').style('background-color: #5898d4;')
    app.storage.user.update({'authenticated': False})
    with ui.card().style('width: 250px;').classes('absolute-center'):
        username = ui.input('Enter Your Username').style('width: 225px;').props('outlined')
        password = ui.input('Enter Your Password', password=True, password_toggle_button=True).style('width: 225px;').props('outlined').on('keydown.enter', try_login)
        ui.button('Login', on_click=try_login).style('margin-left: auto; margin-right: auto;')

ui.run(title='Freight Forever', on_air=True, storage_secret='Freight_Forever_asfhbasf')
```

**Comment by rodja** [comment]
I can reproduce it. Thanks for reporting @Smug246, I'm on it!

**Comment by rodja** [comment]
For a quick workaround you can remove the `/`in your `RedirectResponse`:

```py
return RedirectResponse('login')
```

**Comment by rodja** [comment]
Ok. This one is tricky. It's not only broken for On Air, but whenever a reverse proxy wants to serve the content on a sub-path. We fixed it for NiceGUI elements like `ui.image` in https://github.com/zauberzeug/nicegui/issues/934 by computing the correct source:

https://github.com/zauberzeug/nicegui/blob/ac9180c149b04dbb51ac84bb7e3e1f4f38593088/nicegui/elements/image.js#L28-L30

But in the example the absolute path starting with `/` is a direct http response from FastAPI. To support that "under the hood" we will need a custom middleware which inspects all outgoing responses and checks if the path already contains the `path_prefix`.

I'll try implementing this but it will take some time. Therefore I'll move the release target further along and not block the upcoming 1.3.12 release.

**Comment by rodja** [comment]
Minimal reproduction:

```py
@ui.page('/')
def test():
    return RedirectResponse('/hello')


@ui.page('/hello')
def hello():
    ui.label('it works')
```
