### ISSUE TITLE
ExpiredSignatureError appearing after having open NiceGui for some time

### ISSUE THREAD

**Issue by aersam** [zauberzeug/nicegui#1469]
### Description

![image](https://github.com/zauberzeug/nicegui/assets/5270024/37d3386e-1545-498f-ba75-16e234c8347b)
If I have a Tab with NiceGUI, after some time I get the error above. Is there some way to catch this? In my case I would just like to trigger a reload

**Comment by rodja** [comment]
Very strange. How long do you need to wait for the error to appear? Can you provide an example app to reproduce it?

**Comment by aersam** [comment]
The duration is hard to say, about half an hour. I do call `app.storage.user.update` when rendering the page in an async function
a repo is probably not simple, the app depends a lot on external http servers

**Comment by natankeddem** [comment]
If you pip freeze are you using PyJWT?

**Comment by aersam** [comment]
Sorry guys, it's been on our side, hope you did not waste too much time on it
