### ISSUE TITLE
One-shot timer does not deactivate properly

### ISSUE THREAD

**Issue by bergmansj** [zauberzeug/nicegui#1477]
### Description

```python
        recording_timer = ui.timer(
            interval=60,
            callback=stop_recording,
            once=True
        )
```
When `recording_timer.deactivate()` is called on this timer before the interval runs out, the callback is still called.
I traced this to the `self.active` property not being checked in the `_run_once` method. It ***is*** properly checked in the `_run_in_loop` method. 

I would like to be able to deactivate a timer, ie avoid the callback happening. 
Also, I think it should be possible to cancel the (repeating) timer completely instead of just deactivating its callback.

**Comment by falkoschindler** [comment]
Thanks for reporting this issue, @bergmansj!

Deactivating should, indeed, prevent the callback from happening. I fixed it in [598b805](https://github.com/zauberzeug/nicegui/commit/598b8051b7aacc5d651083a33e0b8e2f2ac46276).

For canceling repeating timers I created a separate pull request #1478. There we can review and discuss this new feature.
