### ISSUE TITLE
throttle function in js script not work for trailing debounce.

### ISSUE THREAD

**Issue by pythonwood** [zauberzeug/nicegui#1483]
### Description

about improve throttle function in the script

## knowledge
what I had learn after view page  
 [Debouncing and Throttling Explained Through Examples](https://css-tricks.com/debouncing-throttling-explained-examples/)
### trailing
![image](https://github.com/zauberzeug/nicegui/assets/5157880/e9fbb7d3-87ce-4bc3-a629-2305da80b0e0)
### leading
![image](https://github.com/zauberzeug/nicegui/assets/5157880/853d332a-21eb-48f1-ae36-5ffe02618e35)
### throthle
Guaranteeing a constant flow of executions every X milliseconds.
Like checking every 200ms your scroll position to trigger a CSS animation.

## prepare for test pr #1484 
let`s add value element trailing throttle
for input element, we donot need to push value in every time when user input new char.
![image](https://github.com/zauberzeug/nicegui/assets/5157880/91fb8a06-9e25-40a9-b73f-102ae2f896a8)

and we improve the chat_app example so it can test leading/trailing debounce and throttle now 

![image](https://github.com/zauberzeug/nicegui/assets/5157880/e7ef1610-76a1-437b-8b80-15fd0b479357)

## test 
trailing is not work as expect. in fact, it is just throttle. (push every 15000 ms)
![image](https://github.com/zauberzeug/nicegui/assets/5157880/2252fb7a-5e92-432c-a49c-120bd6157670)

## fix pr #1485 
with new version throttle function:
![image](https://github.com/zauberzeug/nicegui/assets/5157880/69edd5e9-3fe9-47bb-bff7-3355fb479e5d)

**Comment by pythonwood** [comment]
Hi @falkoschindler

**Comment by falkoschindler** [comment]
@pythonwood The three sliders are - of course - only an example to show how these parameters work. In a real-world application you probably don't want to disable trailing events.

To keep things simple, we send leading _and_ trailing events by default. Ok, this doubles the number of events. But we think it is better to send some more events than to confuse the user with missing events. The user can optimize if it's important.

Anyway, what _exactly_ is your issue?
What do you propose?

**Comment by pythonwood** [comment]
@falkoschindler ok Simply Speaking. the throttle cannot achieve the trailing effect. 

Although the debounce of input is throttle(throttle=0.5, leading=False, trailing=True) , 

### I expect it to work like this.
![image](https://github.com/zauberzeug/nicegui/assets/5157880/1859c311-4f71-4326-9a8a-f4ac4261655a)

### but actually
it just push every 500ms, that is throttle, not trailing. 

![image](https://github.com/zauberzeug/nicegui/assets/5157880/a7d77421-a588-4c8e-95af-794c3f45306c)

**Comment by falkoschindler** [comment]
@pythonwood Thanks for the clarification!

From the [link](https://css-tricks.com/debouncing-throttling-explained-examples/) you posted:
> **Debounce** and **throttle** are two similar (but different!) techniques to control how many times we allow a function to be executed over time.
> ...
> **debounce:** Grouping a sudden burst of events (like keystrokes) into a single one.
> **throttle:** Guaranteeing a constant flow of executions every X milliseconds. Like checking every 200ms your scroll position to trigger a CSS animation.

NiceGUI implements throttling, but you're expecting debouncing.
NiceGUI's parameters are called `leading_events` and `trailing_events` (not "leading" or "trailing") and are _not_ implementing the "leading edge" or "trailing edge" debounce behavior from your link, but whether or not the throttled events contain the very first or the very last event.

So I'm still convinced that the event system is working as _intended_.

**Comment by pythonwood** [comment]
@falkoschindler there is **not need to create an new function to apply debounce**.
in fact. throttle and debounce are almost the same function in lodash. 
[lodash debounce src
](https://github.com/lodash/lodash/blob/4.17.4/lodash.js#L10321)

![image](https://github.com/zauberzeug/nicegui/assets/5157880/1037a3af-809e-4aad-9a33-ce18bd6b22f7)

my pr is the one function for both throttle and debounce.

**Comment by falkoschindler** [comment]
So you want to _introduce_ debouncing?

**Comment by pythonwood** [comment]
> So you want to _introduce_ debouncing? 

maybe not hard to understand with the page?

as lodash source style: throttle() is just debounce(func, leading=true, trailing=true) is just equal to throttle. 

as a simple way in nicegui, I wish that:

disable:  throttle(callback, time=0, ....)
leading:  throttle(callback, time>0, leading=true, trailing=false)
trailing:   throttle(callback, time>0, leading=false, trailing=true)
throttle:  throttle(callback, time>0, leading=true, traling=true)

specially the trailing way is important too, so i rewrite and let it work and not harm any finish job before.

**Comment by pythonwood** [comment]
> NiceGUI's parameters are called leading_events and trailing_events (not "leading" or "trailing")   
@falkoschindler yes in python code. but in js code (template/index.html), param is `leading` and `trailing`. 
as issue title say **throttle function in js script not work for trailing debounce**, that is not the wrong thing in python code, but js code.

bye the way,  what i change in python code #1484  aim at testing function throttle() now.  not good for merge (^_^)

**Comment by falkoschindler** [comment]
You keep talking about debouncing. But there is no debouncing in NiceGUI. Therefore I don't see a problem.

If you want to _add_ debouncing, we can discuss it in a new feature request. But at the moment I don't see the need.

In all cases we shouldn't break existing behavior (which is intended).

**Comment by pythonwood** [comment]
> You keep talking about debouncing. But there is no debouncing in NiceGUI. Therefore I don't see a problem.
> 
> If you want to _add_ debouncing, we can discuss it in a new feature request. But at the moment I don't see the need.
> 
> In all cases we shouldn't break existing behavior (which is intended).

no breaking anything. but fix a unexpect behavior. in my mind.
I just want  ` throttle(throttle=0.5, leading=False, trailing=True)` to work as it should be.  I think it is not now. 
but in your mind, debounce is so diff from throttle that it should be a new feature request? Well, It is a pity.

**Comment by falkoschindler** [comment]
`throttle` is an internal function that works as intended. Why should it behave differently?
If you expect a parameter called "leading" to cause the `throttle` function to debounce, that's ok but. But it's still no bug that needs fixing as indicated in your title.
Of course, we could add support for debouncing. But that would be a new feature which needs more clarification and justification before changing a working system.

**Comment by pythonwood** [comment]
> You keep talking about debouncing. But there is no debouncing in NiceGUI. Therefore I don't see a problem.
> 
> If you want to _add_ debouncing, we can discuss it in a new feature request. But at the moment I don't see the need.
> 
> In all cases we shouldn't break existing behavior (which is intended).

my code in this way:  `throttle: throttle(callback, time>0, leading=true, traling=true, ...)`  do not send last modified ending event.
so I am going to improve my code to ensure last event send out, unless user call with traling=false.

**Comment by falkoschindler** [comment]
Sorry, we're still not convinced that there's anything wrong with the existing implementation. Therefore I'll close this issue.

If you want to request a _new feature_, please open a new [feature request](https://github.com/zauberzeug/nicegui/discussions/categories/ideas-feature-requests).

If you really think the current implementation is _wrong_, please open a new issue with a very clear description, a [minimum reproducible code example](https://en.wikipedia.org/wiki/Minimal_reproducible_example), a description of what you expect and what is happening instead.

**Comment by GinjiJizai** [comment]
> feature request

I hope this is the right place for this:

Just in case: debouncing is still a feature request in NiceGUI. Since `ui.input` wraps Quasar’s `QInput`, you can use the built-in Quasar debounce like this:

`ui.input(label="test").props('debounce="300"')`

See also: Quasar’s documentation — https://quasar.dev/vue-components/input/
It might be worth adding this to the NiceGUI documentation, since debouncing is a common use case.
