### ISSUE TITLE
http://127.0.0.1:8080/service-worker.js not found

### ISSUE THREAD

**Issue by yxlwfds** [zauberzeug/nicegui#1494]
### Description

http://127.0.0.1:8080/service-worker.js not found

**Comment by rodja** [comment]
Can you please elaborate? Where do you see this error? How to reproduce it?

**Comment by rcurrie** [comment]
@yxlwfds I suspect you have a service worker registered in Chrome. I ran into the same thing - had worker.js registered and my browser kept asking for that file when I had removed all references to it. Details on manually removing a registered service worker: https://www.codementor.io/@himank/how-to-unregister-service-workers-n8mzf5jce
