### ISSUE TITLE
Allow Authentication

### ISSUE THREAD

**Issue by uniquename** [zauberzeug/nicegui#15]
Hi,

I'm fairly new to the python world, but found your work and am really enjoying it;-)

I have the need to secure the gui I'm working on without putting it behind a proxy and came across https://justpy.io/tutorial/sessions/. So I thought about opening this issue, maybe it's easy for you guys to implement and others also have a need like me.

cheers
Hendrik

**Comment by rodja** [comment]
Thank you for reaching out, @uniquename. It looks like a useful enhancement for NiceGUI. We need to figure out how to best integrate it into the architecture. As you probably know NiceGUI shares a single UI state for all browsers. It's not obvious right now how to access and manage the session of each connection to this shared state.

The entry point would be https://github.com/zauberzeug/nicegui/blob/fa747104d039eb887bf49115cad97c8200f3b6a9/nicegui/elements/page.py#L45. If the function passed to the `jp.Route` has a parameter `request` it gets filled with the session details as long as the correct `justpy.env` file is provided in the same directory as the NiceGUI main script. Maybe the NiceGUI page should provide a callback which gets called with the request object on each new connection? But how to register the callback for the main page? This one is intentionally "hidden" to make thinks easier in simple use cases. We need to think about this some more.

**Comment by rodja** [comment]
I could not help it and made a first shot on a [feature branch](/zauberzeug/nicegui/tree/feature/sessions). It still misses a callback configuration for the main page. And maybe we also want an `on_disconnect` callback for symmetry....

**Comment by rodja** [comment]
Example Usage so far:

https://github.com/zauberzeug/nicegui/blob/44ea4a9c281aaabc55740ca6f204bf28f65f75c1/main.py#L456-L468

The demo just shows how to work with the `request` object. By providing a `justpy.env` file you are able to implement authentication.

**Comment by rodja** [comment]
We've just released v0.7.8 which contains the on_connect callback as described above. Here is the example: https://nicegui.io/#sessions
