### ISSUE TITLE
ui.input component does not have an id attribute in the HTML tag

### ISSUE THREAD

**Issue by CrystalWindSnake** [zauberzeug/nicegui#1507]
### Description

```python
from nicegui import ui
input = ui.input("test")

async def onclick():
    tag = await ui.run_javascript(f"getElement({input.id}).tagName")
    print(tag)

ui.button("get input tag", on_click=onclick)
```

clicked the button  , an error occurs.

```
KeyError: 'result'
```

Check the generated HTML tag, no id attribute found.
```html
<label class="q-field row no-wrap items-start q-field--standard q-input q-field--labeled" for="f_29f7653c-4eb2-432a-b2dc-d40674e3c1ec">...
```

**Comment by natankeddem** [comment]
I dug down a bit into this because I was interested...my extended demo now with a label and input. Label "works" and input doesn't.
```py
from nicegui import app, ui


async def show_label_tag_name():
    a = await ui.run_javascript(f'getElement({label.id}).tagName')
    ui.notify(a)


async def show_input_tag_name():
    a = await ui.run_javascript(f'getElement({input.id}).tagName')
    ui.notify(a)
ui.button('show label tag', on_click=show_label_tag_name)
ui.button('show input tag', on_click=show_input_tag_name)
label = ui.label('ui.label')
input = ui.input('ui.input')
ui.run()
```

Your input element HTML looks quite different from what I am getting:
```js
<input class="q-field__native q-placeholder" tabindex="0" aria-label="ui.input" loopback="false" list="c7-datalist" id="f_1dc37628-7f20-46a9-ac28-8d5bc92ea591" type="text">
```
The label looks like this:
```js
<div id="c6">ui.label</div>
```

The `getElement` function appears to be:
```js
function getElement(id) {
  const _id = id instanceof HTMLElement ? id.id : id;
  return window.app.$refs["r" + _id];
}
```
When you look at `window.app.$refs`, it appears to be an array of `objects` and `divs`. Not necessarily having anything to do with the element html.
![image](https://github.com/zauberzeug/nicegui/assets/44515217/5e96e4ff-54a8-492b-bb50-7e0e678eb687)

So when you do a `getElement` call you aren't able to get the `tagName` unless it is stored as a simple `div` in that array. So whatever you are trying to do here probably needs to be done some other way.

**Comment by falkoschindler** [comment]
Interesting. I haven't really been aware of this difference between UI elements. But actually there is no hard requirement that each NiceGUI element is translated into an HTML element with an ID. I guess especially Quasar elements don't preserve IDs?

One could argue that `getElement` is broken for these elements. But this function is only a convenient shortcut for querying HTML elements by a given NiceGUI ID. If there is no such ID, the function can't work.

So I would conclude that this behavior is unfortunate, but there's not much we can do about it.

**Comment by paco-sevilla** [comment]
I found the solution for this in SO: https://stackoverflow.com/a/59431022
So it's simple, you just need to set the `for:` `prop` to the element's id (prefixed with "c"):
```Python
input = ui.input("test")
input.prop(f'for=c{input.id}')
```
However, I would argue that this should be done by default in the `__init__` of the [Input class](https://github.com/zauberzeug/nicegui/blob/main/nicegui/elements/input.py#L47-L52):
```Python
self._props['for'] = f'c{self.id}'
```

**Note:** This is also needed for [Select](https://quasar.dev/vue-components/select), as both inherit from [Field](https://quasar.dev/vue-components/field).

**Comment by mikaelho** [comment]
> I found the solution for this in SO: https://stackoverflow.com/a/59431022 So it's simple, you just need to set the `for:` `prop` to the element's id (prefixed with "c"):

This does not seem to work for me. `for` prop sets the `id` of the innermost `<input>` tag, not the outermost `<label>`.

I do have a use case where every component, as seen by Python, should have an `id` set on the corresponding outermost HTML element, and currently I am not able to set this on an `ui.input`. My workaround is to wrap the `ui.input` in an `ui.element`, and refer to that one instead. If nothing else, NiceGUI could do the same, and maybe also consider providing a guarantee of the `id` match.
