### ISSUE TITLE
aggrid example from the documentation does not work

### ISSUE THREAD

**Issue by jsmaupin** [zauberzeug/nicegui#1510]
### Description

I have copied and pasted the [example](https://nicegui.io/documentation/ag_grid) for aggrid element into a new project.  When I run the project, I only see a blank page.  Commenting out the ui.aggrid(...) call causes the buttons from the example to show after a refresh.

I do not see any log messages on the server side, even when I set the logging level to DEBUG.  However, in the browser, I do see this message 
> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec. :8080/_nicegui/1.3.12/static/utils/dynamic_properties.js:1

The issue only exists in version 1.3.12 and does not happen in 1.3.11

**Comment by rodja** [comment]
That's very odd. The example is running fine on my Mac M1. Are you running windows and have tested with different browsers?

**Comment by falkoschindler** [comment]
@aersam Can you, please, have a look into this issue? It seems to be caused by the change in PR https://github.com/zauberzeug/nicegui/pull/1470 where we introduced dynamic_properties.js. Somehow the file isn't served correctly. Do you have an idea what is going on?

**Comment by aersam** [comment]
I cannot repo it with Windows and Firefox nor with Windows and Edge
[repo.zip](https://github.com/zauberzeug/nicegui/files/12461822/repo.zip)

Do you have some more FastAPI Config? Do you use the existing FastAPI version?

**Comment by jsmaupin** [comment]
I am running this on Windows using Chrome.

**Comment by jsmaupin** [comment]
> Do you have some more FastAPI Config? Do you use the existing FastAPI version?

Does this help?

```bash
>pip freeze
aiofiles==23.2.1
aiohttp==3.8.5
aiosignal==1.3.1
annotated-types==0.5.0
anyio==3.7.1
async-timeout==4.0.3
attrs==23.1.0
bidict==0.22.1
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.7
colorama==0.4.6
cryptography==41.0.3
fastapi==0.103.0
fastapi-socketio==0.0.10
frozenlist==1.4.0
h11==0.14.0
httpcore==0.17.3
httptools==0.6.0
httpx==0.24.1
idna==3.4
itsdangerous==2.1.2
Jinja2==3.1.2
markdown2==2.4.10
MarkupSafe==2.1.3
multidict==6.0.4
nicegui==1.3.11
orjson==3.9.5
pscript==0.7.7
pycparser==2.21
pydantic==2.3.0
pydantic_core==2.6.3
Pygments==2.16.1
PyJWT==2.8.0
python-dotenv==1.0.0
python-engineio==4.6.1
python-multipart==0.0.6
python-socketio==5.8.0
PyYAML==6.0.1
requests==2.31.0
sniffio==1.3.0
starlette==0.27.0
typing_extensions==4.7.1
urllib3==2.0.4
uvicorn==0.22.0
vbuild==0.8.2
watchfiles==0.20.0
websockets==11.0.3
yarl==1.9.2
```

**Comment by aersam** [comment]
> > Do you have some more FastAPI Config? Do you use the existing FastAPI version?
> 
> Does this help?
> 
> ```shell
> >pip freeze
> aiofiles==23.2.1
> aiohttp==3.8.5
> aiosignal==1.3.1
> annotated-types==0.5.0
> anyio==3.7.1
> async-timeout==4.0.3
> attrs==23.1.0
> bidict==0.22.1
> certifi==2023.7.22
> cffi==1.15.1
> charset-normalizer==3.2.0
> click==8.1.7
> colorama==0.4.6
> cryptography==41.0.3
> fastapi==0.103.0
> fastapi-socketio==0.0.10
> frozenlist==1.4.0
> h11==0.14.0
> httpcore==0.17.3
> httptools==0.6.0
> httpx==0.24.1
> idna==3.4
> itsdangerous==2.1.2
> Jinja2==3.1.2
> markdown2==2.4.10
> MarkupSafe==2.1.3
> multidict==6.0.4
> nicegui==1.3.11
> orjson==3.9.5
> pscript==0.7.7
> pycparser==2.21
> pydantic==2.3.0
> pydantic_core==2.6.3
> Pygments==2.16.1
> PyJWT==2.8.0
> python-dotenv==1.0.0
> python-engineio==4.6.1
> python-multipart==0.0.6
> python-socketio==5.8.0
> PyYAML==6.0.1
> requests==2.31.0
> sniffio==1.3.0
> starlette==0.27.0
> typing_extensions==4.7.1
> urllib3==2.0.4
> uvicorn==0.22.0
> vbuild==0.8.2
> watchfiles==0.20.0
> websockets==11.0.3
> yarl==1.9.2
> ```
That's pretty much what I have. Do you have any python code other than the sample code?

**Comment by aersam** [comment]
Or a screenshot of the failing network requests in the dev tools?
