### ISSUE TITLE
bug in demo storage

### ISSUE THREAD

**Issue by v479038280** [zauberzeug/nicegui#1511]
### Description

The demo [Counting page visits](https://nicegui.io/documentation/storage#counting_page_visits) doesn't work ,here is the output

```
 counter[app.storage.session.browser[id]] += 1
AttributeError: 'Storage' object has no attribute 'session'
```
![微信截图_20230829105913](https://github.com/zauberzeug/nicegui/assets/25096045/95308eb2-e202-41d7-8350-30a6b4422014)

**Comment by rodja** [comment]
Thanks for reporting @v479038280. The example should have been

```
@ui.page('/')
def index():
    counter[app.storage.browser['id']] += 1
    ui.label(f'{len(counter)} unique views ({sum(counter.values())} overall) since {start}')
```

I'll release a fix shortly.
