### ISSUE TITLE
authentication issues with on_air

### ISSUE THREAD

**Issue by Smug246** [zauberzeug/nicegui#1517]
### Description

when on_air=True authentication doesnt seem to work.

minimal reproduction:

```python
from nicegui import ui, app
from fastapi.responses import RedirectResponse
import asyncio

primary_color = '#13b27c'

info = {'admin': 'admin'} 

@ui.page('/')
def confirm_delivery():
    if not app.storage.user.get('authenticated', False):
        return RedirectResponse('login')

@ui.page('/login')
def login():
    async def try_login():
        input_username = username.value
        input_password = password.value

        if input_username in info and info[input_username] == input_password: 
            app.storage.user.update({'username': input_username, 'authenticated': True}) 
            ui.notify('Logged In', type='success')
            await asyncio.sleep(1.5)
            ui.open('/')
        else:
            ui.notify('Incorrect Username or Password', type='error')
            username.set_value('')
            password.set_value('')

    with ui.card():
        username = ui.input('Enter Your Username')
        password = ui.input('Enter Your Password', password=True, password_toggle_button=True).on('keydown.enter', try_login)
        ui.button('Log In', on_click=try_login, color=primary_color)

ui.run(title='test', storage_secret='test', on_air=True)

```

**Comment by falkoschindler** [comment]
@Smug246
Can you, please, try to reduce the example further? All the styling is not needed. And currently we can't run it without a database. Can you replace it with some simple dictionary lookup?
And what exactly is not working? What is happening? What did you expect?
These information would allow us to help more efficiently. Thanks!

**Comment by Smug246** [comment]
so id expect it to just move on to the / page but it doesnt. check the edited code

**Comment by Smug246** [comment]
> Strange. It works on my machine. After 1.5 seconds I'm redirected to "/".

are you definitley using the on air link thats generated. because its only on that link it doesnt work. it works normally without that

**Comment by falkoschindler** [comment]
Oh, sorry, I forgot to go on air!
It might be related to https://github.com/zauberzeug/nicegui/pull/1501.
@rodja, can you confirm that?

**Comment by rodja** [comment]
@Smug246 oh yes. It is related to #1501 and #1517. It works again with NiceGUI 1.3.12 if you use `RedirectResponse('/login')`. I'll try to fix that later today for the upcoming 1.3.13. It should work with root `/` and without.

**Comment by Smug246** [comment]
uh ye i tried that and it still doesnt work

**Comment by rodja** [comment]
What is the url if you see this error?

**Comment by Smug246** [comment]
https://on-air.nicegui.io/login

**Comment by rodja** [comment]
That is odd. In #1501 I've added a middleware which should add the correct prefix. Are you sure this is the url you end up when starting you demo with 1.3.12 and open the On Air url? Would have been the expected result with 1.3.11. With 1.3.12 I get https://on-air.nicegui.io/devices/vk7MeJ7wlogin/ (eg. the / before login is missing).

**Comment by Smug246** [comment]
Uploading Desktop 2023.08.29 - 15.07.47.02 - Trim.mp4…

**Comment by rodja** [comment]
Maybe you have a virtual env in the dir and the pip version is not used? Try

```py
from nicegui import __version__
print(__version__)
```

**Comment by Smug246** [comment]
> Maybe you have a virtual env in the dir and the pip version is not used? Try
> 
> ```python
> from nicegui import __version__
> print(__version__)
> ```

![image](https://github.com/zauberzeug/nicegui/assets/99215486/60977b79-db7b-49ab-9751-de2afadf542f)

**Comment by rodja** [comment]
Wow. What a mystery. I'm not very confident that my bugfix ec77362 will solve it for you. But it is definitely fixing the original problem which I could reproduce. We will release 1.3.13 shortly. Let's try that and hope for the best.

**Comment by Smug246** [comment]
thanks for trying, i hope 1.3.13 works

**Comment by rodja** [comment]
Ok, 1.3.13 is just released. I hope it helps.

**Comment by rodja** [comment]
@Smug246 have you found the time to try this with 1.3.13?

**Comment by Smug246** [comment]
i'll test today when i'm home and let you know

**Comment by Smug246** [comment]
hi im still having problems after testing today. but its slightly different. when using on_air everytime a login is successful it will write authenticated true in the .nicegui directory, however on_air doesnt seem to track that storage so everytime i login a new session is made. and i can never login without going back to the login page.

```python
from nicegui import ui, app
import asyncio
from fastapi.responses import RedirectResponse

@ui.page('/')
def home():
    if not app.storage.user.get('authenticated', False):
        return RedirectResponse('/login')

@ui.page('/')
def login():
    async def try_login():
        try:
            input_password = password.value

            actual_username = 'admin'
            actual_password = 'admin'

            if input_password == actual_password:
                app.storage.user.update({'username': actual_username, 'authenticated': True})
                ui.notify('Login Successful', color='positive')
                await asyncio.sleep(1.5)
                ui.open('/')
            else:
                ui.notify('Invalid username or password', color='negative')
                username.set_value('')
                password.set_value('')

        except Exception as e:
            print(e)

    ui.query('body')
    with ui.card().style('width: 250px;').classes('absolute-center'):
        username = ui.input('Enter Your Username').style('width: 225px;')
        password = ui.input('Enter Your Password', password=True, password_toggle_button=True).on('keydown.enter', try_login)
        ui.button('Log In', on_click=try_login)

ui.run(on_air=True, reload=False, storage_secret='secret')
```

**Comment by rodja** [comment]
That looks like a completely other issue that the non-working RedirectResponse. Could you repost this a a new issue? 
If you deploy to fly.io make sure you have only one instance or sync the `.nicegui` between instances or use `app.storage.browser`. Otherwise each instance has a different set of storage informations.
