### ISSUE TITLE
Bug between ui.interactive_image.content and e.client.content when being handled within an event handler.

### ISSUE THREAD

**Issue by DavidLeBonk** [zauberzeug/nicegui#1528]
### Description

```py
from nicegui import ui
from nicegui.events import MouseEventArguments

DisplayBug = False

def mouse_handler(e: MouseEventArguments):
    color = 'SkyBlue' if e.type == 'mousedown' else 'SteelBlue'
    if DisplayBug:
        e.client.content += f'<circle cx="{e.image_x}" cy="{e.image_y}" r="15" fill="none" stroke="{color}" stroke-width="4" />'
    else:
        ii.content += f'<circle cx="{e.image_x}" cy="{e.image_y}" r="15" fill="none" stroke="{color}" stroke-width="4" />'
    ui.notify(f'{e.type} at ({e.image_x:.1f}, {e.image_y:.1f})')

src = 'https://picsum.photos/id/565/640/360'
ii = ui.interactive_image(src, on_mouse=mouse_handler, events=['mousedown', 'mouseup'], cross=True)

ui.run()
```

Here is the minimum required code to trigger the bug in question. I am attempting to modify the content of an interactive image object via en event handler. When `DisplayBug` variable is false all will work as expected, when set to true it will attempt to modify content via the event handlers argument displaying an error. Here is the error I get when `DisplayBug` is true:

``e.client.content += f'<circle cx="{e.image_x}" cy="{e.image_y}" r="15" fill="none" stroke="{color}" stroke-width="4" />'
TypeError: unsupported operand type(s) for +=: 'Element' and 'str'``

**Comment by DavidLeBonk** [comment]
```py
from nicegui import ui
from nicegui.events import MouseEventArguments

DisplayBug = True

def mouse_handler(e: MouseEventArguments):
    color = 'SkyBlue' if e.type == 'mousedown' else 'SteelBlue'
    if DisplayBug:
        e.sender.content += f'<circle cx="{e.image_x}" cy="{e.image_y}" r="15" fill="none" stroke="{color}" stroke-width="4" />'
    else:
        ii.content += f'<circle cx="{e.image_x}" cy="{e.image_y}" r="15" fill="none" stroke="{color}" stroke-width="4" />'
    ui.notify(f'{e.type} at ({e.image_x:.1f}, {e.image_y:.1f})')

src = 'https://picsum.photos/id/565/640/360'
ii = ui.interactive_image(src, on_mouse=mouse_handler, events=['mousedown', 'mouseup'], cross=True)

ui.run()
```

I am able to make it work when accessing via the sender, but I will leave this issue up in the case that you are mean't to be able to access via client.

**Comment by falkoschindler** [comment]
Hi @DavidLeBonk!

The error message is correct. `client.content` is an Element and cannot be extended with a string. It has nothing to do with the interactive image. It's actually part of the core page layout:
https://github.com/zauberzeug/nicegui/blob/219da1118c30d0611ec665cb7cf8b185b36833de/nicegui/client.py#L42-L45
In case you're app uses multiple pages with possibly multiple connected browser tabs, `e.client` can help to identify the one that triggered the event. For accessing the element which caused an event, you're right to use `e.sender`.
