### ISSUE TITLE
Failed to fetch dynamically imported module (on_air problem)

### ISSUE THREAD

**Issue by Smug246** [zauberzeug/nicegui#1530]
### Description

another issue with on_air. with help i got the signature pad working all fine but i cant actually test it on my phone because it gives the error in the video below:

https://github.com/zauberzeug/nicegui/assets/99215486/bc9fa2df-4a6f-4c7a-8b52-caec3700049a

**Comment by rodja** [comment]
Yes, I can reproduce the problem when setting `on_air=True` in the [custom vue component example](https://github.com/zauberzeug/nicegui/blob/main/examples/custom_vue_component/main.py).

**Comment by rodja** [comment]
Ok, we could fix the issue on our server. It should work now.
