### ISSUE TITLE
Nicegui Watcher catch log files change and loop

### ISSUE THREAD

**Issue by Bazzu85** [zauberzeug/nicegui#1533]
### Description

Hi,

I made a small repo to test the scenario:
https://github.com/Bazzu85/NiceGui-Watcher-Log-Bug

the main.py is simple.

- Create the log folder
- Set the loggging level to DEBUG and to the log\log.txt file
- Add a label
- Run the app in native mode

When running the debug logging write to file, and this writed is catched from watcher.

The log.txt contains this:
https://gist.github.com/Bazzu85/d0e54299a72df9eebf6612a85add5f88

I'm on Windows 11 PRO with python 3.11

I tried to exclude txt from the uvicorn_reload_excludes but I think that's already excluded from the reload scenario. but the file is activelly watched

Any suggestion to avoid this log loop?

**Comment by natankeddem** [comment]
At a base level NiceGUI is just using uvicorn to get this functionality. Therefore I think this applies?
https://github.com/encode/uvicorn/discussions/1656
More research might find better answers...

**Comment by Bazzu85** [comment]
Thx for you tip.
I resolved creating a custom logger for my application:

```
logger = logging.getLogger("custom_application_logger")
logger.setLevel(logging.DEBUG)
logger_file = logging.FileHandler(log_path + '\\' + log_fileName)
logger_file_formatter = logging.Formatter('%(asctime)s - %(levelname)-7s [%(filename)30s:%(lineno)-4s - %(funcName)30s()] %(message)s')
logger_file.setFormatter(logger_file_formatter)
logger.addHandler(logger_file)
```

this prevent that the default log apply to other libraries if I'm correct

**Comment by rodja** [comment]
Thanks for investigating this. Can we close the issue?
