### ISSUE TITLE
need help with table.Add_Slot()

### ISSUE THREAD

**Issue by OrEye** [zauberzeug/nicegui#1538]
### Description

Hi,

I hope you are well. I am currently working on a project where I need to implement checkboxes using the addslot function, but I am having difficulties in achieving this. As part of my development, I am looking for examples or tips that can point me in the right direction.

If any of you have experience with this function or can provide me with related examples, I would be very grateful. Your help will be invaluable in moving my project forward in an efficient and professional manner.

I thank you in advance for any assistance you can provide.

Best regards!

And please fix the docs, I can't see what would be in ```with table.add_slot(name=?):```

**Comment by OrEye** [comment]
nvm i figured out my self. but fix the docs

**Comment by rodja** [comment]
> And please fix the docs, I can't see what would be in with table.add_slot(name=?):

@OrEye can you point me in the right direction? Can you share a link to the portion where you see something broken? Also a screenshot would be very helpful. And an short explanation what you would expect instead. Thanks for your help!
