### ISSUE TITLE
on_connect is not called for shared pages

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#155]
Consider:

```
@ui.page('/manual_test', shared=True, on_connect=ManualTestPage.on_open, on_disconnect=ManualTestPage.on_close)
def build_manual_test_page():
    ...
```

The `on_connect` handler is not called when I open the page in the browser.
It is likely caused by the following code:
https://github.com/zauberzeug/nicegui/blob/30abbcb4048e4cf221295bb9409c52f87168140b/nicegui/page_builder.py#L26-L33

The `_route_function` of `Page` class is not called for shared pages.

Other lifecycle handlers (on_page_ready, on_disconnect) are called.

**Comment by falkoschindler** [comment]
Yes, exactly! We shouldn't return the shared page without calling its route function.
Thanks for pointing this out!

I fixed it in https://github.com/zauberzeug/nicegui/commit/e278407c26f71c4a52aa8db0f370536e5ea9968b
