### ISSUE TITLE
MATPLOTLIB=false does not prevent importing of matplotlib

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#156]
It appears the environment variable MATPLOTLIB set to false does not prevent importing of `matplotlib`. I'm attaching the importtime.log file for you to analyze.

It takes 8.1 seconds to import NiceGUI 0.9.25 on the Beaglebone Black. By removing imports dependent on `numpy` and `matplotlib` I was able to reduce it to 6.4 seconds.

Specifically, I commented out the import of `chartcomponents` and `pandas` in JustPy package to get rid of `matplotlib` imports entirely. That brought the start up time down to 7.7 seconds.

In addition, commenting out the import of `gridcomponents` in JustPy and `scene` in ui.py of NiceGUI reduced import time even further to 6.4 seconds by preventing import of numpy.

[importtime.log](https://github.com/zauberzeug/nicegui/files/9969461/importtime.log)
[importtime_no_chartcomponents.log](https://github.com/zauberzeug/nicegui/files/9969462/importtime_no_chartcomponents.log)
[importtime_no_chartcomponents_gridcomponents_pandas.log](https://github.com/zauberzeug/nicegui/files/9969464/importtime_no_chartcomponents_gridcomponents_pandas.log)
[importtime_no_chartcomponents_pandas.log](https://github.com/zauberzeug/nicegui/files/9969466/importtime_no_chartcomponents_pandas.log)
[importtime_optimized.log](https://github.com/zauberzeug/nicegui/files/9969467/importtime_optimized.log)

**Comment by falkoschindler** [comment]
You're right. We didn't think about JustPy importing matplotlib.

Since I don't see an easy way to prevent JustPy from doing that and we're planning to remove JustPy anyway in version 1.0, I'll postpone this issue until then.

**Comment by falkoschindler** [comment]
This issue is fix since NiceGUI 1.0.
