### ISSUE TITLE
add a st.code component similar to the one provided in the streamlit module in the official document of Nicegui

### ISSUE THREAD

**Issue by angel0614563** [zauberzeug/nicegui#1567]
### Description

I hope to add a st.code component similar to the one provided in the streamlit module in the official document of Nicegui, displaying different code blocks and having a one click copy function.

_Originally posted by @angel0614563 in https://github.com/zauberzeug/nicegui/discussions/1536_

**Comment by rodja** [comment]
@angel0614563 why have you created a new issue for that? The feature request in #1536 is still valid and already provides some hints.
