### ISSUE TITLE
NiceGUI link in startup message is incorrect with reload=False

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#157]
I'm running NiceGUI with e.g. `    ui.run(port=8078)`. The message I get on startup is: `NiceGUI ready to go on http://127.0.0.1:8000`. The IP address should be 0.0.0.0 and port should be 8078.

`netstat -ant` output: `tcp        0      0 0.0.0.0:8078            0.0.0.0:*               LISTEN`

**Comment by falkoschindler** [comment]
This is strange. I can't reproduce the behavior you're describing. Can you, please, give more details about your OS and Python version? Oh and can you confirm that you have JustPy 0.2.3 installed?

```bash
python3 -c 'import justpy; print(justpy.__version__)'
```

I'm testing on MacOS 12.5.1 with Python 3.10.6 and the following test app:

```python
#!/usr/bin/env python3
from nicegui import ui

ui.label('Hello, world!')

ui.run(port=1234)
```

The resulting startup message is as expected:

> NiceGUI ready to go on http://0.0.0.0:1234

**Comment by rodja** [comment]
Maybe you have the `PORT` set to `8000` as environment variable or within the optional `justpy.env` file?

**Comment by me21** [comment]
It happens if I set `reload=False` parameter.

**Comment by falkoschindler** [comment]
Thanks for the update! Now that you mention the `reload` parameter it totally makes sense: The parameter impacts in which process the server is startet and in which the UI is running. And I guess the environment variables PORT and HOST are not set in the correct process or not at the right time. I'll look into it.
