### ISSUE TITLE
AsyncServer' object has no attribute 'get_environ

### ISSUE THREAD

**Issue by Norwalker** [zauberzeug/nicegui#1582]
### Description

i pull docker images  
pip install nicegui 
my docker shell:
   docker run -dt --name nice -p 8082:8082 --privileged=true --gpus all -v /data/web/Root/Files:/home 8f1
but
 after python my file ,broswer show i want 
when i click something 
the terminal report bug : AsyncServer object has no attribute 'get_environ
please ask for me
thanks

**Comment by rodja** [comment]
I'm sorry. Your description is quite cryptic. Can you share the full error as it appears on the console? And the full content of your Dockerfile?

**Comment by falkoschindler** [comment]
I close this issue due to inactivity. Feel free to re-open it with the information requested by @rodja.
