### ISSUE TITLE
Text inputs don't work in native mode (MacOS 13.5.1, nicegui 1.3.11)

### ISSUE THREAD

**Issue by birchtree02** [zauberzeug/nicegui#1585]
### Description

1. Use a text input in native mode
```python3
from nicegui import ui

ui.input("Enter your name")
ui.run(native=True)
```
2. I expect to be able to type in the text input
3. No text is added to the input box, but is instead typed in the latest accessed text box in another window (e.g. terminal, text editor etc.)

This works fine in the browser

**Comment by rodja** [comment]
It's working for me. What OS are you using? Are there any error messages on the console? Does `ui.button('check', on_click=lambda: ui.notify('bam!'))` work?

**Comment by falkoschindler** [comment]
This sounds like a known pywebview issue: https://github.com/zauberzeug/nicegui/issues/1205.
@birchtree02, can you verify that my code example from https://github.com/zauberzeug/nicegui/issues/1205#issuecomment-1647503872 yields the same problem? Thanks!

**Comment by falkoschindler** [comment]
I'll close this issue due to inactivity. Without additional information there's not much we can do.
