### ISSUE TITLE
Browser is opened too early

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#159]
On my laptop, NiceGUI opens a browser tab too early resulting in "this page cannot be displayed" message.

**Comment by falkoschindler** [comment]
@me21 Can you, please, try moving the following lines down to the end of `run()` and see if it helps?

https://github.com/zauberzeug/nicegui/blob/0f675212c6496d7a6d36053f12290023e0eae61a/nicegui/run.py#L52-L53

**Comment by me21** [comment]
No, it doesn't help. The execution stops inside run() function in https://github.com/zauberzeug/nicegui/blob/0f675212c6496d7a6d36053f12290023e0eae61a/nicegui/run.py#L77-L84

**Comment by rodja** [comment]
To better investigate the issue it would be great to find a reproduction. Could you provide some informations about your Laptop, OS and your default browser? Or maybe it depends on the NiceGUI application? Do you have some example code?

**Comment by me21** [comment]
Laptop: Lenovo Legion 17ACH6, CPU AMD Ryzen 7.
OS: Windows 10 21H2
Browser: Firefox 107.

I forgot to say that the browser is already running, it's only a new tab that opens.

**Comment by rodja** [comment]
Thanks. Does it happen with every NiceGUI program? Could you temporarily change the default browser to Chrome and see what happens?

**Comment by me21** [comment]
I don't have Chrome, I have Microsoft Edge, so I tried that.
In Edge, the problem is virtually non-existent, because Edge reloads the page as soon as Python completes startup. The notification about being unable to load the page is shown for a second, then the page is reloaded and NiceGUI is shown.

**Comment by rodja** [comment]
> In Edge, the problem is virtually non-existent, because Edge reloads the page as soon as Python completes startup.

Chrome does it the same way. Could you try with the [v1 branch](https://github.com/zauberzeug/nicegui/tree/v1)? The release is very near and we have changed quite a bit... maybe we get lucky.

**Comment by rodja** [comment]
We just released NiceGUI 1.0. @me21 could you check if the problem still exists?

**Comment by rodja** [comment]
@me21 have you found the time to test it again with the latest NiceGUI version? Otherwise I would close the issue at the end of the week...

**Comment by me21** [comment]
Unfortunately no. I think I should close the issue for now. If me or someone else finds it still not fixed, we can reopen this.
