### ISSUE TITLE
ui.input().props() doesn't work

### ISSUE THREAD

**Issue by v479038280** [zauberzeug/nicegui#1612]
### Description

The props rounded doesn't work fine in `ui.input('aaa').props('filled rounded')`
here is the result
![微信截图_20230913132738](https://github.com/zauberzeug/nicegui/assets/25096045/7e943d85-e4e1-4752-a1ca-acc7fa6f2d9f)

**Comment by natankeddem** [comment]
If you look at the docs it looks like it is doing things correctly? https://quasar.dev/vue-components/input
I am going to assume you actually want something like this:
```py
from nicegui import app, native_mode, ui

ui.input('not this').props('filled rounded')
ui.input('this').props('rounded standout')
ui.run()
```

**Comment by falkoschindler** [comment]
I'll close this issue since it's exactly how Quasar's QInput is supposed to look with "filled rounded".
