### ISSUE TITLE
ui.input demo page broken

### ISSUE THREAD

**Issue by natankeddem** [zauberzeug/nicegui#1616]
### Description

At first I thought it was something on my end but I think this is legitimate. On https://nicegui.io/documentation/input you will notice only the first demo populates correctly. I tried it locally and got the same behaviour with these errors in the console. Other demos might also be affected, I didn't check all of them.

```
c:\PythonWs\ngd99\nicegui\website\intersection_observer.py:18: RuntimeWarning: coroutine 'more.<locals>.autocomplete_demo' was never awaited
  handle_event(self.on_intersection, UiEventArguments(sender=self, client=self.client))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
c:\PythonWs\ngd99\nicegui\website\intersection_observer.py:18: RuntimeWarning: coroutine 'more.<locals>.clearable' was never awaited
  handle_event(self.on_intersection, UiEventArguments(sender=self, client=self.client))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
c:\PythonWs\ngd99\nicegui\website\intersection_observer.py:18: RuntimeWarning: coroutine 'more.<locals>.styling' was never awaited
  handle_event(self.on_intersection, UiEventArguments(sender=self, client=self.client))
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

It appears to be caused from this commit:
https://github.com/zauberzeug/nicegui/commit/f253d9f3de4ee816281496426c9627ccecda09e2

**Comment by falkoschindler** [comment]
As I just commented on #1617, it is so good you spotted this issue, @natankeddem!
And I agree that https://github.com/zauberzeug/nicegui/commit/f253d9f3de4ee816281496426c9627ccecda09e2 ultimately caused the bug.
