### ISSUE TITLE
Discrepancy between documentation and code for ui.tree

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#162]
At https://nicegui.io/reference#tree, the handler is called `on_click` in the doc snippet to the left, and `on_select` in the code snippet on the right.
The source code of NiceGUI contains `on_select`.

**Comment by falkoschindler** [comment]
Thanks for pointing this out! We fixed it in
https://github.com/zauberzeug/nicegui/commit/70a0ab8cd625bbda58a02beb4003c9874e12a7a4
