### ISSUE TITLE
Loss of ui.tab() Animation When Utilizing ui.link()

### ISSUE THREAD

**Issue by miqsoft** [zauberzeug/nicegui#1622]
### Description

When employing ui.link() in conjunction with ui.tab() as depicted below, the animation of ui.tab() vanishes.
Here is a minimal example showing the problem. 

``` python3

@ui.page('/')
def homepage():
    with ui.tabs():
        with ui.link(target='/'):
            ui.tab('Home')
        with ui.link(target='/test'):
            ui.tab('Test')

    ui.label('Home')

@ui.page('/test')
def testpage():
    with ui.tabs():
        with ui.link(target='/'):
            ui.tab('Home')
        with ui.link(target='/test'):
            ui.tab('Test')

    ui.label('Test')

```

It would be nice to have a way utilizing ui.tab() with links since it can be nicely used to create  a header for navigation through pages. In Quasar this can be realized by using the q-route-tab ([quasardocs](https://quasar.dev/vue-components/tabs#connecting-to-vue-router)).

**Comment by falkoschindler** [comment]
I'm not sure what exactly you're expecting to see and what is happening instead. When I try it, the tabs are somewhat animated.

Besides that this is not the intended way of using `ui.tab`. You might want to have a look into our [Single Page App example](https://github.com/zauberzeug/nicegui/tree/main/examples/single_page_app/) where we navigate using tabs without reloading the page.

**Comment by miqsoft** [comment]
Thanks a lot for the answer! I overlooked the [Single Page App example](https://github.com/zauberzeug/nicegui/tree/main/examples/single_page_app/). This helps a lot and makes it quite simple to utilize with tabs. 
I rewrote the main.py form the SPA example above to work with tabs as needed in my case. 
Here is the example:

``` python3
#!/usr/bin/env python3
from router import Router

from nicegui import ui

class Demo:
    current_tab: str
    def __init__(self):
        self.current_tab = ''

@ui.page('/')  # normal index page (e.g. the entry point of the app)
@ui.page('/{_:path}')  # all other pages will be handled by the router but must be registered to also show the SPA index page
def main():
    router = Router()

    demo = Demo()

    def show_route():
        router.open(demo.current_tab)

    @router.add('/')
    def show_one():
        ui.label('Content One').classes('text-2xl')

    @router.add('/two')
    def show_two():
        ui.label('Content Two').classes('text-2xl')

    @router.add('/three')
    def show_three():
        ui.label('Content Three').classes('text-2xl')
        

    # adding some navigation buttons to switch between the different pages
    with ui.tabs().on('update:model-value', show_route).bind_value(demo, 'current_tab'):
        ui.tab('', label='One').classes('w-32')
        ui.tab('two', label='Two').classes('w-32')
        ui.tab('three', label='Three').classes('w-32')

    # this places the content which should be displayed
    router.frame().classes('w-full p-4 bg-gray-100')


ui.run()
```
