### ISSUE TITLE
Pagination slot for ui.table not working

### ISSUE THREAD

**Issue by DipanshuJuneja** [zauberzeug/nicegui#1632]
### Description

Hi, I just discovered Nicegui a couple days back, and have been really liking it. Thank you for all your hard work building this. 

So, I'm trying to customize the Table component and have added slots for 'top' and 'body' for ui.table/q-table. However, the 'pagination' slot does not seem to work. 

```
table.add_slot('body', r'''
    <q-tr :props="props">
            <q-td key="...... >'''

table.add_slot('top', r'''
        <q-checkbox  .....>'''

 table.add_slot('pagination', r'''
       <q-checkbox />'''
```
 I inspected my HTML and I can't see any element/class for Table bottom as well. 

<img width="608" alt="Screenshot 2023-09-16 133606" src="https://github.com/zauberzeug/nicegui/assets/14841097/ed408b67-042c-4ad4-9a68-08fc5be803f3">

**Comment by falkoschindler** [comment]
Hi @DipanshuJuneja,
Can you, please, give a minimum reproducible code example? This would allow us to help more efficiently. Thanks!

**Comment by DipanshuJuneja** [comment]
Hi @falkoschindler, thanks for the quick response. In this below example, I have a basic slot added for pagination slot which is not getting displayed in the UI. 
<img width="778" alt="Screenshot 2023-09-16 133606" src="https://github.com/zauberzeug/nicegui/assets/14841097/7dc03ba2-44b0-462f-99fb-8fb01a3cf7c1">


```from nicegui import ui

columns = [
    {'name': 'name', 'label': 'Name', 'field': 'name'},
    {'name': 'age', 'label': 'Age', 'field': 'age'},
]
rows = [
    {'name': 'Alice', 'age': 18},
    {'name': 'Bob', 'age': 21},
    {'name': 'Carol', 'age':67},
]

table = ui.table(columns=columns, rows=rows, row_key='name').classes('w-72')
table.add_slot('header', r'''
    <q-tr :props="props">
        <q-th auto-width />
        <q-th v-for="col in props.cols" :key="col.name" :props="props">
            {{ col.label }}
        </q-th>
    </q-tr>
''')
table.add_slot('top', r'''
        <q-checkbox label="Label on Top"/>
               ''')
table.add_slot('pagination', r'''
        <q-checkbox label="Label on Pagination slot"/>
               ''')
table.add_slot('body', r'''
    <q-tr :props="props">
        <q-td auto-width>
            <q-btn size="sm" color="accent" round dense
                @click="props.expand = !props.expand"
                :icon="props.expand ? 'remove' : 'add'" />
        </q-td>
        <q-td v-for="col in props.cols" :key="col.name" :props="props">
            {{ col.value }}
        </q-td>
    </q-tr>
    <q-tr v-show="props.expand" :props="props">
        <q-td colspan="100%">
            <div class="text-left">This is {{ props.row.name }}.</div>
        </q-td>
    </q-tr>
''')


ui.run(title='My App', native=True, window_size=(1024, 800), fullscreen=False)
```

**Comment by falkoschindler** [comment]
Oh, I see. Looks like you need to set `ui.table(..., pagination=True)` to actually see the pagination slot.

**Comment by DipanshuJuneja** [comment]
Yes, this worked. Thanks
