### ISSUE TITLE
Binding is not reapplied correctly in ui.stepper()

### ISSUE THREAD

**Issue by rodja** [zauberzeug/nicegui#1638]
### Description

Consider this code:

```py
name = 'Bob'

with ui.stepper().classes('w-96') as stepper:
    with ui.step('Set name'):
        ui.input('Name').bind_value(globals(), 'name')

        with ui.stepper_navigation():
            ui.button('Next', on_click=stepper.next)

    with ui.step('Show name'):
        ui.label().bind_text_from(globals(), 'name')
        with ui.stepper_navigation():
            ui.button('Back', on_click=stepper.previous)

ui.timer(1, lambda: print(name))
```

On first start the name input is correctly filled with "Bob". If the name is changed via the input field the changed value is printed to the console. Also on the next step the value is correctly shown. But when pressing "Back" the input field shows the value "Bob" again. I would expect it to be the value I've typed in earlier (and which is still printed on the console).

I now this can be fixed by setting the `keep-alive` prop on the stepper. But then I do not need the binding at all because the elements will be reused.

**Comment by falkoschindler** [comment]
I think we can eliminate binding from the reproduction:

```py
name = 'Bob'

with ui.stepper() as stepper:
    with ui.step('Set name'):
        ui.input('Name', value=name, on_change=lambda e: globals().update(name=e.value))
        ui.button('Next', on_click=stepper.next)
    with ui.step('Done'):
        ui.button('Back', on_click=stepper.previous)

ui.timer(1, lambda: print(name))
```

**Comment by falkoschindler** [comment]
Ok, we agreed to introduce a `keep-alive` parameter for `ui.stepper` like we did for `ui.tab_panels`.

**Comment by rodja** [comment]
Side note: the issue was uncovered while trying to answer a question [over on Discord](https://discord.com/channels/1089836369431498784/1152360407432958082).
