### ISSUE TITLE
connection issues when looking at developer tools

### ISSUE THREAD

**Issue by Smug246** [zauberzeug/nicegui#1640]
### Description

this didnt happen before and now doesn't allow me to check the responsiveness of my site. but basically when i run a simple script like the one below:

```python
from nicegui import ui

ui.label('Hello World')

ui.run()
```
and then do `ctrl + shift + I` to access the developer tools. instantly the websocket connection fails.
![image](https://github.com/zauberzeug/nicegui/assets/99215486/5a1f4c8e-b6e6-42ba-8079-28e102e4a922)

**Comment by Smug246** [comment]
windows + brave

**Comment by falkoschindler** [comment]
@Smug246 Does the issue still persist? Have you checked other browsers? Are you using a recent version of NiceGUI?

**Comment by falkoschindler** [comment]
I'll close this issue for now.
@Smug246 Feel free to re-open it if you have new information for us. Thanks!
