### ISSUE TITLE
Menu Demo

### ISSUE THREAD

**Issue by natankeddem** [zauberzeug/nicegui#1657]
### Description

Is the demo `Custom Context Menu` on https://nicegui.io/documentation/menu rendering correctly? All I see is a static image with no visible elements to interact with. Moving my mouse around the image doesn't seem to cause anything to popup either.

![image](https://github.com/zauberzeug/nicegui/assets/44515217/becc9051-8f18-4496-925b-fa9472158b2a)

**Comment by rodja** [comment]
Well, a context menu normally opens on right click: https://quasar.dev/vue-components/menu#context-menu

**Comment by natankeddem** [comment]
It's just me being stupid then. 🤣
