### ISSUE TITLE
Documentation for menu error

### ISSUE THREAD

**Issue by gavinpotter** [zauberzeug/nicegui#1659]
### Description

If you load the example in the menu documentation and run it on a windows desktop machine on its own the menu does not open when you click on it.  The workaround is to add an on_click = lambda: menu.open() into the button.
I can't get the context menu example to work at all on a windows machine.

**Comment by falkoschindler** [comment]
Do you have a recent NiceGUI version installed?
```bash
python -c 'import nicegui; print(nicegui.__version__)'
```

**Comment by gavinpotter** [comment]
version 1.3.11

**Comment by falkoschindler** [comment]
Do you get different results for different browsers? Because I wonder why the OS should be crucial here. It should be - if at all - a browser issue.
And can you, please, check the examples at https://quasar.dev/vue-components/menu#example--basic? Thanks!

**Comment by gavinpotter** [comment]
I've tried the Quasar examples and the ones on your website they both work.  I've tried the code with both Chrome and Microsoft Edge and it doesn't work on either.  Just for the avoidance of doubt, this is the entirety of the code that I am running (lifted from your website).
```
from nicegui import ui

with ui.row().classes('w-full items-center'):
    result = ui.label().classes('mr-auto')
    with ui.button(icon='menu'):
        with ui.menu() as menu:
            ui.menu_item('Menu item 1', lambda: result.set_text('Selected item 1'))
            ui.menu_item('Menu item 2', lambda: result.set_text('Selected item 2'))
            ui.menu_item('Menu item 3 (keep open)',
                         lambda: result.set_text('Selected item 3'), auto_close=False)
            ui.separator()
            ui.menu_item('Close', on_click=menu.close)

ui.run()
```

**Comment by gavinpotter** [comment]
I'm using python 3.11.3

**Comment by falkoschindler** [comment]
Can anyone else confirm this bug?
What could be the cause?

**Comment by gavinpotter** [comment]
Ok - This is very obscure.  I'm using nicegui to create a webapp and running it within a c# program   If I run it directly from the terminal it works fine.

I'll investigate to see if I can find the cause.

**Comment by gavinpotter** [comment]
Ok - Its a very obscure bug on my part.  Apologies.  I've no idea why the rest of the package works without problems though,
