### ISSUE TITLE
some mdi-icons are misplaced 

### ISSUE THREAD

**Issue by WolfgangFahl** [zauberzeug/nicegui#1664]
### Description

I am trying to extend the standard menu for [nicegui widgets](https://github.com/WolfgangFahl/nicegui_widgets) with an "about" button and icon

```python
  def setup_menu(self):
        """Adds a link to the project's GitHub page in the web server's menu."""
        version=self.config.version
        self.config.color_schema.apply()
        with ui.header() as self.header:
            self.link_button("home","/","home")
            self.link_button("settings","/settings","settings")
            self.configure_menu()
            self.link_button("github",version.cm_url,"bug_report")
            self.link_button("chat",version.chat_url,"chat")
            self.link_button("help",version.doc_url,"help")
            self.link_button("about","/about","information-outline")

   def link_button(self, name: str, target: str, icon_name: str,new_tab:bool=True):
        """
        Creates a button with a specified icon that opens a target URL upon being clicked.
    
        Args:
            name (str): The name to be displayed on the button.
            target (str): The target URL that should be opened when the button is clicked.
            icon_name (str): The name of the icon to be displayed on the button.
            new_tab(bool): if True open link in new tab
    
        Returns:
            The button object.
        """
        with ui.button(name,icon=icon_name) as button:
            button.on("click",lambda: (ui.open(target,new_tab=new_tab)))
        return button
```
While the other icons show ok the information/information-outline button is misplaced:

![grafik](https://github.com/zauberzeug/nicegui/assets/1336221/1f70942b-bebd-45f1-a9fe-ca1eacca6f59)

If i use a different Icon such as a second "help" the icon is placed left of the text in the button.

**What might cause this misplacement and how can it be mitigated?**

I am using https://mdisearch.com/ for search mdi-icons. 
**Which mdi-icons might have this misplacemente behavior?**

**Comment by falkoschindler** [comment]
Minimum example:
```py
ui.button('home', icon='home')
ui.button('settings', icon='settings')
ui.button('github', icon='bug_report')
ui.button('chat', icon='chat')
ui.button('help', icon='help')
ui.button('about', icon='information')
```

I'm not sure about mdisearch.com. But as documented on https://nicegui.io/documentation/icon, we recommend using https://fonts.google.com/icons?icon.set=Material+Icons as a reference for possible icon names. And to my knowledge there is no "information", only "info".

**Comment by WolfgangFahl** [comment]
Do you get the same misplacement effect for information?

**Comment by falkoschindler** [comment]
Yes, apparently it happens for every invalid icon name starting with a valid name, like "information", "infoxxx", "face-swap", ...
