### ISSUE TITLE
`ui.aggrid.from_pandas` not display any data when dataframe contains non-string column name

### ISSUE THREAD

**Issue by CrystalWindSnake** [zauberzeug/nicegui#1665]
### Description

```python
from nicegui import ui
import pandas as pd

df = pd.DataFrame({1: list("abc"), "num": range(3)})
ui.aggrid.from_pandas(df)
```

It seems that when defining `columnDefs`, convert `col` to `str` can solve the problem.

[source code](https://github.com/zauberzeug/nicegui/blob/dad7729955e9d8415ee999ec22dc7d43548d58d2/nicegui/elements/aggrid.py#L55)

**Comment by falkoschindler** [comment]
Thanks for spotting this, @CrystalWindSnake!
I'm not sure how common this case is and if `str(col)` introduces any new problems. But if we expect `col` to be a string, wrapping it with `str` shouldn't do any harm. And this way your example works indeed. 👍
