### ISSUE TITLE
Nicegui DDOS help!

### ISSUE THREAD

**Issue by DoPaminexL** [zauberzeug/nicegui#1695]
### Description

Dear Nicegui Team,

I encountered a minor issue while using Nicegui. When attempting to asynchronously retrieve user IP addresses, the website is susceptible to DDoS attacks, resulting in crashes. The DDoS attack was simulated using the Apache Bench (AB) stress testing tool. During the attack, there is a frequent initiation of the first handshake, without proceeding to the next step of data transmission (i.e., not completing the normal three-way handshake), leading to continuous timeout errors of 3 seconds, ultimately causing the website to crash.

Below is the code I used to test Nicegui:

```py
from nicegui import ui, Client

@ui.page("/")
async def index(client: Client):
    await client.connected()
    connect_ip = client.ip
    print(connect_ip)

ui.run()
```

When the code provided is attacked, it will cause frequent output 3 Sensc!!!
 
 If the FastAPI method is used to retrieve the connected user's IP address, the IP of the DDoS attacker can be successfully logged. However, Nicegui only generates a frequent output 3 Sensc errors and is unable to display the attacker's IP address. 
 
 Fastapi Code:
 
 ```py
from fastapi import FastAPI, Request, HTTPException
from nicegui import ui, Client

@ui.page("/")
async def index(request: Request):
    connect_ip = request.client.host
    print(connect_ip)

ui.run()
```

**Comment by rodja** [comment]
Yes. That could be an issue. But 

```py
@ui.page("/")
async def index(request: Request):
   connect_ip = request.client.host
   print(connect_ip)
```

is valid NiceGUI code, so if you want to log attackers ip addresses this should be used. Or do you propose to change `client.ip` to use the request object internally instead of waiting for the handshake?

**Comment by DoPaminexL** [comment]
I like NiceGui's .on_disconnect method, but there is no way to solve this problem

**Comment by DoPaminexL** [comment]
> Yes. That could be an issue. But
> 
> ```python
> @ui.page("/")
> async def index(request: Request):
>    connect_ip = request.client.host
>    print(connect_ip)
> ```
> 
> is valid NiceGUI code, so if you want to log attackers ip addresses this should be used. Or do you propose to change `client.ip` to use the request object internally instead of waiting for the handshake?
![image](https://github.com/zauberzeug/nicegui/assets/111892202/f0e51a70-abf4-45b3-bb1c-890894e60163)

**Comment by DoPaminexL** [comment]
I like NiceGui's .on_disconnect method, but there is no way to solve this problem

**Comment by rodja** [comment]
We created feature request https://github.com/zauberzeug/nicegui/discussions/1727 to improve this.
