### ISSUE TITLE
Connection lost popup drawer interaction

### ISSUE THREAD

**Issue by natankeddem** [zauberzeug/nicegui#1729]
### Description

Using the following code:
```py
from nicegui import ui

with ui.left_drawer(top_corner=True, bottom_corner=True).style("background-color:#d7e3f4").props("width=150"):
    ui.label("LEFT")

ui.run()
```
I am getting this result:
![image](https://github.com/zauberzeug/nicegui/assets/44515217/b84858af-c178-4aeb-922b-e6885ec349a1)

After shutting the application down I get an obscured "Connection lost." popup.

**Comment by falkoschindler** [comment]
Thanks for reporting this issue, @natankeddem!

Looks like adding `z-index: 1000` to `#popup { }` in nicegui.css does the trick.

**Comment by natankeddem** [comment]
Just for my own knowledge...you got `z-index: 1000` from:
`quasar.css`
```js
.q-drawer {
  position: absolute;
  top: 0;
  bottom: 0;
  background: #fff;
  z-index: 1000;
}
```
Does that sound correct?

**Comment by falkoschindler** [comment]
Oh, I actually didn't search for the z-index of `.q-drawer`. I just tried a large number. Turns out Quasar did the same and luckily our popup wins the tie. So you could argue 1000 is just the right value. 😄
