### ISSUE TITLE
UI elements malfunctioning on Iceraven/mobile Firefox

### ISSUE THREAD

**Issue by tbart** [zauberzeug/nicegui#173]
Hi!
Just tried out the demo on the front page (nicegui.io).

On Iceraven (basically mobile Firefox), most of the elements do not work as expected.

Checkbox, radiobutton, on-off slider, box selects not clickable at all.

No element creates output, not even the ones reacting (click button, number slider).

**Comment by falkoschindler** [comment]
Thanks for reporting this issue!
There seems to be a problem with our proxy that occurs on Safari and Firefox, but not on Chrome. Maybe it's related to your problem with Iceraven. We'll look into it as soon as possible.

**Comment by rodja** [comment]
We had an error in our `www.nicegui.io` redirection. It should now be fixed. @tbart could you please try again? Does it now work for you? I only tested Iceraven successfully after the fix...

**Comment by tbart** [comment]
Tested, works on Iceraven and Bromite (with half a second delay at every interaction, both browsers the same, this seems to be unrelated)!
Thanks!
