### ISSUE TITLE
AttributeError: module 'nicegui.ui' has no attribute 'carousel'

### ISSUE THREAD

**Issue by CyberMindX** [zauberzeug/nicegui#1730]
### Description

I wasn't able to execute your carousel picture example: https://nicegui.io/documentation#carousel
further digging showed that the lastest commit: 1010535befc70233394dd3dc86a80f08248e6c01 doesn't include this method anymore.

**Comment by natankeddem** [comment]
Which method specifically? Do you mean element? The demo you linked to seems to work here. You are running the exact demo?
```py
from nicegui import ui

with ui.carousel(animated=True, arrows=True, navigation=True).props('height=180px'):
    with ui.carousel_slide().classes('p-0'):
        ui.image('https://picsum.photos/id/30/270/180').classes('w-[270px]')
    with ui.carousel_slide().classes('p-0'):
        ui.image('https://picsum.photos/id/31/270/180').classes('w-[270px]')
    with ui.carousel_slide().classes('p-0'):
        ui.image('https://picsum.photos/id/32/270/180').classes('w-[270px]')

ui.run()
```
If you are not you should probably post your code here. It looks like the element is still there:
https://github.com/natankeddem/nicegui/blob/main/nicegui/elements/carousel.py

**Comment by CyberMindX** [comment]
Thank you for your response! that example is the one I can't run, so it may be a bug of my own.. I created a new virtual environment in windows, install nicegui with pip, copy that same example https://github.com/natankeddem/nicegui/blob/main/nicegui/elements/carousel.py and after I run it, this error appears: [AttributeError: module 'nicegui.ui' has no attribute 'carousel']

**Comment by natankeddem** [comment]
If you `pip freeze` what is your versions for `nicegui`?

**Comment by CyberMindX** [comment]
nicegui==1.2.24

**Comment by natankeddem** [comment]
That is a pretty old version, older than `ui.carousel`. `ui.carousel` was introduced in [v1.3.4](https://github.com/zauberzeug/nicegui/releases/tag/v1.3.4). The latest version is [v1.3.15](https://github.com/zauberzeug/nicegui/releases/tag/v1.3.15).

**Comment by falkoschindler** [comment]
@natankeddem is absolutely right: `ui.carousel` has been introduced in [v1.3.4](https://github.com/zauberzeug/nicegui/releases/tag/v1.3.4).
Therefore I assume this issue is resolved by upgrading to a more recent NiceGUI version.

**Comment by CyberMindX** [comment]
I see the error, while using "pip install nicegui", it installed an older version. Appreciate the help.
