### ISSUE TITLE
Header is sometimes unusable, necessitating browser restart (Brave)

### ISSUE THREAD

**Issue by iron3oxide** [zauberzeug/nicegui#1751]
### Description

As you will see in the code snippet, I am trying to achieve something similar to the menu_and_tabs example. However, when adding tab panels, my header becomes unusable. I can't switch tabs or click buttons anymore. I have tried nesting things differently, omitting CSS classes, not putting everything in a column and accessing tabs via their name instead, all to no avail.

```python

@ui.page("/home", title="Startseite")
def home():
    with ui.column():
        with ui.header().classes(replace="row items-center"):
            with ui.button():
                with ui.avatar(color="purple"):
                    ui.label("JH")
                with ui.menu():
                    ui.menu_item("A")
                    ui.menu_item("B")
                    ui.menu_item("Abmelden")

            with ui.row().classes("absolute-center"):
                with ui.tabs() as tabs:
                    one = ui.tab("Einträge").classes("text-capitalize")
                    two = ui.tab("Belegung").classes("text-capitalize")
                    three = ui.tab("Beratung").classes("text-capitalize")
                    four = ui.tab("Statistik").classes("text-capitalize")

            with ui.right_drawer(value=False) as right_drawer:
                ui.button("Test")

            ui.button(icon="menu", on_click=lambda: right_drawer.toggle()).classes(
                "absolute-right"
            )

        with ui.tab_panels(tabs, value=one):
            with ui.tab_panel(one):
                with ui.card():
                    ui.label("A")
            with ui.tab_panel(two):
                with ui.card():
                    ui.label("B")
            with ui.tab_panel(three):
                with ui.card():
                    ui.label("C")
            with ui.tab_panel(four):
                with ui.card():
                    ui.label("D")


ui.run(dark=False)
```

**Comment by falkoschindler** [comment]
@iron3oxide Do I understand correctly that you can't switch tabs when running the code you posted?
Do the code snippets on https://nicegui.io/documentation/tabs work?
Which browser are you using?

**Comment by natankeddem** [comment]
Seems to work for me?
[google_screen_recording_2023-10-05T17-34_11.789Z.webm](https://github.com/zauberzeug/nicegui/assets/44515217/9371ffcb-6d45-4c4b-8daa-c6346e4db275)

**Comment by iron3oxide** [comment]
I'll be damned, now it's working even though I didn't change anything. Regarding the tab examples in the documentation: nicegui.io was borderline unusable for me for the past few hours, kept getting 502s

**Comment by iron3oxide** [comment]
To clarify: yes, I couldn't change any tabs and clicking the buttons in the header didn't work either. Now it's all working miraculously and nicegui.io is also up again for me

**Comment by iron3oxide** [comment]
Aaand it's not working again :face_exhaling: 

All I did was attempt to implement a dark mode toggle. Even after I removed all that code, the problem is still there for some reason.

**Comment by falkoschindler** [comment]
The terminal log looks unfamiliar. Is it maybe about some Brave internals?

Without some kind of reproduction it's pretty hard for us to tackle the problem. Can you try to narrow it down to a minimal code example? Your original code contains a number of elements that - according to the description - seem unrelated to the problem. And does it occur with specific browsers? Are you using a recent NiceGUI version?

**Comment by iron3oxide** [comment]
Unfortunately I am a bit puzzled myself as to what exactly causes this, so I changed the title to reflect that. My best guess: make page with header -> add erroneous code somewhere -> something silently fails -> header becomes unusable until Brave is restarted

I am using the latest version of nicegui, I'll try and reproduce it with a leaner snippet and test it on different browsers

**Comment by falkoschindler** [comment]
@iron3oxide Are you still working on a reproduction for this issue? Or can we close it?

**Comment by iron3oxide** [comment]
Unfortunately I'm too busy with university at the moment, so I won't be able to come up with something decent anytime soon. Let's close this

**Comment by iron3oxide** [comment]
Fyi: just happened again to me with completely different header code. Suddenly no interactive element worked at all, even after restarting the app. I then closed it again, closed VSCode as well, retried and voila, everything's working as expected again. Maybe it's some sort of connectivity issue? I certainly don't feel like I can reliably reproduce it, so I won't reopen, but wanted to give this update.
