### ISSUE TITLE
NiceGUI creates memory errors in other programs

### ISSUE THREAD

**Issue by ezio416** [zauberzeug/nicegui#178]
Any time I have NiceGUI server running on a low-spec system (2GB RAM), I experience "out of memory" errors in other programs, even though the Python process is only using a few MB. The programs in question are an installer (Paessler probe), 7-Zip, and Python itself when trying to zip a file using most compression methods (deflate is the only one that seems to always work). I know I have plenty of memory for these operations as they complete successfully with much less RAM available, just as long as NiceGUI isn't running.

**Comment by rodja** [comment]
That sounds very spooky. What operating system are you running? And what kind of hardware?

**Comment by me21** [comment]
On my system (Windows 10), the Task Manager on Processes tab shows Python interpreter to take only 1,4 Mb, whereas full memory consumption on Performance tab goes several hundreds Mbs up.

**Comment by ezio416** [comment]
I'm on Windows 8 (8-6.2.9200-SP0), Python 3.8.10, 2GB RAM, Intel Atom E3845. I do see in Resource Monitor, Python is using about 325MB of RAM, but I still have a few hundred MB free

**Comment by me21** [comment]
Do you have swap file enabled?

**Comment by rodja** [comment]
Could anyone else reproduce this problem? We do not have a comparable system configuration for reproduction...

**Comment by rodja** [comment]
We have changed quite a lot regarding the memory management in the last releases. We guess the issue is solved. Otherwise you can reopen it anytime.
