### ISSUE TITLE
AG Grid: `get_client_data()` causes timeout in `run_javascript()`

### ISSUE THREAD

**Issue by bnxvs** [zauberzeug/nicegui#1794]
### Description

Hello.
I encountered a strange situation while running a script on the server. Here is a sample code:
```py
df = connection() # pd.Dataframe(from sql table)

table = ui.aggrid({
        'columnDefs': [
            {"headerName": "#", "valueGetter": "node.rowIndex + 1",
                "maxWidth": 80},  # нумерация строк в таблице
            {"headerName": "last_name", "field": "l_name",
             'filter': 'agTextColumnFilter', 'floatingFilter': True, "maxWidth": 200},
            {"headerName": "first_name", "field": "f_name", 'filter': 'agTextColumnFilter',
             'floatingFilter': True, "maxWidth": 200},
            {"headerName": "country", "field": "country",
             'filter': 'agTextColumnFilter', 'floatingFilter': True, "maxWidth": 150, },
            {"headerName": "pay_date", "field": "pay_date",
             "editable": True, "maxWidth": 120},
            {"headerName": "aproved", "field": "aproved",
             "editable": True, "maxWidth": 150}
        ],
        'rowData': df.to_dict('records'),
        'rowSelection': 'single',
    }, auto_size_columns=True).style('font-size: 16px; height: 70vh; overflow: auto;')

   async def save_df():
        data = await table.get_client_data()
        if data:
            df2 = pd.DataFrame.from_dict(data)
            df = connection()
            merged = pd.merge(df, df2, how='outer', indicator=True) 
            changed_rows_in_df2 = merged[merged['_merge'] == 'right_only']
            changed_rows_in_df2 = changed_rows_in_df2[['l_name','f_name','country','pay_date','aproved']]
            # Write to database
            try:
                conn = duckdb.connect('guests.db')
                c = conn.cursor()
                for index, row in changed_rows_in_df2.iterrows():
                    sql_m = f'UPDATE guests SET pay_date = ?, aproved = ? WHERE l_name = ? AND f_name = ?'
                    c.execute(sql_m, (row['pay_date'], row['aproved'], row['l_name'], row['f_name']))
            except:
                print('Bla bla bla... I`m busy!')
            finally:
                conn.commit()
                c.close()
                conn.close()
                del df2, changed_rows_in_df2

    table.on('change', save_df)

    def update_page():
        df = connection()
        table.options['rowData'] = df.to_dict('records')
        table.update()
        
    # button for update...
```

When the user checks the checkboxes fast enough the application sometimes generates an error:

> File ...python3.9/site-packages/nicegui/client.py line 145, in run_javascript raise TimeoutError('JavaScript did not respond in time')

This happens irregularly and is probably related to the server performance, because I have not managed to reproduce this situation on the local station.

**Comment by falkoschindler** [comment]
It's well possible that the server simply doesn't respond in time when calling `get_client_data()`. Unfortunately, there's currently no timeout parameter for that method. We should add that.

As a workaround, you can copy-paste the code from `get_client_data` and add a timeout yourself:
```py
data = await run_javascript(f'''
    const rowData = [];
    getElement({table.id}).gridOptions.api.forEachNode(node => rowData.push(node.data));
    return rowData;
''', timeout=5.0)
```

Another probably better approach would be to use `background_tasks.create_lazy` for `save_df`:
```py
from nicegui import background_tasks

table.on('change', lambda: background_tasks.create_lazy(save_df(), name='save_db'))
```
This ensures that the database isn't saved too often, i.e. it skips an execution if a newer "save_db" task is already waiting. (I haven't tested it though, since your code snippet isn't executable as it is.)

**Comment by bnxvs** [comment]
Я получил ошибку, со вторым методом:
```table.on('change', lambda: background_tasks.create_lazy(save_df(), name='save_db'))```

> Traceback (most recent call last):
  File "/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nicegui/background_tasks.py", line 56, in _handle_task_result
    task.result()
  File "/projext/nice_page.py", line 176, in save_df
    data = await table.get_client_data()
  File "/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nicegui/elements/aggrid.py", line 140, in get_client_data
    result = await run_javascript(f'''
  File "/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nicegui/functions/javascript.py", line 22, in run_javascript
    client = globals.get_client()
  File "/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nicegui/globals.py", line 104, in get_client
    return get_slot().parent.client
  File "/user/.pyenv/versions/3.10.7/lib/python3.10/site-packages/nicegui/globals.py", line 100, in get_slot
    return get_slot_stack()[-1]
IndexError: list index out of range
list index out of range

**Comment by bnxvs** [comment]
The first method worked! So far the application survives the test clicks, no errors in the logs.
Thank you very much for your help!
```
data = await run_javascript(f'''
    const rowData = [];
    getElement({table.id}).gridOptions.api.forEachNode(node => rowData.push(node.data));
    return rowData;
''', timeout=5.0))
```

**Comment by falkoschindler** [comment]
Just for the record: The second method probably doesn't work because the background task has no UI context and, thus, doesn't know which client (i.e. browser tab) to talk to. We would probably have to wrap the `safe_db()` call with `with table:` or `with globals.index_client:`.

**Comment by falkoschindler** [comment]
We will add `timeout` parameters after releasing 1.4, because there will be breaking changes to `run_javascript` and this way we can avoid nasty merge conflicts.

**Comment by bnxvs** [comment]
Decided today to upgrade nicegui from version 1.4.37 to the new one and found that the code is now not compatible with this solution. 
data = await run_javascript(f'''''
    const rowData = [];
    getElement({table.id}).gridOptions.api.forEachNode(node => rowData.push(node.data));
    return rowData;
'''', timeout=5.0) does not work now and raises the following error: TimeoutError: JavaScript did not respond within ... (in this case 5.0)

**Comment by falkoschindler** [comment]
@bnxvs I see you also opened a new issue #4240. Let's continue the discussion over there.
