### ISSUE TITLE
coroutine 'AsyncServer.enter_room' was never awaited 

### ISSUE THREAD

**Issue by FlynV** [zauberzeug/nicegui#1809]
### Description

I am running the basic python nicegui script and I come getting this error:

```
\Python\Python38\lib\site-packages\nicegui\nicegui.py:141: RuntimeWarning: coroutine 'AsyncServer.enter_room' was never awaited
  sio.enter_room(sid, client.id)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

Script is:

```py
from nicegui import ui

ui.label('Hello NiceGUI!')
ui.button('BUTTON', on_click=lambda: ui.notify('button was pressed'))

ui.run()
```

It was installed properly, and the server runs but it doesn't update live (have to refresh page for actions to take effect as well.

**Comment by falkoschindler** [comment]
Strange... Can you, please, tell us which version of these packages you have installed:

- nicegui
- fastapi
- fastapi-socketio
- python-socketio

Thanks!

**Comment by Barriradio** [comment]
same on python 3.10
Nicegui: Version: 1.3.16
Fastapi : Version: 0.103.2
Fastapi-Socketio: Version: 0.0.10
Python-Socketio: Version: 5.10.0

**Comment by falkoschindler** [comment]
Oh wow, python-socketio just released version 5.10.0 with a breaking change. Here is the relevant part from the [relase notes](https://github.com/miguelgrinberg/python-socketio/blob/main/CHANGES.md):
> Async versions of enter_room and leave_room should be coroutines (breaking change) ([commit](https://github.com/miguelgrinberg/python-socketio/commit/8e3460c5fcc351ca0cff83c690eedcde0e8a6e7e))

NiceGUI requires fastapi-socketio, which in turn simply requires `python-socketio = ">=4.6.0"`. So we either need to explicitly require `python-socketio = ">=4.6.0,<5.10.0"` or upgrade to `python-socketio = ">=5.10.0"` and work with the new async methods.

**Comment by falkoschindler** [comment]
I forgot to mention: As a workaround you can downgrade to python-socketio 5.9.0.

**Comment by Barriradio** [comment]
checked ok with requirements.txt:

python-socketio<5.10.0
nicegui

very good work

**Comment by FlynV** [comment]
Downgrading fixed it! 
Cheers mate!

**Comment by falkoschindler** [comment]
Great! 🙂
But we still need to improve our requirements to prevent other users from running into the same problem.

**Comment by nghia-vo** [comment]
Just run into this problem and downgrade python-socketio=5.9.0 fixed it.
