### ISSUE TITLE
TimeoutError: JavaScript did not respond in time

### ISSUE THREAD

**Issue by FlynV** [zauberzeug/nicegui#1810]
### Description

Receiving a TimeoutError (JavaScript did not respond in time) when using the run_javascript function. Script is simple, on a button click it is supposed to change the html of the page. 

### Script
```
async def removeSearches():
  await ui.run_javascript('document.getElementById("c8").outerHTML = "";')
ui.button('Clear Results', on_click= removeSearches)
```

### Error: 
```
*\site-packages\nicegui\client.py", line 145, in run_javascript
    raise TimeoutError('JavaScript did not respond in time')
TimeoutError: JavaScript did not respond in time
```

**Comment by jesanwang** [comment]
if thinking:
        ui.spinner("dots", size="md").classes("max-w-3xl mx-auto")
    await ui.run_javascript(
        "window.scrollTo(0, document.body.scrollHeight)", respond=True
    )
