### ISSUE TITLE
Can httpx dependency be updated?

### ISSUE THREAD

**Issue by tscheburaschka** [zauberzeug/nicegui#1820]
### Description

Is anything prohibiting the use of newer dependency versions? E.g. httpx 0.25.* and anyio 4.*
I wanted to migrate a web application to nicegui and now I need to downgrade parts of my dependencies (which in itself is not the end of the world, but I'm wondering if it could be fixed easily.)

Independently of that, I wanted to praise you for your effort of eventually putting together a decent and full featured GUI framework with built-in async and websockets on top of FastAPI. Something I have longed for ever since my first steps with dash.

Cheers!

**Comment by falkoschindler** [comment]
Thanks for the warm words, @tscheburaschka! 😊

Yes, I guess we can upgrade these packages.
Our upcoming release of 1.4 might be a good opportunity since the upgrade could be a breaking change for some users.

**Comment by falkoschindler** [comment]
@tscheburaschka I just checked our anyio dependency, but I can't see any restriction to <4.x. So version 4.x should be fine. It's even already set in poetry.lock:
https://github.com/zauberzeug/nicegui/blob/9c8e88e593b3cb23ed2aeeecfa39e17274000639/poetry.lock#L150-L159
Do you agree, or am I missing something?

**Comment by tscheburaschka** [comment]
It not you ;-)
I also checked only now and found that FastAPI is the one spoiling it. From their pyproject.toml:
```toml
dependencies = [
    "starlette>=0.27.0,<0.28.0",
    "pydantic>=1.7.4,!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0",
    "typing-extensions>=4.5.0",
    # TODO: remove this pin after upgrading Starlette 0.31.1
    "anyio>=3.7.1,<4.0.0",
]
```
Sorry for wasting your time on this minor issue.

**Comment by falkoschindler** [comment]
Ah, ok. That's good to hear. 🙂
What about httpx, would an upgrade to 0.25 still help? From our side it probably doesn't matter. We could also set it to a weaker requirement ">=0.24.0,<1.0.0", since we only need it for some basic things in air.py, so it's unlikely to break with a future release.

**Comment by tscheburaschka** [comment]
To adapt a popular quote: Set the dependencies "as loose as you can, but not looser." 😃 
">=0.24.0,<1.0.0" should be fine. Thanks again.

**Comment by tscheburaschka** [comment]
Just to avoid any possible confusion on this matter:
Because of the dependency chain `httpx` -> `httpcore` -> `anyio>4`, the looser requirement in `nicegui` won't change the current situation unless FastAPI upgrades their dependency on `anyio`.

**Comment by falkoschindler** [comment]
Thanks for the clarification, @tscheburaschka!
Now I wonder how our dependencies can be resolved at all if we depend on FastAPI (implying anyio<4) and httpx (implying anyio>=4)...

**Comment by tscheburaschka** [comment]
You have "httpx>=0.24.0" which allows "httpx==0.24.1" and "anyio==3.7.1" and that makes everyone happy but changes nothing, as I've said.
