### ISSUE TITLE
nicegui import error：json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by javakenny** [zauberzeug/nicegui#1825]
### Description

I mistakenly put the return result of SQLAlchemy directly into app.storage.general during debugging.
```
label_info_list = connection.execute(query)
app.storage.general['label_info_list ']=label_info_list
```

I executed this code and realized it was wrong, but after that I could no longer call nicegui, and all code that referenced nicegui would report an error: **json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)**

As long as I execute from nicegui import ui，will report an error，please how can i fix it
**Detailed error content:**
> _Traceback (most recent call last):
>   File "E:/work_code/MyBusiness/learning_fastapi/ChaQuanGou/test2.py", line 1, in <module>
>     from nicegui import ui
>   File "E:\work_code\MyBusiness\learning_fastapi\venv\lib\site-packages\nicegui\__init__.py", line 1, in <module>
>     from . import ui  # pylint: disable=redefined-builtin
>   File "E:\work_code\MyBusiness\learning_fastapi\venv\lib\site-packages\nicegui\ui.py", line 174, in <module>
>     from .elements.upload import Upload as upload
>   File "E:\work_code\MyBusiness\learning_fastapi\venv\lib\site-packages\nicegui\elements\upload.py", line 7, in <module>
>     from ..nicegui import app
>   File "E:\work_code\MyBusiness\learning_fastapi\venv\lib\site-packages\nicegui\nicegui.py", line 26, in <module>
>     globals.app = app = App(default_response_class=NiceGUIJSONResponse)
>   File "E:\work_code\MyBusiness\learning_fastapi\venv\lib\site-packages\nicegui\app.py", line 19, in __init__
>     self.storage = Storage()
>   File "E:\work_code\MyBusiness\learning_fastapi\venv\lib\site-packages\nicegui\storage.py", line 77, in __init__
>     self._general = PersistentDict(globals.storage_path / 'storage_general.json')
>   File "E:\work_code\MyBusiness\learning_fastapi\venv\lib\site-packages\nicegui\storage.py", line 44, in __init__
>     data = json.loads(filepath.read_text()) if filepath.exists() else {}
>   File "D:\install\python\lib\json\__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "D:\install\python\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "D:\install\python\lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)_

**Comment by javakenny** [comment]
Deleting storage_general.json in the .nicegui folder of the project file and making sure nicegui is the latest version can resolve this issue.

**Comment by falkoschindler** [comment]
Yes, removing the corrupt JSON file helps.
Maybe we find a more user-friendly solution in the future, e.g. ignoring the broken file and printing a warning...
