### ISSUE TITLE
Bug: Event Handling Breaks when Sub Mounting on FastAPI App using `lifespan`

### ISSUE THREAD

**Issue by rj-vera** [zauberzeug/nicegui#1849]
### Description

I wanted to run `nicegui` app alongside my existing `fastapi` app. 
I followed the example for using `ui.run_with()`

It was working fine, until I got to trying to use buttons. The events wouldn't fire. I could see the button click event in the logs, however nothing would happen in the UI.

I  was finally able to determine what was causing the issue, and its because my FastAPI app was using `lifespan`. If I move back to the deprecated `on_event("startup")` then things work fine.

I would expect that niceGUI works with FastAPI when using `lifespan` as `on_startup` is deprecated. 
https://fastapi.tiangolo.com/advanced/events/#alternative-events-deprecated

Example of how things break

```python
from contextlib import asynccontextmanager

from fastapi import FastAPI
from nicegui import ui, app

# contains all the page logic using nicegui
from my_app import nicegui_pages

# contains logic I want to run at startup
from my_app import init

@asynccontextmanager
def lifespan(app: FastAPI):
    print('Startup')
    # here is where I did some startup logic like opening DB connections
    init()
    yield
    print('shutdown')

# NOTE using the below breaks niceGUI event handling
# app = FastAPI(lifespan=lifespan)

app = FastAPI()

# the below is deprecated in FastAPI, but only way to use startup hook w/ nicegui
app.on_event("startup")(lambda: init())

# mount nicegui to fastAPI
ui.run_with(app)
```

**Comment by rodja** [comment]
Oh my. I have not seen this coming. This will produce quite some headache because it seems the new `livespan` API and old `on_event("startup")` API are meant to be used exclusively. I have not yet found out why it's not supported to use both in parallel. But it seems Starlette and FastAPI agree on dropping support for `on_event("startup")`, because the `livespan` API makes it easier to not forget to tear down resources (see https://github.com/encode/starlette/discussions/2067).

I fear we should address this in the upcoming 1.4 release which was almost finished already.

**Comment by falkoschindler** [comment]
If I understand correctly we need to support both ways for a while, at least as long as FastAPI does.
Isn't it something we can add later (say in 1.4.x), since we won't break anything?
Well, maybe we should talk about it on Monday. 😑

**Comment by rodja** [comment]
> If I understand correctly we need to support both ways for a while

I'm not sure how we can do this because both ways are exclusive. Do we need to detect what the user has set and then switch our implementation accordingly? And I'm not sure if it won't break anything :-(

**Comment by rj-vera** [comment]
just my 2 cents as a user of the library:

I think its reasonable to either:

(a) Only support `lifespan` and require newer version of FastAPI on next release of `nicegui`
(b) Not automatically infer, but provide a kwarg called `use_legacy_fastapi_hooks` or something to that effect. 

For (b) this line would look like:
https://github.com/zauberzeug/nicegui/blob/main/nicegui/run_with.py#L38-L39

```python
if use_legacy_fastapi_hooks:
    app.on_event('startup')(lambda: handle_startup(with_welcome_message=False))
    app.on_event('shutdown')(handle_shutdown)
else:
        # set lifespan on router
        # NOTE there is no `set_lifespan` function, so this code is copied from the Router source code
        # see https://github.com/encode/starlette/blob/master/starlette/routing.py#L629-L651
        if inspect.isasyncgenfunction(lifespan):
            app.router.lifespan_context = asynccontextmanager(
                lifespan,  # type: ignore[arg-type]
            )
        elif inspect.isgeneratorfunction(lifespan):
            app.router.lifespan_context = _wrap_gen_lifespan_context(
                lifespan,  # type: ignore[arg-type]
            )
        else:
            app.router.lifespan_context = lifespan
```

However, its probably not too hard to infer if you wanted. Looks like the Router sets `DefaultLifespan` if not set in constructor.
Here are 2 screenshots, one inspecting relevant `app` variables with lifespan, the other with the deprecated `on_` functions

<img width="636" alt="Screenshot 2023-10-21 at 2 41 43 PM" src="https://github.com/zauberzeug/nicegui/assets/142926978/7b95409f-9189-464d-b101-55fb9241157e">

<img width="582" alt="Screenshot 2023-10-21 at 2 43 25 PM" src="https://github.com/zauberzeug/nicegui/assets/142926978/69b73b75-93b1-4e97-9710-c86fd9f7e340">

**Comment by rodja** [comment]
I now think we can simply switch to the new lifespan API. NiceGUI has it's own `app.on_startup` and `app.on_shutdown` which are not affected. I've made a first attempt in https://github.com/zauberzeug/nicegui/pull/1855 which looks pretty much straight forward. We still need to do this in 1.4 because as soon as we release it, existing NiceGUI apps which use `@on_event("startup")` will not longer work.
