### ISSUE TITLE
Providing Highcharts lib with NiceGUI requires commercial products to buy a license

### ISSUE THREAD

**Issue by rodja** [zauberzeug/nicegui#1850]
### Description

As pointed out by [gothenbirder on Discord](https://discord.com/channels/1089836369431498784/1164926111852003328),  any commercial NiceGUI is currently required to buy a Highcharts license. Even if the project does not use any Highcharts chart? Merely the fact that it is "installed" triggers the [license to be invoked](https://shop.highcharts.com/license#:~:text=By%20installing%20or%20using%20Software%20or%20any%20part%20thereof%2C%20Licensee%20agrees%20to%20be%20bound%20by%20this%20Standard%20License%20Agreement.).

To avoid these licensing implications of Highcharts and ensure that commercial products using NiceGUI are not obliged to purchase a Highcharts license, we must remove the Highcharts dependency from NiceGUI.

**Comment by rodja** [comment]
Because this is super bad, we should do it as quick as possible. The upcoming 1.4 release looks like a good opportunity. I suggest we extract `ui.charts` into a separate pip package and rename it to `ui.highcharts`. NiceGUI will still have charting capabilities through `ui.echarts`. We could throw an informative exception which contains instructions on how to install highcharts or transition to echarts when `ui.charts` is called from there on.

**Comment by falkoschindler** [comment]
Oh wow! I agrees, 1.4 would be a good opportunity. But if it turns out to be really challenging to create a new package that interacts with an existing NiceGUI installation (i.e. how `ui.highcharts` hooks into the existing `ui` namespace), I could imaging scheduling it for an early 1.5 release in a few weeks. This would allow us release "nicegui-highcharts" first, then deprecate `ui.charts` and finally remove it when the new package works as expected.

**Comment by natankeddem** [comment]
Luckily, you guys twisted my arm into making `ui.echarts`. 😄 
Once you cleave off `ui.charts` it might provide a good reference for creating other third party interacting modules in the official\recommended way.

**Comment by falkoschindler** [comment]
> how `ui.highcharts` hooks into the existing `ui` namespace

I'm a bit worried that we need some kind of extension mechanism for NiceGUI (see #1618 and #1817)...

**Comment by rodja** [comment]
I think we could do the following

1. move `ui.charts` into own pip package `nicegui-highcharts` which provides a `Highchart` class
2. add `from nicegui-highcharts` import Highchart as highchart` to `ui.py` and wrap it in a try/except ImportError.

That way, everyone who has installed the `nicegui-highcharts` package can use `ui.highchart`.
