### ISSUE TITLE
ui.select documentation - can take a label value

### ISSUE THREAD

**Issue by gavinpotter** [zauberzeug/nicegui#1851]
### Description

ui.select can take a label, so you can do this:

```py
ui.select(["French","English","German"],label="Select language")
```

which improves the look of the element.

Its a very small point, I know, but its not mentioned in the documentation at the top which I took to be a list of values that could be used when creating the element. There is an example, in the multiselection example,  but it works in a single selection scenario as well.

**Comment by falkoschindler** [comment]
Thanks, @gavinpotter! Somehow the documentation for this parameter has been forgotten. I fixed it. 🙂
