### ISSUE TITLE
Can nicegui used in the production environment. ? 

### ISSUE THREAD

**Issue by muratbedir** [zauberzeug/nicegui#1859]
### Description

I am going to code a new site, I found nicegui very well abstraction to Vue, java script and low-level html. NiceGui very good framework, I want to get things related to "Can NiceGUI currently stable to use production environment? or do you suggest to wait a while until its maturity increases. "

Thanks for your opinions.

**Comment by falkoschindler** [comment]
This has already been discussed and answered here: #395 (February 2023).
Therefore I'll close this issue as duplicate. Feel free to open a new [discussion](https://github.com/zauberzeug/nicegui/discussions) in case you have a more specific question.
