### ISSUE TITLE
Log viewer inside tabs issue

### ISSUE THREAD

**Issue by marcin-koziol** [zauberzeug/nicegui#1869]
### Description

I want to place the Log component in the tab, everything is OK, but to see the logs, you first need to switch to the Log viewer tab

```python
from datetime import datetime
from nicegui import ui


with ui.row():
    with ui.tabs().classes('w-full').props(add="dense align=left") as tabs:
        one = ui.tab('Something')
        logs = ui.tab('Logs')
    ui.separator()

    with ui.tab_panels(tabs, value=one).classes('w-full').style('min-height: 268px'):
        with ui.tab_panel(one):
            ui.image('https://picsum.photos/id/377/640/360').style('max-width: 420px')
        with ui.tab_panel(logs):
            log = ui.log(max_lines=10).classes('w-full h-20')


with ui.row():
    ui.button('Log time', on_click=lambda: log.push(datetime.now().strftime('%X.%f')[:-5]))

ui.run()
```

In this example:
 * run
 * click on "Log time" button
 * switch to the "Logs" tab - no entries here
 * click again
 * enties are visible

**Comment by falkoschindler** [comment]
Wow, thanks for reporting this issue, @marcin-koziol!

It seems like the `log` element doesn't exist before opening the tab. When I print its ID `print(log.id)` (→"13") and try to get the element from the JavaScript console `getElement(13)`, it is `undefined.

Right now I'm not sure how to fix it. When calling `log.update()` right after pushing new content, it works. But the main idea of `ui.log` was to _not_ update the whole element for each new line. I guess there's a better way...

**Comment by marcin-koziol** [comment]
maybe we could add the ability to bind a variable to the log (same as for inputs), so we'll be able to push logs to this var , without having rendered component? Is the truncating logic implemented only on the client?

**Comment by falkoschindler** [comment]
I still have no idea how to fix this issue. Therefore I'll remove the milestone for now.

**Comment by falkoschindler** [comment]
We have spotted a similar problem with AG Grids:
```py
with ui.tabs().classes('w-full') as tabs:
    one = ui.tab('One')
    two = ui.tab('Two')
with ui.tab_panels(tabs, value=one).classes('w-full'):
    with ui.tab_panel(one):
        async def get_data():
            ui.notify(await grid.get_client_data())
        ui.button('Get data', on_click=get_data)
    with ui.tab_panel(two):
        grid = ui.aggrid({
            'columnDefs': [{'headerName': 'Name', 'field': 'name'}],
            'rowData': [{'name': 'Alice'}, {'name': 'Bob'}],
        })
```
Like with `ui.log` the UI element doesn't get mounted until the user visits the tab. How can we fix that?

**Comment by E-H-E-H** [comment]
Hi, just wondering, what is the best strategy for an workaround? , if you want multiple logs updating on multiple views?  (for example on seperate pages, on multiple tabs, etc.)

**Comment by E-H-E-H** [comment]
@falkoschindler, 

I see that you made a new implementation of the ui.log(). Great! thanks a lot! :)

**Comment by kyloe** [comment]
I have just run into the AG Grid issue - I have multiple grids on multiple tabs. Is there any similar work around now (or in the pipeline) for grids?
