### ISSUE TITLE
Raise warning instead of ValueError for wrong CSS syntax in `.style()`

### ISSUE THREAD

**Issue by adarshpunj** [zauberzeug/nicegui#1889]
### Description

This is not a bug but a potential enhancement. 

The element method `_parse_style` attempts to split user's text in `.style()` on a colon `:`. 

It throws `ValueError` in case of wrong CSS syntax. Should we consider raising a warning like "CSS styling won't be applied, did you forget a colon?" as the Python code can still be run?

Reproducible example:
```python
ui.label("Sign Up").style("color=red;") # throws ValueError > Internal Server Error
```

**Comment by falkoschindler** [comment]
@adarshpunj Thank you for your suggestion. However, we'll retain the `ValueError` as it adheres to Python’s philosophy of "Errors should never pass silently" (PEP 20), ensuring immediate awareness of syntax errors. This approach also maintains consistency across our library's error handling and facilitates easier debugging.

**Comment by adarshpunj** [comment]
Yes, both points are valid. Thanks.
