### ISSUE TITLE
Broken page with ui.element ('<h3>Foo</h3>')

### ISSUE THREAD

**Issue by ed2050** [zauberzeug/nicegui#1908]
### Description

I may have found a bug in nicegui.   When adding an `<h3>` to my script, I accidentally used ui.element instead of ui.html:
```py
ui.element ('<h3>Foo</h3>')
```

Result: entire page turned black.  No messages, no output, nothing but pure black.

Looking at page source, the html markup was there.  Header, scripts, etc.  I didn't check it in detail but there was markup.  But it renders as a blank page.

If you get same result on your end, then it would seem to be a bug.  My guess is ui.element doesn't expect brackets in the tag arg and doesn't sanitize the string.  Then the output has invalid tags like `<<h3> foo </h3>>` or such and the browser parser breaks.

Just a guess, I didn't go over output markup to verify.  It could also be a backend error, but there were no messages in the terminal.

**Comment by ProbablyBrian** [comment]
For simple HTML tags, you only need to provide the opening tag. When used in a with statement, the closing tag is added in at the end of the with block.  So, you might try something like this:

```python
with ui.element("h3"):
    ui.label("foo")
# with block ends...
ui.label("bar")
```

In the above, the "foo" label will be wrapped in <h3></h3> tags while the "bar" label will not.

**Comment by ProbablyBrian** [comment]
@ed2050 - as a working example of a cleaner approach (so you're not nesting the ui.label's div element in the heading tag):

```python
from typing import Literal

from nicegui import ui  # For running the example.
from nicegui.elements.mixins.text_element import TextElement


class Heading(TextElement):
    def __init__(self, text: str, level: Literal[1, 2, 3, 4, 5, 6] = 1):
        """Basic HTML heading element.

        :param text: The text of the heading.
        :param level: Integer from 1 to 6 indicating the heading level.
        """
        if not isinstance(level, int) or not 1 <= level <= 6:
            raise ValueError(
                f"argument value {level} for 'level'" " must be an integer from 1 to 6"
            )
        super().__init__(tag=f"h{level}", text=text)
        self.classes(add=f"text-h{level}")


Heading("Heading 1", level=1)
Heading("Heading 2", level=2)
Heading("Heading 3", level=3)
Heading("Heading 4", level=4)
Heading("Heading 5", level=5)
Heading("Heading 6", level=6)


ui.run()
```

Hope this was helpful.

**Comment by ed2050** [comment]
Thanks @ProbablyBrian.  I wouldn't use first approach (divs inside h3 is madness), and agree second one is proper.  For my quick tests, ui.html is good enough.

The reason for this bug report is that calling `ui.element()` with a malformed text arg shouldn't bring down the whole app.  Someone should look into that.  Even though it's not an approach anyone should use (I did it by mistake), validating & sanitizing inputs avoids a whole lot of other problems.

Have a nice weekend.

**Comment by rodja** [comment]
@ed2050 thanks for reporting this. I agree, we should do some validation on the input of `ui.element`. That would help new users to see whats going on. Anyone interested in creating a pull request?
