### ISSUE TITLE
tabs break with header in a refreshable UI

### ISSUE THREAD

**Issue by knowsuchagency** [zauberzeug/nicegui#1953]
### Description

I'm looking to switch tabs based on the state managed via `ui.state(...)` within a `@ui.refreshable`

This works fine until I try to put the tab bar within a `ui.header()`. When doing so, it reaches a broken state that isn't possible to escape

This is a minimum reproducible example:

```python
from nicegui import ui


@ui.refreshable
def app():
    username, set_username = ui.state("")

    with ui.header():

        with ui.tabs().classes("w-full") as tabs:

            app_tab = ui.tab("App")
            settings_tab = ui.tab("Settings")

    with ui.tab_panels(tabs, value=app_tab if username else settings_tab).classes("w-full"):

        with ui.tab_panel(app_tab):
            ui.label(f"Hello {username}!").classes("text-2xl")

        with ui.tab_panel(settings_tab):
            field = ui.input("Username", value=username)
            ui.button("Submit", on_click=lambda e: set_username(field.value))

app()

ui.run()
```

https://github.com/zauberzeug/nicegui/assets/11974795/0b425442-8b0e-4de2-92b8-6d8532e23f66

**Comment by falkoschindler** [comment]
Hi @knowsuchagency,

`ui.refreshable` creates a container which is cleared and refilled automatically. But `ui.header` creates a UI element in the client's page `layout`, i.e. not in the container managed by `ui.refreshable`. Therefore it is not correctly replaced when `refresh` is called.

Maybe we should throw an exception when creating layout elements within a container. A non-empty slot stack could be a good indicator.

In your specific case you might need two separate refreshables, one for the tabs placed within `ui.header` and one for the tab panels.

**Comment by falkoschindler** [comment]
See PR #1970.

**Comment by knowsuchagency** [comment]
Thanks @falkoschindler ! This seemed to do the trick. Adding it here in case someone (me) stumbles on something similar in the future 

```python
from nicegui import ui


@ui.refreshable
def app(tabs, app_tab, settings_tab):
    username, set_username = ui.state("")

    with ui.tab_panels(tabs, value=app_tab if username else settings_tab).classes("w-full"):
        with ui.tab_panel(app_tab):
            ui.label(f"Hello {username}!").classes("text-2xl")

        with ui.tab_panel(settings_tab):
            field = ui.input("Username", value=username)
            ui.button(
                "Submit",
                on_click=lambda e: set_username(field.value),
            )


# app()


@ui.page("/")
def index():
    with ui.header():
        with ui.tabs().classes("w-full") as tabs:
            app_tab = ui.tab("App")
            settings_tab = ui.tab("Settings")

    app(tabs, app_tab, settings_tab)


ui.run()
```
