### ISSUE TITLE
Treeview widget? 

### ISSUE THREAD

**Issue by nghia-vo** [zauberzeug/nicegui#197]
Many thanks for great software to design a browser-based GUI. I'm interesting to give it a go. Is it possible or will it possible to make a folder browser using NiceGUI? Something similar to pyqt5 here:
https://stackoverflow.com/questions/5144830/how-to-create-folder-view-in-pyqt-inside-main-window

**Comment by rodja** [comment]
Year, we got you covered :-)
Have a look at `ui.tree`: https://nicegui.io/reference#tree. It's based on https://quasar.dev/vue-components/tree. Therefore you have all the listed styling options of Quasar available.
