### ISSUE TITLE
specifiy the release notes for 1.4.0 nicegui.globals

### ISSUE THREAD

**Issue by AndyPermaRobotics** [zauberzeug/nicegui#1976]
### Description

Hi there!

When I updated nicegui, I was confronted with the fact that I could no longer access `nicegui.globals.app`. In the release notes, it says:

> We removed the ugly globals module, which was never intended to be public API,
but might have been used nonetheless.
If you need the app configuration, use app.config instead.
If you need the current client or slot, use the context module instead.
If you need the client dictionary, use Client.instances instead.

However, the app is now located in **nicegui.core**. I would suggest adding this to the release notes.

**Comment by rodja** [comment]
Thanks @AndyPermaRobotics! We specified it in [1.4.0](https://github.com/zauberzeug/nicegui/releases#:~:text=The%20globals%20module%20is%20gone).

**Comment by falkoschindler** [comment]
Well, we didn't mention `app` because it could and can still be accessed "officially" via `from nicegui import app`.
No need to tap into `globals` or `core`.

**Comment by rodja** [comment]
I've still added this information to the release notes: https://github.com/zauberzeug/nicegui/releases/tag/v1.4.0#:~:text=using%20from%20nicegui%20import%20app%20to%20get%20the%20app%20object
