### ISSUE TITLE
Show error message when connection is lost

### ISSUE THREAD

**Issue by rodja** [zauberzeug/nicegui#199]
NiceGUI should show an error message in the frontend when the socket connection is lost. For example due to internet connection problems. Otherwise users may try to interact with the UI and wonder why nothing is working anymore.

This is somehow related to #198 where a server is not available anymore. But there we can simply auto-reload because the server is just replaced by another instance. This issue should focus on the more general case where just reloading may not be the best option.

**Comment by falkoschindler** [comment]
Has been implemented in PR https://github.com/zauberzeug/nicegui/pull/239.
