### ISSUE TITLE
on_change in (for-/while)loop doesn't take the right input argument. 

### ISSUE THREAD

**Issue by JohnG2045** [zauberzeug/nicegui#2001]
### Description

Usecase using niceGUI 1.4.2:
I have multiple input fields, with on_change like following sample code(in realcode I have more complex logic for on_change):
```py
ui.number(value=1, on_change=lambda e:print(1))
ui.number(value=2, on_change=lambda e:print(2))
ui.number(value=3, on_change=lambda e:print(3))
```

In this case, if one inputfield got a new value, I got a correct print of 1/2/3 depends on which inputfield got new value. However, if now I use loop(no matter for or while), then it takes only the last value and prints always value 3:

```py
for x in range(1,4):
    ui.number(value=x, on_change=lambda e:print(x))
```

Actually this behavior exists for all other input components, e.g. ui.input. 
Could you please confirm whether this is a bug? Or is there another way to create inputfields dynamically in last version 1.4.2?
thanks a lot in Advanced
John

**Comment by falkoschindler** [comment]
Hi @JohnG2045, this is a common misconception about how Python binds values in function definitions or lambda expressions:
https://github.com/zauberzeug/nicegui/wiki/FAQs#why-have-all-my-elements-the-same-value

> You are probably experiencing Python's "late binding".
> 
> Try
> 
> ```py
> for i in [1, 2, 3]:
>     ui.button(i, on_click=lambda: ui.label(i))
> ```
> 
> vs.
> 
> ```py
> for i in [1, 2, 3]:
>     ui.button(i, on_click=lambda i=i: ui.label(i))
> ```
> 
> The `i=i` captures the `i` within the lambda statement. 
> When the lambda is eventually evaluated, it would use the current value of `i` (which is now 3). 
> But with `i=i` the label is created using a local copy.

**Comment by JohnG2045** [comment]
@falkoschindler , thanks a lot for your quick answer! Yes I can confirm this solution. Only for info, if someone else has same issue with that, the following sample code can be used for on_change of inputfields:
```
datalist = [1,2,3]
for i in datalist:    
    ui.number(value=i, on_change=lambda e,  i=i: print("current value of pos ", i,  e.value))
```
