### ISSUE TITLE
The website is just permanently loading

### ISSUE THREAD

**Issue by Shahin-rmz** [zauberzeug/nicegui#2005]
### Description

I have checked it with different devices, but the website of nicegui is just loading and it is a bit unfunctional.
is it just for me or it is a legit problem?

For Reference: it is after some minutes
![image](https://github.com/zauberzeug/nicegui/assets/32805117/5dabd02a-548f-4a82-ab38-752fe25fb341)

**Comment by BartKeulen** [comment]
I have been experiencing the same problem, the www.nicegui.io website is extremely slow and unresponsive. 

Machine details:

Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
Kernel:           6.5.6
Browser:        Firefox (119.0.1)

**Comment by phoskee** [comment]
I think the problem is the host service, I fork the library and run it locally, everything works perfectly

**Comment by falkoschindler** [comment]
Sorry, we also noticed a pretty poor performance and lots of reloads.
We just restarted the servers and right now it the site behaves much better. 🤞
