### ISSUE TITLE
Fail to start in native window

### ISSUE THREAD

**Issue by 0O0o0oOoO00** [zauberzeug/nicegui#2012]
### Description
I have installed Webview2 Runtime already, but it always say "Couldn't find a compatible Webview2 Runtime". And I could open nicegui through chrome, but failed in native window which is totally white and blank. The native window opened with nothing. I have tried to reinstall nicegui and pywebview, but still failed

### Code
```python
from nicegui import ui

ui.button('Click me!', on_click=lambda: ui.notify('You clicked me!'))
toggle1 = ui.toggle([1, 2, 3], value=1)
toggle2 = ui.toggle({1: 'A', 2: 'B', 3: 'C'}).bind_value(toggle1, 'value')
ui.run(native=True)
``` 

### Error
```
NiceGUI ready to go on http://localhost:8000
[pywebview] WebView2 initialization failed with exception:
 Couldn't find a compatible Webview2 Runtime installation to host WebViews. ---> System.IO.FileNotFoundException: 系统找不到指定的文件。 (异常来自 HRESULT:0x80070002)
   --- 内部异常堆栈跟踪的结尾 ---
   在 Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__25.MoveNext()
```
### Env
- Operating system: Windows 10 22H2
- Nicegui version: 1.4.2
- Pywebview version: 4.4.1
- Python version: 3.11

**Comment by falkoschindler** [comment]
Hi @0O0o0oOoO00, that's unfortunate.
Could you, please, try the pywebview Hello World example to see if it's an issue with this library? Thanks!
https://github.com/r0x0r/pywebview#hello-world

**Comment by 0O0o0oOoO00** [comment]
> Hi @0O0o0oOoO00, that's unfortunate. Could you, please, try the pywebview Hello World example to see if it's an issue with this library? Thanks! https://github.com/r0x0r/pywebview#hello-world

Tried, still same problem. Should I use older version of pywebview?

**Comment by 0O0o0oOoO00** [comment]
@falkoschindler Ok, I solved this problem just now.  I totally removed the Webview2 Runtime and installed it again. Maybe my runtime was broken. Thanks for your help.
