### ISSUE TITLE
ui.select with_input and multiple=True not desirable behavior (Allow multi-select)

### ISSUE THREAD

**Issue by netnem** [zauberzeug/nicegui#2015]
### Description

```py
from nicegui import ui

continents = [
    'Asia',
    'Africa',
    'Antarctica',
    'Europe',
    'Oceania',
    'North America',
    'South America',
]
ui.select(options=continents, with_input=True, multiple=True,
          on_change=lambda e: ui.notify(e.value)).classes('w-40')

ui.run()
```

When I type the word "America" into the text box, I want to be able to rapidly (or multi) select both "North America" and "South America" without having to retype another character into the text box. If I have a bunch of things ending with a specific suffix for example, this becomes cumbersome to select all of them.

The current state:

- Type "America" to filter the first time 
![image](https://github.com/zauberzeug/nicegui/assets/32517635/153e4c31-98d7-4d73-bf30-97335eb026af)

- Select North America - Ideally at this point it should still be filtering only "America"

![image](https://github.com/zauberzeug/nicegui/assets/32517635/6f83e0ae-e9e3-41e4-882c-191f97b4d1b2)

- "Backspace" to "Americ" or click on the typed characters
- Select South America

Desired behavior:
- Type "America" to filter dropdown list
- Select North America
- Select South America
- Click off to finish

**Comment by falkoschindler** [comment]
Thanks for the bug report, @netnem!
I agree, the filtered options should remain unchanged when selecting one of them.

Here is a minimal reproduction of the problem:
```py
ui.select(options=['A1', 'A2', 'B1', 'B2'], with_input=True, multiple=True)
```

I think I fixed the problem in https://github.com/zauberzeug/nicegui/commit/b9229b8869980dc42221c29ef716063d0f1667b8. Will be part of the upcoming release of version 1.4.3
