### ISSUE TITLE
Wrong (or non-existent) url when using "search" in nicegui site

### ISSUE THREAD

**Issue by phoskee** [zauberzeug/nicegui#2019]
### Description

I noticed that `search_index.json` has a url that does not in fact exist, let me explain:

![immagine](https://github.com/zauberzeug/nicegui/assets/125825348/cf69a7e5-4b80-4481-bb0e-3c59fcabbbbe)

result:

![Issue](https://github.com/zauberzeug/nicegui/assets/125825348/2094a4d2-5ded-4077-b907-b0dfd490085e)

**Comment by phoskee** [comment]
Other broken links:

https://github.com/zauberzeug/nicegui/tree/main/examples/nginx_subpath/main.py is not accessible. Error: 404 Client Error: Not Found for url: https://github.com/zauberzeug/nicegui/tree/main/examples/nginx_subpath/main.py
https://github.com/zauberzeug/nicegui/tree/main/examples/editable_table_aggrid/main.py is not accessible. Error: 404 Client Error: Not Found for url: https://github.com/zauberzeug/nicegui/tree/main/examples/editable_table_aggrid/main.py
http://127.0.0.1:8080/documentation/highchart is not accessible. Error: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8080/documentation/highchart
http://127.0.0.1:8080/documentation/highchart#chart_with_extra_dependencies is not accessible. Error: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8080/documentation/highchart#chart_with_extra_dependencies
http://127.0.0.1:8080/documentation/highchart#chart_with_draggable_points is not accessible. Error: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8080/documentation/highchart#chart_with_draggable_points
http://127.0.0.1:8080/documentation/shutdown is not accessible. Error: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8080/documentation/shutdown
http://127.0.0.1:8080/documentation/add_static_files is not accessible. Error: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8080/documentation/add_static_files

**Comment by rodja** [comment]
I'll look into this.

**Comment by falkoschindler** [comment]
I already fixed incorrect links to main.py:
https://github.com/zauberzeug/nicegui/commit/98d35bf7f9cc3bcb81c7442ab1e45895083f5ca7
But things like /shutdown are more complicated to handle.

**Comment by rodja** [comment]
Hmmm... but which part is linking to `/documentation/shutdown`? The search points to `/documentation#shutdown` which resolves as expected.

**Comment by falkoschindler** [comment]
@rodja
```json
  {
    "title": "Shut down NiceGUI.",
    "content": "This will programmatically stop the server. Only possible when auto-reload is disabled.",
    "url": "/documentation/shutdown"
  },
```

**Comment by falkoschindler** [comment]
We're planning to refactor the whole documentation infrastructure, which will implicitly solve this issue.
