### ISSUE TITLE
flutter_service_worker.js?v=1549198364 not found

### ISSUE THREAD

**Issue by ljchuying** [zauberzeug/nicegui#2027]
### Description

OS: win 10 LTSC x64 21H2
Python: 3.11.4
nicegui: 1.4.2

I am a novice, and when I test this simple code, there is a prompt that the file cannot be found. I don't know if this is a bug

```py
from nicegui import ui
ui.button("Click me!", on_click=lambda: ui.notify("You clicked me!"))
ui.run()
```

0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
NiceGUI ready to go on http://localhost:8080, http://169.254.144.216:8080, http://169.254.175.188:8080, http://169.254.76.234:8080, http://169.254.83.8:8080, http://192.168.110.38:8080, http://192.168.2.19:8080, and http://192.168.56.1:8080
http://127.0.0.1:8080/flutter_service_worker.js?v=1549198364 not found
http://127.0.0.1:8080/flutter_service_worker.js?v=1549198364 not found

I have created a virtual environment and only installed nicegui, so I'm also surprised why there's a Flutter. Don't you have this tip?

**Comment by falkoschindler** [comment]
There must be something else going on. Is there a Flutter app running in the background, requesting "/flutter_service_worker.js?v=..."?
At least there is no file "flutter_service_worker.js" in NiceGUI, so I'm not sure if we can help.

**Comment by mnesarco** [comment]
I have the same strange message (2024-11-01)

```
python main.py
NiceGUI ready to go on http://localhost:8080, http://127.0.0.1:8080 
http://127.0.0.1:8080/flutter_service_worker.js?v=4089678422 not found
http://127.0.0.1:8080/flutter_service_worker.js?v=4089678422 not found
```

App with only 2 dependencies (venv):

```
[project]
name = "x-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "nicegui>=2.5.0",
    "sqlalchemy>=2.0.36",
]
```

Trivial code:

```python
# main.py
from nicegui import ui
slider = ui.slider(min=0, max=100, value=50)
ui.label().bind_text_from(slider, 'value')
ui.run()
```

**Comment by mnesarco** [comment]
The culprit is that another application instilled the service worker on localhost:8080. It can be uninstalled using DevTools:

![image](https://github.com/user-attachments/assets/543e9463-caac-4d50-abb4-611d31647e15)
