### ISSUE TITLE
Dark theme for mermaid diagrams

### ISSUE THREAD

**Issue by sunnymax2002** [zauberzeug/nicegui#2030]
### Description

Hello, I tried the following simple mermaid code, which works with ui.mermaid, but even when I use dark_mode globally, the mermaid diagram doesn't seem to be drawn in dark theme

```
---
config:
  theme: dark
---

flowchart BT
  classDef vcn fill:yellow

  vcp_55711386009614{{IDM}}:::vcn
  vcp_55711386009614_TSM[TSMC Fab] -.- vcp_55711386009614
  vcp_55711386009614_INTC[Intel Fab] -.- vcp_55711386009614

  vcp_55711386009612{{EDA}}:::vcn
  vcp_55711386009612_SNPS[Synopsys EDA] -.- vcp_55711386009612
  vcp_55711386009612_CDNS[Cadence EDA] -.- vcp_55711386009612
  vcp_55711386009612 --> vcp_55711386009614
```

**Comment by falkoschindler** [comment]
This works for me:

```py
from nicegui import ui

ui.mermaid('''
---
config:
  theme: dark
---

flowchart BT
  classDef vcn fill:yellow

  vcp_55711386009614{{IDM}}:::vcn
  vcp_55711386009614_TSM[TSMC Fab] -.- vcp_55711386009614
  vcp_55711386009614_INTC[Intel Fab] -.- vcp_55711386009614

  vcp_55711386009612{{EDA}}:::vcn
  vcp_55711386009612_SNPS[Synopsys EDA] -.- vcp_55711386009612
  vcp_55711386009612_CDNS[Cadence EDA] -.- vcp_55711386009612
  vcp_55711386009612 --> vcp_55711386009614
''')

ui.run(dark=True)
```

What did you do differently?

**Comment by sunnymax2002** [comment]
Thanks for your quick response. Yes it runs, but it renders the diagram in normal theme - at least on my browser - which means 'dark' elements of diagram are hardly visible - pls see the snippet.

![image](https://github.com/zauberzeug/nicegui/assets/63592658/f3bb7e34-8419-4c4a-b322-c5ffa07f5fb0)

**Comment by falkoschindler** [comment]
I checked on Chrome, Firefox and Safari:
<img width="310" alt="Screenshot 2023-11-17 at 01 11 47" src="https://github.com/zauberzeug/nicegui/assets/5767091/12d78571-7ac7-40db-93a3-4e9d5c5ec222">
Looks correct.

**Comment by sunnymax2002** [comment]
Just an update, not sure why this happens. When I host my app from my PC (windows), I face above issue. But I just tried running my app on EC2 (ubuntu) and dark mode mermaid diagram renders correctly - on the same client (browser on my windows PC). So possibly this might have to do with windows / linux... how the HTML is being generated...

**Comment by falkoschindler** [comment]
One of the discussions you referred to mentioned browser extensions. If your browser sets custom colors, e.g. for dark mode emulation, it could explain the rendering issues.
