### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by nguyenxuanhoa493** [zauberzeug/nicegui#2036]
### Description

      building 'yarl._quoting_c' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/      
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for yarl
Failed to build aiohttp frozenlist multidict yarl
ERROR: Could not build wheels for aiohttp, frozenlist, multidict, yarl, which is required to install pyproject.toml-based projects
I can not install it

**Comment by falkoschindler** [comment]
It looks like something is wrong with your Python/pip setup. Can you `pip install aiohttp`?

**Comment by rodja** [comment]
We will remove the aiohttp dependency in the 1.4.3 as part of providing Python 3.12 support (see https://github.com/zauberzeug/nicegui/pull/1798).

**Comment by falkoschindler** [comment]
I'll close this issue since it's probably resolved by removing aiohttp in version 1.4.3.
Feel free to re-open it in case you keep having trouble installing NiceGUI.
