### ISSUE TITLE
ui.table does not update when appending row data

### ISSUE THREAD

**Issue by JS-Aibel** [zauberzeug/nicegui#204]
table.options['rowData'].append() does not update grid table. NiceGui version 1.0.7. 
If the client clicks refresh in the browser, the table shows the grid with added rows. See code below:

```python
from nicegui import ui

table = ui.table({
    'columnDefs': [
        {'headerName': 'Name', 'field': 'name'},
    ],
    'rowData': [
        {'name': 'Alice'},
    ],
}).classes('max-h-40')

def addRow():
    table.options['rowData'].append({'name': 'Bob'})
    table.update()

ui.button('addRow', on_click=addRow)

ui.run()
```

**Comment by falkoschindler** [comment]
Thanks for reporting this issue! We tried updating the grid by updating each option entry, which apparently does not work for *new* entries.

I just committed a new approach that replaces the whole DOM element on every update, like JustPy and NiceGUI 0.9 did. This might cause a tiny bit of flickering and the grid scrolls back to the top. But it works in principle.

The behavior (adding rows, updating cells, receiving events) can be tested with the following UI:

```python
table = ui.table({
    'columnDefs': [
        {'field': 'name'},
        {'field': 'age'},
    ],
    'rowData': [
        {'name': 'Alice', 'age': 18},
        {'name': 'Bob', 'age': 21},
        {'name': 'Carol', 'age': 42},
    ],
}).classes('max-h-40')

def add():
    table.options['rowData'].append({'name': 'Foo', 'age': 0})
    table.update()

def update():
    table.options['rowData'][0]['age'] += 1
    table.update()

ui.button('Add', on_click=add)
ui.button('Update', on_click=update)
table.on('cellClicked', lambda msg: print(msg, flush=True))
```

@rodja What do you think?

**Comment by rodja** [comment]
Looks good. Released in https://github.com/zauberzeug/nicegui/releases/tag/v1.0.8

**Comment by sandro-qiang** [comment]
ui.aggrid has same problem and have not fixed yet.
