### ISSUE TITLE
Import Error using 'Package for Installation' code in documentation

### ISSUE THREAD

**Issue by cjschmidt1494** [zauberzeug/nicegui#2059]
### Description

I'm working on packaging up nicegui using the suggested process here: [package_for_installation.](https://nicegui.io/documentation#package_for_installation)

I had an import error when running the main.py in the documentation:
```py
from nicegui import native_mode, ui

ui.label('Hello from PyInstaller')

ui.run(reload=False, port=native_mode.find_open_port())
```

Import error: 
```py
ImportError: cannot import name 'native_mode' from 'nicegui'
```

I changed it to this, and it worked for me:
```py
from nicegui import ui
from nicegui.native import native_mode

ui.label('Hello from PyInstaller')

ui.run(reload=False, port=native_mode.find_open_port())
```

Is this something that should be updated in the documentation or is it something on my end?
Thanks for the awesome tool!

**Comment by falkoschindler** [comment]
Thanks for spotting this, @cjschmidt1494!
Should be fixed in https://github.com/zauberzeug/nicegui/commit/df320df0f97ca1f32f9fc14d4bc95ed6d3c18598. 🙂
