### ISSUE TITLE
Page with `ui.upload` reconnects when used on a phone

### ISSUE THREAD

**Issue by apple-pen** [zauberzeug/nicegui#2073]
### Description

when i use phone's browser view nicegui.page   , it contains a ui.upload.  when picker files, it just reconect ,and files are cleared
当我在使用手机浏览器访问由nicegui制作的网页的时候,  包含了一个 ui.upload 组件,一旦开始选择文件, 页面就会刷新, 丢失掉选择好的文件

```py
    def handler(e: UploadEventArguments):
        print(e.name)
        file_path = base_dir / e.name
        with open(file_path, 'wb') as fp:
            fp.write(e.content.read())

        if is_image(file_path):
            trans_img(file_path)
        else:
            os.remove(file_path)

    ui.upload(on_upload=handler, multiple=True)
```

**Comment by falkoschindler** [comment]
Hi @apple-pen, can you, please, provide a minimal reproducible example? The code you posted is missing some functions and cannot be executed. They are either irrelevant and can be removed, or are essential to reproduce the bug. Thanks!

**Comment by apple-pen** [comment]
``> Hi @apple-pen, can you, please, provide a minimal reproducible example? The code you posted is missing some functions and cannot be executed. They are either irrelevant and can be removed, or are essential to reproduce the bug. Thanks!

thanks reply. below is my minimal code.please help me check it.it can work on computer well, but on cellphone's browser, when picker files, it just reconect 



`
import math
import os
from glob import glob
from pathlib import Path
from functools import partial
from typing import List

from nicegui import ui
from nicegui.events import UploadEventArguments
from fastapi import FastAPI, UploadFile, File
from fastapi.responses import HTMLResponse
import uvicorn
from PIL import Image
import re

os.path.exists("data") or os.mkdir('data')


def is_image(file_path):
    try:
        with Image.open(file_path) as im:
            return True
    except:
        return False


def trans_img(file_path):
    p = Path(file_path)
    if p.suffix.lower() in ['.jpg', '.jpeg']:
        return

    image_open = Image.open(file_path).convert('RGB')
    new_p = p.with_suffix('.jpg')
    image_open.save(new_p, 'JPEG')
    os.remove(p)


app = FastAPI()


@ui.page('/upload/{username}')
def upload(username: str):
    username = re.sub(r'[\\/:*?"<>|\r\n]+', "_", username)
    base_dir = 'data' / Path(username)
    base_dir.mkdir(exist_ok=True)
    ui.label(username)

    def handler(e: UploadEventArguments):
        print(e.name)
        file_path = base_dir / e.name
        with open(file_path, 'wb') as fp:
            fp.write(e.content.read())

        if is_image(file_path):
            trans_img(file_path)
        else:
            os.remove(file_path)

    ui.upload(on_upload=handler, multiple=True)


ui.run_with(app)

if __name__ == '__main__':
    uvicorn.run(app, host='0.0.0.0', port=8080)
`

**Comment by rodja** [comment]
You are doing cpu intensive work on the main thread. Please check https://github.com/zauberzeug/nicegui/wiki/FAQs#how-to-not-get-the-reconnect-popup-or-avoid-laggy-interaction.

**Comment by apple-pen** [comment]
> 您正在主线程上执行 CPU 密集型工作。请检查https://github.com/zauberzeug/nicegui/wiki/FAQs#how-to-not-get-the-reconnect-popup-or-avoid-laggy-interaction。


Yes, there is indeed an issue with my code that you mentioned, but the issue I reported is not here. It happened when I selected the file and did not click the upload button to upload it. I tried commenting the handle function and this phenomenon also occurred. Let me describe the problem again

This is a simple file upload page. When using the mobile browser, click the select file button to enter the file selector on the phone. The websocket link will be reconnected, and when selecting a file and jumping back to the browser, the page will automatically refresh


是的,我的代码确实有你说的问题, 但是我报告的问题不在这里.而是在我选择文件还未点击上传按钮进行上传文件的时候发生的.我试着把handle函数注释也会发生这个现象.让我再一次描述问题
这是一个简单的文件上传页面,在手机浏览器上使用的时候,点击选择文件按钮,进入到手机的文件选择器的时候,websocket链接会重连,并且当选择完文件跳回浏览器的时候,页面会自动刷新

**Comment by falkoschindler** [comment]
Sorry, I can't reproduce the problem. Maybe it's your phone that stops pinging the server while the user is selecting the file?
Does the problem also occur with the examples on https://nicegui.io/documentation/upload?
And does it help to set the reconnect timeout to something like a minute: `ui.run_with(app, reconnect_timeout=60)`?

**Comment by falkoschindler** [comment]
I'll close this issue due to inactivity. But feel free to re-open it in case you have new information on how to reproduce the problem.
