### ISSUE TITLE
$() is treated in a wrong way

### ISSUE THREAD

**Issue by retsyo** [zauberzeug/nicegui#2079]
### Description

```python
from nicegui import ui
ui.html(r"xxxx${HOSTNAME}")
ui.run()
```
renders nothing. Obviously, `$(somestring)` is interpreted in a VUE manner, which makes such unexpected behavior. So how to fix this bug, or supply an escape function in nicegui?

Thanks

**Comment by falkoschindler** [comment]
Thanks, @retsyo! I haven't thought about the dollar sign. But since we already have a mechanism for dealing with such characters, the bug was easy to fix.
