### ISSUE TITLE
ValueError: Too many packets in payload

### ISSUE THREAD

**Issue by rodja** [zauberzeug/nicegui#209]
The connection can break down with "ValueError: Too many packets in payload" if lots of data need to be transferred. This happens due to a packets limit from `engineio`. It can be fixed by increasing the limit (see see https://github.com/miguelgrinberg/python-engineio/issues/142) before importing nicegui:

```python
from engineio.payload import Payload
Payload.max_decode_packets = 500

from nicegui import ui

...
```

We should increase this limit directly in NiceGUI so users do not run into the issue in normal scenarios.

**Comment by falkoschindler** [comment]
I'd like to find a reproduction before implementing a solution. Unfortunately, I can't get the ValueError to show up, even with thousands of labels, huge content or complex UIs as in our production systems. So I'll keep testing.

**Comment by FI-Mihej** [comment]
I've also encountered this exception yesterday while working on locally launched nicegui.io web page. I believe this issue can occur in high load situation, which is not good. Investigating.

**Comment by rodja** [comment]
I've not been able to reproduce it locally yet. But with [a proxy setup running]() on an external server I get the error with this simple example:

```python
for i in range(125):
    ui.interactive_image(f'https://picsum.photos/id/29/640/360').classes('w-1/5')
```

The number of images I need to create varies. Sometimes it already happens with only 5 or even less. I took 125 because they always failed for me. It also happens with `ui.image` but maybe a little less often...

**Comment by rodja** [comment]
Ok. By increasing the number significantly I could also reproduce the error locally on very few occasions:

```
#!/usr/bin/env python3
@ui.page('/')
def index():
    for i in range(10000):
        ui.interactive_image(f'https://picsum.photos/id/29/640/360').classes('w-1/5')
```

I wrapped it in a page builder to trigger the code for every browser reload to speed up testing.

**Comment by rodja** [comment]
It also reproduces with 1000 or less images. Sometimes. After the error occurs, the server is in a strange state and does not respond correctly anymore.

**Comment by rodja** [comment]
I'll further test on the remote system. It has the easier reproduction. Interestingly the client keeps sending the events

```
42["event",{"id":10,"type":"connect"}]
```

if the server exits with the ValueError. But the connection error popup is not showing up on the web page.

**Comment by rodja** [comment]
I'm getting closer. On initial loading of the page each of the interactive_images is sending a separate "connect" event to the backend to receive its content. If I use `ui.scene` instead, there are many "init" events being fired which also lead to the ValueError. Why I saw sometimes the error with `ui.image` is unclear. Maybe I still had a page open which had `ui.interactive_image` elements loaded...

The cause seems to be the huge number of simultainous connect events:

https://github.com/zauberzeug/nicegui/blob/39b764868bc79292eb9603c6f7a44951eebcc4c4/nicegui/elements/interactive_image.js#L67-L71
