### ISSUE TITLE
Solid gauge is not visible in Highcharts

### ISSUE THREAD

**Issue by hogmoff** [zauberzeug/nicegui#210]
Solid-gauge charts are not visible due to uncomplete files for highcharts.

As shown in [Highcarts Demo Example](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/gauge-solid) there are missing files. highcharts-more.js and modules for solid-gauge.

```
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/highcharts-more.js"></script>
<script src="https://code.highcharts.com/modules/solid-gauge.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script src="https://code.highcharts.com/modules/export-data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>
```

After insert following code in chart.py and copied the missing files in the folders the chart works fine:
`register_component('chart', __file__, 'chart.js', ['lib/highcharts.js', 'lib/highcharts-more.js', 'modules/solid-gauge.js'])`

**Comment by rodja** [comment]
Thanks for figuring this out. Would you like to create a quick pull request? We would love to credit you with this contribution :-)

**Comment by hogmoff** [comment]
You are welcome. I created a pull request [ull request](https://github.com/zauberzeug/nicegui/pull/211)

**Comment by rodja** [comment]
Wonderful. I just merged your code :-)
