### ISSUE TITLE
Swagger/Redoc endpoints show blank pages

### ISSUE THREAD

**Issue by iron3oxide** [zauberzeug/nicegui#2102]
### Description

I have an app that exposes both ui pages and API endpoints and would like to have the endpoint documentation via Swagger/redoc. Unfortunately, both `/docs` and `/redoc` show a blank page (Title and favicon indicate that the links are correct though). Minimal example for reproduction:
```python
from fastapi import APIRouter
from fastapi.responses import PlainTextResponse
from nicegui import app, ui

router = APIRouter()


@ui.page("/")
def home():
    ui.label("home")


@router.get("/api")
def api():
    return PlainTextResponse("Hello")


app.include_router(router)
ui.run(endpoint_documentation="all")
```
Switching to the nicegui APIRouter doesn't change anything.

NiceGUI version: 1.4.1
Browser: Brave

**Comment by falkoschindler** [comment]
Sorry, I can't reproduce the problem. When I try your code, both endpoints /docs and /redoc work on Chrome, Firefox and Safari. Can you, please, try it with a different browser?

**Comment by iron3oxide** [comment]
I seem to be hexed, this is the second issue I reported and again it suddenly doesn't exist anymore? Even in Brave it works now, but I swear I didn't change anything that should be relevant... Thanks for your time though!

**Comment by giladshay** [comment]
> Sorry, I can't reproduce the problem. When I try your code, both endpoints /docs and /redoc work on Chrome, Firefox and Safari. Can you, please, try it with a different browser?

I am experiencing the same issue both on Brave and Safari. I am using the [First Steps of FastAPI](https://fastapi.tiangolo.com/tutorial/first-steps/) but when I surf to 127.0.0.1:8000/docs or 127.0.0.1:8000/redoc I get an empty page (all white).

This is the code I am using 

```py
from fastapi import FastAPI

app = FastAPI()


@app.get("/")
async def root():
    return {"message": "Hello World"}

```

**Comment by falkoschindler** [comment]
@giladshay If the problem occurs without using NiceGUI, I'd suggest reporting the problem to FastAPI. There's nothing we can do here, especially since we can't reproduce it.

**Comment by evnchn** [comment]
1. In 2.9.0, https://github.com/zauberzeug/nicegui/releases/tag/v2.9.0, NiceGUI natively allow to configure the documentation pages via fastapi_docs parameter in ui.run(). Then, you no need to use `ui.run_with` just so the endpoint documentation show up. 

2. Be sure to also check your FastAPI version. If you are unsure, it may be a good idea to update all dependencies to as new as possible in a new virtual environment and test again. Then, we can compare the environment and see which package may be at fault.
