### ISSUE TITLE
bad search result in document

### ISSUE THREAD

**Issue by retsyo** [zauberzeug/nicegui#2103]
### Description

when I search `add_static_files` on `https://nicegui.io/`, it tells me `Add a directory of static files`, however which leads me to a [wrong url](https://nicegui.io/documentation/add_static_files)
```
500
Server error
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by rodja** [comment]
Yes, we are sorry. This will be fixed with PR #2084.
