### ISSUE TITLE
Improve dependency registration and routing

### ISSUE THREAD

**Issue by rodja** [zauberzeug/nicegui#212]
In https://github.com/zauberzeug/nicegui/pull/211 we started to load Highcharts dependencies on demand. ~~In this issue we will discuss and implement a more general solution.~~

- [x] rename vue.py into dependencies.py
- [x] add a flag `optional` to the Dependency class to avoid code duplication in register_component()
- [x] move the URL generation for extras from chart.py to dependencies.py

**Comment by falkoschindler** [comment]
@rodja Isn't there a URL prefix missing?

https://github.com/zauberzeug/nicegui/blob/a64050a084eabdf55d3012113e27ce9a00a2786f/nicegui/elements/chart.py#L99-L101
