### ISSUE TITLE
Exception raised when exiting standalone app

### ISSUE THREAD

**Issue by nghia-vo** [zauberzeug/nicegui#2120]
### Description

I generated a standalone executable [app](https://github.com/algotom/broh5/blob/main/generate_exe.py). After running, exiting the app by Ctrl+ C works fine if the app runs on a single browser tab. However if I don't close the tab but running the app again (now the app running on two browser tabs), I got the following errors: 
```
^CERROR:    Traceback (most recent call last):
  File "starlette/routing.py", line 686, in lifespan
  File "uvicorn/lifespan/on.py", line 139, in receive
  File "asyncio/queues.py", line 159, in get
asyncio.exceptions.CancelledError
```
This issue doesn't show when running the app from python (python main.py) or from conda environment. I run the test on RedHat Linux.

**Comment by frankhuurman** [comment]
@falkoschindler this issue might be slightly related to https://github.com/zauberzeug/nicegui/issues/2138 cause I had those asyncio exceptions as well.

Are you using Python 3.12 by any chance @nghia-vo? 

I know my issue was Windows & Python 3.12 related but I'm curious if the problem emerges from Py 3.12 as a whole and that asyncio on 3.12 has introduced some of these issues or that it's something else entirely.

**Comment by nghia-vo** [comment]
I'm using python 3.10

**Comment by frankhuurman** [comment]
Then that's not it 👍 
Which RHEL version are you running the app on?
I'll have to dive in your code this weekend but it might have something to do with pyinstaller if this issue doesn't happen when running your app like `python main.py`

Just in case you didn't know, there are other ways to run the app as an 'executable' on Linux that launch a bit faster than the --onefile option from PyInstaller.
You could create a .bashrc alias that runs the app with all its venv dependencies like this:
```bash
alias broh5='~/Documents/broh5/venv/bin/python.exe ~/Documents/broh5/main.py '
```

But I'm unsure if that will suffice for you since I don't know if you have other dependencies or reasons to use pyinstaller.

**Comment by nghia-vo** [comment]
It's Red Hat Enterprise 8.9. Thanks for the tip Frank. I use pyinstaller so users don't have to install python and all dependencies to run broh5. The machine is used by multiple users locally/remotely.

**Comment by frankhuurman** [comment]
When you run the app again with the 2 browser tabs, does the error just show in the terminal but the app itself runs fine when you use it in the browser? Or does the entire app not work/respond at all when you start it that second time and you see the asyncio errors?

I haven't been able to replicate it yet on CentOS 8 (had a VM for this already, should have the same base packages but if signs point to a distro issue I can always install RHEL to test) so we'll have to dig a little deeper.


A suggestion would be to try and make the most basic NiceGUI app with PyInstaller and see if the same error occurs when you run it on your RHEL server:

```python
from nicegui import ui
ui.label("basic app")
ui.run()
```

**Comment by falkoschindler** [comment]
I'll close this issue due to inactivity. Feel free to re-open it if you have new information, a reproduction or even a solution. 🙂
