### ISSUE TITLE
Some UI elements dont work

### ISSUE THREAD

**Issue by shakamoushie** [zauberzeug/nicegui#213]
I am new to nicegui. I tried the examples listed in the API reference, but some elements such as table, toggle, etc., do not work for me. The code I used was a copy-paste from the nicegui site:

```python
from nicegui import ui
slider = ui.slider(min=0, max=1, step=0.01, value=0.5)
ui.linear_progress().bind_value_from(slider, 'value')
ui.run()
```

The error message I get is: AttributeError: 'Ui' object has no attribute 'linear_progress'

-----------------------------------------------------------
For toggle (and some other elements), I can't get the value of the toggle into a variable. For example:

```python
toggle1 = ui.toggle([1, 2, 3], value=1)
print(f"Value of toggle1 = {toggle1}")
```

does not print out. If I use a callback function, I can, at best print out / notify the value of the variable with e.value, but can't assign it to a variable in the main function, even though I use something like return e.value from the callback.

Is there something I'm doing wrong; is there some comprehensive nicegui document I can refer to for help?

**Comment by falkoschindler** [comment]
The progress example should work as is. Can you, please, confirm that you have a recent version of NiceGUI installed?

```bash
python3 -m pip show nicegui
```

---

To print the value of an input element you can use its `value` property:

```python
toggle1 = ui.toggle([1, 2, 3], value=1)
print(f"Value of toggle1 = {toggle1.value}")
```

Note that this prints the value only once before startup. If you want to print it whenever it changes, you should use the `on_change` callback. There you can also assign the value to a global variable:

```python
def handle_change(e):
    global toggle_value
    toggle_value = e.value

toggle1 = ui.toggle([1, 2, 3], value=1, on_change=handle_change)
toggle_value = toggle1.value
```

---

At the moment NiceGUI's documentation basically consists of the API reference at https://nicegui.io/reference. This is where we describe every UI element and constantly add more information. There are also some more complex [examples](https://nicegui.io/#demos) for certain aspects. More thorough explanations of core concepts and step-by-step tutorials are on our roadmap.

**Comment by shakamoushie** [comment]
Thank you @falkoschindler for the immediate response:

1. _python3 -m pip show nicegui_ gave me the error message: _Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases._

However, _pip show nicegui_ gave me the following response:
Name: nicegui
Version: 0.7.22
Summary: Web User Interface with Buttons, Dialogs, Markdown, 3D Scences and Plots
Home-page: https://github.com/zauberzeug/nicegui
Author: Zauberzeug GmbH
Author-email: info@zauberzeug.com
License: MIT
Location: c:\users\shawnpe\appdata\local\programs\python\python39\lib\site-packages
Requires: asttokens, docutils, justpy, markdown2, matplotlib, pydantic, Pygments, typing-extensions, uvicorn, watchgod, websockets
Required-by:

2. I used the above code and added a terminal print line:

```
def handle_change(e):
    global toggle_value
    toggle_value = e.value

toggle1 = ui.toggle([1, 2, 3], value=1, on_change=handle_change)
toggle_value = toggle1.value

print(f"toggle_value:=> {toggle1.value}")
```

but I still got the terminal output only once on first run _(toggle_value:=> 1_). Subsequent widget changes didn't print out the changed result to the terminal despite using the callback.

Do I have a missing library or something?

**Comment by rodja** [comment]
Your NiceGUI version is quite old: 0.7.22. Try installing the recent 1.0.9 version with 

```bash
pip install nicegui==1.0.9
```

**Comment by shakamoushie** [comment]
Thank you @rodja, my nicegui version is now 1.0.9 (confirmed with pip show nicegui)

A good outcome is that the circular_progress, linear_progress and tree (as per the examples) started working.

However, I still can't get the value of the toggle stored into a variable. More specifically, the changed event value is accessible within the toggle callback, but is unavailable, and therefore, cannot be assigned to another variable on callback return. The Toggle code suggested above does not work.

Any ideas why something so simple (as assigning a widget value to a variable) is so difficult?

**Comment by rodja** [comment]
Happy that upgrading made the progress and tree elements work, @shakamoushie. 

What do you want to accomplish with the toggle? The change event does get fired. And it changes the global `toggle_value` to the new selection. But you do not have any code which uses the updated value. The print statement is only evaluated once on startup before the program blocks at the `ui.run` call. Look, the selected value shows when you print `toggle_value` every second:

```python
def handle_change(e):
    global toggle_value
    toggle_value = e.value


toggle1 = ui.toggle([1, 2, 3], value=1, on_change=handle_change)
toggle_value = toggle1.value
ui.timer(1, lambda: print(f"toggle_value:=> {toggle1.value}"))
```

**Comment by shakamoushie** [comment]
Aaah, now I understand @rodja. Thank you for clearing that up and for your patience. 

God bless :-)

**Comment by rodja** [comment]
Glad I could help. We are happy to see people using NiceGUI. Feel free to ask again. You can also share success stories here in the discussions if you like :-)
