### ISSUE TITLE
ui.select option list displayed on the interface is incorrect

### ISSUE THREAD

**Issue by CrystalWindSnake** [zauberzeug/nicegui#2137]
### Description

In the case of multiple selections, if the order of the options list in ui.select is modified, the option list displayed on the interface is incorrect

```python
from nicegui import ui


options = ["a", "b", "c", "d"]

select = ui.select(options, value=["a"], multiple=True).props("use-chips outlined")


def on_modify_options():
    # I want to update the options and keep the selected value.
    new_opts = ["d", "c", "b", "a"]
    select.set_options(new_opts, value=["a"])


ui.button("modify options", on_click=on_modify_options)
```

After clicking the button, open the option list of the drop-down box and  its display is disordered.

![image](https://github.com/zauberzeug/nicegui/assets/36034954/977cb353-fd4a-4783-bd12-095dec32892f)

I found that not only is the display disordered, because when calling `set_options`, if the value is a list, it will not modify the `model-value`, so the value of the drop-down box is also incorrect.

https://github.com/zauberzeug/nicegui/blob/main/nicegui/elements/choice_element.py#L28

**Comment by falkoschindler** [comment]
@CrystalWindSnake Thanks for reporting this issue. I agree that after calling `select.set_options(new_opts, value=["a"])` option "a" should be highlighted, not "d". We'll need to look into it, together with other issues and pull requests related to `ui.select`.

But I don't understand what you mean with "disordered". After setting the options to `["d", "c", "b", "a"]`, the screenshot looks just right with "d" on top and "c", "b" and "a" further down.

**Comment by falkoschindler** [comment]
@CrystalWindSnake Can you, please, clarify why you think the "display is disordered"?

**Comment by CrystalWindSnake** [comment]
@falkoschindler Sorry for the late reply, I later realized that it was a logic problem on my side of the code, the order of the list of options should be fine
