### ISSUE TITLE
Formatting incorrect in ui.markdown with markdown2==2.4.11

### ISSUE THREAD

**Issue by thetableman** [zauberzeug/nicegui#2153]
### Description

I recently created a new `venv` and found that the text output of `ui.markdown` suddenly displayed incorrectly with an exisiting project. It seems when installing NiceGUI from `pip` the new `venv` grabbed `markdown2==2.4.11` whereas the previous was `2.4.10`.
```
from nicegui import ui

ui.markdown('''Test **Markdown**.  
                **over** multiple lines.''')

ui.run
```

With `markdown2==2.4.10`
![image](https://github.com/zauberzeug/nicegui/assets/78121198/b395eb5d-50ae-4df2-a82a-188ec1cecdd8)

With `markdown2==2.4.11`
![image](https://github.com/zauberzeug/nicegui/assets/78121198/3e710daf-54db-4cde-91f2-a09dbfe4025f)

The issue seems to arise when a new line starts with markdown identifiers.

**Comment by falkoschindler** [comment]
Thanks for the bug report, @thetableman!
There is an upstream bug https://github.com/trentm/python-markdown2/issues/546 which has already been fixed. Until it gets released, we should indeed apply your PR #2154. 👍
