### ISSUE TITLE
Issue with loading video from url in windows

### ISSUE THREAD

**Issue by the-code-rider** [zauberzeug/nicegui#2159]
### Description

I am trying to load a video from url, but it keeps throwing error.

url: 'https://ak.picdn.net/shutterstock/videos/1053841541/preview/stock-footage-travel-blogger-shoot-a-story-on-top-of-mountains-young-man-holds-camera-in-forest.mp4'

> using a windows machine

code snippet :    

```
from nicegui import ui
v = ui.video('https://ak.picdn.net/shutterstock/videos/1053841541/preview/stock-footage-travel-blogger-shoot-a-story-on-top-of-mountains-young-man-holds-camera-in-forest.mp4')
```    

**Error**
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'https:\\[ak.picdn.net](https://ak.picdn.net/)\\shutterstock\\videos\\1053841541\\preview\\stock-footage-travel-blogger-shoot-a-story-on-top-of-mountains-young-man-holds-camera-in-forest.mp4'

looks like the pathlib library is trying to check whether its a file and blowing up. essentially when this piece runs:
```
from pathlib import Path
Path(url).is_file()
```

removing the protocol from the url will get rid of the error, but then the video won't load

**Comment by falkoschindler** [comment]
Thanks for reporting this issue, @the-code-rider!

I wonder how we could catch this error:

1. Test if the source starts with "http://" or "https://"?
2. Test if the source contains "://"?
3. Or catch any `OSError`?

Maybe option 3 is best, because it would also catch any invalid characters the user might come up with.

**Comment by the-code-rider** [comment]
i think a combination of 1 & 3, should do the trick. i feel slightly icky about adding a try-exception block in init method though (more of a personal preference than standard practice). 

i'll try to submit a pr sometime next week.

**Comment by falkoschindler** [comment]
@the-code-rider It's actually encouraged to use try-except over if-else:
https://docs.python.org/3.12/glossary.html#term-EAFP
So I think we don't need an extra check for an HTTP protocol, which simplifies the code.

**Comment by falkoschindler** [comment]
I noticed that we can simply use the `is_file` function from our `helpers` module. It already catches all OSErrors and works nicely in case of invalid file paths.
