### ISSUE TITLE
reduce "gap" between elements

### ISSUE THREAD

**Issue by petergaultney** [zauberzeug/nicegui#2171]
### Description

https://github.com/zauberzeug/nicegui/blob/main/nicegui/static/nicegui.css#L26

I am trying to populate a large form, and it appears that `nicegui`'s `gap` CSS element is to blame for the page taking up twice as much room, vertically, as would be ideal for my use case. In my case I'm using `ui.input` to create the inputs in the form.

Mainly I'm creating this issue to ask if there's supposed to be a documented way of customizing this hardcoded value - I did not see anything in the docs. Not being a CSS expert, I don't know what the 'preferred' way of overriding this would be - in my case I probably want to override it for just about the entire application, but I suppose it would be nice to know whether there's a good way to override it from certain parts of the application hierarchy down, or if it's an all-or-nothing thing.

**Comment by petergaultney** [comment]
It seems like the supported solution here is to:

```
with ui.column().style('gap: 0.1rem'):
    # ... add ui.inputs here
```

I'll close this issue if somebody can point me to existing documentation on this. 

Or, if there isn't any documentation on it, I'd be happy to have somebody point me to a place in the docs that would be the right place to insert some language to the effect of:

"NiceGUI defines some CSS styles on its own, including column gap/padding - in order to customize those, you should first create an explicit `ui.column` object and then call `.style()` and provide inline CSS styles."

(or whatever it is that  you'd actually recommend people do)

**Comment by falkoschindler** [comment]
Ok, I created PR #2183 to allow changing such default values like gap and padding. What do you think?

**Comment by mattie47** [comment]
Thanks @petergaultney for that suggestion. 

In my case, I wanted to change the row gap of only several elements on the page, not all row elements. 

Here's a simple example which may help someone else finding this page from a web search. 

```
#!/usr/bin/env python3
from nicegui import ui

with ui.column().style('row-gap: 0.1rem'):
    with ui.row().style('align-items: center; width: 100%;').classes('w-full no-wrap q-py-none'):
        ui.label("THING1").style('flex: 6; font-weight: bold; font-size: 24px')
        ui.label("THING2").style('flex: 6; font-weight: bold; font-size: 24px')

    with ui.row().style('align-items: center; width: 100%').classes('w-full no-wrap'):
        ui.label("Thing Info").style('flex: 12; font-size: 20px')
        ui.label("Thing Info").style('flex: 12; font-size: 20px')

#other stuff on page with default row-gap. 

ui.run()
```

I had tried to use things like `margin-bottom: 0` and `margin-top: 0` between the differenet elements, as well as tailwind `gap-y-0` or even just `row-gap: 0px;` but I had no luck applying them to different things on the page, until I put them in the column (which I guess is essentially being a container) 

Thanks
