### ISSUE TITLE
Mypy and pylint errors when using @refreshable methods

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#2174]
### Description

When using the `@refreshable` decorator on class methods, mypy and pylint complain about a missing `self` argument and a missing `refresh` member:

```py
class Demo:
    @ui.refreshable
    def ui(self) -> None:
        ui.label(f'Time: {datetime.now()}')

demo = Demo()
demo.ui()
ui.button('Refresh', on_click=demo.ui.refresh)
```

mypy:
```
error: Missing positional argument "self" in call to "__call__" of "refreshable"  [call-arg]
```

pylint:
```
E1101: Method 'ui' has no 'refresh' member (no-member)
```

I tried to quickly fix it myself, but couldn't find a solution yet.

**Comment by meirdev** [comment]
Hi,

To fix the typing for mypy you need to use [Concatenate](https://docs.python.org/3/library/typing.html#typing.Concatenate) to remove `self` from the parameter list:

```python
from typing import Any, Awaitable, Callable, Concatenate, Generic, TypeVar, Union

from typing_extensions import ParamSpec

_S = TypeVar('_S')
_T = TypeVar('_T')
_P = ParamSpec('_P')


class refreshable(Generic[_S, _P, _T]):

    def __init__(self, func: Callable[Concatenate[_S, _P], Union[_T, Awaitable[_T]]]) -> None:
        self.func = func

    def __call__(self, *args: _P.args, **kwargs: _P.kwargs) -> Union[_T, Awaitable[_T]]:
        return self.func(*args, **kwargs)

    def refresh(self, *args: Any, **kwargs: Any) -> None:
        pass


class Demo:
    @refreshable
    def ui(self) -> None:
        pass


demo = Demo()
demo.ui()
demo.ui.refresh()
```

Regarding pylint, it seems like it's a [known bug](https://github.com/pylint-dev/pylint/issues/9246).

**Comment by falkoschindler** [comment]
Wow, thanks @meirdev! This looks very promissing!

I tried using `Concatenate`, but now there's a new mypy error when using `ui.refreshable` with normal functions:
```py
@ui.refreshable
def ui2() -> None:
    ui.label(f'Time: {datetime.now()}')

ui2()
ui.button('Refresh 2', on_click=ui2.refresh)
```

> error: Argument 1 to "refreshable" has incompatible type "Callable[[], None]"; expected "Callable[[<nothing>], Awaitable[None] | None]"  [arg-type]

Do you have an idea how to fix that?

Regarding the pylint bug: It's great new that they are already aware of this bug. A PR is already underway.

**Comment by meirdev** [comment]
Interesting, it seems [impossible](https://github.com/python/mypy/issues/13222)!

They offer two solutions:

1. Use TypeVar (you lose the original types of the parameters):

```python
from typing import Any, Callable, Generic, TypeVar, cast

F = TypeVar('F', bound=Callable[..., Any])


class refreshable(Generic[F]):

    def __init__(self, func: F) -> None:
        self.func = func

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        return cast(F, self.func(*args, **kwargs))

    def refresh(self, *args: Any, **kwargs: Any) -> None:
        pass


class Demo:
    @refreshable
    def ui(self) -> None:
        pass

demo = Demo()
demo.ui()
demo.ui.refresh()


@refreshable
def ui2(a: int, b: int) -> None:
    pass

ui2(1, 2)
```

2. Create a distinct function:

```python
from typing import Any, Awaitable, Callable, Concatenate, Generic, TypeVar, Union

from typing_extensions import ParamSpec

_S = TypeVar('_S')
_T = TypeVar('_T')
_P = ParamSpec('_P')


class refreshable(Generic[_S, _P, _T]):

    def __init__(self, func: Callable[Concatenate[_S, _P], Union[_T, Awaitable[_T]]]) -> None:
        self.func = func

    def __call__(self, *args: _P.args, **kwargs: _P.kwargs) -> Union[_T, Awaitable[_T]]:
        return self.func(*args, **kwargs)

    def refresh(self, *args: Any, **kwargs: Any) -> None:
        pass


class refreshable_fn(refreshable[_S, _P, _T]):

    def __init__(self, func: Callable[_P, Union[_T, Awaitable[_T]]]) -> None:
        self.func: Callable[_P, Union[_T, Awaitable[_T]]] = func


class Demo:
    @refreshable
    def ui(self, a: int, b: int) -> None:
        pass


@refreshable_fn
def ui2(a: int, b: int) -> None:
    pass


demo = Demo()
demo.ui(3, 4)

ui2(1, 2)
```

**Comment by falkoschindler** [comment]
You're right, @meirdev, it really seems impossible.

Option 1 is very unfortunate, because we absolutely would like to preserve the original type information.

Option 2 might be the best solution. I tried to implement it in PR #2268. What do you think, @meirdev?

**Comment by meirdev** [comment]
@falkoschindler, Looks good!

Maybe it's worth mentioning the `refreshable_method` at least once in the [documentation](https://nicegui.io/documentation/refreshable).

**Comment by valankar** [comment]
Came across this issue and found refreshable_method. Yes it would be great to add it to the documentation.
