### ISSUE TITLE
Connection lost when running time intensive code.

### ISSUE THREAD

**Issue by JS-Aibel** [zauberzeug/nicegui#2177]
### Description

When clicking the button in the code below, the function will **sleep for 10** seconds and a **“Connection lost. Trying to reconnect”** will appear in the web browser. This will result in the `ui.notify("Test done")` not appearing for the user. If changing the **sleep to 1** second, the ui.notify will appear as expected.

How can we prevent the “Connection lost” and loss of the subsequently ui calls when code is time intensive?

```py
from nicegui import ui
import time

async def run_test():
    time.sleep(10)
    ui.notify("Test done")

ui.button("Test", on_click=run_test)

ui.run(reload = False)
```

**Comment by rodja** [comment]
Sure. That's expected. See https://github.com/zauberzeug/nicegui/wiki/FAQs#why-is-my-long-running-function-blocking-ui-updates.

**Comment by JS-Aibel** [comment]
Thank you, @rodja 

Based on the examples in the FAQ, does it mean that ui calls can not be in the same function as time intensive code?

For the code below, I got **_Ignoring notification "Test done" because the client is not connected_**. Is this due to it running in a different process and thus being "detached" from the client?

Do we need to separate the time intensive code and ui calls in different functions?

```
def run_test():
    time.sleep(10)
    ui.notify("Test done")

ui.button("Test", on_click=lambda: run.cpu_bound(run_test))
```

**Comment by falkoschindler** [comment]
@JS-Aibel Yes, CPU-bound functions, which run on a separate process, don't have access to the UI context.
If you only want to show a notification after the computation is done, you can simply move `ui.notify` out of `run_test`.
If you want to show some progress indicator while the computation is running, you can work with queues like we show in the ["progress" example](https://github.com/zauberzeug/nicegui/blob/main/examples/progress/main.py).
