### ISSUE TITLE
On Air not functioning

### ISSUE THREAD

**Issue by thetableman** [zauberzeug/nicegui#2179]
### Description

I can't get On Air to work at all. I've tried multiple computers, with and without a token, multiple versions of NiceGUI, with and without page decorators. 

On all attempts the local ip addresses display but no url.

```py
from nicegui import ui

ui.label('Test On Air')

ui.run(on_air=True)
```

OS: Win 10, Win 11
NiceGUI: 1.3.18, 1.4.3, 1.4.5
Country: AU
Python: 3.9.4, 3.10.5

**Comment by falkoschindler** [comment]
Strange, I can't reproduce any problem.
@rodja Do we have servers running in or close to Australia?

**Comment by rodja** [comment]
Sorry for the late reply. I've just started another On Air instance in Sydney. Could you please try again, @theableman?

**Comment by thetableman** [comment]
Unfortunately this didn't resolve the issue, @rodja. 

However, I connected to a vpn server in Germany and retested and got an on-air url almost instantly; I tested with a vpn connection to Sydney but still couldn't get it working.

 I then tested via a vpn in Singapore and it also worked, although it took about 5 seconds for the on-air connection message to appear.

**Comment by thetableman** [comment]
@rodja any further thoughts on why On Air doesn't work in Australia?

**Comment by rodja** [comment]
I'm a bit at a loss why it's not working for you in Australia. Anyone else from Australia who can confirm this? @thetableman could you try a vpn connection to Australia? Maybe it has something to do with your local network setup?

**Comment by thetableman** [comment]
No such luck! I tried Sydney via VPN and it failed to return a url, connecting to a VPN in Germany worked straight away again.

It is possible it's a local network configuration issue but that would be surprising given the issue occurs on multiple devices in multiple places.

**Comment by rodja** [comment]
Ok, I now have reproduced the connection error with a VM in Sydney and could find a routing issue in one of our configs. It should be fixed now. At least I can not reproduce it anymore. Please try again.

**Comment by thetableman** [comment]
It does now appear to be working!

**Comment by snowbollaanm** [comment]
Hi, it seems this issue has persisted. I've tried connecting to a Sydney server via VPN and when I connected to the Netherlands with my VPN on_air worked straight away. 

When connected to Australia it doesn't give a link however sometimes it does but am given an error code when opening the link saying no device connected

**Comment by rodja** [comment]
Sounds like https://github.com/zauberzeug/nicegui/discussions/2089. Could you please try again. We have just fixed some internal redis connection errors.

**Comment by snowbollaanm** [comment]
> Sounds like #2089. Could you please try again. We have just fixed some internal redis connection errors.

Still does not work

**Comment by rodja** [comment]
And now? I've started a dedicated server in Sydney...

**Comment by snowbollaanm** [comment]
> And now? I've started a dedicated server in Sydney...

Still doesn't work for me, Ill test later on today with a different network to see if that's the issue however on_air has worked for me before
