### ISSUE TITLE
`ui.number` is not working properly anymore

### ISSUE THREAD

**Issue by rodja** [zauberzeug/nicegui#2192]
### Description

Since the introduction of kebab-case event types (78d679c64d569a0207ef2654f68c1fe985d8ac7e) digits entered into a `ui.number` element are cleared in the ui when losing the focus.

Reproduction:

1. create a `ui.number`
2. enter some number
3. switch to another element or browser address bar to lose the focus

The number should still be visible in the input area. But it is not.

**Comment by rodja** [comment]
In 2a85b4e6056a09a8a157be2e6382b9b08ff4fbd5 I pushed a unit test to demonstrate the problem.

**Comment by falkoschindler** [comment]
Wow... When I converted all events from "row-click" to "rowClick" (which is correct), I didn't think about events like "update:model-value" which shouldn't be converted to "update:modelValue". So I could probably add an exception for when an event starts with "update:" or at least contains a colon ":", but is that always correct? What is the general rule?

**Comment by falkoschindler** [comment]
The fix was much easier: The if condition in index.html, which checks for the special case of "update:model-value" without loopback, needs to use the new camelCase string.
