### ISSUE TITLE
misplaced element if ui.markdown meets long text

### ISSUE THREAD

**Issue by retsyo** [zauberzeug/nicegui#2197]
### Description

it is obviously that 
```python
from nicegui import ui

with ( ui.button()
    .props('autofocus outlined rounded item-aligned input-class="ml-3" align="left" no-caps ')
    .classes('w-full')
):
    with ui.row():
        ui.icon("help")
        ui.markdown('hello ').props('align="left"')

ui.run()
```
places `ui.markdown` on the right of `ui.icon`

However, code
```python
from nicegui import ui

with ( ui.button()
    .props('autofocus outlined rounded item-aligned input-class="ml-3" align="left" no-caps ')
    .classes('w-full')
):
    with ui.row():
        ui.icon("help")
        ui.markdown('hello '*100).props('align="left"')

ui.run()
```
renders as 

![bug](https://github.com/zauberzeug/nicegui/assets/7960913/b5ca3555-d66a-499c-9e9a-f588da75fd9d)

but what I expected is
![bug](https://github.com/zauberzeug/nicegui/assets/7960913/a27d4d10-fcc1-48ed-a991-81f00b5fdef9)

Yes, I do use `ui.icon`, `ui.markdown` and more elements in `ui.button`'s slots really. It is not a nonsense demo.

**Comment by falkoschindler** [comment]
If there's not enough horizontal space, `ui.row` wraps by default. You can disable it with `ui.row(wrap=False)`.

Is there a specific reason why you opened two tickets on this subject? Or can we close https://github.com/zauberzeug/nicegui/discussions/2196 as a duplicate?

**Comment by retsyo** [comment]
Thanks

> If there's not enough horizontal space, `ui.row` wraps by default. You can disable it with `ui.row(wrap=False)`.
thanks

> Is there a specific reason why you opened two tickets on this subject? Or can we close #2196 as a duplicate?
but I think https://github.com/zauberzeug/nicegui/discussions/2196 is a different one

**Comment by falkoschindler** [comment]
Ah, I see. The code looked so familiar, but is actually different. 😄
