### ISSUE TITLE
Authentication example does not redirect to '/' after logging in 

### ISSUE THREAD

**Issue by Mantanium** [zauberzeug/nicegui#221]
ui.open() doesn't seem to work when used in a function that gets called while loading a page or clicking a button. Code used is an exact copy of the authentication example from: 

https://github.com/zauberzeug/nicegui/blob/main/examples/authentication/main.py

The function that get's called after login button is pressed:

```python
def try_login(session_id: str, username: str, password: str) -> None:
    if (username, password) in users:
        session_info[session_id] = {'username': username, 'authenticated': True}
    ui.open('/')
```

**Comment by falkoschindler** [comment]
Unfortunately, I can't reproduce this issue. When running the authentication example you're referring to, after entering "user1" and "pass1" I'm redirected to "/" as expected. I tested it with Chrome, Firefox and Safari on MacOS.

Can you give more information about your system or if you changed anything w.r.t. to the original example? What version of NiceGUI are you working with?

**Comment by Mantanium** [comment]
I'm working with 1.09. But I just realised i was starting the file from PyCharm. After starting it from command line it did work. But I do not entirely understand why this works compared to starting it from PyCharm. Could you by any chance help me out with what should I search for if I want to get more information about this issue/subject?

**Comment by falkoschindler** [comment]
I don't understand it either. I just tried PyCharm, but after setting it up and installing all required packages it just works as expected.

Maybe SocketIO does not connect successfully and, thus, the backend does not even receive the user input. Did you check if `try_login` is called with the correct input values? PyCharm might run a different Python installation with missing packages...

Maybe you can also check the JavaScript console for any suspicious output (something different compared to when starting from the command line). The next step would be to check the network monitor for which websocket packages are sent back and forth between Python back end and JavaScript frontend.

**Comment by Mantanium** [comment]
I did confirm earlier that all the correct  input values where given but it just seemed to stop at the ui.open('/'). There was no difference between command line and pycharm run  in the console. After a complete reinstall with a clean venv and the newest nicegui version 1.0.10 the issue seems to have disappeared. I think the most likely cause was some issue with the packages like you suggested.
