### ISSUE TITLE
Weird loading time when behind Traefik

### ISSUE THREAD

**Issue by Aestyo** [zauberzeug/nicegui#2254]
### Description

Hello NiceGUI Team,

I'm experiencing a issue with loading times when accessing a NiceGUI website hosted on a local machine, which is connected to a Traefik reverse proxy. I don't have a code example to provide, the problem happens no matter the code. To test, I use your example: [Menu and tabs](https://github.com/zauberzeug/nicegui/blob/main/examples/menu_and_tabs/main.py)

### Environment
- NiceGUI Version: **1.4.8**
- Traefik Version: **2.9**
- Operating System: **Debian** (Traefik and NiceGUI on docker)
- Browser: **Chrome 120.0.6099.111** (Same problem on Edge & Firefox)

### Issue Description
When I access the server that hosts nicegui from its domain name + port, , the site loads promptly, and I can interact with the UI without any delay. Specifically, clicking on menu buttons leads to instant page switches. However, when accessing the same application behind a Traefik reverse proxy (still local, traefik on the same host), there is a consistent delay of approximately 2-3 seconds before I can navigate from page to page, page loads but buttons and menus don't work.

### Steps to Reproduce
1. Host a NiceGUI example on a local machine with Docker.
2. Set up Traefik reverse proxy on the same machine with Docker to route traffic to the NiceGUI application.
3. Access the application:
   - Directly on the local machine (observe normal behavior).
   - Through the Traefik proxy (observe the delay).

### Expected Behavior
The application should have similar responsiveness when accessed directly or through the Traefik reverse proxy. The UI should allow immediate interaction after loading, with minimal delay when switching between pages.

### Actual Behavior
There is a noticeable delay of about 3 seconds when trying to navigate between pages in the NiceGUI application when accessed through the Traefik reverse proxy, unlike the immediate response when accessed locally.

I hope this information helps in diagnosing the issue. I don't have much to give because the problem occurs 100% of the time and no matter what the program is running. I've obviously never seen a similar problem with other applications we host on Traefik and I don't think the Traefik installation is to blame.

Thank you for your assistance!

**Comment by rodja** [comment]
Can you share your Traefik config? We have a Trafik example at https://github.com/zauberzeug/nicegui/blob/main/docker-compose.yml which works fine.

**Comment by Aestyo** [comment]
I'm currently investigating the issue and beginning to suspect that Traefik might be the root cause. This is quite surprising to me, as our Traefik configuration is almost like your example.

I hope to come back to you with more information soon.

**Comment by Aestyo** [comment]
I ended up solving the problem by modifying the DNS and Traefik configuration only, however we host a lot of applications and only those using NiceGUI had this problem. 

It must be linked to the way frontend and backend communicate even after DNS resolution. Still, it's not a NiceGUI issue, so sorry for wasting your time.

I hope no one else will experience the same issue, thanks for your help.
