### ISSUE TITLE
Significant issue version 1.4.8 in windows

### ISSUE THREAD

**Issue by gavinpotter** [zauberzeug/nicegui#2276]
### Description

If you run a script containing nicegui when you are not in the directory containing that script you get an error.
![niceguibug](https://github.com/zauberzeug/nicegui/assets/41059217/54037e94-2b3b-4897-9839-d7da3e65389a)

So my very simple script contains:
``` 
from nicegui import ui
print("hello world")
```

when you run it using python temp_script.py from within the directory containing the script it works correctly.  However, when you run it from any other directory it fails.  I hope the screenshot of the terminal explains it sufficiently.  If not please respond asking for further details.  I note that storage.py has been changed recently.  That may have introduced the bug.

Thanks

**Comment by falkoschindler** [comment]
Hi @gavinpotter, thanks for reporting this issue!
It looks like there is an empty storage_*.json in your working directory which can't be decoded. Does it help to remove this file?
Anyway, we should certainly skip such files like we do here:
https://github.com/zauberzeug/nicegui/blob/924720a67da80a7b2fbe9ce8809cc590bfeef541/nicegui/storage.py#L48-L52
