### ISSUE TITLE
'cellRenderer': 'checkboxRenderer' for ui.table stopped working in NiceGui version 1.0.

### ISSUE THREAD

**Issue by JS-Aibel** [zauberzeug/nicegui#228]
To be able to work with checkboxes in the ui.table we used the `'cellRenderer': 'checkboxRenderer'` in a column definition with NiceGui version 0.0.9. 

```  
'columnDefs': [
    {'headerName': "",'field': "enabled", 'cellRenderer': 'checkboxRenderer', 'maxWidth': 40},
```

After updating to NiceGui version 1.0. we are not able to use the 'cellRenderer': 'checkboxRenderer'. Has this anything to do with NiceGUI 1.0 does not use JustPy anymore?

**Comment by falkoschindler** [comment]
This feature will be available in the next release of version 1.1.0.
