### ISSUE TITLE
ui.code copy button inside ui.card dialog overlaps content

### ISSUE THREAD

**Issue by frankhuurman** [zauberzeug/nicegui#2283]
### Description

Whilst trying to make a dialog that will pop up to show an error to our other developers I found out that the "copy code" button is overlapping the content in this dialog when using ui.code() inside of it.

```python
from nicegui import ui

def show_error(error):
    
    with ui.dialog() as dialog, ui.card().classes("items-center"):
        ui.label("An error occurred during the request")
        ui.separator()
        ui.code(content=f"{type(error).__name__} - {str(error)}\n\n Something doesn't seem right")
        ui.separator()
        ui.button("close", on_click=dialog.close)
    
    dialog.open()

try:
    peter_file = open("bla.txt", "r")
except Exception as e:
    show_error(e)

ui.run()
```

Results in:

![image](https://github.com/zauberzeug/nicegui/assets/19980966/2ee2b227-3537-449f-a935-a492790e80a5)

It's a minor visual issue which has an easy workaround by adding something like "#Error details \n\n" at the start of the content to free up a line and make the button stand out again but still wanted to make it known.

I think ui.code() wasn't meant to be used with this limited amount of width anyway?

**Comment by falkoschindler** [comment]
I think there are two separate issues here:

1. **The dialog is too small for the code element.** Depending on the alignment (e.g. "items center"), the code overflows the dialog card to the right. Adding a class like "w-full" to the code element should avoid this problem. The code itself will scroll horizontally.

2. **The copy button overlaps the code.** This is unfortunate, but I'm not sure how to avoid it. How does GitHub handle such long lines of code?

    ```py
    # This is just a test. This is just a test. This is just a test. This is just a test. This is just a test. This is just a test. This is just a test. This is just a test. This is just a test.
    ```

    It seems like they hide the copy button as soon as the user scrolls horizontally. But if the line has just the right width, the last characters are hidden while there is no horizontal scrolling. Anyway, it might still be a rather good solution.

**Comment by falkoschindler** [comment]
I just created PR #2288 to dynamically hide the copy button when scrolling. What do you think, @frankhuurman?

**Comment by frankhuurman** [comment]
It's a really nice solution to make the error message more visible during horizontal scrolling, thanks :) Github does this cleverly indeed! Great to have this implemented in NG as well.

My main concerns were the dialog element being too small (and the w-full on ui.code fixed the alignment issue I had with that 👍 thank you for that) and the copy button being on top of the first line in ui.code() starting at the 63th character of that line. I really want that copy button to stand out as a feature of the code field for some of my coworkers that have a little less experience with the copy functionality of those blocks.

![image](https://github.com/zauberzeug/nicegui/assets/19980966/cc82036a-25ea-49b3-bba7-73cb44132088)

In the image above the copy button looks more like a visual glitch on line 1 than a button in my opinion.

Is there a more elegant solution than my suggested `# Error details` on the first line? I've tried inserting empty lines, `\n\n`'s and `<br>`'s but that first line is pretty picky about not having emptiness in it. I've also noticed that when using \n\n and an extra space behind it for example that even with the `items-center ui.dialog()` and the `w-full ui.code()` some characters start falling off the  codeblock unable to be reached like the examples below.

![image](https://github.com/zauberzeug/nicegui/assets/19980966/fb0bcaed-a893-4388-a8a1-f1c7bdc94439)
![image](https://github.com/zauberzeug/nicegui/assets/19980966/b0f66782-1df2-4c2d-aaac-4142e159f967)

here the "h" of "hi" falls off into a black hole for example, nowhere to be found.

code example:

```python
with ui.dialog() as dialog, ui.card().classes("items-center"):
        ui.label("An error occurred!")
        
        ui.separator()
        ui.code(content=f"\n\n {type(error).__name__} - {str(error)} TEST \n\nhi").classes("w-full")
        ui.separator()

        ui.button("close", on_click=dialog.close)
```

but perhaps that's on me trying to do something derp with the empty line.

**Comment by falkoschindler** [comment]
@frankhuurman The missing "h" is caused by a NiceGUI "feature", which is supposed to automatically remove leading whitespace. Consider the following example:

```py
ui.code('''
    import time

    print(time.time())
''')
```

Usually the code would be indented, because every line - except the first one - contains leading whitespace. But NiceGUI automatically counts the number of spaces of the first non-empty line and removes it from all lines:

![Screenshot 2024-01-05 at 16 49 42](https://github.com/zauberzeug/nicegui/assets/5767091/7281dcf5-713c-405e-9fb1-7d132c52270a)

I find this feature very handy and use it all the time, but it can break in certain scenarios like yours.

Anyway, we could think about making the copy button more prominent. As a workaround you can manipulate it like this:
```py
code = ui.code('print("Hi!")')
code.copy_button.classes(remove='opacity-20')
```
