### ISSUE TITLE
Plotly double click to zoom out doesn't work

### ISSUE THREAD

**Issue by zilch42** [zauberzeug/nicegui#2310]
### Description

Hey there,

Plotly has zoom controls built in. You can click and drag with the zoom tool to zoom. The first time you do this plotly should display a tool tip in the top right a corner of the screen that says "Doubleclick to zoom back out". However, double clicking the zoomed plot doesn't do anything. 

Is NiceGUI intercepting the double click?

You can test this on the plotly example in the NiceGUi docs
[https://nicegui.io/documentation/section_data_elements#plotly_element](https://nicegui.io/documentation/section_data_elements#plotly_element)
Click and drag on the plot to zoom.
Double click does nothing.

Contrast this with the behaviour on the example in the plotly docs
[https://plotly.com/python/figure-structure/](https://plotly.com/python/figure-structure/)
Click and drag on the plot to zoom.
Double click zoom back out.

**Comment by falkoschindler** [comment]
Hi @zilch42!

That's strange. It does work for me:

![Jan-08-2024 07-22-39](https://github.com/zauberzeug/nicegui/assets/5767091/8214268f-a25d-48c9-ba7b-6f7665e55618)

I tested with Chrome, Firefox and Safari on MacOS. What's your browser and OS?

**Comment by zilch42** [comment]
Ah sorry, after attempting to make a gif and seeing the odd attempt actually work, I realised I've been victim to plotly's short double click delay, which is configurable [https://github.com/plotly/plotly.js/issues/2206](https://github.com/plotly/plotly.js/issues/2206)

Not sure why the nicegui example and plotly example would have a different delay, or if it was just coincidence, but not a bug you need to solve.

I'll close this. Thanks
