### ISSUE TITLE
EChart collapses when nested in a row element

### ISSUE THREAD

**Issue by mswastik** [zauberzeug/nicegui#2316]
### Description

Not able to add ui.echart to a row container.
For example when executing below code chart is not drawn
```py
r1=ui.row()
with r1:
    ec=ui.echart({'xAxis':{},'yAxis': {},'series': [{'type': 'line', 'data': []},{'type': 'line', 'data': [1,2,3]}]})
```
But if we pass `ui.echart` function without  wrapping it under `ui.row` then it draws without any issue.

**Comment by mswastik** [comment]
![image](https://github.com/zauberzeug/nicegui/assets/7689061/caba3e53-1d43-41c2-a4cd-92ec152b2263)
I see the div id 'c10' created correctly under row element id c7 but it is not displayed in browser. When the div id c10 is not under c7, chart is displayed in the browser.

**Comment by falkoschindler** [comment]
Hi @mswastik, thanks for bringing this up!

We also had problems with ECharts in flexboxes like `ui.row`. It might be related to https://github.com/apache/echarts/issues/11791, but I'm not sure. So far I couldn't come up with a simple workaround.

If anyone has an idea how to work around or fix this problem, we're all ears!

**Comment by falkoschindler** [comment]
@mswastik Yes, that might work in certain cases. But as soon as you add a second chart, they resize strangely when resizing the browser window.

**Comment by mswastik** [comment]
ok, maybe you can try experimenting with tailwind classes as a workaround.

**Comment by falkoschindler** [comment]
I think I finally understand the original problem:
- `ui.echart` comes with "width: 100%" by default. That means it gets the width from its parent container.
- `ui.row` is a flexbox with an undefined width.
- Because the nested `ui.echart` has a minimum width of 0, the `ui.row` shrinks to this size.

To avoid this problem, you can either set a width or minimum width on the `ui.echart` or on the `ui.row`:
```py
with ui.row().classes('w-full'):
    ui.echart({'xAxis': {}, 'yAxis': {}, 'series': [{'type': 'line', 'data': [1, 2, 3]}]})
```
