### ISSUE TITLE
Table in call_api_method needs to expand args

### ISSUE THREAD

**Issue by maxim-trokhimtchouk** [zauberzeug/nicegui#233]
I think on this line the args when being passed to run_method need to be expanded.

https://github.com/zauberzeug/nicegui/blob/f58ff7063035e123b1ddbef76fc55fb8f8b123a3/nicegui/elements/table.py#L34

Otherwise call_api_method calls api with an array of single element which contains the actual args.

A simple way to replicate this issue is to call

```        
filter = {
    'account': {
        'filterType': 'text',
        'type': 'equals',
        'filter': '1001'
    }
}
table.call_api_method('setFilterModel', filter)
```
Which then results in _"AG Grid: setFilterModel() - no column found for colId: 0"_

**Comment by falkoschindler** [comment]
You are absolutely right. Thanks for pointing this out!

I fixed it in [bf9a316](https://github.com/zauberzeug/nicegui/commit/bf9a316e8a604407969aecbcb30c9abe6353083c).

Here is an example to try it out:

```python
table = ui.table({
    'columnDefs': [{'field': 'name', 'filter': True}],
    'rowData': [{'name': 'Alice'}, {'name': 'Bob'}, {'name': 'Carol'}],
})
filter = {
    'name': {
        'filterType': 'text',
        'type': 'equals',
        'filter': 'Alice'
    }
}
ui.button('Filter', on_click=lambda: table.call_api_method('setFilterModel', filter))
```
