### ISSUE TITLE
Performance issues in `binding.py`'s `remove` function causing high CPU usage

### ISSUE THREAD

**Issue by ruiheng** [zauberzeug/nicegui#2335]
### Description

I have a web app that occasionally shows 100% CPU usage and becomes unresponsive. Looking at the call stacks from `faulthandler` during these incidents, there is always a thread executing the `remove` function in `binding.py`. Although I have not been able to reliably reproduce this in testing, observing the `remove` code shows obvious performance problems.

The `remove` function mainly modifies three global variables to delete some instances from them. However, there is unnecessary copying of objects even though it is shallow copies. With large numbers of objects, this still has a performance impact. 

I wrote a simple test program to create 1000 page element objects and delete them one-by-one. The test code is:

```python
from nicegui import ui, binding
import os
import time


def mk_element():
    dat = { 'text': 'hello' }
    return ui.label().bind_text_from(dat, 'text')

@ui.page('/')
async def home_page():
    num = 10000
    ele_list = [ mk_element() for _ in range(num) ]

    print(f'remove function implementation: {binding.remove.__name__}')
    print(f'num of active_links: {len(binding.active_links)}')
    print(f'num of bindings: {len(binding.bindings)}')
    print(f'num of bindable_properties: {len(binding.bindable_properties)}')

    t0 = time.time()

    for i in range(num):
        ele_list[i].delete()
 
    t1 = time.time()
    print(f'''{num} elements deleted in {t1-t0:.3f} seconds''')


if __name__ == '__mp_main__' or __name__ == '__main__':
    ui.run(
        binding_refresh_interval=1,
        port=4000,
        show=False,
        reload=True,
        )

```

Modifying the `remove` implementation shows large differences in execution times:

- remove_original: ~ 151 seconds  
- remove_0: ~ 68 seconds
- remove_1: ~ 3.x seconds  
- remove_2: ~ 0.07 seconds

So the modifications provide large performance improvements.

Here is the code of different implementations for the test. To support `remove_2`, I also add a global variable, which now show here. See below.

```python
def remove_original(objects: Iterable[Any], type_: Type) -> None:
    """Remove all bindings that involve the given objects.

    The ``type_`` argument is as a quick pre-filter.

    :param objects: The objects to remove.
    :param type_: The type of the objects to remove.
    """
    active_links[:] = [
        (source_obj, source_name, target_obj, target_name, transform)
        for source_obj, source_name, target_obj, target_name, transform in active_links
        if not (isinstance(source_obj, type_) and source_obj in objects or
                isinstance(target_obj, type_) and target_obj in objects)
    ]
    for key, binding_list in list(bindings.items()):
        binding_list[:] = [
            (source_obj, target_obj, target_name, transform)
            for source_obj, target_obj, target_name, transform in binding_list
            if not (isinstance(source_obj, type_) and source_obj in objects or
                    isinstance(target_obj, type_) and target_obj in objects)
        ]
        if not binding_list:
            del bindings[key]
    for (obj_id, name), obj in list(bindable_properties.items()):
        if isinstance(obj, type_) and obj in objects:
            del bindable_properties[(obj_id, name)]


def remove_0(objects: Iterable[Any], type_: Type) -> None:
    """Remove all bindings that involve the given objects.

    The ``type_`` argument is as a quick pre-filter.

    :param objects: The objects to remove.
    :param type_: The type of the objects to remove.
    """
    def should_keep_0_2(t) -> bool:
        (source_obj, _1, target_obj, _3, _4) = t
        return not (
                source_obj in objects and isinstance(source_obj, type_) or
                target_obj in objects and isinstance(target_obj, type_)
        )

    def should_keep_0_1(t) -> bool:
        (source_obj, target_obj, _2, _3) = t
        return not (
                source_obj in objects and isinstance(source_obj, type_) or
                target_obj in objects and isinstance(target_obj, type_)
        )

    active_links_copy = active_links
    active_links.clear()
    active_links.extend(filter(should_keep_0_2, active_links_copy))

    for key, binding_list in list(bindings.items()):
        binding_list_copy = binding_list
        binding_list.clear()
        binding_list.extend(filter(should_keep_0_1, binding_list_copy))

        if not binding_list:
            del bindings[key]

    for (obj_id, name), obj in list(bindable_properties.items()):
        if isinstance(obj, type_) and obj in objects:
            del bindable_properties[(obj_id, name)]


def remove_1(objects: Iterable[Any], type_: Type) -> None:
    """Remove all bindings that involve the given objects.

    The ``type_`` argument is as a quick pre-filter.

    :param objects: The objects to remove.
    :param type_: The type of the objects to remove.
    """
    def should_keep_0_2(t) -> bool:
        (source_obj, _1, target_obj, _3, _4) = t
        return not (
                source_obj in objects and isinstance(source_obj, type_) or
                target_obj in objects and isinstance(target_obj, type_)
        )

    def should_keep_0_1(t) -> bool:
        (source_obj, target_obj, _2, _3) = t
        return not (
                source_obj in objects and isinstance(source_obj, type_) or
                target_obj in objects and isinstance(target_obj, type_)
        )

    active_links_copy = active_links
    active_links.clear()
    active_links.extend(filter(should_keep_0_2, active_links_copy))

    bindings_to_del = []

    for key, binding_list in bindings.items():
        binding_list_copy = binding_list
        binding_list.clear()
        binding_list.extend(filter(should_keep_0_1, binding_list_copy))

        if not binding_list:
            bindings_to_del.append(key)

    for key in bindings_to_del:
        del bindings[key]

    bindable_properties_to_del = []

    for key, obj in bindable_properties.items():
        if obj in objects and isinstance(obj, type_):
            bindable_properties_to_del.append(key)

    for key in bindable_properties_to_del:
        del bindable_properties[key]


def remove_2(objects: Iterable[Any], type_: Type) -> None:
    """Remove all bindings that involve the given objects.

    The ``type_`` argument is as a quick pre-filter.

    :param objects: The objects to remove.
    :param type_: The type of the objects to remove.
    """
    def should_keep_0_2(t) -> bool:
        (source_obj, _1, target_obj, _3, _4) = t
        return not (
                isinstance(source_obj, type_) and source_obj in objects or
                isinstance(target_obj, type_) and target_obj in objects
        )

    def should_keep_0_1(t) -> bool:
        (source_obj, target_obj, _2, _3) = t
        return not (
                isinstance(source_obj, type_) and source_obj in objects or
                isinstance(target_obj, type_) and target_obj in objects
        )

    #log.warning(f'{len(active_links)} {len(bindings)}')

    active_links_copy = active_links
    active_links.clear()
    active_links.extend(filter(should_keep_0_2, active_links_copy))

    bindings_to_del = []

    for key, binding_list in bindings.items():
        binding_list_copy = binding_list
        binding_list.clear()
        binding_list.extend(filter(should_keep_0_1, binding_list_copy))

        if not binding_list:
            bindings_to_del.append(key)

    for key in bindings_to_del:
        del bindings[key]

    for obj in objects:
        names = bindable_properties_names.pop( id(obj) )
        for name in names:
            key = (id(obj), name)
            bindable_properties.pop( key, None )


#remove = remove_original
#remove = remove_0
#remove = remove_1
remove = remove_2
```

Compared to the original `remove_original`, `remove_0` modifies the implementation for in-place removal of elements from lists. The original makes a filtered copy of the original list and then copies that back. I changed it to use `filter` which avoids making an intermediate full copy of the list.

`remove_1` further optimizes the removal of elements from dicts compared to `remove_0`. The original implementation makes a full copy of the dict first and then iterates over that. The new implementation directly iterates over the original dict to note down the keys to remove, and then deletes those.

`remove_2` specifically optimizes modifications to the `bindable_properties` dict compared to `remove_1`. By adding a global variable (`bindable_properties_names`) to record reverse lookup info from values to keys in `bindable_properties`, the keys to remove can be directly computed from the passed in parameters without iteration.

```python
bindable_properties_names: DefaultDict[int, List] = defaultdict(list)

# add this about line 142, after inserting new entry to bindable_properties
        bindable_properties_names[id(owner)].append(self.name)

```

Additionally, I suspect the page code may automatically refresh if the server is unresponsive for too long. If true, a slow `remove` implementation could trigger a refresh, which would rerun `remove` (I see `Client.handle_disconnect` called on refresh, which calls `remove` indirectly), causing a death loop.

**Comment by falkoschindler** [comment]
Wow, what a catch, @ruiheng! We've also noticed a poor performance when removing bindings, but haven't done such extensive analysis and optimizations. (In PR #2311 we focused on the binding propagation instead.)

I'll need some time to review your code and try to understand the changes you made. But it would be a great addition to the next release. 🚀

**Comment by ruiheng** [comment]
Oh, I missed one change. If using my `remove_2` implementation, function `reset` in binding.py needs a new line of code:
`bindable_properties_names.clear()`

**Comment by rodja** [comment]
@ruiheng maybe you could create a pull request for remove_2? That would certainly help with the review and testing.

**Comment by falkoschindler** [comment]
@ruiheng I checked your code and I'm still impressed by the performance boost! I'm just not a big fan of `filter` and would replace it with a more compact comprehension like this:

```py
def remove_3(objects: Iterable[Any], type_: Type) -> None:
    """Remove all bindings that involve the given objects.

    The ``type_`` argument is as a quick pre-filter.

    :param objects: The objects to remove.
    :param type_: The type of the objects to remove.
    """
    active_links_copy = active_links
    active_links.clear()
    active_links.extend(
        (source_obj, source_name, target_obj, target_name, transform)
        for source_obj, source_name, target_obj, target_name, transform in active_links_copy
        if not (isinstance(source_obj, type_) and source_obj in objects or
                isinstance(target_obj, type_) and target_obj in objects)
    )

    bindings_to_del = set()
    for key, binding_list in bindings.items():
        binding_list_copy = binding_list
        binding_list.clear()
        binding_list.extend(
            (source_obj, target_obj, target_name, transform)
            for source_obj, target_obj, target_name, transform in binding_list_copy
            if not (isinstance(source_obj, type_) and source_obj in objects or
                    isinstance(target_obj, type_) and target_obj in objects)
        )
        if not binding_list:
            bindings_to_del.add(key)
    for key in bindings_to_del:
        del bindings[key]

    for obj in objects:
        for name in bindable_properties_names.pop(id(obj)):
            bindable_properties.pop((id(obj), name), None)
```

But there's a more important point I don't quite understand:

Among other changes, you replaced
```py
active_links[:] = [(...) for ... in active_links if ...]
```
with
```py
active_links_copy = active_links
active_links.clear()
active_links.extend((...) for ... in active_links_copy if ...)
```

But after you created a shallow copy `active_links_copy`, `.clear()` will clear _both_ lists. So the filter step always processes an empty list. I haven't found a failing pytest and or a code example where this implementation breaks something. But in theory the `.extend()` call doesn't make sense. What do you think?

**Comment by falkoschindler** [comment]
Correction: Some tests in tests/test_element_delete.py are red.

**Comment by ruiheng** [comment]
You are probably right. I actually do not understand Python's internal workings very well. I write code more based on a "try it and see" approach. There may be some mistakes here.  I may have subconsciously transferred habits from other programming languages here.
 
However, the bottleneck for the entire `remove` function seems to be related to handling the `bindable_properties`, since there are so many entries in it. As long as this part of the code can improve performance, the impact on other parts should not be too significant.

**Comment by ruiheng** [comment]
The core issue here is how to efficiently modify a list in-place. My previous approach was indeed incorrect. I googled a bit and found that using "slice assignment" could be a better option. Testing shows this seems to work correctly. The performance is still somewhat better than the original method. Using this method, `remove_0` takes around 105 seconds.

For example, to filter `active_links` list:

```python
active_links[:] = filter(should_keep_0_2, active_links)
```

**Comment by ruiheng** [comment]
After applying this trick to `remove_2`, it now takes around 22 seconds. So the bottleneck now changes to "filtering a list in-place".

**Comment by ruiheng** [comment]
> @ruiheng maybe you could create a pull request for remove_2? That would certainly help with the review and testing.

My previous modifications were not thoroughly tested and I am not very familiar with the codebase for this project. However, I believe the issue I have identified is quite serious, as it has been bothering me for a long time. I hope that by bringing up this discussion, we can address this problem as soon as possible. That's why I did not submit a formal PR.

The performance of the revised `remove_2` function is still not satisfactory. If there is no efficient way to implement the requirement of "modifying a list in-place", then please consider using another data structure instead of a list.

**Comment by falkoschindler** [comment]
I just found a crucial improvement over `remove_2` (see #2373). With a slightly streamlined test code
```py
NUM = 10000
data: dict = {}

@ui.page('/')
def home_page():
    with ui.card() as card:
        for i in range(NUM):
            ui.label().bind_text_from(data, f'text{i}')

    t0 = time.perf_counter()
    card.clear()
    t1 = time.perf_counter()
    print(f'{NUM} elements deleted in {t1-t0:.3f} seconds')
```
the original code takes 1.8 seconds on my machine and still 0.9 seconds with `remove_2` (but with slice assignment for correct results). By introducing an object set for more efficient lookup the time goes down to 0.015 seconds! 🚀

**Comment by falkoschindler** [comment]
No, it turned out that `remove_4` still causes tests to fail, because `bindable_properties_names` doesn't handle objects with multiple binding attributes. But if we simply use its most powerful trick with and use an `object_set` with the original code, the time still goes down to 0.05 seconds from originally 1.8 seconds:

```py
def remove_5(objects: Iterable[Any], type_: Type) -> None:
    """Remove all bindings that involve the given objects.

    The ``type_`` argument is as a quick pre-filter.

    :param objects: The objects to remove.
    :param type_: The type of the objects to remove.
    """
    object_set = set(objects)
    active_links[:] = [
        (source_obj, source_name, target_obj, target_name, transform)
        for source_obj, source_name, target_obj, target_name, transform in active_links
        if not (isinstance(source_obj, type_) and source_obj in object_set or
                isinstance(target_obj, type_) and target_obj in object_set)
    ]
    for key, binding_list in list(bindings.items()):
        binding_list[:] = [
            (source_obj, target_obj, target_name, transform)
            for source_obj, target_obj, target_name, transform in binding_list
            if not (isinstance(source_obj, type_) and source_obj in object_set or
                    isinstance(target_obj, type_) and target_obj in object_set)
        ]
        if not binding_list:
            del bindings[key]
    for (obj_id, name), obj in list(bindable_properties.items()):
        if isinstance(obj, type_) and obj in object_set:
            del bindable_properties[(obj_id, name)]
```
