### ISSUE TITLE
pyproject.toml version is out of sync

### ISSUE THREAD

**Issue by iron3oxide** [zauberzeug/nicegui#2345]
### Description

The version in `pyproject.toml` is still set to "1.4.0". This is a very minor issue and might not be trivial to fix in a way that automatically prevents it from happening again. The only somewhat reliable way I can think of is to have a script or action do this, similarly to `update_citations.py`

**Comment by falkoschindler** [comment]
Hi @iron3oxide, the version is set by the GitHub "release" action:

https://github.com/zauberzeug/nicegui/blob/20962e408f8bd045f379a24ad5e095ee7391fac1/.github/workflows/publish.yml#L26-L27

So the released packages contains the correct version.

Do you see a practical disadvantage of not setting the most recent version in pyproject.toml?

**Comment by iron3oxide** [comment]
I got that, the only disadvantage I see is that the version is "incorrect" when installing nicegui as a git package or locally during development. I did the former to have the fix for #2333 (and potentially other fixes/features in the future) instantly available in my project. So definitely a minor gripe
