### ISSUE TITLE
on_connect does not execute run_javascript

### ISSUE THREAD

**Issue by mukral** [zauberzeug/nicegui#235]
Hello,
how the code has to look to make a javascript file running at start up?
I've tried with `ui.on_startup` or `ui.on_connect`.

The code-examples `ui.on_connect(countdown)` and running javascript with `ui.button('fire and forget', on_click=alert)` work fine, but executing javascript with `ui.on_connect(alert)` does not.

```python
from nicegui import ui
import asyncio
l = ui.label()
async def countdown():
    for i in [5, 4, 3, 2, 1, 0]:
        l.text = f'{i}...' if i else 'Take-off!'
        await asyncio.sleep(1)
async def alert():
    await ui.run_javascript('alert("Hello!")', respond=False)
ui.on_connect(countdown)
ui.on_connect(alert)
ui.button('fire and forget', on_click=alert)
```

the error message is
> IndexError: list index out of range

and somehow I do understand - if there nothing existing, it's not possible to show anything - but is there a way of handling this?
Background is that I would like to begin with a javascript plugin before anything else happens.

Thank you,
Markus

**Comment by mukral** [comment]
Hi, thank you for looking into it.
Update done, error is still there.
Full error message is:
File "C:\....\Python310\site-packages\nicegui\globals.py", line 72, in get_slot
    return get_slot_stack()[-1]
IndexError: list index out of range

**Comment by rodja** [comment]
Very strange. Please have a look at your local file "C:....\Python310\site-packages\nicegui\helpers.py". It should contain the function definition

```python
def safe_invoke(func: Union[Callable, Awaitable], client: Optional[Client] = None) -> None:
```

instead of 

```python
def safe_invoke(func: Union[Callable, Awaitable]) -> None:
```

If not, your installation is broken and I would suggest to remove the nicegui package and reinstall it.

**Comment by mukral** [comment]
Thank you rodja,
problem solved, It was a local issue.
Reason was a concurrent new installation of python 3.11 where all updates went to and a Windows 3.10 installation for the  VSCode environment where the last update was with 1.0.9.

Thanks for the hint.
Markus
