### ISSUE TITLE
ros2 example does not shutdown with ctrl+c 

### ISSUE THREAD

**Issue by kyuhyong** [zauberzeug/nicegui#2356]
### Description

If I run by entering `ros2 run` command, it will display the web ui however it does not shut down by Ctrl+C combination.
The only way to kill the process is by kill -9 process ID. 
How can I solve this issue?

**Comment by JensOgorek** [comment]
What does your code look like? When NiceGUI is jetz added to a ROS2 node, ROS2 and NiceGUI fight over the main thread and the node will not execute properly.
When running NiceGUI with ROS2, you have to bind the ROS2 node to NiceGUI in its own thread. You can see how it's done in the [examples.](https://github.com/zauberzeug/nicegui/blob/main/examples/ros2/ros2_ws/src/gui/gui/node.py#L72)

**Comment by kyuhyong** [comment]
Yes I am using the ROS example 
https://github.com/zauberzeug/nicegui/tree/main/examples/ros2/ros2_ws/src/gui
```
$ ros2 run gui nicegui_node
NiceGUI ready to go on http://localhost:8080, http://172.17.0.1:8080, and http://192.168.0.121:8080
^C^C^C^C^C
```
I cannot shut it down. And I still can see the node is running.
```
ros2 node list
/nicegui
```

**Comment by JensOgorek** [comment]
What operating system are you using? What version of NiceGUI are you using? There were some changes with newer NiceGUI versions, that also effected these examples. 
Besides not being able to be stopped, does the example work (together with the simulator)? Is there an error message in the terminal after the node getting killed?

**Comment by kyuhyong** [comment]
I'm running ubuntu 20.04 and ros-foxy
pip3 show nicegui gives Version 1.4.9
The example code work just fine. The node does not give any message when killed by kill -9 process.

**Comment by JensOgorek** [comment]
Ok, there might be a problem with the ROS version. All of this is made with ROS Humble, Foxy is way older (2020).

You can also try the other examples (maybe after changing the ROS distro) [image switcher](https://github.com/zauberzeug/ros_nicegui_image_example) and [turtle sim joystick](https://github.com/zauberzeug/ros_nicegui_turtlesim_joystick) (which works with the ROS2 Tutorial turtle sim)

**Comment by kyuhyong** [comment]
I installed ros-humble on ubuntu 22.04 and tested again.
Now it shutdown normally. I don't know exactly what's different handling threading between foxy and humble, maybe humble handles better?
Hope there could be solution for foxy too. Thanks for your comments.
