### ISSUE TITLE
Calls of 'task_logger.create_task' are never awaited

### ISSUE THREAD

**Issue by TutorExilius** [zauberzeug/nicegui#236]
Hello,

I found the call `create_task()` of the task_logger in some lines in client.py.

The function `create_task()` seems to return an asyncio.task object, which is not "awaited" in any calls I found (not only in client.py)

Is this how it should be and not better to wait for it?

I would expect code like this:
`await create_task(...)`

Note: All tasks need to be hold es reference to avoid disapperaing.
see: https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task

> **Important:** Save a reference to the result of this function, to avoid a task disappearing mid-execution.

**Comment by rodja** [comment]
Wow. We completely missed that. Thanks for identifying this bug of possible huge magnitude. Please have a look at my pull request https://github.com/zauberzeug/nicegui/pull/237. Is it sufficient?

**Comment by rodja** [comment]
We're using `task_logger.create_task` mainly to create background tasks. Maybe we should also rename it to `background_tasks.create` to better convey the meaning?

**Comment by TutorExilius** [comment]
Looks good to me, thanks for fixing!
