### ISSUE TITLE
ui.code() can't copy in safari browser

### ISSUE THREAD

**Issue by Wzhipeng** [zauberzeug/nicegui#2377]
### Description

<img width="923" alt="image" src="https://github.com/zauberzeug/nicegui/assets/34640461/5688d84e-00ef-47e1-95cc-dc060ba97b6d">
The ui.code component uses navigator.clipboard.writeText from the copy function, but an error will be reported in the safari browser and cannot be copied.

![image](https://github.com/zauberzeug/nicegui/assets/34640461/82f3137d-c7ad-42cd-83de-73ea97469c81)

**Comment by Wzhipeng** [comment]
![image](https://github.com/zauberzeug/nicegui/assets/34640461/c2359fa9-1ecd-43ec-b97a-f24ecfd3d7c3)

**Comment by falkoschindler** [comment]
Thanks for reporting this issue, @Wzhipeng!

As I just learned from ChatGPT:
> Modern browsers often require a user-initiated action, like a click or tap, to access the clipboard. Ensure your clipboard writing code is triggered by such an event.

I managed to fix it by writing to the clipboard directly on the client without making the detour over the server. This way Safari recognizes the clipboard access as user-initiated and doesn't raise an error.

**Comment by adrastaea** [comment]
> I managed to fix it by writing to the clipboard directly on the client without making the detour over the server. This way Safari recognizes the clipboard access as user-initiated and doesn't raise an error.

Could you show a code snippet? On Safari, I seem to still be getting `Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.` with the following code

```
@ui.page()
async def example_page(client: Client):
    async def copy_url():
        await client.connected()
        await client.run_javascript(f"navigator.clipboard.writeText('{BASE_URL}{app.url_path_for('example_page')}')")
    ui.icon("link").on("click", copy_url)
```

**Comment by rodja** [comment]
@adrastaea I think the trick is in this line

https://github.com/zauberzeug/nicegui/blob/5ef413015b6dda8719e21997d127cc3dea932e04/website/documentation/demo.py#L44

And it will get nicer in the next release with #2536. It allows registering of javascript code for events with `.on`.
