### ISSUE TITLE
ui.code unable to copy when there contain ` symbol

### ISSUE THREAD

**Issue by Wzhipeng** [zauberzeug/nicegui#2400]
### Description

Can't copy when my content contains \` symbol
This is caused by multiple \` symbol in JavaScript variable substitution

Below is the code I solved:
```py
copy_button._prop['onclick'] = f"""navigator.clipboard.writeText({json.dumps(message)})"""
```

**Comment by falkoschindler** [comment]
Thanks a lot for reporting this issue, @Wzhipeng!
You're right, we need to correctly serialize the content, which can be done using `json.dumps`. I fixed it in https://github.com/zauberzeug/nicegui/commit/328e3ad6e3b630da4161b53092b6869046dc4b02.
