### ISSUE TITLE
Drawer ignores `top_corner` and `bottom_corner` in native window

### ISSUE THREAD

**Issue by afpineda** [zauberzeug/nicegui#2402]
### Description

When the UI is running in a native window (`ui.run(native=True)`), the drawer's constructor parameters `top_corner=False,bottom_corner=False` are ignored.

## What are you trying to do?

Create a simple left drawer like this:

```python
from nicegui import ui

with ui.header():
    with ui.row().classes("align-middle"):
        ui.button(icon="menu").on("click", lambda: drawer.toggle()).props(
            "flat color=white dense"
        ).classes("align-bottom")
        ui.label('test').classes("text-h3 align-middle tracking-wide ellipsis")

with ui.left_drawer(value=False,top_corner=False,bottom_corner=False) as drawer:
    ui.label("test")

ui.run(native=True, reload=False)
```

## What do you expect to happen?

When I click the "menu" button and the drawer toggles, it should *not* overlap the header.

## What happens instead?

The drawer, when open, overlaps the header.

## Other information

When run in a browser window, the same code behaves as expected.

## Context

```text
>pip show nicegui
Name: nicegui
Version: 1.4.11
...
```

```text
>pip show pywebview
Name: pywebview
Version: 4.4.1
...
```

**Comment by falkoschindler** [comment]
I think this is because your native window is too narrow, so that Quasar automatically switches to "mobile" mode.
You can enforce "desktop" mode using `.props('behavior=desktop')` on the drawer. See https://quasar.dev/layout/drawer for more information.
