### ISSUE TITLE
Ubuntu22.04: NiceGUI running Native Mode (with native=True) failed

### ISSUE THREAD

**Issue by yuanxion** [zauberzeug/nicegui#2419]
### Description

When I run the nicegui sample below with "native=False":
```py
# test_native_mode.py 
from nicegui import ui

@ui.page('/')
async def page():
    ui.label('Hello from page')

ui.run(reload=False, native=False)
#ui.run(reload=False, native=True)
```
it works with a Web UI popped up:
<img width="181" alt="image" src="https://github.com/zauberzeug/nicegui/assets/96522341/8d42f83a-5f54-49c2-851d-e45b7e777e77">

But when changed to "**native=True**", it will prompt "**Connection terminated unexpectedly**" :
![image](https://github.com/zauberzeug/nicegui/assets/96522341/676365c8-6da6-4220-b5af-9a630346c966)

The test_native_mode.py file I used is from PR [test-native-mode](https://github.com/zauberzeug/nicegui/tree/test-native-mode).
The tested environment is:
```
Operating System: Ubuntu 22.04.3 LTS              
Kernel: Linux 6.5.0-14-generic
Python:  3.10.12
nicegui: 1.4.6 (& 1.4.12)
pywebview: 4.4.1
```
BTW, running on Windows 11 worked with "native=True" (as well as "native=False").
```
OS: Windows 11
Python: 3.10.11
nicegui: 1.4.6
pywebview: 4.4.1
```
<img width="403" alt="image" src="https://github.com/zauberzeug/nicegui/assets/96522341/799074b4-eccd-4f16-b93f-205bd7893d4f">

**Comment by falkoschindler** [comment]
Hi @yuanxion, can you, please, try a minimal pywebview app:
```py
import webview

webview.create_window('Test', html='Hello World')
webview.start()
```
Does that work correctly?

**Comment by yuanxion** [comment]
Hi @falkoschindler, thanks for looking at this.
Yes, the simple app you provided works.

<img width="404" alt="image" src="https://github.com/zauberzeug/nicegui/assets/96522341/83873f82-b0cf-4c31-bec8-428a25e0b86e">

**Comment by rodja** [comment]
Sorry we can not reproduce the behaviour with your setup. Anyone else?

**Comment by yuanxion** [comment]
> Sorry we can not reproduce the behaviour with your setup. Anyone else?

Hi @rodja, that's great to hear you cannot reproduce my issue.

I found that I will get the above "Connection terminated unexpectedly" issue on my Host Ubuntu machine (where source code test_native_mode.py located in).
```
Operating System: Ubuntu 22.04.3 LTS              
Kernel: Linux 6.5.0-14-generic
Python:  3.10.12
nicegui: 1.4.13
pywebview: 4.4.1

WAYLAND_DISPLAY=wayland-0
GNOME_SETUP_DISPLAY=:1
DISPLAY=:0
```
![login-1-failed](https://github.com/zauberzeug/nicegui/assets/96522341/1129f402-1690-4842-9b6d-5beb1fae7932)


But if I run the test_native_mode.py from git bash on another Windows machine (login via ssh),
```
OS: Windows 11
Git version 2.43.0.windows.1

DISPLAY=localhost:10.0
```
Though I will not get the UI on Windows:
<img width="685" alt="image" src="https://github.com/zauberzeug/nicegui/assets/96522341/7ead2ec0-e072-44c8-ae30-2927af9ec490">

I can get the UI from the remote Ubuntu Host:

![login-2-succ](https://github.com/zauberzeug/nicegui/assets/96522341/5a27642c-f913-4757-beda-6b3d1260edd5)

Not sure whether the DISPLAY variable affects this.

**Comment by rodja** [comment]
Could you please run your `test_native_mode.py` again and run the command

```bash
nghttp -v http://localhost:8000
```

for `native=True` and `native=False` and compare the results. `nghttp` is similar to curl but has better http2 debugging capabilities. Install with `apt install nghttp2-client`.

**Comment by yuanxion** [comment]
@rodja The outputs of nghttp are the same and have no difference.

- Native=False
```
python test_native_mode.py
NiceGUI ready to go on http://localhost:8000, http://10.239.82.137:8000, and http://172.18.0.1:8000

WARNING:  Invalid HTTP request received.
```
nghttp -v http://localhost:8000
```
$ nghttp -v http://localhost:8000
[  0.000] Connected
[  0.000] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
[  0.000] send PRIORITY frame <length=5, flags=0x00, stream_id=3>
          (dep_stream_id=0, weight=201, exclusive=0)
[  0.000] send PRIORITY frame <length=5, flags=0x00, stream_id=5>
          (dep_stream_id=0, weight=101, exclusive=0)
[  0.000] send PRIORITY frame <length=5, flags=0x00, stream_id=7>
          (dep_stream_id=0, weight=1, exclusive=0)
[  0.000] send PRIORITY frame <length=5, flags=0x00, stream_id=9>
          (dep_stream_id=7, weight=1, exclusive=0)
[  0.000] send PRIORITY frame <length=5, flags=0x00, stream_id=11>
          (dep_stream_id=3, weight=1, exclusive=0)
[  0.000] send HEADERS frame <length=38, flags=0x25, stream_id=13>
          ; END_STREAM | END_HEADERS | PRIORITY
          (padlen=0, dep_stream_id=11, weight=16, exclusive=0)
          ; Open new stream
          :method: GET
          :path: /
          :scheme: http
          :authority: localhost:8000
          accept: */*
          accept-encoding: gzip, deflate
          user-agent: nghttp2/1.43.0
[  0.000] [ERROR] Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.
Some requests were not processed. total=1, processed=0
```
- Native=True
```
NiceGUI ready to go on http://localhost:8000
Could not find ':' in DISPLAY: needs-to-be-defined
(test_native_mode.py:267827): dbind-WARNING **: 05:30:27.930: Could not open X display

WARNING:  Invalid HTTP request received.
```
nghttp -v http://localhost:8000
```
$ nghttp -v http://localhost:8000
[  0.000] Connected
[  0.000] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
[  0.000] send PRIORITY frame <length=5, flags=0x00, stream_id=3>
          (dep_stream_id=0, weight=201, exclusive=0)
[  0.000] send PRIORITY frame <length=5, flags=0x00, stream_id=5>
          (dep_stream_id=0, weight=101, exclusive=0)
[  0.000] send PRIORITY frame <length=5, flags=0x00, stream_id=7>
          (dep_stream_id=0, weight=1, exclusive=0)
[  0.000] send PRIORITY frame <length=5, flags=0x00, stream_id=9>
          (dep_stream_id=7, weight=1, exclusive=0)
[  0.000] send PRIORITY frame <length=5, flags=0x00, stream_id=11>
          (dep_stream_id=3, weight=1, exclusive=0)
[  0.000] send HEADERS frame <length=38, flags=0x25, stream_id=13>
          ; END_STREAM | END_HEADERS | PRIORITY
          (padlen=0, dep_stream_id=11, weight=16, exclusive=0)
          ; Open new stream
          :method: GET
          :path: /
          :scheme: http
          :authority: localhost:8000
          accept: */*
          accept-encoding: gzip, deflate
          user-agent: nghttp2/1.43.0
[  0.000] [ERROR] Remote peer returned unexpected data while we expected SETTINGS frame.  Perhaps, peer does not support HTTP/2 properly.
[  0.000] send GOAWAY frame <length=25, flags=0x00, stream_id=0>
          (last_stream_id=0, error_code=PROTOCOL_ERROR(0x01), opaque_data(17)=[SETTINGS expected])
Some requests were not processed. total=1, processed=0
```

**Comment by yuanxion** [comment]
Hi @rodja & @falkoschindler, finally I figured out a way to address the above connect exception by setting no_proxy for localhost.
```
export no_proxy=localhost,127.0.0.1
```

Sorry for this stupid question and thanks for your attention😀. I will close this issue.
