### ISSUE TITLE
ui.notification element not changing style based on `type`

### ISSUE THREAD

**Issue by csrubin** [zauberzeug/nicegui#2427]
### Description

1. I am trying to use the `type` argument shown in the [docs](https://nicegui.io/documentation/notification) to change the styling of a notification. 

```
ui.notification("Hello, World!", type="positive")
```
<img width="504" alt="Screenshot 2024-01-24 at 1 38 19 PM" src="https://github.com/zauberzeug/nicegui/assets/19996600/519ffdf8-b000-4e4e-9c8d-393a467de439">

2. I expect the behavior to be the same as it is for `ui.notify` ->  for the notification to change color (positive = green, negative = red). 
3. The notification remains the default regardless of value set in the `type` argument.

**Comment by rodja** [comment]
Thanks for reporting this! It seems that `ui.notificaiton` is setting many more defaults than `ui.notify`. If I remove the line which sets `color` to None (https://github.com/zauberzeug/nicegui/blob/df60f2424346890c42459fc74332e9ed299eadbd/nicegui/elements/notification.py#L66) the type is rendered green. @falkoschindler should we update the parameter init to use the same technique as in `ui.notify`?

**Comment by falkoschindler** [comment]
If fixed this bug by removing `type`, `color` and `icon` from the options dictionary whenever they are `None`.
