### ISSUE TITLE
Contact information and additional customization options for error page

### ISSUE THREAD

**Issue by tjakobi** [zauberzeug/nicegui#243]
I like the smooth dynamic error pages that are generated by nicegui.

However, if used for a public web application, it would be very helpful to include additional contact information, such as an email address and/or web link similar to apache-generated error pages. 

E.g. ``Please contact the server administrator at change@this.com for additional support.`` or similar. This parameter could be passed to ``ui.run`` when starting the service.

Potentially, custom error images instead of the _sad_ nice guy might be provided, too.

What do you think?

**Comment by rodja** [comment]
Thanks for reaching out @tjakobi. You are absolutely right, this would be a nice addition. But maybe we can already archive it without expanding the API. Consider this code:

```python
from fastapi import Request, Response
from nicegui import Client, app, ui

@app.exception_handler(404)
async def exception_handler_404(request: Request, exception: Exception) -> Response:
    with Client(ui.page('')) as client:
        with ui.column().style('width: 100%; padding: 5rem 0; align-items: center; gap: 0'):
            ui.label('Sorry').style('font-size: 3.75rem; line-height: 1; padding: 1.25rem 0')
            ui.label('Something went wrong.').style('font-size: 1.25rem; line-height: 1.75rem; padding: 1.25rem 0')
            ui.label('Please contact the server administrator at change@this.com for additional support.').style(
                'font-size: 1.125rem; line-height: 1.75rem; color: rgb(107 114 128)')
    return client.build_response(request, 404)

ui.link('Go to nonexisting page', '/nonexisting')

ui.run()
```

Here we simply register a new FastAPI exception handler for 404 errors in the same manner as in https://github.com/zauberzeug/nicegui/blob/8693f4e9417ce6e5982dad253742614ec91371e5/nicegui/nicegui.py#L70

If you launch the code and access a route which does not exist, you will see the custom error message coded inside the exception handler. Same can be done for all other exceptions by using `@app.exception_handler(Exception)`. Does that suit your needs?

**Comment by tjakobi** [comment]
Hi @rodja,

Thank you, this is great, exactly what I was looking for!

No need to to expand the API then.

In case of actual errors in the application, i.e. error 500, I probably would be able to pass the error message through using the exception object I suppose?

Thank you,

Tobias

**Comment by falkoschindler** [comment]
> In case of actual errors in the application, i.e. error 500, I probably would be able to pass the error message through using the exception object I suppose?

Exactly, you can use the `exception` argument to fill the content of your error page. NiceGUI is doing something similiar here https://github.com/zauberzeug/nicegui/blob/8693f4e9417ce6e5982dad253742614ec91371e5/nicegui/nicegui.py#L82 and here, respectively:

https://github.com/zauberzeug/nicegui/blob/8693f4e9417ce6e5982dad253742614ec91371e5/nicegui/error.py#L7-L26
