### ISSUE TITLE
nicegui x fastApi problem

### ISSUE THREAD

**Issue by Gus-The-Forklift-Driver** [zauberzeug/nicegui#244]
When trying to launch the [fast api example](https://github.com/zauberzeug/nicegui/tree/main/examples/fastapi), I get this error :
```AttributeError: module 'nicegui.globals' has no attribute 'tailwind'```
I'm a bit of a noob and tried to install the package tailwind, but this gave no results.
> This problem is also true in my own project using the code from the example

**Comment by elik-vayyar** [comment]
I just had the same problem.
There is a missing globals definition in the [run_with ](https://github.com/zauberzeug/nicegui/blob/e37789ce8ce85ac2fd73349ad74564378c153d68/nicegui/run_with.py#L9)function: 
```python
globals.tailwind = True
```

**Comment by falkoschindler** [comment]
Hi, thanks for reaching out!
This was indeed a tiny bug when starting NiceGUI with an existing FastAPI app. This should be fixed in [e37789c](https://github.com/zauberzeug/nicegui/commit/e37789ce8ce85ac2fd73349ad74564378c153d68).
