### ISSUE TITLE
Serving app behind reverse proxy subpath

### ISSUE THREAD

**Issue by schmurian** [zauberzeug/nicegui#245]
When trying to serve a nicegui app behind Nginx reverse proxy, I get an Error message "Connection lost. Trying to reconnect...

Basic Nginx configuration

```
...

location /nicegui/ {
   proxy_http_version 1.1;
   proxy_set_header Connection "";
   proxy_pass http://127.0.0.1:5556/;
}
...

```

main.py from the Basic Example

```
from nicegui import ui

ui.label('Hello NiceGUI!')

ui.run(host="127.0.0.1", port=5556, show=False)

```

Any advice would be appreciated.

**Comment by schmurian** [comment]
Hi,

Thank you for sharing the configuration you're using. Does this work on a subpath too?
I will try it and let you know if it worked.

**Comment by schmurian** [comment]
No, sorry. It resulted again in the "Connection lost..." message.

**Comment by rodja** [comment]
I'll try myself and hopefully provide a demonstration with two docker containers soon.

**Comment by rodja** [comment]
Here is an fully working example: https://github.com/zauberzeug/nicegui/blob/main/examples/nginx_subpath/nginx.conf
The main thing I forgot earlier was the pattern matching. Basically you need to route all requests with the specific path prefix to NiceGUI.

**Comment by schmurian** [comment]
Thank you for sharing!
