### ISSUE TITLE
`examples/opencv_webcam` doesn't work due to the lack of `cv2`

### ISSUE THREAD

**Issue by solzard** [zauberzeug/nicegui#248]
[examples/opencv_webcam/main.py](https://github.com/zauberzeug/nicegui/blob/635937d19aec074bb918f88a58c10786ece28267/examples/opencv_webcam/main.py#LL5C6-L5C6) raises `ModuleNotFoundError: No module named 'cv2'` because `opencv-python` is not on dev dependencies. 

https://github.com/zauberzeug/nicegui/blob/635937d19aec074bb918f88a58c10786ece28267/examples/opencv_webcam/main.py#L5

**Comment by rodja** [comment]
Thanks for spotting this. There are also other examples which use external libs. Like the `replica` package in https://github.com/zauberzeug/nicegui/blob/main/examples/ai_interface/main.py for example. Maybe instead of adding them to NiceGUI developer dependencies (as you did with pull request #249) we could add `requirements.txt` files to the specific example folders. That way it would be more clear for what the packages are needed. What do you think, @solzard?

**Comment by solzard** [comment]
Another idea to resolve dependencies is to use `poetry`'s optional dependency groups.
We can add an optional `examples` group to `pyproject.toml` and move `replicate`, `opencv-python`, or future dependencies there.

```toml
[tool.poetry.group.examples]
optional = true

[tool.poetry.group.examples.dependencies]
replicate = "^0.4.0"
opencv-python = "^4.7.0.68"
```

Dependencies in Optional groups are skipped while installing dependencies with the normal `poetry install`.
If someone wants to try examples, they just do `poetry install --with examples` instead.

Pros of the `poetry` optional group:
- All dependencies are put together into a single `pyproject.toml` instead of having `requirements.txt` in each example folder.
- `poetry` will do all dependency resolving.

Cons:
- The project management will be more locked in to `poetry`.

I prefer this approach, but it's up to maintainers.


Cf: [Optional groups: Managing dependencies | master | Documentation | Poetry - Python dependency management and packaging made easy](https://python-poetry.org/docs/master/managing-dependencies/#optional-groups)

**Comment by falkoschindler** [comment]
Thanks again for your contribution, @solzard! Making use of additional dependency groups is certainly a very reasonable solution.

However, we came to the conclusion to add individual requirements.txt files for the two examples that have additional dependencies. We think this simplifies things for anyone who has pip-installed NiceGUI and is quickly looking into an example. Knowing how to tap into the main pyproject.toml might be not so obvious as to read or install the requirements.txt.
