### ISSUE TITLE
multiplying events

### ISSUE THREAD

**Issue by bmaranville** [zauberzeug/nicegui#2504]
### Description

1. I want to listen for a click event on one plotly plot, then use that to update a second plotly plot.
2. I expect the `on('plotly_click', ...)` handler to fire exactly once for each click
3. Instead, the handler fires 3x on the first click, then 4x on the second click, then 5x ... etc.

Here is code to reproduce the issue:
```python
from nicegui import ui
import plotly.graph_objects as go

fig = go.Figure(go.Scatter(x=[0,1,2,3,4], y=[3,5,2,7,8]))
plot = ui.plotly(fig)

fig2 = go.Figure(go.Scatter(x=[0,1,2,3,4], y=[2,5,1,2,1]))
plot2 = ui.plotly(fig2)

def click_handler(ev):
    plot2.update()
    print(ev.args)

plot.on("plotly_click", click_handler)
ui.run()
```

**Comment by platinops** [comment]
I believe this same bug also causes #2435
