### ISSUE TITLE
How to create tabs in NiceGUI 1.1?

### ISSUE THREAD

**Issue by JS-Aibel** [zauberzeug/nicegui#251]
Hi,

I am looking for a more single-page application approach for my GUI, and for that, tabs would be nice to have.
In this post https://github.com/zauberzeug/nicegui/discussions/133#discussioncomment-4411042 you are showing how to create tabs in NiceGui. 

**1.	How do we give the different tabs content?**

**2.	Is it possible to use “Q-tabs” within the NiceGui Page Layout?**
[NiceGUI](https://nicegui.io/reference#page_layout)
[Layout Header and Footer | Quasar Framework](https://quasar.dev/layout/header-and-footer#example--playing-with-qtabs)

**single-page application**
I think having the option to use tabs will make it easier to design a single-page application (SPA). SPAs will in my opinion be a good fit when NiceGui start supporting desktop, ref. [Provide Desktop Mode · Discussion #89 · zauberzeug/nicegui (github.com)](https://github.com/zauberzeug/nicegui/discussions/89)

**Comment by falkoschindler** [comment]
Here is a minimum example combining QTabs with QTabPanels. Using a generic event subscription `.on('update:model-value', ...)` we can handle tab changes and set the new `model-value` for both the tabs and the panels:

```python
def handle_change(msg: dict) -> None:
    name = msg['args']
    tabs.props(f'model-value={name}')
    panels.props(f'model-value={name}')

with Element('q-tabs').on('update:model-value', handle_change) as tabs:
    for name in ['A', 'B', 'C']:
        Element('q-tab').props(f'name={name} label={name}')

with Element('q-tab-panels').props('model-value=A animated') as panels:
    for name in ['A', 'B', 'C']:
        with Element('q-tab-panel').props(f'name={name}'):
            ui.label(f'Content of {name}')
```

Tabs and panels can be placed independently of each other. So you can wrap the tabs with a `with ui.header():`.

**Comment by rodja** [comment]
I just pushed a new example combining a foldable menu with tabs: https://github.com/zauberzeug/nicegui/commit/5e1610bad6216e20a148fd6f221e41921523b268. Still, on this issue we should think about a nicer integration of tabs.

**Comment by rbeeli** [comment]
+1 A very important component IMO. Good stuf.

**Comment by falkoschindler** [comment]
I implemented an API for tabs and tab panels on the [tabs](https://github.com/zauberzeug/nicegui/tree/tabs) branch.

You can try it out as follows:

```py
with ui.tabs() as tabs:
    ui.tab('Home', icon='home')
    ui.tab('About', icon='info')

with ui.tab_panels(tabs, value='Home'):
    with ui.tab_panel('Home'):
        ui.label('This is the first tab')
    with ui.tab_panel('About'):
        ui.label('This is the second tab')
```

**Comment by rodja** [comment]
Great! Merged into main.

**Comment by rafo** [comment]
@falkoschindler So the [Example](https://github.com/zauberzeug/nicegui/issues/251) should be modified?

**Comment by falkoschindler** [comment]
@rafo What example do you mean? Why should it be modified?

**Comment by rafo** [comment]
@falkoschindler Sorry, pasted the wrong link. Should be https://github.com/zauberzeug/nicegui/blob/main/examples/menu_and_tabs/main.py 

I will fix my https://github.com/zauberzeug/nicegui/issues/251#issuecomment-1540306075

**Comment by rafo** [comment]
BTW: @falkoschindler @rodja nicegui is wonderful!

**Comment by falkoschindler** [comment]
@rafo Oh yes, we need to review and update some of our examples. With NiceGUI's more recent features, some of them surely can be simplified. That's a great opportunity for a pul request, by the way. 🙂
