### ISSUE TITLE
Nicegui execute anything

### ISSUE THREAD

**Issue by versus666jzx** [zauberzeug/nicegui#2514]
### Description

When the user drags any file into the application window in native mode, NiceGui launches it or opens the browser.
How can this be avoided?

**Comment by falkoschindler** [comment]
Hi @versus666jzx, this doesn't happen on my machine... 🤔

- What OS are you using?
- Does it happen with this minimal NiceGUI app?
    ```py
    from nicegui import ui
    ui.label('Hello, world!')
    ui.run(native=True)
    ```
- Does it also happen with this minimal pywebview app?
    ```py
    import webview
    webview.create_window('Test', html='Hello World!')
    webview.start()
    ```

**Comment by versus666jzx** [comment]
@falkoschindler. hi!
I'm using win 11 pro, build 22631.3085.
Yes, this reproduces in minimal NiceGui and pywebview apps.

**Comment by falkoschindler** [comment]
Maybe you can workaround this problem by disabling drag and drop events with some custom JavaScript:
```js
document.addEventListener('dragover', function(event) {
    event.preventDefault();
}, false);

document.addEventListener('drop', function(event) {
    event.preventDefault();
}, false);
```

Apart from that it'd be probably best to report an issue over at [pywebview](https://github.com/r0x0r/pywebview/), since it seems like an issue on their side.

**Comment by versus666jzx** [comment]
Yes, this works. Thank you for solution!
