### ISSUE TITLE
ui.run_with with mount_path is broken

### ISSUE THREAD

**Issue by aersam** [zauberzeug/nicegui#2515]
### Description

Hi there

I tried embedding nicegui with an existing app under a mount path like this:

```python
ui.run_with(
    app,
    mount_path="/nicegui",
    storage_secret=os.getenv("NICEGUI_STORAGE_SECRET", "fA3478GN$N$*wT60#--"),
)
```

However, this breaks the websocket connection. as a workaround I did this:

```python
import nicegui.nicegui

nicegui.nicegui.sio_app.engineio_path = "/nicegui" + nicegui.nicegui.sio_app.engineio_path
``` 

The issue seeems to be that the `sio_app` in nicegui.py hardcodes the path:

`sio_app = socketio.ASGIApp(socketio_server=sio, socketio_path='/_nicegui_ws/socket.io')`, while the fronend assumes it's under the mount_path. I guess you had to overwrite that engineio_path in the run_with method

**Comment by rodja** [comment]
I traced the error back to python-engineio where it hopefully gets fixed with my pull request.
