### ISSUE TITLE
`ui.plotly` looses event handlers when toggling its visibility

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#2519]
### Description

As noticed by @bmaranville on PR #2505, `ui.plotly` won't emit events after the element has been hidden:

```py
fig = {'data': [{'x': [1, 2, 3], 'y': [1, 2, 3]}]}
plot = ui.plotly(fig).classes('w-96 h-96').on('plotly_click', ui.notify)
ui.checkbox('visible').bind_value(plot, 'visible')
```

**Comment by bmaranville** [comment]
It looks like it's not specific to the visibility attribute... adding any class (or just calling `plot.classes`?) causes the event handlers to be lost.

```python
from nicegui import ui

fig = {'data': [{'x': [1, 2, 3], 'y': [1, 2, 3]}]}
plot = ui.plotly(fig).classes('w-96 h-96').on('plotly_click', ui.notify)
ui.checkbox('visible').bind_value(plot, 'visible')
ui.button("add class", on_click=lambda: plot.classes('bg-red-100'))

ui.run()
```

**Comment by bmaranville** [comment]
Also I can't reproduce the error in v1.4.13, so it's something that changed very recently.

**Comment by falkoschindler** [comment]
Very interesting, @bmaranville!
Calling `.classes('bg-red-100')` drops event handlers, but a plain `.classes()` or `.update()` does not.

**Comment by falkoschindler** [comment]
I just created PR #2523 with a possible solution.
@bmaranville Would you like to try it out?

**Comment by bmaranville** [comment]
It seems to work, but I am still confused why the re-render is (only sometimes) causing the events to stop firing?

**Comment by falkoschindler** [comment]
@bmaranville Yeah, that's weird. But I guess Vue is "magically" deciding when to re-render: While `plot.classes('bg-red-100')` actually changes something, `plot.classes()` and `plot.update()` don't. This might be the reason for the different behavior.

**Comment by bmaranville** [comment]
This fix seems to work:
```diff
diff --git a/nicegui/elements/plotly.vue b/nicegui/elements/plotly.vue
index 8e2a51b1..c72f7f05 100644
--- a/nicegui/elements/plotly.vue
+++ b/nicegui/elements/plotly.vue
@@ -1,19 +1,21 @@
 <template>
-  <div></div>
+  <div>
+    <div></div>
+  </div>
 </template>
 
 <script>
 export default {
   async mounted() {
     await this.$nextTick();
-    this.update();
+    await this.update();
     this.set_handlers();
   },
-  updated() {
+  async updated() {
     this.update();
   },
   methods: {
-    update() {
+    async update() {
       // default responsive to true
       const options = this.options;
       if (options.config === undefined) options.config = { responsive: true };
@@ -21,7 +23,7 @@ export default {
 
       // Plotly.react can be used to create a new plot and to update it efficiently
       // https://plotly.com/javascript/plotlyjs-function-reference/#plotlyreact
-      Plotly.react(this.$el.id, this.options.data, this.options.layout, options.config);
+      await Plotly.react(this.$el.children[0], this.options.data, this.options.layout, options.config);
 
       // store last options
       this.last_options = options;
@@ -47,7 +49,7 @@ export default {
         "plotly_redraw",
         "plotly_animated",
       ]) {
-        this.$el.on(name, (event) => {
+        this.$el.children[0].on(name, (event) => {
           const args = {
             ...event,
             points: event?.points?.map((p) => ({
```

**Comment by bmaranville** [comment]
My version will be more efficient than the other way, but I don't know how much (removing and reattaching event handlers doesn't seem very costly). 

As for styling, I don't think this change will break much of anything.  There's not much you can do with custom CSS on a plotly target element anyway - if you want to style things in the plot you need to add CSS rules targeting the inner elements (you might have noticed that adding 'bg-red-100' had no effect at all on the visual rendering)

The only exception to this is that plotly figures out the size of the plot based on the size of the target div: so you might want to add a scoped style in plotly.vue:
```css
.js-plotly-plot {
  height: inherit;
  width: inherit;
}
```
so that the size of the plot can be controlled by setting the height/width of the outer div.

**Comment by bmaranville** [comment]
One more detail... is it possible that nicegui is removing the 'js-plotly-plot' class that plotly is adding to the div, because it's not on the list of classes that nicegui is tracking (it's added by the component itself)?  Is there any way to stop nicegui from doing that?

**Comment by bmaranville** [comment]
```diff
diff --git a/nicegui/elements/plotly.py b/nicegui/elements/plotly.py
index 72e44b6b..734a4183 100644
--- a/nicegui/elements/plotly.py
+++ b/nicegui/elements/plotly.py
@@ -13,6 +13,7 @@ except ImportError:
 
 
 class Plotly(Element, component='plotly.vue', libraries=['lib/plotly/plotly.min.js']):
+    _default_classes = ['js-plotly-plot']
 
     def __init__(self, figure: Union[Dict, go.Figure]) -> None:
         """Plotly Element
```
... also solves the problem, with no other changes needed.

**Comment by bmaranville** [comment]
But this might be even better, because it doesn't add the class to the element, but just to the list of managed classes after the plot is initialized.  Plotly adds the class directly to the element, but nicegui won't later remove it...

```diff
diff --git a/nicegui/elements/plotly.py b/nicegui/elements/plotly.py
index 72e44b6b..cc912581 100644
--- a/nicegui/elements/plotly.py
+++ b/nicegui/elements/plotly.py
@@ -36,6 +36,7 @@ class Plotly(Element, component='plotly.vue', libraries=['lib/plotly/plotly.min.
 
         self.figure = figure
         self.update()
+        self._classes.append('js-plotly-plot')
 
     def update_figure(self, figure: Union[Dict, go.Figure]):
         """Overrides figure instance of this Plotly chart and updates chart on client side."""
```

**Comment by falkoschindler** [comment]
@bmaranville Wow, that's a really nice solution! 😎
Indeed, NiceGUI seems to be removing all unmanaged classes of the plotly element. Adding it to the `_classes` list seems to be just the right thing to do.
