### ISSUE TITLE
_handle_delete of Elements is never called when a Client is deleted

### ISSUE THREAD

**Issue by Johannes-** [zauberzeug/nicegui#2589]
### Description

**Description**
The code block from Line 300 to 302 is never reached as the elements array will be always empty as each element in the array is deleted in row 298 before. Hence the method _handle_delete of an element is never called when a Client is deleted. 

**Reproduce**
For example in the case of the ui.upload component it leads to the fact that the upload routes are never removed from the app, as the _handle_delete method of the ui.upload element is never called.

**Fix**
Changing the order of the loops should fix the problem.

https://github.com/zauberzeug/nicegui/blob/fdab7b80886b54d3c2af0d3d105f75c91a785849/nicegui/client.py#L293-L302

https://github.com/zauberzeug/nicegui/blob/fdab7b80886b54d3c2af0d3d105f75c91a785849/nicegui/elements/upload.py#L73-L75

**Comment by falkoschindler** [comment]
Thanks for reporting this issue, @Johannes-!
I just merged your pull request. 🙂
