### ISSUE TITLE
ui.html cannot generate 'arbitrary' html, always produces div

### ISSUE THREAD

**Issue by kleynjan** [zauberzeug/nicegui#2604]
### Description

Currently, ui.html always generates a \<div> around the given content. This behavior is not documented; it certainly means I cannot create "arbitrary" html. I want to be able to create inline elements too.

It would be a small non-breaking change to add an optional 'tag' argument to html.py:

```diff
diff --git a/nicegui/elements/html.py b/nicegui/elements/html.py
index b72dbbc3..db53d2d3 100644
--- a/nicegui/elements/html.py
+++ b/nicegui/elements/html.py
@@ -3,7 +3,7 @@ from .mixins.content_element import ContentElement

 class Html(ContentElement):

-    def __init__(self, content: str = '') -> None:
+    def __init__(self, content: str = '', tag: str = "div" ) -> None:
         """HTML Element

         Renders arbitrary HTML onto the page.
@@ -12,5 +12,6 @@ class Html(ContentElement):
         to add it into the body.

         :param content: the HTML code to be displayed
+        :param tag: the HTML tag to use (default: div)
         """
-        super().__init__(tag='div', content=content)
+        super().__init__(tag=tag, content=content)
```

We can then generate a \<p> or a \<span> etc:
```python
ui.html('This is a text paragraph', tag='p')
```

If you like I can send a PR for this, including updating the documentation.

**Comment by rodja** [comment]
Looks good to me. What do you think @falkoschindler?

**Comment by kleynjan** [comment]
See PR #2610 
Hope the docs side is OK too, that's a bit hairy to test.
Cheers, -Peter
