### ISSUE TITLE
Weird behavior of select

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#2643]
### Description

Consider the following code:
```py
@ui.page('/test', title='Test page')
async def setup_test_page():
    data = {'test_value': 'option 1'}
    async def open_dialog():
        with ui.dialog() as dialog, ui.card():
            ui.select(['option 1'], validation={'This field is required': bool}, new_value_mode='add-unique').bind_value(data, 'test_value')
            ui.button('OK', on_click=lambda: dialog.submit('OK'))
            ui.button('Cancel', on_click=lambda: dialog.submit('Cancel'))
        result = await dialog
        if result == 'Cancel':
            print('Resetting test_value to \'option 1\'.')
            data['test_value'] = 'option 1'

    ui.button('Open dialog', on_click=open_dialog)
    ui.timer(callback=lambda: print(f'Test value: {data["test_value"]}'), interval=1)
```

Maybe it can be minimized further, I'm not sure.

To reproduce, click on the button, then press Tab to focus on the select, enter "fizz" there, press Tab again, then Cancel. So far so good.
Now click on the button again, press Tab, enter "buzz", press Tab again. You will get a "This field is required" error. What's going on?

**Comment by falkoschindler** [comment]
Thanks for the report, @me21!
There's a "RecursionError: maximum recursion depth exceeded in comparison" somehow related to the binding module.
I bet we can reduce it further.

**Comment by me21** [comment]
Yes, I saw that exception from time to time, but could not reliably reproduce it.

**Comment by falkoschindler** [comment]
We figured that point 2 is actually ok: When adding a new option, this option isn't synchronized with the other element, so the value is set to `None` over there. Because everything is bound, the `None` value is synchronized back to the first element.

Point 3, however, is even worse than thought. We don't seem to delete any children when calling `delete()` on an element:
```py
with ui.card() as card:
    ui.timer(1.0, lambda: print('Hello, world!'))

ui.button('Delete card', on_click=card.delete)
```
The timer keeps running when deleting the card.

**Comment by me21** [comment]
Point 2 is ok but may be not immediately obvious. However, it seems to be a rare use case to bind two drop-down elements to the same variable, right?
