### ISSUE TITLE
cannot work properly in remote development

### ISSUE THREAD

**Issue by talon-gao** [zauberzeug/nicegui#2657]
### Description

I'm trying to run the standard "Hello World" script on a clean install in a virtrualenv on Python 3.10 and I'm getting several error messages.

```python
from nicegui import ui

ui.label("Hello World")

ui.run()
```

use "python main.py" to run the program
develop in vscode with "Remote - SSH"

The browser is empty and the console displays the following messages:
GET http://127.0.0.1:8080/ net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
:8080/:10 
        
 GET http://127.0.0.1:8080/_nicegui/1.4.17/static/quasar.prod.css net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
:8080/:16 
        
GET http://127.0.0.1:8080/_nicegui/1.4.17/static/es-module-shims.js net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
:8080/:17 
        
GET http://127.0.0.1:8080/_nicegui/1.4.17/static/socket.io.min.js net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)
:8080/:23 
        
GET http://127.0.0.1:8080/_nicegui/1.4.17/static/vue.global.prod.js net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
:8080/:19 
        
GET http://127.0.0.1:8080/_nicegui/1.4.17/static/tailwindcss.min.js net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)

**Comment by rodja** [comment]
I've just tested it successfully. Maybe you have already something running on port 8080 on your local machine? Does it work if you access it with the remote ip? Eg when not relying on the magical port forwarding from VSCode?

**Comment by talon-gao** [comment]
> I've just tested it successfully. Maybe you have already something running on port 8080 on your local machine? Does it work if you access it with the remote ip? Eg when not relying on the magical port forwarding from VSCode?

Thanks for your testing. My leader has tested it successfully, but I'm still failed today. Maybe there're something wrong with my PC.😭

**Comment by rodja** [comment]
Ok. In this case we will close this issue.
