### ISSUE TITLE
Selection for ui.table not working when using drop down

### ISSUE THREAD

**Issue by JS-Aibel** [zauberzeug/nicegui#2695]
### Description

**Describe the bug**
Not able to use ui.table with drop down selection and checkbox selection at the same time.

**To Reproduce**
1. Use the example [table_with_drop_down_selection](https://nicegui.io/documentation/table#table_with_drop_down_selection).
2. Add in the argument, `selection='multiple'` as shown below.

`table = ui.table(columns=columns, rows=rows, row_key='name', selection='multiple').classes('w-full')`

The checkbox column is missing. See picture below.
![image](https://github.com/zauberzeug/nicegui/assets/100705556/c134b491-54d6-4984-926c-9caec120d64b)

**Comment by falkoschindler** [comment]
Hi @JS-Aibel,

When using `selection='multiple'` we shouldn't override the "body" slot, but only the "body-cell-name" slot:
```py
table = ui.table(columns=columns, rows=rows, row_key='name', selection='multiple').classes('w-full')
table.add_slot('body-cell-name', r'''
    <q-td key="name" :props="props">
        <q-select
            v-model="props.row.name"
            :options="''' + str(name_options) + r'''"
            @update:model-value="() => $parent.$emit('rename', props.row)"
        />
    </q-td>
''')
table.on('rename', rename)
```

I updated the demo, because using the cell slot is shorter and simpler for both selection types.
