### ISSUE TITLE
Provide a Date Element

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#270]
### Discussed in https://github.com/zauberzeug/nicegui/discussions/263

<div type='discussions-op-text'>

<sup>Originally posted by **shakamoushie** January 20, 2023</sup>
I couldn't find a date popup. Are there plans to add this widget (with an initial blank date)?

Thanks in advance..</div>

- [x] implement `ui.date`
- [x] add example for API reference
- [x] write test
- [x] support [multiple](https://quasar.dev/vue-components/date#multiple-selection) or [range](https://quasar.dev/vue-components/date#range-selection) selections

**Comment by falkoschindler** [comment]
@rodja I implemented both `ui.date` and `ui.time` since they are pretty similar. Would you like to have a look into [4b5a9a0](https://github.com/zauberzeug/nicegui/commit/4b5a9a02f502369e9eebb132d94bf67ab9accc65)?

I thought about using `datetime.date` and `datetime.datetime` as value types. But they are not JSON-serializable and therefore a bit tricky to handle. When binding a date to a label text, you would need to specify a conversion function to avoid an exception.
That's why I decided to store date and time as a string. The format can be defined with a `mask` parameter, exactly like with QDate and QTime. This allows binding `ui.date` and `ui.time` to the very same model value if needed.

**Comment by falkoschindler** [comment]
Maybe we should also provide an easy-to-use date/time _popup_ like [`ui.color_input`](http://127.0.0.1:8080/reference#color_input) or [`ui.color_picker`](http://127.0.0.1:8080/reference#color_picker). But I'm not sure about the most useful API.

**Comment by rodja** [comment]
I don't think we need to provided additional popup elements. They can be build fairly easy as needed:

```python
with ui.menu() as calendar:
    ui.date(value='2023-01-01', on_change=lambda e: ui.notify(e.value))
ui.button('', on_click=calendar.open).props('icon=calendar_month fab')
```

But the current `ui.date` implementation does not support [multiple](https://quasar.dev/vue-components/date#multiple-selection) or [range](https://quasar.dev/vue-components/date#range-selection) selections. Do you have an idea on how to support that?

**Comment by falkoschindler** [comment]
@rodja So far I focussed on single date selection. Using multiple dates or ranges is certainly possible, but I might need to adjust some value conversions. At least it didn't work out-of-the box when I tried this morning.

**Comment by rodja** [comment]
Ok. I think we should build the API in a way that we do not need to break it when adding multiple dates or ranges. Maybe the best way to do this is implement it right away. Or can we be pretty sure that we can do it later on with the current API?

**Comment by falkoschindler** [comment]
Ok, I managed to get date ranges and multiple selection working with `ui.date`. I just had to adjust the list of arguments we expect to get back.

**Comment by MasterSergius** [comment]
Is there any possibility to limit values of calendar? For example, I don't want to let users to choose future dates.

**Comment by falkoschindler** [comment]
@MasterSergius Yes, here's a piece of code I just wrote recently for another project:
```py
ui.date(value=climb.date.strftime(r'%Y-%m-%d'), on_change=handle_date_change) \
    .props(f''':options="date => date <= '{datetime.today().strftime(r'%Y/%m/%d')}'"''')
```
