### ISSUE TITLE
Assets files not found when deployed in docker container

### ISSUE THREAD

**Issue by CharlesPeng1998** [zauberzeug/nicegui#2714]
### Description

Hi team,

I was trying to package a nicegui application and run in a docker container, but got following error:
```
http://<internal_url>/_nicegui/1.4.10/static/nicegui.css not found
http://<internal_url>/_nicegui/1.4.10/static/fonts.css not found
http://<internal_url>/_nicegui/1.4.10/static/quasar.prod.css not found
http://<internal_url>/_nicegui/1.4.10/static/es-module-shims.js not found
http://<internal_url>/_nicegui/1.4.10/static/socket.io.min.js not found
http://<internal_url>/_nicegui/1.4.10/static/tailwindcss.min.js not found
http://<internal_url>/_nicegui/1.4.10/static/quasar.umd.prod.js not found
http://<internal_url>/_nicegui/1.4.10/static/vue.global.prod.js not found
http://<internal_url>/_nicegui/1.4.10/static/lang/en-US.umd.prod.js not found
```

It works fine with version `1.4.5`. Could you help shed some light on what might go wrong?

**Comment by falkoschindler** [comment]
Hi @CharlesPeng1998,

- Is this the log from the Python or JavaScript console?
- Does clearing the browser cache help?
- Have you tried with a minimal Hello-World example? Can you, please, share the code?
- How do you start the Docker container?
- Can you, please, try the most recent version 1.4.18?

Thanks!

**Comment by CharlesPeng1998** [comment]
Hi @falkoschindler, 

Thank you for your reply.

The log is from the Python console.

Clearing the browser cache does not help.

I was deploying the application via our organization's service (It is Google Kubernetes Engine under the hood). Basically I only need to provide the Docker image, so I don't know the details about how the Docker container is started behind the scene. 

I tried to deploy following minimal codes:
```python
from nicegui import app, ui

ui.label("This is a test app")

app.root_path = "/byoa/nicegui-1-4-18-test-oa386q"

ui.run()
```
And this is the Dockerfile:
```
FROM python:3.10-slim

EXPOSE 8080

WORKDIR /app

COPY . .

RUN pip3 install --no-cache-dir --trusted-host pypi.org --trusted-host files.pythonhosted.org -r requirements.txt

ENTRYPOINT [ "python3", "main.py"]
```
After deploy with the Docker image, I should be able to access the page at `https://<internal domain>/byoa/nicegui-1-4-18-test-oa386q/`, but got not found error:
```
...
http://<internal domain>/_nicegui/1.4.18/static/nicegui.css not found
http://<internal domain>/_nicegui/1.4.18/static/fonts.css not found
...
```
![image](https://github.com/zauberzeug/nicegui/assets/32303546/19368550-e70c-4524-a307-c6661dd9ad42)

However, if I deploy with another Docker image only changing the NiceGUI version from `1.4.18` to `1.4.5`. Everything works fine.
![image](https://github.com/zauberzeug/nicegui/assets/32303546/20751cbb-0a11-4115-9dbc-5bbf96a65ae3)

I can load the static file with this url using `1.4.5`:
![image](https://github.com/zauberzeug/nicegui/assets/32303546/fbda5488-cb7f-42aa-924e-293cdf6a373b)
Normally it should also work for `1.4.18` but I got the `Connection lost`.
![image](https://github.com/zauberzeug/nicegui/assets/32303546/54c52062-422d-464e-8ed3-967a7193e3b5)

Would be much grateful if you can help on this!

**Comment by rodja** [comment]
Does it work with 

```
ui.run(root_path="/byoa/nicegui-1-4-18-test-oa386q")
```

instead of writing it into `app.root_path`?

**Comment by CharlesPeng1998** [comment]
@rodja It works now. Thank you! May I know why directly modifying `app.root_path` is not working for `1.4.18` but works for `1.4.5`?

**Comment by rodja** [comment]
Maybe it has to do with https://github.com/zauberzeug/nicegui/issues/848? Or with a newer FastAPI dependency? I'm not sure.
