### ISSUE TITLE
ui.toggle missing box and shadow in ui.card

### ISSUE THREAD

**Issue by Nemecsek** [zauberzeug/nicegui#2723]
### Description

The style of **ui.toggle** changes according to the context:
```python
with ui.row():
    ui.toggle([1, 2, 3], value=1)
ui.toggle([1, 2, 3], value=1)  
```
produces
![Screenshot_20240319_125605](https://github.com/zauberzeug/nicegui/assets/25978536/85a621b3-78bb-46c2-b344-ecf960a28d3f)

while inside a **ui.card** the shadow is lost:
```python
with ui.card():
    with ui.row():
        ui.toggle([1, 2, 3], value=1)
    ui.toggle([1, 2, 3], value=1)  # <==== MISSING SHADOW!
```
we get
![Screenshot_20240319_125512](https://github.com/zauberzeug/nicegui/assets/25978536/1eabb100-062d-4e8d-a36d-9f6521a4070c)

**Comment by falkoschindler** [comment]
Hi @Nemecsek, this is a known issue, which has been discussed in https://github.com/zauberzeug/nicegui/discussions/2696 and https://github.com/zauberzeug/nicegui/issues/2265. We're working on a solution for the next major release.
