### ISSUE TITLE
Allow a link to open in a new tab

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#273]
Following up on [this comment on Reddit](https://www.reddit.com/r/Python/comments/10d6ugv/comment/j4u3x6b/) I would propose a new parameter `ui.link(..., new_tab: bool = False)`. Although we already can achieve the same with `.props('target=_blank')`, this solution is pretty hard to find if you are not very well familiar with NiceGUI and good old HTML.

To be exact: `_blank` opens in a new window _or_ tab. But usually it's probably going to be a new tab nowadays. So I'd stick with the name `new_tab`.

**Comment by falkoschindler** [comment]
It's already done in [6f5fa27](https://github.com/zauberzeug/nicegui/commit/6f5fa27d69a4c7b909b0f6821b1a6c4124e364c6).

@rodja Do you think we can write a test for it?

**Comment by rodja** [comment]
Done!
