### ISSUE TITLE
http://<ip>:8080/inform not found - appearing repeatedly in console

### ISSUE THREAD

**Issue by SnapshotCiTy** [zauberzeug/nicegui#2732]
### Description

On MacOS 14.4 - Python 3.12.2 - in a venv with only icecream, nicegui and pywebview installed.

when running ui.run() the message
http://<my_ip_here>:8080/inform not found appears every 20 seconds or so in the console.

same behavior with reload=False
doesn't happen with native=True

I didn't find any mention of that error message in the docs.
Is it normal? What does it mean and what to do about it ?

**Comment by falkoschindler** [comment]
Hi @SnapshotCiTy,

There is no "/inform" route in the NiceGUI code base. So whatever is trying to access this path must come from user code or something else running in your network. It could be some kind of watchdog, for example.

**Comment by sonicno1** [comment]
Must be defined @ui.page('/highLightTitle.png') to resolve not found the error

**Comment by wirelessfrank** [comment]
I have the same issue with all tried examples: todo_list, progess etc....

**Comment by rodja** [comment]
@wirelessfrank there is some program somewhere which tires to access this file. It has nothing to do with NiceGUI. You may try restarting your computer or disconnect it from the local network.
