### ISSUE TITLE
Use of viewport for mobile devices

### ISSUE THREAD

**Issue by jfroco** [zauberzeug/nicegui#274]
Hello,

In order to display the examples correctly on a mobile device, I needed to use:

`
ui.add_head_html("<meta name='viewport' content='width=device-width, initial-scale=1'>")
`

![nicegui](https://user-images.githubusercontent.com/2047144/213784429-433a18c7-519e-44b7-86a2-f042eb7f27df.png)

Am I doing something wrong? If not, shouldn't this meta tag be included always?

Thank you!!

**Comment by falkoschindler** [comment]
Good point! For the website https://nicegui.io/ we do set this tag. But maybe we should do it always.
Is it good practice? Or are there any disadvantages?

**Comment by jfroco** [comment]
> Good point! For the website https://nicegui.io/ we do set this tag. But maybe we should do it always. Is it good practice? Or are there any disadvantages?

It is a good practice according to: https://www.w3schools.com/css/css_rwd_viewport.asp and all web apps I have worked on have this meta tag.

I could create a pull request,: the default behaviour would be to include the viewport tag, but it could be disabled at global/page level like "title" attribute. What do you think?

**Comment by rodja** [comment]
Sounds great. We would love to see a pull-request from you, @jfroco. Thanks for identifying this.

**Comment by falkoschindler** [comment]
Great, I merged the PR. Thanks again, @jfroco!
