### ISSUE TITLE
Provide `on_confirm` callback for `ui.input` element

### ISSUE THREAD

**Issue by rodja** [zauberzeug/nicegui#276]
Over at [Reddit](https://www.reddit.com/r/Python/comments/10d6ugv/comment/j5776zs/?context=3) the question came up how to implement a search bar where pressing RETURN inside an input element fires an action. Right now, we only have the `on_change` callback which fires for every keystroke.

- [x] support key modifiers
- [x] add tests for various event modifiers
- [x] add a note about `.on('keydown.enter', ...)` in the documentation

**Comment by rodja** [comment]
It looks like we need to do some Quasar/Vue magic to accomplish this. See https://stackoverflow.com/a/53621886/364388

**Comment by falkoschindler** [comment]
NiceGUI should already support Vue's event modifiers. At least I implemented it some time ago and thought the following line would work (using a "." to add the modifier "once"):

```py
ui.input().on('keydown.once', lambda msg: print(msg, flush=True))
```

Apparently this doesn't work. But the following line does:

```py
ui.input().on('keydownOnce', lambda msg: print(msg, flush=True))
```

But it doesn't work with the suffix ".enter" or "Enter". [Here](https://stackoverflow.com/questions/75194322/how-to-define-vue-event-modifiers-with-a-render-function) I learned that there's a difference between event modifiers and key modifiers. While NiceGUI uses `Vue.withModifiers`, it doesn't seem to work for key modifiers.

There is a private and undocumented `Vue.withKeys` function that we could use. We would rely on an unofficial API that could change any time. But with a fixed Vue version and proper tests this should be ok.

**Comment by falkoschindler** [comment]
Because I'm not sure Vue's `withModifiers` is behaving as it is supposed to, I opened an issue over there: https://github.com/vuejs/core/issues/7566

**Comment by falkoschindler** [comment]
I think I start to understand event modifiers a bit better:

- The modifiers `.passive`, `.capture`, and `.once` can be concatenated after the event name like `onClickCapture` or `onKeyupOnce`. In NiceGUI that would be `on('clickCapture')` and `on('keyupOnce')`.
- Other event modifiers can be passed to the `withModifiers` function. That's what NiceGUI already supports using a dot: `on('click.prevent')`.
- _Key_ modifiers also go with `withModifiers`. This includes "alt", "meta", "shift", and "ctrl".
- But _keys_ like "a", "esc", or "enter" don't work with `withModifiers` but only with `withKeys`. This is missing in Vue's documentation (`withKeys` doesn't occur at all). And this is where we need to improve NiceGUI. We either need to implement a mapping of which modifier needs to go to which function. Or we need a different syntax for keys. But I think I would prefer the mapping.

**Comment by falkoschindler** [comment]
Unfortunately, it looks like `withModifiers` and `withKeys` can't be combined:

```html
<html>
  <body>
    <div id="app"></div>
    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.prod.js"></script>
    <script>
      const app = Vue.createApp({
        render() {
          return Vue.h("input", { onKeydown: Vue.withKeys(Vue.withModifiers((e) => console.log(e), []), []) });
        },
      }).mount("#app");
    </script>
  </body>
</html>
```

Even though both arrays are empty, the event handler isn't called anymore. So maybe we have to change strategy, register to a regular keydown event and filter keys in Python.

**Comment by falkoschindler** [comment]
Forget my last comment! An empty array for `withKeys` subscribes to _no_ key and the handler is never called. So NiceGUI needs to switch between using `withKeys` if there are any keys in the modifier list or not using it at all.

**Comment by falkoschindler** [comment]
In [1d8c7de](https://github.com/zauberzeug/nicegui/commit/1d8c7dec3ec026b93c9c453a0e512b674e2ccaaf) I managed to support all kinds of event modifiers with our dot notation: `keydown.once`, `keydown.enter`, `keydown.once.enter`, `keydown.shift.enter`, ...

As a next step I'd like to add tests for these modifiers, especially because we are using undocumented Vue functions that might break at some point.

**Comment by falkoschindler** [comment]
We decided not to introduce an additional callback `on_confirm` but only document how to use `.on('keydown.enter', ...)`. So the user can better decide when exactly a callback should be executed.

**Comment by atomicrichard** [comment]
The documentation is stale here: https://nicegui.io/documentation/select#dropdown_selection

It says:

> on_change: callback to execute when the input is confirmed by leaving the focus

But in https://github.com/zauberzeug/nicegui/commit/4a8be60583f99e7424d8807f88ac14126012d24f:

> The `on_change` event is called on every keystroke and the value updates accordingly.

The latter appears to be correct.

**Comment by falkoschindler** [comment]
Thanks, @atomicrichard! I guess you mean https://nicegui.io/documentation/input#text_input.
Commit [ad76177](https://github.com/zauberzeug/nicegui/commit/ad76177a57e269506fbed050ec3a591cc820a0a5) should fix the inconsistency. I will be online with the next release.

**Comment by jonathanasdf** [comment]
How would I add an event that fires on enter key but only if shift is not pressed?

So shift+enter should create a new line while enter by itself fires the event

**Comment by falkoschindler** [comment]
@jonathanasdf I could imaging something like
```py
def handle_keydown(msg: dict):
    if not msg['args']['shiftKey']:
        ui.notify('Done!')

ui.textarea().on('keydown.enter', handle_keydown, args=['shiftKey'])
```

But this doesn't prevent the last enter from inserting a line break... 🤔

**Comment by jonathanasdf** [comment]
@falkoschindler I wonder if you have ideas on how to better handle clearing the textarea, right now it seems the keydown fires before the textarea's value is updated, so changes to textarea.value inside the handler doesn't do anything. I've been relying on some hacky tricks that isn't great...

```
textarea = ui.textarea()

async def clear_text():
    await asyncio.sleep(0.1)
    textarea.value = ''

async def handle_keydown(evt):
    if not evt.args['shiftKey']:
        print(textarea.value)
        asyncio.create_task(clear_text())

textarea.on('keydown.enter', handle_keydown, args=['shiftKey'])
```
