### ISSUE TITLE
Invalid websocket upgrade

### ISSUE THREAD

**Issue by j4nSolo** [zauberzeug/nicegui#2781]
### Description

I've set up a server with the help of NiceGUI and Nginx on a VPS. The requests are coming through a subdomain and routed correctly: The server receives the request and prints the html elements.

 However, upon making use of the websockets, I can see the following error on my server's out:
```ERROR:engineio.server:Invalid websocket upgrade (further occurrences of this error will be logged with level INFO)```.

Conversely, my browser shows ```manager.js:108 WebSocket connection to 'wss://{I-hid-this}/_nicegui_ws/socket.io/?client_id=ce259c07-9781-4739-9faa-051f24e911bd&EIO=4&transport=websocket' failed```.

The same setup, running it `on_air` **works perfectly**.

Here's my nginx config for my subdomain:

```
server {
    listen 80;
    server_name {I-hid-this};

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
server{
        # SSL configuration
        listen 443 ssl;
        server_name {I-hid-this};
        ssl_certificate /etc/nginx/ssl/{I-hid-this}_ssl_certificate.cer;
        ssl_certificate_key /etc/nginx/ssl/_.{I-hid-this}_private_key.key;

        location / {
                proxy_pass http://127.0.0.1:8080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }

}
```
I tried adding sockets on extra ports, but it made no difference. 

The main problem I have with this is that I can't find any specific documentation on the posted error.

I logged the headers received and it's quite notable that the `transport` is set to `websocket`, however there's no `HTTP_UPGRADE` passed, and that's what kills the logic. Moreover, it seems my local working server recives `ws` as scheme whereas my non working VPS receives `https`. I hope this helps.

I guess it's worth mentioning that anything else on the website works fine, SSL certificate is valid, etc.

**Comment by j4nSolo** [comment]
I solved it. It obvioulsy had nothing to do directly with NiceGUI but with the reverse proxy setup on nginx. I leave the solution here in case someone faces the same problem:

> I solved it by adding the following configuration to my nginx config file:
> 
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "Upgrade";
> 
> thanks to this source: https://www.nginx.com/blog/websocket-nginx/
>

**Comment by rodja** [comment]
We have such a configuration in one of our examples: https://github.com/zauberzeug/nicegui/tree/main/examples/nginx_subpath. Maybe it is not visible enough?

**Comment by tjakobi** [comment]
Interestingly I had exactly the same issue `Invalid websocket upgrade (further occurrences of this error will be logged with level INFO)`. However, I am using Apache instead of nginx. 

For reference, this is the Apache config that works for me in combination with nicegui (1.4.22). Maybe this could also be helpful as an example in the repository since the translation from nginx to Apache was not trivial (at least for me).

```
<VirtualHost server.name.org:80>
    # only used for mapping HTTP to HTTPS
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}
    RewriteCond %{SERVER_NAME} =server.name.org
    RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
    ServerName server.name.org
</VirtualHost>

<VirtualHost server.name.org:443>

    # SSL configurations would go here...
    
    RequestHeader set X-Forwarded-Proto "https"
    
    ServerName server.name.org
    ServerSignature Off
    
    # below the important parts required for WS to work 
    RewriteEngine On
    RewriteCond %{HTTP:Connection} Upgrade [NC]
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteRule /(.*) ws://127.0.0.1:8080/$1 [P,L]
    
    ProxyPreserveHost On
    
    <Location />
        ProxyPass http://127.0.0.1:8080/
        ProxyPassReverse /
    </Location>
</VirtualHost>
```

**Comment by rodja** [comment]
That looks very helpful indeed @j4nSolo. Would you like to create a pull request with a `apache_subpath` example similar to the existing `nginx_subpath`?
