### ISSUE TITLE
ui.grid(columns='1fr 300px 1fr') missing style

### ISSUE THREAD

**Issue by vhunyad** [zauberzeug/nicegui#2794]
### Description

It produces this: 
`<div id="c68" class="nicegui-grid w-full h-full" style="">`
instead of the example https://nicegui.io/documentation/grid
`<div id="c251" class="nicegui-grid w-full gap-0" style="grid-template-columns: auto 80px 1fr 2fr;">`

columns=3 works well, but then the widths are not defined. I have manually listed ui.columns() in all cells (without for cycle).

**Comment by falkoschindler** [comment]
@vhunyad Have you upgraded to the newest NiceGUI version?
This feature has just been added in [version 1.4.19](https://github.com/zauberzeug/nicegui/releases/tag/v1.4.19).

**Comment by vhunyad** [comment]
Thanks, it works after update.
