### ISSUE TITLE
Async callback in Element.on() can lead to IndexError in slot stack

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#285]
Discussed in https://github.com/zauberzeug/nicegui/discussions/280

Here is a minimal reproduction. The first button works as expected, the second one doesn't.

```py
async def handle_click():
    await asyncio.sleep(0.1)
    ui.notify('clicked')

ui.button('Works', on_click=handle_click)
ui.button('Fails').on('click', handle_click)
```

- [x] support async callbacks in `Element.on()`
- [x] while we are here: make `Element` available as `ui.element`

**Comment by SebastienDorgan** [comment]
Hi @falkoschindler,
As I really wanted this to work I have created a simple work around that is, I hope, interesting to share
```python
import asyncio
from nicegui import ui, Client
from nicegui.events import ClickEventArguments, handle_event
@ui.page('/')
async def main_page(client: Client):
    async def handle_click():
        await asyncio.sleep(0.1)
        ui.notify('clicked')

    ui.button('Works', on_click=handle_click)
    button = ui.button("Works with effort")
    button.on("click", lambda _: handle_event(handle_click, ClickEventArguments(sender=button, client=button.client)))
    ui.button('Fails').on('click', lambda _: handle_click())

ui.run(show=False)
```

**Comment by falkoschindler** [comment]
Thanks for sharing, @SebastienDorgan! That's basically what needs to be done.
We just have to check where to put the additional call to `handle_event` so that "normal" event handlers like `on_click` don't call it twice internally. So we probably have to move the `handle_event` call out of UI elements like `button` and into `.on()` in the `element` base class.

**Comment by falkoschindler** [comment]
I created PR https://github.com/zauberzeug/nicegui/pull/305 which should solve this issue.

**Comment by rodja** [comment]
I've just merged the code.
