### ISSUE TITLE
AG Grid doesn't resize correctly with its container

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#2852]
### Discussed in https://github.com/zauberzeug/nicegui/discussions/2850

<div type='discussions-op-text'>

<sup>Originally posted by **tz301** April  8, 2024</sup>
### Question

I have use aggrid combined with left drawer. When click button to show/hide the left drawer, aggrid style is strange, not fully fill the width.

```py
from nicegui import ui

rows = [
    {'name': 'Alice', 'age': 18},
    {'name': 'Bob', 'age': 21},
]

left_drawer = ui.left_drawer(value=True).classes('bg-blue-100')
ui.button('click', on_click=left_drawer.toggle)

grid = ui.aggrid({
    'columnDefs': [
        {'headerName': 'Name', 'field': 'name'},
        {'headerName': 'Age', 'field': 'age'},
    ],
    'rowData': rows,
})

ui.run()
```

![image](https://github.com/zauberzeug/nicegui/assets/35760938/89a9d7a4-dfd1-4105-bdd2-d1dbb8a67a55)
![image](https://github.com/zauberzeug/nicegui/assets/35760938/a26d94cd-2e6e-4348-a4ff-d62653502a73)

</div>

---

This can be reproduced with this tiny example:
```py
with ui.card().style('width: 500px') as card:
    ui.aggrid({'columnDefs': [{'field': 'name'}], 'rowData': [{'name': 'Alice'}]})
ui.checkbox('Wide', on_change=lambda e: card.style('width: 1000px' if e.value else 'width: 500px'))
```

Strangely it doesn't happen when resizing the AG Grid directly:
```py
grid = ui.aggrid({'columnDefs': [{'field': 'name'}], 'rowData': [{'name': 'Alice'}]}).style('width: 500px')
ui.checkbox('Wide', on_change=lambda e: grid.style('width: 1000px' if e.value else 'width: 500px'))
```

**Comment by vickorian** [comment]
@falkoschindler 

So something like this is part of what inspired me to create #2822 since i was having so much trouble controlling the size of the grid. Rows would stick with original window size, they wouldn't flex correctly, etc. until i dropped a lot of the tailwind-css elements, went directly to style with hard pixel values, and passed " 'resizeable':True"  explicitly in defaultColDef of ui.aggrid. 

I attempted to expand the container size and have AgGrid match container dimensions but had to drop that after a while and do like you did and resize the table directly.

I'm working on a client project right now with nicegui, but when i get to a stopping point i was planning on investigating anyways since i'll be needing nicegui for future work.

**Comment by wasabismile** [comment]
I have also encountered this issue. I resolved it by adding the following code in aggrid.js. Hope this helps.
 
```javascript
onGridSizeChanged: this.auto_size_columns ? (params) => params.api.sizeColumnsToFit() : undefined,
```

**Comment by falkoschindler** [comment]
Nice, @wasabismile!

We can use this workaround by passing the "onGridSizeChange" event handler to the options dictionary:
```py
with ui.card().style('width: 500px') as card:
    ui.aggrid({
        'columnDefs': [{'field': 'name'}],
        'rowData': [{'name': 'Alice'}],
        ':onGridSizeChanged': '(params) => params.api.sizeColumnsToFit()',
    })
ui.checkbox('Wide', on_change=lambda e: card.style('width: 1000px' if e.value else 'width: 500px'))
```

**Comment by falkoschindler** [comment]
I managed to integrate this solution into aggrid.js, so we can finally resolve this issue. 🚀

**Comment by tiburciomzt** [comment]
I did this solution for autosizeColumns and when the columns not cover all the width, in my case was for angular ag grid but is the same methods:

```js
this.gridApi.autoSizeColumns(keys, false);

let totalColumnWidth = 0;
this.gridApi.getAllDisplayedColumns().forEach(col => {
  totalColumnWidth += col.getActualWidth();
});
const gridElement = document.getElementById(this.tableID);
/// Where this.tableID is the id of html, example => id="#ag-grid"
const gridWidth = gridElement ? gridElement.clientWidth : 0;
if (gridWidth > 0 && totalColumnWidth < gridWidth) {
  this.gridApi.sizeColumnsToFit();
}
```
