### ISSUE TITLE
Javascript error: crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by alexzaech** [zauberzeug/nicegui#2866]
### Description

When accessing NiceGUI other than using `localhost` address, the browser JS console shows `TypeError: crypto.randomUUID is not a function` (nicegui.js:339). UI elements are rendered correctly, but no callback seems to work.

Minimal example to reproduce the issue:
```python
from nicegui import ui

@ui.page("/")
async def home():
    ui.button("Test me", on_click=lambda: ui.notify("Hello, world!"))

if __name__ in {"__main__", "__mp_main__"}:
    ui.run()
```
Open browser dev tools console to see the error message.

> This issue occurs with the latest code from GitHub main branch but **NOT** with release version 1.4.20.

**Comment by falkoschindler** [comment]
Oh wow, thanks for spotting this, @alexzaech!
This line has been added in PR #2837. We'll look into it.

**Comment by rodja** [comment]
Interesting. `crypto.randomUUID` is only available locally or when serving https: https://stackoverflow.com/a/2117523/364388. I think we should try to use `crypto.randomUUID` and if it fails fall back to a custom uuid generation function (like the one from the StackOverflow answer).
