### ISSUE TITLE
May I ask if it's possible to apply for a CVE for this project if a security vulnerability is found?

### ISSUE THREAD

**Issue by sunriseXu** [zauberzeug/nicegui#2870]
### Description

Hi there, recently, I found a security bug in this project, may I ask if it's possible to apply for a CVE for this project if a security vulnerability is found?

**Comment by falkoschindler** [comment]
Thanks for bringing this to our attention, @sunriseXu!
We're very interested in documenting and fixing security vulnerabilities in NiceGUI. But we don't have experience with CVEs in our own project yet. What would need to be done from our side? How does it compare to reporting a regular GitHub issue? Can you help us setting things up, or should we ask for help from the community?

**Comment by sunriseXu** [comment]
Thanks for your response! 
Do you mind enable project [private-vulnerability-reporting-for-a-repository](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository#enabling-or-disabling-private-vulnerability-reporting-for-a-repository), so I can report the bug privately. After maintainers review and confirm the bug, I will submit a CVE request to [https://cveform.mitre.org/](https://cveform.mitre.org/) to get a CVE id. When the bug is fixed, the bug report can be disclosed which will be referenced by CVE information parts.

**Comment by falkoschindler** [comment]
@sunriseXu Alright, we enabled private vulnerability reporting. 👍🏻

**Comment by sunriseXu** [comment]
Thank you!

**Comment by sunriseXu** [comment]
Hi, sorry for the mistake, I published the bug reports by mistake, now i can't edit it, can you change the report back to private @falkoschindler !!!

**Comment by falkoschindler** [comment]
@sunriseXu No, I just published it because I thought that's the right thing to do after providing a fix in https://github.com/zauberzeug/nicegui/releases/tag/v1.4.21. Shouldn't GitHub's Dependabot start warning other developers about this security issue in NiceGUI? Please correct me if I'm wrong.

**Comment by falkoschindler** [comment]
@sunriseXu I just edited your description to hide any details until I understand what should be part of the public advisory and what not.

**Comment by sunriseXu** [comment]
Thank you for the application for CVE, I have confirmed the bug is fixed.  I think it is fine to hide details about vulnerability, just a general description is good.
