### ISSUE TITLE
[AG Grid] Setting column to sortable doesn't work in a callback function

### ISSUE THREAD

**Issue by Magic-wei** [zauberzeug/nicegui#2885]
## Test Environment

- OS: Windows 10 Home, version 22H2
- Virtual environment manager: Conda
- Python version: 3.9.18
- NiceGUI version: 1.4.21

## Description

Inspired by [this discussion](https://github.com/zauberzeug/nicegui/discussions/2823#discussioncomment-9010856), I tried to set one column to sortable in a button callback function and it failed. However, it works outside a callback function.

## Desired Behavior

`aggrid.options['columnDefs'][0]['sortable'] = True` should work properly as well in a callback function (a button callback function here for example).

## Minimal Reproducible Code

The following code will show the issue. There are two columns defined in code, and the second column is set to sortable outside a callback function which works properly, whereas the first column is set to sortable in a callback function which failed.

```python
from nicegui import ui
import pandas as pd

df = pd.DataFrame(data={'col1': [1, 2], 'col2': [3, 4]})
aggrid = ui.aggrid.from_pandas(df)

# set second column to sortable directly outside a callback function
aggrid.options['columnDefs'][1]['sortable'] = True

# set first column to sortable in a callback function
def sortFirstColumnCb():
    aggrid.options['columnDefs'][0]['sortable'] = True

ui.button('Make first column sortable', on_click=sortFirstColumnCb)

ui.run()
```

**Comment by falkoschindler** [comment]
Hi @Magic-wei!
Unfortunately NiceGUI can't reliably notice changes to the options dictionary.
Therefore you need to call `aggrid.update()` like in [this demo](https://nicegui.io/documentation/aggrid#ag_grid).

**Comment by Magic-wei** [comment]
Thanks @falkoschindler, adding `aggrid.update()` to the callback function works! But I see that the whole AG grid is regenerated when I call `aggrid.update()`, which might be a problem when I work with a really big table and just set some columns to sortable in the UI. Anyway, so far I think this could be the solution for me, since I can just manually set columns to sortable outside callback functions. Just wonder if there is any plan for NiceGUI to add this feature (i.e. notice changes to the options dictionary) in the future?

**Comment by Magic-wei** [comment]
Just closed this issue since the solution kind of works and I will explore more about NiceGUI to get better understanding before we dive deeper in this direction. Thanks again for quick reply!

**Comment by falkoschindler** [comment]
You're right, `update()` will regenerate the whole AG Grid. Maybe we'll find a more efficient way to update it in the future.
