### ISSUE TITLE
ui.date doesn't not close the menu after picking the day

### ISSUE THREAD

**Issue by Nemecsek** [zauberzeug/nicegui#2896]
### Description

In the `ui.date` documentation page, [Input element with date picker](https://nicegui.io/documentation/date#input_element_with_date_picker) the example code, when copied to an app, doesn't behave in the same way: after the click **the menu doesn't close**. 

Is there some other property to set in order to close automatically after day pick?

**Comment by falkoschindler** [comment]
Hi @Nemecsek, this is a bug we just fixed in https://github.com/zauberzeug/nicegui/issues/2894, but the website hasn't been updated yet. The menu staying _open_ is the desired behavior. If you want to close it as soon as a value is selected, you can do so like this:
```py
with ui.input('Date', on_change=lambda: menu.close()) as date:
    ...
```

**Comment by Nemecsek** [comment]
@falkoschindler , the lambda `menu.close()` works. 

Now I have this code: 
```python
from nicegui import ui

with ui.input('Date', on_change=lambda: menu.close()) as date:
    with date.add_slot('append'):
        ui.icon('edit_calendar').on('click', lambda: menu.open()).classes('cursor-pointer')
    with ui.menu() as menu:
        ui.date().props("range").bind_value(date)
        
ui.run()
```
We can have 3 values as result: 
* None 
* a string: a single day
* a dictionary: a range

How to write a callback that translates the 3 cases to 3 strings?

**Comment by falkoschindler** [comment]
You can try these callbacks:
```py
with ui.input('Date', on_change=lambda: menu.close()) as date:
    with date.add_slot('append'):
        ui.icon('edit_calendar').on('click', lambda: menu.open()).classes('cursor-pointer')
    with ui.menu() as menu:
        ui.date().props('range').bind_value(
            date,
            forward=lambda v: f'{v["from"]} - {v["to"]}' if isinstance(v, dict) else v,
            backward=lambda v: {'from': v.split(' - ')[0], 'to': v.split(' - ')[1]} if isinstance(v, str) and ' - ' in v else v,
        )
```

**Comment by Nemecsek** [comment]
Wow, @falkoschindler ! Thank you, exactly what I meant. 

It would be nice if all this complexity (it is very complex, at least for me) was hidden behind a few parameters for `ui.date`:
`ui.date(non_valid_message="click here to set a date", range_mask="DD/MM[/YYYY]..DD/MM/YYYY")`
`[/YYYY]` means: show the year only if different from the final year. 

You are doing a great job with NiceGUI!

**Comment by falkoschindler** [comment]
Thanks, @Nemecsek!
An API for such a `range_mask` parameter might be tricky to get right. If you're interested, I suggest to open a new feature request where we can discuss any details and ask for help from the community.

**Comment by Nemecsek** [comment]
I added my proposal at [Discussion #2904](https://github.com/zauberzeug/nicegui/discussions/2904).
The biggest issue IMHO is that `ui.date` returns 3 different data types (None, String, Dict), while it should return only one. My proposal is to break compatibility and always return a dictionary). 
Thank you for the time you dedicated me.
