### ISSUE TITLE
'Tailwind' object has no attribute 'value'

### ISSUE THREAD

**Issue by miccs0** [zauberzeug/nicegui#2916]
### Description

If there is `.tailwind()` being used, you cannot set any values to an element.
This is a consistent error when trying to do something like this:

```py
name = ui.input('Name').tailwind('capitalize')
name.value = ''
```

You have to workaround it like this:

```py
style = Tailwind().font_size("xl")
title = ui.label('Title')
style.apply(title)
```

**Comment by rodja** [comment]
Yes that is expected behaviour. You should use the `.element` property of the Tailwind object:

```py
name = ui.input('Name').tailwind('capitalize').element
name.value = ''
```
