### ISSUE TITLE
Plotly chart changes position after updating the chart.

### ISSUE THREAD

**Issue by drummerboy2543** [zauberzeug/nicegui#2917]
### Description

I would like to report a unexpected behavior/bug about plotly dynamically changes position, after being updated. 

Working off of the demo code, that is given via the [documentation](https://nicegui.io/documentation/plotly#plot_updates).  The only differences I made was  adding some rows for some inputs and labels before button (Going to be used later, but made a dummy to show a example). I also specified a different height, for the plotly graph

https://github.com/zauberzeug/nicegui/assets/15644157/69a09889-8c4e-471b-90eb-1929d2aa5990

As you can see in the video attached the formatting gets a bit messed up and does not adhere to the column and row structure that was outlined. 

The code is shown below.

```python
import plotly.graph_objects as go
from nicegui import ui
from random import random

fig = go.Figure()
fig.update_layout(margin=dict(l=0, r=0, t=0, b=0))
plot = ui.plotly(fig).classes('w-full h-full')




with ui.row():
    ui.input(label="Cord 1 (x,y)", placeholder="Enter a value").props("dense")
    ui.label("(45.5, 35.23)")
with ui.row():
    ui.input(label="Cord 2 (x,y)", placeholder="Enter a value").props("dense")
    ui.label("(45.5, 35.23)")
with ui.row():
    ui.input(label="Cord 3 (x,y)", placeholder="Enter a value").props("dense")
    ui.label("(45.5, 35.23)")
with ui.row():
    ui.input(label="Cord 4 (x,y)", placeholder="Enter a value").props("dense")
    ui.label("(45.5, 35.23)")
def add_trace():
    fig.add_trace(go.Scatter(x=[1, 2, 3], y=[random(), random(), random()]))
    plot.update()

ui.button('Add trace', on_click=add_trace)

ui.run() 
```
Notice at the beginning the formation that was given in code failed. Only after the update it would go back to what is expected behavior.  However constantly updating it changes back and forth. I wonder if this is some sort of race condition.

After talking about the issue on discord we were able to narrow down the issue of the demo code exactly, if height is not specified. 

The context of the discord conversation can be seen  [here
](https://discord.com/channels/1089836369431498784/1230680629067386931)

```python

import plotly.graph_objects as go
from nicegui import ui
from random import random


fig = go.Figure()
fig.update_layout(margin=dict(l=0, r=0, t=0, b=0))
plot = ui.plotly(fig).classes('w-full')

def add_trace():
    fig.add_trace(go.Scatter(x=[1, 2, 3], y=[random(), random(), random()]))
    plot.update()

ui.button('Add trace', on_click=add_trace)

ui.run()
```

Both examples should in result a behavior where the format of the page should not move. 
The video of the file should be attached to this issue. 
Let me know if there is anything I can help with!

**Comment by falkoschindler** [comment]
Thank you so much for reporting this issue, @drummerboy2543!

With your minimal reproduction I could narrow it down to PR #2516, which switched from `Plotly.newPlot` to `Plotly.react`. And I think this stale bug report explains the behavior: https://github.com/plotly/plotly.js/issues/4856

@bmaranville @platinops, you do - by any chance - have an idea how we could work around this bug?

**Comment by wikiselev** [comment]
I've had a similar issue while clicking on the trace in the plot legend. Sometimes the plot completely disappeared from the view. I worked around it by making the traces in the legend unclickable.

**Comment by bmaranville** [comment]
There is a conflict in philosophies at play: in general, plotly plots determine their size from their parent container unless you set a manual height, while nicegui is structured so that elements like `row` don't specify a height and are sized to their content.  The css height of the `body` element is not specified in a nicegui app, nor any of its children; I think this is an intentional design choice from nicegui, making it easy to create scrolling apps where the total height is determined by the content, but it makes it challenging to create single-page apps that fit responsively into the height of the browser window.

If no height can be determined from the parent, I think plotly sets a default height (450px?) but only during the draw - when the plot is cleared as part of the redraw, it reverts briefly to its natural height (which is 0 in this case). 

One quick solution to your problem is to set a fixed height for your plot, like this:
 _(using class `h-full` does not work, because that translates to `height: 100%;`, relative to its parent, which has no height defined)_
```python
import plotly.graph_objects as go
from nicegui import ui
from random import random


fig = go.Figure()
fig.update_layout(margin=dict(l=0, r=0, t=0, b=0))
plot = ui.plotly(fig).classes('w-full').style('height: 450px;')

def add_trace():
    fig.add_trace(go.Scatter(x=[1, 2, 3], y=[random(), random(), random()]))
    plot.update()

ui.button('Add trace', on_click=add_trace)

ui.run()
```

For an app I was working on that fills the height of the page, I had to add some global CSS, overriding the default styling of internal nicegui components:
```python
import plotly.graph_objects as go
from nicegui import ui
from random import random

ui.add_head_html('''
    <style>
        #app {
            height: 100%;
            width: 100%;
        }

        main.q-page, div.nicegui-content {
            height: 100%;
            width: 100%;
            display: flex;
            flex-direction: column;
            justify-content: flex-start;
            flex: 1 1 0;
        }

        div.plot-container.plotly, div.js-plotly-plot {
            height: 100%;
        }
    </style>
''')
                 
fig = go.Figure()
fig.update_layout(margin=dict(l=0, r=0, t=0, b=0))
plot = ui.plotly(fig).classes('w-full flex-1')

def add_trace():
    fig.add_trace(go.Scatter(x=[1, 2, 3], y=[random(), random(), random()]))
    plot.update()

ui.button('Add trace', on_click=add_trace)

ui.run()
```

**Comment by falkoschindler** [comment]
Ok, that's very unfortunate. Of course we could require a fixed height for the Plotly element. But it worked out-of-the-box before PR #2516, using the default height of 450px.

A (hacky) solution might be adding
```css
.js-plotly-plot {
  height: 450px;
}
```
to nicegui.css. I still think it is a Plotly bug (https://github.com/plotly/plotly.js/issues/4856), but this way we wouldn't need to wait for it to get fixed.

**Comment by bmaranville** [comment]
Agreed that the bug is still there.

**Comment by falkoschindler** [comment]
I just noticed that the Plotly element at https://nicegui.io/documentation/plotly#plotly_element is too large when using `Plotly.react`, even though `h-40` is set:

<img width="341" alt="Screenshot 2024-04-23 at 18 20 39" src="https://github.com/zauberzeug/nicegui/assets/5767091/9a8054dd-39ca-43ff-bc8a-6ebae5f39a01">

The chart simply overflows the element, which has the correct height of 10rem (160px).

And my potential fix from above
```css
.js-plotly-plot {
  height: 450px;
}
```
doesn't change anything.

**Comment by falkoschindler** [comment]
I was about to revert PR #2516. But the size problem on https://nicegui.io/documentation/plotly#plotly_element persists. I bisected it and found commit https://github.com/zauberzeug/nicegui/commit/328fbab10c449f593a0ace69960470af2b158e39 which seems to break the layout for the Plotly demo (given a reverted PR #2516).

**Comment by falkoschindler** [comment]
I just created a draft PR #2957 to develop a solution. It's still work in progress.

**Comment by drummerboy2543** [comment]
Thank you for taking the time for looking at this! Looking forward to the next release! 

Is there anything you want me to test or validate this change on?

**Comment by falkoschindler** [comment]
@drummerboy2543 We tested manually and successfully ran all automated tests. So it's looking pretty good so far. But if you like, you _can_ try the current main branch with your code to verify it doesn't break anything.
