### ISSUE TITLE
When executing the run_method , a KeyError error occurs.

### ISSUE THREAD

**Issue by CrystalWindSnake** [zauberzeug/nicegui#2951]
### Description

Below is the code to reproduce the issue:
```python
from nicegui import ui

async def get_ticked():
    selected = await tree.run_method("getTickedNodes")
    ui.notify(selected)

tree = ui.tree(
    [{"id": "m1", "children": [{"id": "n1"}, {"id": "n2"}]}],
    label_key="id",
    tick_strategy="leaf",
)

ui.button("query", on_click=get_ticked)

ui.run()
```

Clicking the button prints the data normally. However, an error occurs on the backend.
And the error only occurs once; clicking the button again does not produce any error.

Error message:
```
  File "D:\Programs\Python\Python311\Lib\site-packages\nicegui\javascript_request.py", line 20, in resolve
    request = cls._instances[request_id]
              ~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: '3d068f2a-375a-4136-8318-0db5978e1cb0'
```

If the page creation is moved inside `@ui.page`, everything works fine.
```python
@ui.page('/')
def index():
      ...
```

Environment information:
- python: 3.11
- nicegui: 1.4.22

**Comment by falkoschindler** [comment]
Hi @CrystalWindSnake,
Strangely I can't reproduce the error.
Do you see any JavaScript error on the developer console?

**Comment by CrystalWindSnake** [comment]
Strange, everything is working fine now when I rerun the code today.

**Comment by CrystalWindSnake** [comment]
@falkoschindler I encountered the same situation again. I suspect it's caused by the run_javascript method.
Here is the code to reproduce the issue. 

```python
from nicegui import ui

input = ui.element("input").classes("outline")

async def on_input():
    result = await ui.run_javascript(f"""return getElement({input.id}).value;""")
    print(f"input changed to {result}")

input.on("input", on_input)

ui.run()
```

When rapidly entering content into the input box, a KeyError error occurs on the backend.

**Comment by falkoschindler** [comment]
Oh, I see. Both problems only occur if you don't use page functions and multiple browser tabs are connected to `/`. Then there are JavaScript responses from multiple tabs, but after the first one is processed the second one can't find a corresponding request.

First of all, you should move your code out of the [auto-index client](https://nicegui.io/documentation/section_pages_routing#auto-index_page) into a page function, when you're sending JavaScript requests to the client.

Besides that, we need to think about how to deal such cases. Should we raise an exception when you `await ui.run_javascript` from the auto-index client? Or is there a way to work with 1-to-n relations between server and client?

**Comment by falkoschindler** [comment]
We should probably prevent the user from _awaiting_ JavaScript calls from the auto-index client, because it's expected result is unclear.
