### ISSUE TITLE
Nginx subpath example doesn't redirect correctly when navigating to subpage with trailing slash

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#2977]
### Description

The Nginx subpath example should redirect from

- http://localhost/nicegui/subpage/

to

- http://localhost/nicegui/subpage

but leads to

- https://app:8080/subpage

**Comment by Lucas-lyh** [comment]
Hey! It seems that rodja is working on other issue. I've tried to help solving this issue in PR. 
Adding proxy_redirect is helpful.
