### ISSUE TITLE
Troubles while periodically updating the 3D scene

### ISSUE THREAD

**Issue by kovalp** [zauberzeug/nicegui#2989]
### Description

Hi,

I have been making the game of life and I stumbled upon a misbehavior of the 3D scene when I update the material of objects.
I tried to reproduce the problem with a sample script and found yet another problem with 3D scene periodic updates.

The sample script (below) initializes a square-shaped field with boxes (625 boxes) and starts to update the color of all the boxes with an interval of 0.2 s. After some time, typically ten seconds the screen resets, the timer stops and the field is initialized again.
If I increase the time interval to 1 s, then the iterations continue much longer but ultimately stops and resets nevertheless.

- How to write such program to have a reliable iteration?
- Is it possible to wait until updates are fully applied and it is possible to run another updates?
- Is it possible to batch-update the properties of the existing objects?

![image](https://github.com/zauberzeug/nicegui/assets/8431900/17dea1e4-bc2a-4adf-807e-17840641037d)

```py
from nicegui import ui
from nicegui.elements.scene_objects import Box
import numpy as np

n = 25
boxes = np.empty((n, n), dtype=Box)

current_color = 'red'
colors = ('red', 'yellow', 'green')
counter = 0

def add_boxes(scene):
    k = 1.2
    s = -(n - 1) / 2.0 * k
    for r in range(n):
        for c in range(n):
            box = scene.box()
            box.move(r * k + s, c * k + s)
            box.material('red')
            boxes[r, c] = box

def update_material():
    global counter
    counter += 1

    color = colors[counter % 3]
    for r in range(n):
        for c in range(n):
            box = boxes[r, c]
            box.material(color)
            boxes[r, c] = box

@ui.page('/')
def main() -> None:
    with ui.scene(400, 400) as scene:
        scene.move_camera(0, 0, n * 0.85)
        add_boxes(scene)

    def update_material_and_counter():
        update_material()
        label.set_text(f'{counter * boxes.size }')

    timer = ui.timer(0.2, update_material_and_counter, active=False)

    with ui.row():
        ui.button('start', on_click=timer.activate)
        ui.button('stop', on_click=timer.deactivate)
        label = ui.label('num_boxes')

ui.run()
```

**Comment by falkoschindler** [comment]
Hi @kovalp, thanks for reporting this issue.

I just boiled it down to the following snippet and let it run for a while:
```py
state = {'counter': 0}

with ui.scene(400, 400) as scene:
    scene.move_camera(z=20)
    boxes = [scene.box(0.9, 0.9).move(r - 12.5, c - 12.5) for r in range(25) for c in range(25)]

def update():
    state.update(counter=state['counter'] + 1)
    for box in boxes:
        box.material(('red', 'yellow', 'green')[state['counter'] % 3])

ui.timer(0.2, update)
```
But the scene never resets and I can't reproduce any problem. 🤔

**Comment by kovalp** [comment]
Hi,

While boiling down the script you omitted the decorator `@ui.page`. This seems to be crucial. 

For example, I modified my script by removing the decorator and calling `main()` before `ui.run()`. In this case, I do not see the resets. _Vice versa_, when I add the decorator page to your snippet, I start to observe these resets.

I am using Ubuntu 22.04, nicegui = "^1.4.22", python 3.11.9, Firefox browser.

**Comment by falkoschindler** [comment]
Ah, I see. Because the page decorator didn't make a difference in Chrome, I removed it. But wrapping my example in a page function unveils a reset after around 150-175 increments in _Firefox_.

There's probably some client-side message queue filling up and Chrome seems to be faster in processing the messages. But I'm not sure what to do about it. At some point the communication (or rendering?) gets too inefficient and the client would need to drop updates. But this would cause unexpected results either.

**Comment by kovalp** [comment]
I tried Chrome. It is much faster indeed.

To make the updates robust, I could use a function which tells if there are on-going messages in the queue. Jam detector so to speak.

Does such function exist?

Next on my wish list is a batch update of the scene. For example, a function which operates on a batch of elements and using just one, albeit bigger message.

**Comment by kovalp** [comment]
> I tried Chrome. It is much faster indeed.

The other real problem does not appear in Chrome at least with the moderate number of boxes (2500) on the field.
