### ISSUE TITLE
Native mode and resizability of the window

### ISSUE THREAD

**Issue by 4mg1n3** [zauberzeug/nicegui#3000]
### Description

Hi,

When the app is ran in native mode, the absence of border prevents the app from being resized with the mouse (or at least that's my understanding of it).

Not sure it can be considered a bug given that it is logical behavior but if not it could be a good feature to have a reimplementation of a border hover type of window resizing.

**Comment by falkoschindler** [comment]
Hi @4mg1n3,
I'm not sure if I understand correctly. When I run a native app like the following, I can very well resize the window, at least on macOS.

```py
from nicegui import ui

ui.label('Hello, world!')

ui.run(native=True)
```

What OS are you referring to?

**Comment by 4mg1n3** [comment]
Oh no sorry I totally forgot to mention that I was in frameless

**Comment by falkoschindler** [comment]
@4mg1n3 Can you, please, try this native pywebview example:

```py
import webview

window = webview.create_window('Simple browser', 'https://pywebview.flowrl.com/', frameless=True)
webview.start()
```

I guess you can't resize it either, so it's not a NiceGUI but pywebview limitation.

**Comment by 4mg1n3** [comment]
Yes I had tried it and it didn't work, I looked a bit a the source code of pywebview yesterday and it didn't seem like there was a simple way to solve this problem. I'll have to reimplement it I guess...
Anyway thanks for your time and for your contribution on this amazing project
