### ISSUE TITLE
Text in input and select components is not aligned to each other

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#3001]
### Description

Consider the following code:

```python
    with ui.row():
        ui.input('Input', value='input value')
        ui.select(['Option 1', 'Option 2', 'Option 3'], value='Option 1')
```

It gives this result:

![изображение](https://github.com/zauberzeug/nicegui/assets/807120/70d277f6-14ca-448f-84d9-598392e8053e)

As you can see, the text in input is lower than the text in select, giving the UI a sloppy look.

**Comment by chrschorn** [comment]
If you want to make them line up, try either giving both elements a label or none of them:

```python
with ui.row():
    ui.input(value="Input")
    ui.select(["Option 1", "Option 2"], value="Option 1")

with ui.row():
    ui.input("Input", value="value")
    ui.select(["Option 1", "Option 2"], value="Option 1", label="Select")
```

![image](https://github.com/zauberzeug/nicegui/assets/6242043/12f32bae-fe00-4b79-9594-2cebe6fc8115)

**Comment by me21** [comment]
Thank you, I feel stupid 🥴

**Comment by falkoschindler** [comment]
@chrschorn I just wonder why both elements are well aligned on a plain Quasar page - independent of labels:

```html
<!DOCTYPE html>
<html>
  <head>
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons"
      rel="stylesheet"
      type="text/css"
    />
    <link href="https://cdn.jsdelivr.net/npm/quasar@2.15.4/dist/quasar.prod.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="q-app">
      <div class="row">
        <q-input label="Input" model-value="input value" />
        <q-select model-value="A" />
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.prod.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/quasar@2.15.4/dist/quasar.umd.prod.js"></script>
    <script>
      const app = Vue.createApp({ setup: () => {} });
      app.use(Quasar);
      app.mount("#q-app");
    </script>
  </body>
</html>
```

![Screenshot 2024-05-02 at 11 07 33](https://github.com/zauberzeug/nicegui/assets/5767091/4c7d6cfe-8656-4495-b567-e69638eb8ec6)

**Comment by me21** [comment]
@falkoschindler oh, I'm not sure what's going on here then. Feel free to reopen the issue.

**Comment by falkoschindler** [comment]
@me21 I found my mistake! We can't use auto-closing tags in HTML. Instead we need to write
```html
<div class="row">
  <q-input label="Input" model-value="input value"></q-input>
  <q-select model-value="A"></q-select>
</div>
```
This way Quasar yields the same result like NiceGUI. And if you think about it, it makes sense to vertically align the select value in the middle (next to the arrow) if there is no label. If there was no input element, the `ui.select` without a label would look strange with a value shifted towards the bottom.
