### ISSUE TITLE
Select fails to change value on first try.

### ISSUE THREAD

**Issue by natankeddem** [zauberzeug/nicegui#3014]
### Description

I am testing the following code:
```py
from nicegui import ui

def changed(value):
    ui.notification(value)

options = ["default"]
select = ui.select(options, label="Select", value=options, with_input=True, new_value_mode="add", multiple=True, on_change=lambda e: changed(e.value))
select.props("hide-dropdown-icon use-chips popup-content-style='display: none'")
select.tailwind.width("full")

ui.run(show=False, reload=False)
```
Here is a video of my experience:
[google_screen_recording_2024-05-04T02-39_11.781Z.webm](https://github.com/zauberzeug/nicegui/assets/44515217/4c9e60ad-eb34-4ce0-ba54-6964851278fa)

You will note the first entry disappears on submission and I must retype the name and submit it again to get it to change value.

**Comment by rodja** [comment]
Interesting combination @natankeddem. It works if you use `value=options[0]` instead of `value=options`. Could be some Quasar issue. Could you try setting up the same scenario in Quasar only and see if it is reproduicable?

**Comment by natankeddem** [comment]
I was basically trying to recreate the example on the Quasar site:
https://quasar.dev/vue-components/select#the-new-value-mode-prop

**Comment by rodja** [comment]
@natankeddem the Quasar example does not have a preselection of values...

**Comment by falkoschindler** [comment]
Minimum reproduction:
```py
options = ['default']
ui.select(options, value=options, with_input=True, new_value_mode='add', multiple=True).props('use-chips')
```

Working counterexample:
```py
ui.select(['default'], value=['default'], with_input=True, new_value_mode='add', multiple=True).props('use-chips')
```

I guess there is a problem with using the same reference for the options and the value. Maybe we can simply copy on of the arguments. I'll look into it.

**Comment by falkoschindler** [comment]
Actually I'm not sure if we really need to change the implementation by copying arguments. Maybe we should warn or raise instead if both arguments are the same object, because that doesn't make much sense and the expected behavior is not very clear.

**Comment by natankeddem** [comment]
@falkoschindler thank you so much for digging into this so quickly. @rodja and your commitment to this project is exceptional. Your breakdown of the core issue makes sense, the options and value somehow are interacting strangely when they are sharing a list. In my use case I was attempting to restore the value and options from storage at startup. That is why both objects were the same. I don't have an opinion on the best resolution on this issue, I'll defer to yours.
