### ISSUE TITLE
Using `copy.deepcopy` on storage causes data loss.

### ISSUE THREAD

**Issue by natankeddem** [zauberzeug/nicegui#3023]
### Description

Sorry if this example is too verbose but it required a specific sequence of events to make happen so this was my best shot at highlighting what I am seeing.
```py
import json
import copy
import asyncio
from pathlib import Path
from nicegui import app, ui

@ui.page("/")
def root() -> None:
    async def test() -> None:
        log.push("Clearing storage-general.json...")
        Path(".nicegui", "storage-general.json").write_text("{}")
        await asyncio.sleep(1)
        log.push("Read storage-general.json:")
        log.push(Path(".nicegui", "storage-general.json").read_text("utf-8"))
        log.push("Loading storage...")
        app.storage.general["a"] = {"b": {"c": {"d": "e"}}}
        await asyncio.sleep(1)
        log.push("Read storage-general.json:")
        log.push(Path(".nicegui", "storage-general.json").read_text("utf-8"))
        log.push("Copy storage...")
        storage_copy = copy.deepcopy(app.storage.general["a"])
        await asyncio.sleep(1)
        log.push("Read storage-general.json:")
        log.push(Path(".nicegui", "storage-general.json").read_text("utf-8"))

    log = ui.log().classes("w-full h-[480px]")
    ui.button("Test Storage", on_click=test)

if __name__ in {"__main__", "__mp_main__"}:
    ui.run(show=False, reload=False)
```

Performing a `copy.deepcopy` on a nested element inside `app.storage.general` causes the loss of data which was stored inside the storage file. I am not sure if this a known issue but the documentation/searching didn't turn up anything. Maybe this behaviour might be worth documenting, if it hasn't already?

**Comment by falkoschindler** [comment]
Very interesting, @natankeddem!

Here is an example with just a `PersistentDict`:

```py
import copy
from pathlib import Path
from nicegui import observables, storage, ui

@ui.page('/')
def index():
    d = storage.PersistentDict(Path('tmp.json'))
    d['a'] = {'b': 0}
    copy.deepcopy(d['a'])
    ui.timer(0.1, lambda: print(Path('tmp.json').read_text()), once=True)
```

I think the `deepcopy` function copies some internals of the underlying `ObservableDict`, so that the change handler is triggered during the copy operation, which writes an empty dictionary to the JSON file.

Here is another example demonstrating how `on_change` is called with an empty "a" attribute:
```py
from nicegui import observables

d = observables.ObservableDict({'a': {'b': 0}}, on_change=lambda sender: print('changed:', sender))
print('copying...')
copy.deepcopy(d['a'])
```
```
copying...
changed: ObservableChangeEventArguments(sender={'a': {}})
changed: ObservableChangeEventArguments(sender={'b': 0})
```

**Comment by natankeddem** [comment]
It took me a bit to figure out what kept on deleting my storage. Then once I saw it was the `deepcopy` I guessed something similar to what you suggested but didn't dig too deep since I was trying to get some other things working on my project. To accomplish the `deepcopy` I ended up using the `json.loads(json.dumps(app.storage.general["key"]))` trick.

**Comment by falkoschindler** [comment]
It looks like we need to overwrite the `__copy__` and `__deepcopy__` methods of our observable collections:
https://docs.python.org/3/library/copy.html

**Comment by natankeddem** [comment]
Thank you!
