### ISSUE TITLE
Problem for passing parameter to handler function for dynamic added `ul.html` , `ui.botton`, maybe others.

### ISSUE THREAD

**Issue by bukun** [zauberzeug/nicegui#3027]
### Description

For some tasks I want to use `ui.html` to generate several elements and pass different parameter to handler function for each element. However, I found just the last parameter is passed, and is passwd to all the elements.

```py
from nicegui import ui
def check_val(ii):
    print(ii)
for ii in range(10):
    ui.html(f'<a>{ii}</a>').style("color:blue").on('click', lambda: check_val(ii))
# for ii in range(11,20):
#     ui.button(f'{ii}').style("color:blue").on('click', lambda: check_val(ii))
ui.run()
```

There should be `0`, `1`, `2` , ...  when click the elements one by one, but there just `9`, `9`, `9` , ... .

And same thing happend to `ui.button`. Must also to other controls.

**Comment by bukun** [comment]
I am new to NiceGUI.  and maybe other methods for my task ?

**Comment by rodja** [comment]
See our FAQ: https://github.com/zauberzeug/nicegui/wiki/FAQs#why-is-the-last-element-of-my-for-loop-used-in-every-step
