### ISSUE TITLE
Change to MS-Windows style windows is not possible?  

### ISSUE THREAD

**Issue by richlysakowski** [zauberzeug/nicegui#3042]
### Description

DESIGN BUG/FLAW:
All the demos and documentation show Macintosh-style windows.  They all have the 3-colored close, minimize, maximize buttons in the toolbar.  This is nice for macintosh-only users, but is a hassle and it is simply a wrong design for PC users, because it violates expectations and requires retraining on mouse and keyboarding skills.  

I have not seen any application examples for standard MS-Windows windowing interfaces.  Without support for Microsoft GUI standard windows, controls, layout, menus and so on, this Macintosh-only windowing toolkit is a non-starter for building native-looking Windows applications.  

Please give some examples how to target applications specifically to build Microsoft conformant GUIs.

Thank you.

**Comment by rodja** [comment]
We use pywebview for native windows. And -- on Windows -- the style is not Macintosh. Have you tried it? Or are you only referring to the documentation on https://nicegui.io? On the website we are simply using a bit of html to make clear that on piece contains source code and another the result in a browser window.

**Comment by falkoschindler** [comment]
As far as I understand you're referring to the visual appearance of the mocked browser windows of our online demos. But I don't see how this affects the UX of NiceGUI apps, since it's just a stylized example of how the app might look in a browser. Therefore I'll close this issue.
