### ISSUE TITLE
custom vue.js component not updated after modification

### ISSUE THREAD

**Issue by MLaurenceFournier** [zauberzeug/nicegui#3074]
### Description

I've copied the `custom_vue_component` example in my project. When I change the html template in `counter.js`, the component isn't updated in the browser (watchfile isn't involved, I'm restarting the whole process). I found that renaming `counter.js` and changing the `component` parameter forces an update.

I know almost nothing about vue.js, but I suspect some kind of compilation step is cached and not invalidated when I edit `counter.js`.

How can I force a "recompilation" of `counter.js` every time I relaunch the process?

**system information**
os: windows 10
package manager: conda
channel: conda-forge
python: 3.10.12
nicegui: 1.4.25

**Comment by falkoschindler** [comment]
Hi @MLaurenceFournier, I guess your browser is caching the counter.js file. Try reloading the page with caching disabled and you should be able to seen an update.

**Comment by MLaurenceFournier** [comment]
Thanks a lot @falkoschindler. The browser cache was indeed the problem. Now I feel stupid asking the question, but I hope it will save you from answering it another time. May I suggest adding a comment on the subject in `counter.js`?

**Comment by falkoschindler** [comment]
I'm glad we found the root cause. 🙂
I added a comment in a3e982a90ff63989fc8b5bcc52025b07592004e5.
