### ISSUE TITLE
non-existing on_pointer parameter in InteractiveImage

### ISSUE THREAD

**Issue by MLaurenceFournier** [zauberzeug/nicegui#3078]
### Description

The parameter `on_pointer` of `InteractiveImage.__init__` mentioned in the documentation doesn't really exist.

Starting from the documentation example, I found that I can accept `"pointermove"` events and handle them in the `mouse_handler` instead.

The documentation should better explain how one is expected to use pointer events if they are supported.

**Comment by falkoschindler** [comment]
Thanks, @MLaurenceFournier!
This line was a relict of PR #2745 where we ultimately decided against an extra parameter.
