### ISSUE TITLE
Bump plotly.js to 2.32.0 version supporting zindex

### ISSUE THREAD

**Issue by denis-x** [zauberzeug/nicegui#3086]
### Description

Hello,

Appreciate the framework, that you are creating. Really enjoy to make my pet project on it. I would like to ask you, if you can bump plotly.js to 2.32.0 version by the next release. plotly.js is currently at version 2.27, the recent version 2.32 has the most wanted feature of having zindex to control relative positions of drawn objects.

BR Denis

**Comment by falkoschindler** [comment]
Hi @denis-x,
We usually upgrade dependencies during major releases only, because they can introduce breaking changes. Therefore I'll schedule this request for the upcoming 2.0.0 milestone.

**Comment by denis-x** [comment]
Hello,

Good to know, thanks Falko. By the way, is any workaround to overload 2.27 by 2.32 version from static location?
Unfortunately, I did not succeed to achieve it with add_resource or by adding script in HEAD/BODY.
Maybe I did something wrong.

BR Denis

**Comment by falkoschindler** [comment]
Hi Denis, I found a rather neat workaround to replace the library with a different version. You can simply change the file path the first item of `ui.plotly.libraries` is pointing to. Assuming you have a custom plotly.min.js in your working directory:
```py
ui.plotly.libraries[0].path = Path('plotly.min.js')
```

**Comment by denis-x** [comment]
Herzlichen Dank Falko, ich habe es geschafft!
