### ISSUE TITLE
Lifespan state is not passed when a FastAPI app mount a Nicegui app

### ISSUE THREAD

**Issue by RomainEconomics** [zauberzeug/nicegui#3094]
### Description

Following this example: https://github.com/zauberzeug/nicegui/tree/main/examples/fastapi

But simply adding a lifespan with some state in the main app:

```python
from contextlib import asynccontextmanager

import frontend
from fastapi import FastAPI, Request


@asynccontextmanager
async def lifespan(app: FastAPI):
    yield {"some_state": 10}


app = FastAPI(lifespan=lifespan)


@app.get("/")
async def read_root(request: Request):
    print(request.state.__dict__)

frontend.init(app)
```

When calling the "/" route, the state dict is empty.

However, this works normally when running the app without mounting the frontend.

This seems to come from the fact that in the [ui_run_with.py](https://github.com/zauberzeug/nicegui/blob/bbc9977136f4f8f7f09aff1b2d0ffe268a884db3/nicegui/ui_run_with.py#L72) the state is not passed.

```py
    @asynccontextmanager
    async def lifespan_wrapper(app):
        await _startup()
        async with main_app_lifespan(app) as state:
            yield state

        await _shutdown()
```

When yielding the state, this works again

**Comment by rodja** [comment]
Thanks for bringing this up @RomainEconomics. I was not aware about the ability to yield state in a lifespan context manager. Would you like to create a pull request for this?

**Comment by RomainEconomics** [comment]
Yes, for sure
I've created the pull request with the small modification

**Comment by rodja** [comment]
Wonderful. Thank you so much, @RomainEconomics!
