### ISSUE TITLE
auto-reload make pyinstaller build failed

### ISSUE THREAD

**Issue by atticus-lv** [zauberzeug/nicegui#3106]
### Description
when auto-reload in `ui.run(reload = True)`, build is ok but open exe will report error
![image](https://github.com/zauberzeug/nicegui/assets/64118610/fd90dcef-7a1b-47c7-84b3-443fe633d2c6)

**Comment by falkoschindler** [comment]
Yes, that's why we recommend setting `reload=False`:
https://nicegui.io/documentation/section_configuration_deployment#package_for_installation

**Comment by atticus-lv** [comment]
Thanks~
