### ISSUE TITLE
Audio with hashtags in filenames are not loaded

### ISSUE THREAD

**Issue by gotev** [zauberzeug/nicegui#3124]
### Description

I have a folder with two audio files and I'm trying to play them:
- artist - #title.mp3
- artist - title.mp3

Minimal app:
```python
from nicegui import ui, native
import urllib
from pathlib import Path

ui.audio(src="artist - #title.mp3", controls=True)  # this triggers an error
ui.audio(src=urllib.parse.quote_plus("artist - #title.mp3"),
         controls=True)  # this triggers an error
ui.audio(src=Path("artist - #title.mp3"),
         controls=True)  # this triggers an error
ui.audio(src="artist - title.mp3", controls=True)  # this works

ui.run(
    reload=False,
    native=True,
    dark=True,
    port=native.find_open_port(),
    title='Audio Demo'
)
```
When the app is run this is what I see on screen:
<img width="473" alt="Screenshot 2024-05-25 alle 09 51 52" src="https://github.com/zauberzeug/nicegui/assets/16792495/d744e9eb-5a17-42a0-9bf6-2852c31a3a9b">

And this is what I see in the console:
```shell
$ python app.py
NiceGUI ready to go on http://localhost:8002
http://127.0.0.1:8002/artist+-+#title.mp3 not found
http://127.0.0.1:8002/_nicegui/auto/media/9ea021d92f620e392dc6848d57e79cca/artist -  not found
http://127.0.0.1:8002/_nicegui/auto/media/9ea021d92f620e392dc6848d57e79cca/artist -  not found
```
using Python 3.11.7 on macOS Sonoma 14.4

Tried URL escaping the file name and parsing file name with Path, but without success. Has this already happened to others before?

**Comment by afullerx** [comment]
This seems to be due to an oversight where file names are not escaped when the URL is generated. I experimentally added the escaping to `App.add_media_file()` using `urllib.parse.quote()` and the provided example seems to be working. I'll submit a pull request once I do some more testing, unless anyone else has a better idea. I would do the same to `App.add_static_file()`
