### ISSUE TITLE
Pytest: recursive dependency in fixtures

### ISSUE THREAD

**Issue by taschini** [zauberzeug/nicegui#3137]
### Description

Most important thing first; NiceGUI is great.

When trying to write unit tests following the example in the repository, I get:

```
file /home/myself/Projects/nicegui_poc/.venv/lib/python3.11/site-packages/nicegui/testing/conftest.py, line 25
  @pytest.fixture
  def chrome_options(chrome_options: webdriver.ChromeOptions) -> webdriver.ChromeOptions:
E       recursive dependency involving fixture 'chrome_options' detected
>       available fixtures: anyio_backend, anyio_backend_name, anyio_backend_options, ...
```

I am not familiar with the pattern that you guys use:

```python
def fixture(fixture: type) -> type:
```

But it does strike me as introducing a cyclic dependency whereby `chrome_options` requires `chrome_options` itself .  I would think that

```python
@pytest.fixture
def chrome_options() -> webdriver.ChromeOptions:
    chrome_options = webdriver.ChromeOptions()
    ...
```    

would be a more robust definition.

I can provide a full example if necessary.

**Comment by falkoschindler** [comment]
Hi @taschini,

We're following the [pytest-selenium documentation](https://pytest-selenium.readthedocs.io/en/latest/user_guide.html#configuration-1):

> ```py
> import pytest
> @pytest.fixture
> def chrome_options(chrome_options):
>     chrome_options.binary_location = '/path/to/chrome'
>     chrome_options.add_extension('/path/to/extension.crx')
>     chrome_options.add_argument('--kiosk')
>     return chrome_options
> ```

The `chrome_options` are a fixture which is implicitly created by pytest and extended by this function definition. It is unclear why you're getting an exception. Are you running our original pytest example?

**Comment by taschini** [comment]
Thanks to your reply, I figured out what the problem was: in my virtual environment I had `selenium` but not `pytest-selenium`. 

With the information at its disposal, `pytest` cannot possible know that `chrome_options` in `nicegui` shadows the fixture of the same name defined by `pytest-selenium`, and erroneously infers that there is a circular dependency on `chrome_options` itself.

By explicitly adding `pytest-selenium` to my dev dependencies, the problem goes away.
