### ISSUE TITLE
Plotly charts are not responsive

### ISSUE THREAD

**Issue by tmlmt** [zauberzeug/nicegui#3158]
## Problem

Despite it being the default in the `ui.plotly` element: 
https://github.com/zauberzeug/nicegui/blob/92a0cf0fdaee28ffba8329483e55f2a5d5c529fe/nicegui/elements/plotly.vue#L17-L19
Plotly charts are not responsive.

## Minimal repro

```py
ui.plotly({
    "data": [{
        "type": "scatter",
        "name": "my_series",
        "mode": "markers+lines",
        "x": [0, 1],
        "y": [0, 1],
    }],
    "layout": {"title": "My long title which I want to be responsive"},
})
```

### Laptop screen 

![image](https://github.com/zauberzeug/nicegui/assets/10244927/2dc9279e-fb3d-42eb-b88f-c6ecd941bbfc)

### Mobile screen

![image](https://github.com/zauberzeug/nicegui/assets/10244927/a0c845a4-aadf-4f42-8a73-e7748e51dfed)

**Comment by falkoschindler** [comment]
Hi @tmlmt,

I wonder what `{ responsive: true }` is actually supposed to do. I checked a plain HTML example and the plot resizes nicely, but the title isn't wrapped:
```html
<html>
  <head>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  </head>
  <body>
    <div id="plot"></div>
    <script>
      Plotly.newPlot("plot", [], { title: "My long title which I want to be responsive" }, { responsive: true });
      window.onresize = () => Plotly.Plots.resize("plot");
    </script>
  </body>
</html>
```

Even though your Python version doesn't resize automatically, you can easily add `.classes('w-full')` to set the width to 100%.

**Comment by tmlmt** [comment]
Thanks for looking at it, @falkoschindler ! 

Indeed, it seems that responsiveness in plotly is very minimal: the only place there is mention of it in the code is:
https://github.com/plotly/plotly.js/blob/7ffcdd7d602d52e8a0e75d766ae18fe8e9eb54fb/src/plot_api/plot_api.js#L169-L180

The plot gets resized with an event listener, but plots for small sizes don't seem to take care of this sort of things:
An issue was posted 4 years ago and hasn't been followed up since: https://github.com/plotly/plotly.js/issues/5109

I guess it's an upstream issue so the issue can be closed here. Perhaps it could be useful to add a few words in the docs: I've added it to my list [here](https://github.com/zauberzeug/nicegui/discussions/3155)
