### ISSUE TITLE
integrate with plotly.py

### ISSUE THREAD

**Issue by misterkramer** [zauberzeug/nicegui#317]
look https://github.com/zauberzeug/nicegui/discussions/307

It would be cool to have something similar to `ui.plotly` element in nicegui.

- [x] Implement `ui.plotly`
- [x] Add dependency to pyproject.toml
- [x] Write tests
- [x] Add example to API reference
- [x] Introduce `ui.pyplot` and make `ui.plot` a (deprecated) alias?

**Comment by keepexploring** [comment]
Alone the same lines ...

Is there, or could there be a way to integrate with bokeh (https://bokeh.org) or holoviews (https://holoviews.org)?

**Comment by rodja** [comment]
> integrate with bokeh (https://bokeh.org/) or holoviews (https://holoviews.org/)?

Sure. Could you create separate issues for these? Then we can track the progress of the implementations individually.

**Comment by keepexploring** [comment]
sure - will do now.

**Comment by rodja** [comment]
We should use dynamic dependency loading like done in `ui.chart` to not load the plotly js by the client if not needed.

**Comment by falkoschindler** [comment]
@rodja Ready for review.

Tiny example I tested with:

```py
fig = px.scatter(x=[1, 2, 3], y=[1, 2, 3], title='Test')
plot = ui.plotly(fig)

ui.button('Add trace', on_click=lambda: (
    fig.add_trace(go.Scatter(x=[0, 1, 2], y=[2, 1, 0], name='Trace 2')),
    plot.update()
))
```

**Comment by rodja** [comment]
It's merged
