### ISSUE TITLE
JS exception due to wrong variable in download function

### ISSUE THREAD

**Issue by 123swk123** [zauberzeug/nicegui#3173]
### Description

https://github.com/zauberzeug/nicegui/blob/bbab081de130a538d9f437df961e079fb0cc842d/nicegui/static/nicegui.js#L243
argument `url` should be changed to `anchor.href`

exception details
``` 
nicegui.js:363 ReferenceError: url is not defined
    at download (nicegui.js:244:25)
    at download (nicegui.js:348:28)
    at nicegui.js:355:41
    at a.<anonymous> (nicegui.js:361:23)
    at U.emit (index.mjs:136:20)
    at a.value (socket.js:498:20)
    at a.value (socket.js:485:18)
    at a.value (socket.js:455:22)
    at U.emit (index.mjs:136:20)
    at manager.js:204:18
```

**Comment by falkoschindler** [comment]
Thanks for reporting this issue, @123swk123!

Reproduction (like in [this demo](https://nicegui.io/documentation/download#download_raw_bytes_from_memory)):
```py
ui.button('Download', on_click=lambda: ui.download(b'Hello World', 'hello.txt'))
```

Looks like I introduced this bug during a code review:
https://github.com/zauberzeug/nicegui/commit/9dbf8b96f681ff15d83409f718ba85f4c2bef1c1#diff-4e4cc16e68c714c6a8433c24c00c6bc837f4f7ed51259f6e4bff356931927ed0
