### ISSUE TITLE
ECharts 3D Line Doesn't Render

### ISSUE THREAD

**Issue by natankeddem** [zauberzeug/nicegui#3184]
### Description

I am trying to render a 3D Line chart utilizing `ui.echart`. I am only getting a blank page.

```py
from nicegui import ui

options = {
    "xAxis3D": {},
    "yAxis3D": {},
    "zAxis3D": {},
    "grid3D": {},
    "series": [
        {
            "type": "line3D",
            "data": [
                [1, 123, 111],
                [1, 1123, 211],
            ],
        }
    ],
}
ui.echart(options=options)
ui.run()
```

I am fairly certain these options should be acceptable as I tried them inside the echart playground and it seemed to work there:
https://echarts.apache.org/examples/en/editor.html?c=line3d-orthographic&gl=1&code=PYBwLglsB2AEC8sDeBYAULTsBEAPAgrhAM4DMAItgFzIC-ANOljgJ6EkXV2MZbYBe7MpRpIGTPgHMAThAAmnUeN6ZsxAKaz1xLgG0JzTKhWHm2MCxDqu2ADYRo6zj1OnscgIZgPeg69O6AIz0sIEATKQhgdEAui7-rkFR4ZGwYeFxfv6ZJsy0fjm0ANxAA

I don't think I am doing anything incorrectly but maybe I am missing something? It looks like there might be some additional imports that might be required for the 3D rendering from a quick look in the playground?

**Comment by falkoschindler** [comment]
Hi @natankeddem,

It looks like 3D lines require [ECharts-GL](https://github.com/ecomfe/echarts-gl), which is an ECharts extension not included in NiceGUI.

**Comment by natankeddem** [comment]
Hi @falkoschindler,
Thank you for looking into this. Is adding support for this functionality acceptable to you? I can try to work on a PR for this if it is.
