### ISSUE TITLE
how can i upload a directory use ui.upload component

### ISSUE THREAD

**Issue by moukexian** [zauberzeug/nicegui#3185]
### Description

How can I upload a directory and all the files in the directory use ui.upload component.I want to upload all the files in an directory,but ui.upload cannot select the directory,please help me,thank you very much.I an waiting for the result.

**Comment by python-and-fiction** [comment]
Follow this https://github.com/zauberzeug/nicegui/tree/main/examples/local_file_picker/
you can use mkdir in your server, pick up the directory's name,which looks like upload

**Comment by falkoschindler** [comment]
It looks like you asked the very same question three weeks ago, see issue #3103 which I converted into Q&A #3104.
