### ISSUE TITLE
Changing min/max limits of `ui.range` breaks the element

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#3191]
### Discussed in https://github.com/zauberzeug/nicegui/discussions/3167

<div type='discussions-op-text'>

<sup>Originally posted by **bojh** June  3, 2024</sup>
### Question

I want to programmatically re-set the ui.range min/max boundaries and min/max values. 
```python
from nicegui import app, ui

my_range = ui.range(min=0, max=100, value={'min':5, 'max':95})
my_value = ui.label().bind_text_from(my_range, 'value', 
    backward=lambda v: f'v_min: {v["min"]}, v_max: {v["max"]}')

def set_bnd_val(b_min, b_max, v_min, v_max):
        my_range.props((f'min={b_min} max={b_max}'))
        my_range.value = {'min':v_min, 'max':v_max}

my_button_set1 = ui.button("value In: [40- 60]", on_click=lambda: set_bnd_val(40, 60, 45,55))
my_button_set2 = ui.button("value In: [ 0-100]", on_click=lambda: set_bnd_val( 0,100,  5,95))

ui.run()
```
... pressing buttons seems working well. The range slider does update and the new proportion is OK. 
The troubles come up touching the value handles: The reported values does create 'None' values, depending which handle is moved and the slider is no longer correct.

The question is what is wrong or missing to do it in the right way?
</div>

**Comment by falkoschindler** [comment]
Here is a minimum example:
```py
r = ui.range(min=0, max=100, value={'min': 30, 'max': 70})
ui.button('Change limits', on_click=lambda: r.props('min=10 max=90'))
ui.label().bind_text_from(r, 'value', str)
```

After changing the limits, adjusting the range causes it to disappear and the value is `None`.

A plain Quasar example works fine though:
```html
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/quasar@2.16.4/dist/quasar.prod.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="q-app">
      <q-range v-model="range" :min="rangeLimits.min" :max="rangeLimits.max"></q-range>
      <q-btn label="Change limits" @click="changeLimits"></q-btn>
      <div>Current range: {{ range.min }} - {{ range.max }}</div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.prod.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/quasar@2.16.4/dist/quasar.umd.prod.js"></script>
    <script>
      const app = Vue.createApp({
        data() {
          return { range: { min: 30, max: 70 }, rangeLimits: { min: 0, max: 100 } };
        },
        methods: {
          changeLimits() {
            this.rangeLimits = { min: 10, max: 90 };
          },
        },
        setup() {
          return {};
        },
      });
      app.use(Quasar);
      app.mount("#q-app");
    </script>
  </body>
</html>
```

Does anyone have an idea?

**Comment by Ezbaze** [comment]
This seems to be caused by the missing `:` in front of the [prop names](https://github.com/zauberzeug/nicegui/blob/a435775e5cf4a8a14e44163812744964f449cc6e/nicegui/elements/range.py#L27-L29), adding those in seems to fix the issue, but I'm unsure why.

Modified minimum example:
```python
from nicegui import ui

r = ui.range(min=0, max=100, value={"min": 30, "max": 70})
ui.button("Change limits", on_click=lambda: r.props(":min=10 :max=90"))
ui.label().bind_text_from(r, "value", str)

ui.run()
```

I also submitted a draft pull request with the changes.

**Comment by falkoschindler** [comment]
Oh, nice catch, @Ezbaze! I think I understand:

When calling `r.props('min=10 max=90')`, we're setting `r._props['min'] = '10'` and `r._props['max'] = '90'`. Both limits are treated as strings, because `.props()` can't recognize data types. Quasar's QRange, however, doesn't seem to be able to handle strings as range limits, which causes the strange behavior.

When we update the limits by writing floats to `r._props`, the range element behaves nicely:
```py
r = ui.range(min=0, max=100, value={'min': 30, 'max': 70})

def change_limits():
    r._props.update(min=10, max=90)
    r.update()

ui.button('Change limits', on_click=change_limits)
ui.label().bind_text_from(r, 'value', str)
```

So we don't even need PR #3242. But we should provide a public API for changing `min` and `max` to avoid this data type confusion.
