### ISSUE TITLE
User Storage Intercommunication Across Devices on Non-Standard Ports

### ISSUE THREAD

**Issue by talongao** [zauberzeug/nicegui#3196]
### Description

I'm using a translator, so I may not be expressing myself accurately.

### Description
I've encountered an issue with the user_storage functionality when deploying on a server. It appears that the same user_storage is accessible across different devices, which is not the intended behavior.

### Steps to Reproduce
1. Deploy on a server.
2. Access user_storage from different devices.
3. Observe that the data of user_storage can be accessible across different devices.

### Expected Behavior
Different devices should access different user storage.

### Actual Behavior
User storage is shared between devices.

### Environment
- Server Configuration: Ubuntu 22.04
- Port Used: 13564

### Question
Does user_storage only functions correctly on ports 80 or 443? If not, could you provide guidance on how to resolve this issue?

Thank you for your time and assistance.

**Comment by falkoschindler** [comment]
Hi @talongao,

I assume you tested with something like this:
```py
from nicegui import app, ui

@ui.page('/')
def index():
    app.storage.user['count'] = app.storage.user.get('count', 0) + 1
    with ui.row():
        ui.label('your own page visits:')
        ui.label().bind_text_from(app.storage.user, 'count')

ui.run(port=13564, storage_secret='secret')
```

I'm struggling to reproduce the behavior. What kind of server do you use for deployment? Do you simply copy the script to another machine or is there some proxy like nginx involved?

Can anyone else reproduce the issue?

**Comment by talongao** [comment]
@falkoschindler 
Thanks for you help.

Your example is working fine. Maybe because I directly assigned app.storage.user directly to a class for ease of use. The class was previously used on a local app, this time I copied it directly without considering the difference.
