### ISSUE TITLE
ui.image will never load local image in single page app example

### ISSUE THREAD

**Issue by atticus-lv** [zauberzeug/nicegui#3223]
### Description
system: win11
nicegui: 1.4.27

code from https://github.com/zauberzeug/nicegui/tree/main/examples/single_page_app/
only modify the `show_two` in single page app example `main.py` like this, and local image will never be loaded

```python
    @router.add('/two')
    def show_two():
        # https://github.com/zauberzeug/nicegui/blob/main/website/static/logo_square.png?raw=true
        ui.image('logo_square.png')
```
https://github.com/zauberzeug/nicegui/assets/64118610/87d0dbe0-0389-47f5-ba91-e57ebcb5fde5

**Comment by python-and-fiction** [comment]
path is wrong.you should start uri with project root directory.
right code is
`ui.image('single_page_app/logo_square.png')`

**Comment by atticus-lv** [comment]
the main.py file is insdie single_page_app. actually I use an absolute path/web image will also have this problem. I will upload a screenshot later

**Comment by python-and-fiction** [comment]
> the main.py file is insdie single_page_app. actually I use an absolute path/web image will also have this problem. I will upload a screenshot later

any errors from your program?

**Comment by atticus-lv** [comment]
yes, check this video @python-and-fiction 

https://github.com/zauberzeug/nicegui/assets/64118610/fd79e713-0e47-4f37-ac20-f5573edda08c

```python
    @router.add('/')
    def show_one():
        ui.image('https://github.com/zauberzeug/nicegui/blob/main/website/static/logo_square.png?raw=true')

    @router.add('/two')
    def show_two():
# my local path
        ui.image(r'C:\Users\atticus\Desktop\ToDoList-nicegui\single_page_app\logo_square.png')

    @router.add('/three')
    def show_three():
# your solution
        ui.image('single_page_app/logo_square.png')
```

**Comment by atticus-lv** [comment]
@falkoschindler hi falkoschindler, do you have any idea on this problem?

**Comment by python-and-fiction** [comment]
because of this
`@ui.page('/{_:path}')  # all other pages will be handled by the router but must be registered to also show the SPA index page`
the local image file's uri  is  handled by the router.
so image which is from the internet is shown correctly.

**Comment by python-and-fiction** [comment]
same as #2011

**Comment by atticus-lv** [comment]
add statics file seem not work for me, but adding all reroute with `ui.page` works

**Comment by falkoschindler** [comment]
Hi @atticus-lv,

This is very confusing, but I think I understand what is happening:
The `@ui.page('/{_:path}')` decorator creates an endpoint that matches all routes including static images paths. But since the router can't serve images, the image isn't displayed.

As a workaround, you can limit the route to non-path strings (i.e. strings not containing a slash `/`): `@ui.page('/{_}')`.

I'll close this issue, because it isn't really a bug but a limitation of our small "single page app" example.
A much more powerful API is in the making: PR #2811.
