### ISSUE TITLE
ui.download N times when you open N tabs

### ISSUE THREAD

**Issue by wangduanduan** [zauberzeug/nicegui#3240]
### Description

if i open **four** http://127.0.0.1:8080/ pages,  when i click  the download button of the first page, i get four download confirm dialog。

```python
from nicegui import ui

ui.button("Download", on_click=lambda: ui.download(b"Hello World", "hello.txt"))

ui.run()
````

if i only keep one page, the download become normal

# expect to happen
i click the button one time,  i should get one download confirm,  not four.

**Comment by rodja** [comment]
Have you seen https://github.com/zauberzeug/nicegui/wiki/FAQs#why-is-everyone-seeing-the-same-content?
