### ISSUE TITLE
Javascript libraries not discovered in 1.4.27

### ISSUE THREAD

**Issue by artreven** [zauberzeug/nicegui#3266]
### Description

Hi. I have recently updated NiceGUI to 1.4.27 (I believe from 1.4.26, but I am not 100% sure). This update broke some functionality, after an investigation I have found the problem: `libraries` from my custom JS component are not loaded in certain scenario. Namely, if the component, that requires those libraries, is only loaded on request -- inside `on_click` of a button.

The minimal example requires a bit of structure, so I zipped it, but here I post the code from the `main.py` that illustrates the issue:

```py
from nicegui import ui

from elements.draggable import Draggable  # this is my custom component, see .zip


async def make_dialog():
    with ui.dialog() as d, ui.card() as c:
        dd = Draggable(['Clicks', 'smth1', 'smth2'])
        ui.button('Save', on_click=lambda: ui.notify('success', color='positive')).props('small outline')
    return d


async def show_dialog():
    dialog = await make_dialog()
    return await dialog


ui.markdown('''
#### Try the new click counter!

Click to increment its value.
''')

ui.button('click to open draggable dialog', on_click=show_dialog)

# IF YOU UNCOMMENT 2 LINES BELOW THEN EVERYTHING WORKS!
# with ui.card():
#     dd = Draggable(['Clicks', 'smth1', 'smth2'])

ui.run(port=5555)

```

A workaround is not complex, but not elegant.

[js_libs_issue.zip](https://github.com/user-attachments/files/15935869/js_libs_issue.zip)

**Comment by falkoschindler** [comment]
Hi @artreven,

I just tried to reproduce your problem. But I can't get it to work with 1.4.26 or even 1.4.10. Do you have an idea what else you might have changed?

**Comment by artreven** [comment]
hi @falkoschindler thanks a lot for looking into this. I tried it on my end and I confirm your findings, sorry for incorrect description.
Now i tried to investigate what really happened and I fail so far. Unfortunately, I am going on vacation soon and I cannot devote more time to this now. Therefore, I suggest closing this ticket. Yet, I will keep this issue on my mind and once I encounter anything similar or once I just have more time, I will try to investigate in further details and, if successful, reopen this ticket.
Sorry again for bothering.
