### ISSUE TITLE
RuntimeError: app.storage.user needs a storage_secret passed in ui.run()

### ISSUE THREAD

**Issue by bin-san** [zauberzeug/nicegui#3273]
### Description

Though I have `ui.run(host=host, port=port, show=False, storage_secret='bin-san-2002', favicon='🎉')`

**Comment by python-and-fiction** [comment]
Need more details, I can't reproduce it.

**Comment by bin-san** [comment]
Steps to reproduce:
1. get the code at: [https://gist.github.com/bin-san/ede5d876aba43eff290a776915659345](url)
2. run the file
3. open webpage localhost:8999 to see 
![Screenshot from 2024-06-24 16-33-56](https://github.com/zauberzeug/nicegui/assets/75874218/4fd67399-ac1d-4291-be62-273ad70680e7)

4. Click the floating action button on the bottom right
![Screenshot from 2024-06-24 16-34-21](https://github.com/zauberzeug/nicegui/assets/75874218/7eac384b-c5af-4a83-bc5f-ef52cd59de05)

5. Click the create fab-action
![Screenshot from 2024-06-24 16-34-51](https://github.com/zauberzeug/nicegui/assets/75874218/eb2cb056-e69f-4adf-b34c-38bee68f99ac)

6. Enter some dummy string
![Screenshot from 2024-06-24 16-35-00](https://github.com/zauberzeug/nicegui/assets/75874218/cfe139d5-9e0d-46b2-88d3-7e53f7184665)

7. Click on the indigo color arrow button of the newly created card `->`
![Screenshot from 2024-06-24 16-35-27](https://github.com/zauberzeug/nicegui/assets/75874218/56a29793-08f5-4773-896b-2ae547062d6b)

8. Now check your log: 
> NiceGUI ready to go on http://localhost:8999, http://172.17.0.1:8999, and http://192.168.1.2:8999
app.storage.user needs a storage_secret passed in ui.run()
Traceback (most recent call last):
  File "/home/point/PycharmProjects/PartyRooms/.venv/lib/python3.12/site-packages/nicegui/background_tasks.py", line 52, in _handle_task_result
    task.result()
  File "/home/point/PycharmProjects/PartyRooms/.venv/lib/python3.12/site-packages/nicegui/binding.py", line 39, in refresh_loop
    _refresh_step()
  File "/home/point/PycharmProjects/PartyRooms/.venv/lib/python3.12/site-packages/nicegui/binding.py", line 49, in _refresh_step
    value = transform(_get_attribute(source_obj, source_name))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/point/PycharmProjects/PartyRooms/main.py", line 444, in monitor_cmd
    if not app.storage.user.get('last-command'):
           ^^^^^^^^^^^^^^^^
  File "/home/point/PycharmProjects/PartyRooms/.venv/lib/python3.12/site-packages/nicegui/storage.py", line 143, in user
    raise RuntimeError('app.storage.user needs a storage_secret passed in ui.run()')
RuntimeError: app.storage.user needs a storage_secret passed in ui.run()

**Comment by falkoschindler** [comment]
Hi @bin-san, this does indeed look like a bug. At least the error message doesn't make too much sense if the `storage_secret` is given in `ui.run`.

In order to help narrowing down this bug and to compare it to #2520: Could you, please, try to extract a _minimum_ reproducible code example? Thanks!
[Why is it important to provide a minimal reproducible example?](https://github.com/zauberzeug/nicegui/wiki/FAQs#why-is-it-important-to-provide-a-minimal-reproducible-example)

**Comment by bin-san** [comment]
Yes sir. I am trying to write the minimum reproducible code.

**Comment by bin-san** [comment]
```
from nicegui import ui, app

@ui.page('/')
def index():
    app.storage.user['name'] = 'San'
    def f(v):
        ui.notify(app.storage.user.get('name'))
        return v
    ui.label().bind_text_from(app.storage.user, 'name', backward=f)


ui.run(show=False, storage_secret='bin-san-2002')
```
The  problem is that the function given in backward function can not access user storage.

**Comment by falkoschindler** [comment]
Thanks a lot, @bin-san! This is very helpful.

Actually, there's another error happening because the `backward` function has no current UI context:

```
The current slot cannot be determined because the slot stack for this task is empty.
This may happen if you try to create UI from a background task.
To fix this, enter the target slot explicitly using `with container_element:`.
```

But even after fixing this problem by explicitly using the current `client`, the warning about a missing `storage_secret` remains:
```py
@ui.page('/')
def index():
    app.storage.user['name'] = 'San'
    client = ui.context.client

    def f(v):
        with client:
            ui.notify(app.storage.user.get('name'))
        return v
    ui.label().bind_text_from(app.storage.user, 'name', backward=f)
```

**Comment by python-and-fiction** [comment]
I set a print in `storage.py`,And I found `starlette.middleware.base._CachedRequest object` becomes None during first visiting page.
![image](https://github.com/zauberzeug/nicegui/assets/16256910/a87902be-2565-4938-b65a-38581786aacf)
![1719294409597](https://github.com/zauberzeug/nicegui/assets/16256910/2874aad2-5b49-4e4d-ba95-3b35575dd2dc)
Then I look it up in starlette's repository,similar question is founded:
`RuntimeError("No response returned")` in `BaseHTTPMiddleware` · Issue #2516 · encode/starlette
https://github.com/encode/starlette/issues/2516
Maybe it is helpful.Or it is a direction for others who would solve this problem.

**Comment by bin-san** [comment]
@falkoschindler Hi. Same problem accessing app.storage.user from an app.websocket
```
from nicegui import ui, app
from fastapi import WebSocket
from uuid import uuid4
from time import time_ns
def uid():
    """Generates an unique id"""
    return f'{uuid4()}-{time_ns()}'

app.add_media_file(local_file='./sample.mp4', url_path='/video')

app.storage.general['octopus'] = {}

@app.websocket('/sync_video/{video_id}')
async def sync_video(websocket:WebSocket, video_id):
    if not app.storage.general['octopus'].get(video_id):
        app.storage.general['octopus'][video_id] = {
            'subscribers': []
        }
    # app.
    with ui.context.client:
        if not app.storage.user.get('id'):
            app.storage.user['id'] = uid()
        if app.storage.user.get('subscribed') != video_id:
            app.storage.general['octopus'][video_id]['subscribers'].append(app.storage.user['id'])
            app.storage.user['subscribed'] = video_id
    await websocket.accept()
    while True:
        msg = await websocket.receive_text()
        print(f'Got message: {msg}')
        for subscriber in app.storage.general['octopus'][video_id]['subscribers']:
            if subscriber != app.storage.user['id']:
                await websocket.send_text(msg)


@ui.page('/{video_id}')
def index(video_id):
    ui.add_head_html(f'''
    <script defer>
    window.ws = new WebSocket('ws://{host}:{port}/sync_video/{video_id}')
    window.ws.onmessage = (event)=>{{
    window.display1.innerText = event.data
    }}
    </script>
    ''')
    ui.input('Enter a message').classes('w-full').props('id=input1')
    ui.button('Broadcast').on('click', js_handler='''
    (event)=>window.ws.send(input1.value)
    ''')
    ui.label().classes('w-full').props('id=display1')

host = 'localhost'
port = 8000

ui.run(host=host, port=port, show=False, storage_secret='bin-san')


```
