### ISSUE TITLE
on air not working from UK

### ISSUE THREAD

**Issue by tomjridge** [zauberzeug/nicegui#3285]
### Description

I am trying to use on-air functionality. I am based in UK (Leicester). 

I have signed up to an account, have a device-0, and a token. 

on-air does not work, either with ui.run(...,on_air=True) or ui.run(...,on_air='THETOKEN')

What happens with on_air=True (other case is similar):

1. Application starts; url is printed e.g.  https://europe.on-air.io/devices/PdhCp1QW/
2. Accessing that url, I am directed to the https://europe.on-air.io/ login page. This already seems wrong, since I expect to see the app (and expect that others can see the app).
3. If I log on, I am in my on-air account, and can see e.g. device-0. There is then no way to see my app.

It seems like the URL ...1QW/ redirects to the wrong place?

Any help appreciated!

BTW nicegui is very nice! Thanks for your work.

**Comment by rodja** [comment]
Strange. It works for us. Have you tested with a minimal application? Maybe your code is doing the redirect? Can you try to create a minimum reproducible code example? This would allow us and the community to help more efficiently. Thanks!
[Why is it important to provide a minimal reproducible example?](https://github.com/zauberzeug/nicegui/wiki/FAQs#why-is-it-important-to-provide-a-minimal-reproducible-example)

**Comment by tomjridge** [comment]
Ah! Of course. Thanks for the steer. I am using some auth middleware from the nicegui docs, which of course redirects to /login. So I guess that hosting under ...on-air.io/some/path will cause problems. Thank you very much, and apologies for the noise.
