### ISSUE TITLE
on_upload doesn't seem to be working

### ISSUE THREAD

**Issue by paulGeoghegan** [zauberzeug/nicegui#3293]
### Description

I'm trying to create a select that will create it's options based on the columns in a CSV file. This is done by using the upload component in order to get the csv however the on_upload event doesn't seem to be triggering my callback function so the select is just blank and doesn't show up. I have tried a few different things such as adding the if statements to check if the values are actually there and I have added a print inside the handle_file_upload function but it never seemed to run.

```py
from nicegui import app, events, ui
from utils.languages_file import languages
import pandas as pd

project_name=None
project_text= None

app.native.window_args["resizable"]=False
app.native.start_args["debug"]=True


@ui.page("/create_project")
def create_project():
    ui.button("Go Back",on_click=ui.navigate.back)
    ui.label("Create New Project")
    ui.label("Upload your Spreadsheet.")
    ui.upload(on_upload=handle_file_upload)
    ui.link("Continue",project_information)


def handle_file_upload(e:events.UploadEventArguments):
    global project_name, project_text
    project_name=e.name
    project_text=pd.DataFrame(e.content.read().decode("utf-8").splitlines())


@ui.page("/project_information")
def project_information():
    global project_name, project_text
    ui.label("Project Information")            
    if project_name is not None:
        ui.input(label="What is the language code for your language?",value=project_name)
    if project_text is not None:
        ui.select(label="What column contains the name of the character?",options=project_text.columns.tolist())


ui.label("What do you want to do?")
ui.link("Create a New Project",create_project)


ui.run(native=True,window_size=(400,300),fullscreen=False,title="example")
```

**Comment by falkoschindler** [comment]
Hi @paulGeoghegan,

I tried running your code, replaced reading the file content with some dummy data because I have no such spreadsheet, but could reproduce any problem.
Can you, please, try to reduce the code to its bare minimum? Are you sure the file isn't uploaded? Or is there a problem with extracting its content?

**Comment by paulGeoghegan** [comment]
@falkoschindler as I mentioned the handle_file_upload function doesn't run at all as far as I can tell. I tried adding a print statement to the start of it to check if it was the data that was the problem but even the print didn't run.

**Comment by falkoschindler** [comment]
Ok, then my question would be, does it work without native mode, without placing `ui.upload` on a subpage, with a minimum example from https://nicegui.io/documentation/upload#file_upload, on different browsers, ...?

**Comment by python-and-fiction** [comment]
It is not a bug,just missing `auto_upload=True`.
You shoud click upload button after file has been uploaded completely.
```python3
from nicegui import events, ui

def handle_upload(e: events.UploadEventArguments):
    text = e.content.read().decode('utf-8')
    print(text)
with ui.card():
    ui.label('no auto upload')
    ui.upload(on_upload=handle_upload) 
with ui.card():
    ui.label('with auto upload')
    ui.upload(on_upload=handle_upload,auto_upload=True)
ui.run()
```
![image](https://github.com/zauberzeug/nicegui/assets/16256910/67e3a45c-a6d8-411d-a648-6e0da6f1a569)

**Comment by 1945083536** [comment]
> Ok, then my question would be, does it work without native mode, without placing `ui.upload` on a subpage, with a minimum example from https://nicegui.io/documentation/upload#file_upload, on different browsers, ...?

Hi, I tried the code in document shown below. And the handle_upload isn't be invoked. Could you please take a try?

`from nicegui import events, ui

with ui.dialog().props('full-width') as dialog:
    with ui.card():
        content = ui.markdown()

def handle_upload(e: events.UploadEventArguments):
    text = e.content.read().decode('utf-8')
    content.set_content(text)
    dialog.open()

ui.upload(on_upload=handle_upload).props('accept=.md').classes('max-w-full')

ui.run()`

Thanks

**Comment by python-and-fiction** [comment]
> > Ok, then my question would be, does it work without native mode, without placing `ui.upload` on a subpage, with a minimum example from https://nicegui.io/documentation/upload#file_upload, on different browsers, ...?
> 
> Hi, I tried the code in document shown below. And the handle_upload isn't be invoked. Could you please take a try?
> 
> `from nicegui import events, ui
> 
> with ui.dialog().props('full-width') as dialog: with ui.card(): content = ui.markdown()
> 
> def handle_upload(e: events.UploadEventArguments): text = e.content.read().decode('utf-8') content.set_content(text) dialog.open()
> 
> ui.upload(on_upload=handle_upload).props('accept=.md').classes('max-w-full')
> 
> ui.run()`
> 
> Thanks

what is your steps?

**Comment by falkoschindler** [comment]
This code works for me. How large is the Markdown file?

**Comment by python-and-fiction** [comment]
@falkoschindler  I think they didn't click upload button after adding file whitout `auto_upload=True`.

**Comment by paulGeoghegan** [comment]
@python-and-fiction was correct adding auto_upload=True fixed it.

**Comment by 1945083536** [comment]
> This code works for me. How large is the Markdown file?

The handle_upload will not be invoked. "python-and-fiction" is right, it must add auto_upload=True.

My question resolved. Thanks
