### ISSUE TITLE
Connection lost within 3 seconds when app is deployed on kubernetes

### ISSUE THREAD

**Issue by pingretispec** [zauberzeug/nicegui#3298]
### Description

I have an app that utilizes a ui.timer on the main page to perform rolling updates. The app runs fluently on local computer and a normal ECS set-up. However, I was not able to keep the app's connection alive when it is deployed on kubernetes. It seems like the client's connection to the server is lost when the next health check handshake is done. Has anyone observed this issue?

**Comment by rodja** [comment]
It may be something like in #2891 and #1449. You need to make sure the website connects back to the right server. Either by running only one server in the first place. Or activate sticky sessions. If that is not possible, you might find other workarounds like we did for fly.io (see #3212).
