### ISSUE TITLE
The ticking strategy for trees doesn't work

### ISSUE THREAD

**Issue by thingumajig** [zauberzeug/nicegui#331]
I tried all three ticking strategies for the tree, the boxes are displayed, but the checkmark does not appear.
Code:
```py
ui.tree([
    {'id': 'numbers', 'children': [{'id': '1'}, {'id': '2'}]},
    {'id': 'letters', 'children': [{'id': 'A'}, {'id': 'B'}]},
], label_key='id').props('tick-strategy=strict')
```
Maybe there's a workaround?
Thanks

**Comment by falkoschindler** [comment]
Thanks for bringing this up!
It looks like `ui.tree` didn't implement tick events at all. But I think I could fix it in [c427aaa](https://github.com/zauberzeug/nicegui/commit/c427aaab92cddfa0870eb523cb8179be37bc9869) and we can squeeze it into the 1.1.5 release this afternoon.
