### ISSUE TITLE
TypeError: Client.__init__() missing 1 required keyword-only argument: 'request'

### ISSUE THREAD

**Issue by TeeFiX42** [zauberzeug/nicegui#3314]
### Description

Since yesterday, I suddenly get next Error in my code (that worked before):
```
TypeError: Client.__init__() missing 1 required keyword-only argument: 'request'
```

due to a missing default value (=None):
```py
class Client:
    def __init__(self, page: page, *, request: Optional[Request]) -> None:
```

Shouldn't that be:
```py
class Client:
    def __init__(self, page: page, *, request: Optional[Request] = None) -> None:
```

**Comment by falkoschindler** [comment]
Hi @TeeFiX42,

It looks like you're instantiating `Client` instances yourself. Is that correct?

In version 1.4.28 we added the `request` argument to the `Client` class. But since `Client` is meant to be used internally only, it shouldn't cause any problems. 🤔

**Comment by TeeFiX42** [comment]
Hi,
It's not clear to me that this is for interal use only.
We use it like described in [(https://github.com/zauberzeug/nicegui/discussions/883)]
below is part of our code:
`@app.exception_handler(SnipSreException)
async def _internal_server_error(request: Request, exception: Exception) -> Response:
    with Client(page("")) as client:
        with theme.frame("Homepage"):
            error_content(500, exception)
    return client.build_response(request, 500)`
Can you suggest another method to create custom error pages?

**Comment by falkoschindler** [comment]
I see. Try passing the `request` object to `Client`:
```py
    with Client(page(""), request=request) as client:
```
