### ISSUE TITLE
Tooltip 

### ISSUE THREAD

**Issue by FSchmidt-FUNKE** [zauberzeug/nicegui#3322]
### Description
When attempting to add a delay to tooltips using the `props('delay=1000')` method, the delay is not being applied as expected. This appears to be an inconsistency between NiceGUI's tooltip implementation and Quasar's native tooltip behavior.

### Steps to Reproduce
1. Create a NiceGUI element with a tooltip
2. Add the `props('delay=1000')` (or any other delay value) to the tooltip
3. Hover over the element

### Expected Behavior
The tooltip should appear after the specified delay (e.g., 1000ms) as it is in the [Quasar example](https://quasar.dev/vue-components/tooltip#customize)

### Actual Behavior
The tooltip appears immediately, without any noticeable delay.

### Code Example
```python
ui.button('Hover me').tooltip('This should be delayed').props('delay="1000"')
ui.button('Hover me').tooltip('This should be delayed').props('delay=1000')
```

Thank you for your attention to this issue. Let me know if you need any additional information or clarification.

**Comment by falkoschindler** [comment]
Hi @FSchmidt-FUNKE,

When you are using the builder-pattern method `.tooltip()`, the next method `.props()` also refers to the `ui.button` element. But you can nest a `ui.tooltip` element with its own props like this:
```py
with ui.button('Hover me'):
    ui.tooltip('This should be delayed').props('delay=1000')
```

**Comment by FSchmidt-FUNKE** [comment]
Hi @falkoschindler,

thanks for the reply!
I just assumed the props behind the tooltip will be towards the tooltip object. Maybe it might be helpful to add an example in the docs of the Tooltip on how to change the props.

**Comment by rodja** [comment]
@FSchmidt-FUNKE adding this as a demo is an excellent suggestion. Would you like to create a small pull request. We look forward to make you an official contributor.

**Comment by FSchmidt-FUNKE** [comment]
I created a pull request.
Also added a demo on how to add a tooltip for elements like ui.upload
