### ISSUE TITLE
3D objects get stuck in scene when reloading.

### ISSUE THREAD

**Issue by afullerx** [zauberzeug/nicegui#3339]
### Description

To reproduce, run this example (adapted from https://github.com/zauberzeug/nicegui/discussions/1269#discussioncomment-6573818).  Reload repeatedly and you'll observe red spheres are often stranded in the scene.
```python
import numpy as np
from nicegui import ui

scene = ui.scene()

def update_points(points: np.ndarray):
    for obj in list(scene.objects.values()):
        if obj.name == 'point':
            obj.delete()

    with scene:
        for point in points:
            scene.sphere(0.05).material('red').move(*point).with_name('point')

ui.timer(.1, lambda: update_points(np.random.randn(10, 3)))
ui.run()
```
I think this is likely the same issue as in #659. While it was solved for `ui.page`, it still remains an issue for the auto-index page. If I'm right about the cause, I think it could easily be fixed by moving the `is_initialized` flag from that fix to the JavaScript side. I'll submit a PR once I'm done with the current one I'm working on.

**Comment by falkoschindler** [comment]
Oh wow, thanks for reporting this issue, @afullerx!
We're looking forward to reviewing the fix you mentioned. But focussing on one PR at a time sounds totally reasonable. 👍🏻
