### ISSUE TITLE
Integration on nicegui with data visualisation libraries

### ISSUE THREAD

**Issue by keepexploring** [zauberzeug/nicegui#335]
Is it possible to integrate nicegui with libraries such as bokeh (https://bokeh.org), holoviews, or even panel (https://panel.holoviz.org)

For example, it would amazing if you could use all of the widgets in panel in nicegui so that the two integrate cleanly. This would allow you to easily integrate data science etc into nicegui and also build interactive data dashboards as part of a nicegui site.

I'm not sure it's necessary to integrate with everything, but having something that builds in an existing mature data visualisation tool/widgets would be really valuable.

**Comment by rodja** [comment]
Bokeh and Panel are quite different in their approach and should be discussed seperately. I created the discussion ideas #359 (bokeh) and #360 (panel). Please help us implement these.
