### ISSUE TITLE
`True (error) or False (no error)` in `Input validation` should be `True (no error) or False (error)`

### ISSUE THREAD

**Issue by python-and-fiction** [zauberzeug/nicegui#3350]
### Description
In https://nicegui.io/documentation/input#input_validation,
`True (error) or False (no error)` in `Input validation` should be `True (no error) or False (error)`
According to source code of `validation_element.py`,validation rules is `{'error message':'validation rule'}`,'validation rule' returns True if the value is valid.So,the right is  `True (no error) or False (error)`.

**Comment by falkoschindler** [comment]
Thanks for spotting this, @python-and-fiction!
