### ISSUE TITLE
Add support for input validation rules

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#336]
[As noticed by @fuxionline](https://github.com/zauberzeug/nicegui/issues/151#issuecomment-1413730259) the possibility of defining validation rules for input elements is gone since we left JustPy behind in version 1.0. We should try to bring back this undocumented but useful feature.

**Comment by falkoschindler** [comment]
A workaround might be server-side input validation:

```py
def handle_change(event):
    if not event.value:
        event.sender.props('error error-message="This field is required"')
    elif len(event.value) < 3:
        event.sender.props('error error-message="This field must be at least 3 characters long"')
    else:
        event.sender.props(remove='error')

ui.input('Input', on_change=handle_change)
```

This might even be a solution for implementing an official "validation" feature without the need for passing a JavaScript callback to the client.

**Comment by falkoschindler** [comment]
I pushed a first implementation of server-side input validation onto branch [validation](https://github.com/zauberzeug/nicegui/tree/validation).
My main concern is _when_ to do the validation. Currently it is done on value change, i.e. every keystroke. But maybe we should throttle it or postpone it to a "enter" or "blur" event. Should we make the _event_ for the validation configurable?

**Comment by falkoschindler** [comment]
Demo code:

```py
ui.input('Name', validation={
    'This field is required': lambda value: not value,
    'This field must be at least 3 characters long': lambda value: len(value) < 3,
})

ui.number('Age', validation={
    'This field is required': lambda value: value is None,
    'This field must be at least 3': lambda value: value < 3,
})
```

**Comment by falkoschindler** [comment]
Oh, we probably should invert the lambdas, i.e. describing the positive case.
At least that's how Quasar is doing it: https://quasar.dev/vue-components/input#validation

**Comment by rodja** [comment]
Great! Merged into main.
