### ISSUE TITLE
[WinError 10013] at start  (Problem binding to port 80?)

### ISSUE THREAD

**Issue by ECOM-Engineering** [zauberzeug/nicegui#3360]
### Description

Problem under Windows11
Cannot run a nicegui script: **ui.run()** leads to system message [WinError 10013]

Is there a solution?

**Comment by python-and-fiction** [comment]
Try another port may succed?

**Comment by falkoschindler** [comment]
Hi @ECOM-Engineering,
The default port is 8080, so there shouldn't be a problem with port 80.
Maybe there's another app running on port 8080?
https://stackoverflow.com/questions/48198/how-do-i-find-out-which-process-is-listening-on-a-tcp-or-udp-port-on-windows

**Comment by ECOM-Engineering** [comment]
Hi 
Cannot kill this process:
**PS F:\kdrive\projekte\Python GUI Evaluationen> Get-Process -Id (Get-NetTCPConnection -LocalPort 8080).OwningProcess**

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    549      48    15844      15576             13152   0 ApplicationWebServer

**PS F:\kdrive\projekte\Python GUI Evaluationen> taskkill /PID 13152**
FEHLER: Der Prozess mit PID 13152 konnte nicht beendet werden.
Ursache: Zugriff verweigert

Can I change the default port for niceGUI?

**Comment by ECOM-Engineering** [comment]
> Try another port may succeed?
> 
> ```python
> ui.run(port=native.find_open_port(80))
> ```

This gets error message:
NameError: name 'native' is not defined

**Comment by falkoschindler** [comment]
Yes, you can change the port like this: `ui.run(port=8081)`.

For using `native.find_open_port()` you'd need to import it like this: `from nicegui import native`.
