### ISSUE TITLE
Update `fastapi` to 0.111.1

### ISSUE THREAD

**Issue by pierrecdn** [zauberzeug/nicegui#3384]
### Description

In https://github.com/zauberzeug/nicegui/commit/40b16813d3d634538f0e514be440d196234c6fe3, I noticed that the fastapi version has been constrained quite a lot.

0.111.0 and 0.111.1 have been released since, and I'm interested by several patches they bring.

The question being why did this hard enforcement was done. Is there a sort of QA process that somehow happens to check if minor releases are breaking stuff or audit the changelog?

**Comment by rodja** [comment]
Hi @pierrecdn. This looks like a duplicate to https://github.com/zauberzeug/nicegui/discussions/2992. We hope to release a 2.0 with latest FastAPI in August.

**Comment by pierrecdn** [comment]
Oh, indeed, didn't see that one, sorry.
