### ISSUE TITLE
Aggrid upgrade. v30 to v32

### ISSUE THREAD

**Issue by ruidiasbraga** [zauberzeug/nicegui#3393]
### Description

Hi, 

after some unexpected behaviours from what I see on the Aggrid documentation and what I experienced in nicegui, I found out that the version difference (v30) could be the problem.

nicegui is using v30 and the latest is v32 of aggrid. are you considering and upgrade?

**Comment by python-and-fiction** [comment]
nicegui 2.0 will upgrade dependency。

**Comment by falkoschindler** [comment]
Yes, we're working on version 2.0 which will update Python dependencies like FastAPI as well as JavaScript libraries like AG Grid. To avoid breaking changes, we need to wait for such a major update. We hope to get it out by the end of August.

**Comment by ruidiasbraga** [comment]
Great news! Thanks for the answer :)

**Comment by gaby** [comment]
@falkoschindler Probably worth adding a dependabot.yml to track dependencies.

**Comment by falkoschindler** [comment]
@gaby Sounds interesting. So far we don't have experience with dependabot.yml. Would you like to create a new feature request or pull request, also explaining benefits over using Dependabot without such a config file? Thanks!

**Comment by gaby** [comment]
@falkoschindler Using the `dependabot.yml` will enable the feature on the repo, you can set a schedule and it will auto-create a Pull Request any time a dependency has an update. It supports python, gh actions, docker, javascript, etc. I will do a PR and we can discuss schedule there.
