### ISSUE TITLE
Quasar components in tables with Python loops

### ISSUE THREAD

**Issue by maxnix** [zauberzeug/nicegui#3397]
### Description

Hello everyone,

I have written this sample code to present my issue: I need to insert Quasar components into a table because NiceGui does not support elements such as buttons or badges within table cells. However, I also need some values to be dynamically inserted through a Python loop, and it seems that using a mix of Python and JavaScript (i.e., Quasar) results in the Python loop being executed first and then rendered by JavaScript. Consequently, the outcome was that all rows of the table displayed only the last value of from the Python "users" list.

I put also a picture of the wrong rendered code:
![NiceGUI](https://github.com/user-attachments/assets/128ea123-c83b-42f7-beac-e813b186d0c4)

Here the code:
```py
from nicegui import ui

columns = [
    {'name': 'role', 'label': 'Role', 'field': 'role'},
    {'name': 'name', 'label': 'Name', 'field': 'name'},
]

rows = [
    {'role': 'director'},
    {'role': 'secretary'},
    {'role': 'employee'}
]

users = [{'name':'mario'}, {'name':'gianni'}, {'name':'franco'}]

table = ui.table(columns=columns, rows=rows, row_key='role')

# Assign the correct names to the rows and create slots dynamically
for row in users:
    table.add_slot('body-cell-name', f'''
        <q-td>
            <q-badge>
                {row['name']}
            </q-badge>
        </q-td>
    ''')
    table.update()
ui.run()
```

**Comment by python-and-fiction** [comment]
The slot is like a template.
You should do it like this:
```python3
from nicegui import ui

columns = [
    {'name': 'role', 'label': 'Role', 'field': 'role'},
    {'name': 'name', 'label': 'Name', 'field': 'name'},
]

rows = [
    {'role': 'director'},
    {'role': 'secretary'},
    {'role': 'employee'}
]

users = [{'name':'mario'}, {'name':'gianni'},{'name':'franco'}]

table = ui.table(columns=columns, rows=rows, row_key='role')
for row in range(len(users)):
    rows[row].update(users[row])
table.add_slot('body-cell-name', '''
        <q-td>
            <q-badge v-show="props.value">
               {{ props.value }}
            </q-badge>
        </q-td>
    ''')

ui.run()
```
![image](https://github.com/user-attachments/assets/6786adbb-1fe0-4d86-b5d9-92f31b73d3a1)
