### ISSUE TITLE
Packed exe file gave "internal server error" when ran

### ISSUE THREAD

**Issue by STCJustin** [zauberzeug/nicegui#3399]
### Description

Below are the screenshot of the error, the packing and the command generated from the pytoexe tool, when running the exe nothing but the black window with the error comes up. Any ideas what i am doing wrong? Thanks in advance.
![Screenshot_2024-07-26_145200](https://github.com/user-attachments/assets/8bc0340c-84f4-4408-a0ff-fa49ba525449)
![Screenshot_2024-07-26_145132](https://github.com/user-attachments/assets/342d0033-eaf5-4695-a933-bc0abd69065f)
`pyinstaller --noconfirm --onedir --windowed --name "Test" --add-data "C:\Users\user\OneDrive桌面\Progress_Display\AF.jpg;." --add-data "C:\Users\user\OneDrive桌面\Progress_Display\AV.jpg;." --add-data "C:\Users\user\OneDrive桌面\Progress_Display\EN.jpg;." --add-data "C:\Users\user\OneDrive桌面\Progress_Display\GFS_logo.png;." --add-data "C:\Users\user\OneDrive桌面\Progress_Display\oop.jpg;." --add-data "C:\Users\user\OneDrive桌面\Progress_Display\uams.jpg;." --add-data "C:\Users\user\OneDrive桌面\Progress_Display\static;static/" --add-data "C:\Users\user\OneDrive桌面\Progress_Display\sad_face.svg;nicegui/static"  "C:\Users\user\OneDrive桌面\Progress_Display\test.py"`

**Comment by python-and-fiction** [comment]
Is it same to simple example?

**Comment by falkoschindler** [comment]
Hi @STCJustin,

The generated pyinstaller command seems to be missing the path to NiceGUI.
As described in the [documentation](https://nicegui.io/documentation/section_configuration_deployment#package_for_installation), we recommend using `nicegui-pack`. Either way you can use it to generate the pyinstaller command:
```bash
nicegui-pack --dry-run test.py
```
