### ISSUE TITLE
The pages of the website can only be accessed by one person, and the other person is currently under the control of another person after accessing it

### ISSUE THREAD

**Issue by sonicno1** [zauberzeug/nicegui#3416]
### Description

1. user1 open http://1.2.3.4 
2. user1 click  button , The button can be clicked normally
3. user2 open http://1.2.3.4 
4. user1 Clicking the button is unresponsive
5. It shows up in User2 

It should actually be displayed on which page the user clicks on

**Comment by python-and-fiction** [comment]
Please show your code.

**Comment by sonicno1** [comment]
@ui.page('/blank/highLightTitle')
def test_aaa():
    pass

@ui.page('/blank/lowLightTitle')
def test_bbb():
    pass

1.When /blank/highLightTitle is opened in a tab, it is displayed normally
2.At this time, /blank/lowLightTitle is opened in tab 2, and when the button in tab 1 is clicked, it is displayed on the page in tab 2

**Comment by python-and-fiction** [comment]
Please show your full executable code.Where is button?
Why is it important to provide a minimal reproducible example?
https://github.com/zauberzeug/nicegui/wiki/FAQs#why-is-it-important-to-provide-a-minimal-reproducible-example

**Comment by python-and-fiction** [comment]
You'd better create a discussion if you don't make sure of a bug.

**Comment by sonicno1** [comment]
button on page 2
![image](https://github.com/user-attachments/assets/ba3a4d87-fe4a-465c-8577-a8f26101a316)

This is the trigger button in page 2 and it will pop up the conversation button above
![image](https://github.com/user-attachments/assets/14cc9f6c-6a7b-42de-bece-766da9667200)

button on page 1
![image](https://github.com/user-attachments/assets/69eb68ff-e05e-4e85-b018-b928b3996060)


When page 1 is refreshed, it should normally be displayed on page 2 when the button is clicked on page 2, but it is displayed on page 1

**Comment by python-and-fiction** [comment]
如果需要解决问题，请提供能够表现出问题的最简化的、可以直接复制执行的代码。不要使用原始的程序代码和不完整的程序代码，不要浪费每一位参与者的每一次提问。&nbsp;


我心飞翔
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月31日(星期三) 晚上6:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zauberzeug/nicegui] The pages of the website can only be accessed by one person, and the other person is currently under the control of another person after accessing it (Issue #3416)














 
button on page 2
 image.png (view on web)
 
This is the trigger button in page 2 and it will pop up the conversation button above
 image.png (view on web)
 
button on page 1
 image.png (view on web)
 
When page 1 is refreshed, it should normally be displayed on page 2 when the button is clicked on page 2, but it is displayed on page 1

**Comment by python-and-fiction** [comment]
Why is it important to provide a minimal reproducible example?
https://github.com/zauberzeug/nicegui/wiki/FAQs#why-is-it-important-to-provide-a-minimal-reproducible-example

**Comment by sonicno1** [comment]
I don't know what's wrong, all pages are the same, because I used the account password login function, I don't know if it's caused by this.

The same page, open in two tab pages, if you click on all functions on the first page after the second page is refreshed, such as pop-ups, it will be displayed on the second page

**Comment by python-and-fiction** [comment]
If you can't prove a bug by providing  a minimal reproducible example,you should start a discussion first.

**Comment by sonicno1** [comment]
On the left is the first page, and on the right is the second page

https://github.com/user-attachments/assets/95ab5566-0f46-424d-b9f5-0050c704dbfc

**Comment by sonicno1** [comment]
After the second page is refreshed, click the button on the first page and it will be displayed on the second page

**Comment by python-and-fiction** [comment]
If you can't prove a bug by providing  a minimal reproducible example,you should start a discussion first.
It is usually your bug but not nicegui's.

**Comment by python-and-fiction** [comment]
> After the second page is refreshed, click the button on the first page and it will be displayed on the second page

Where is your bug?I can't see it.

**Comment by sonicno1** [comment]
I click the button on the first page, it shouldn't show on the first page?

**Comment by sonicno1** [comment]
For example, if User 1 opens the page on the 10.0.0.1 client browser, if User 2 opens the page on the 10.0.0.5 client browser, then when User 1 clicks the button on the page, it will be displayed on the client of User 2, do you think this is normal?

**Comment by python-and-fiction** [comment]
So what is your code?Maybe it is your bug,not nicegui's.

**Comment by python-and-fiction** [comment]
Make sure it is really an issue (see [FAQs](https://github.com/zauberzeug/nicegui/wiki/FAQs)).
A lot of people will read your message.
Make it worth their time.

What are you trying to do?
1. If possible, give a [minimal reproducible code example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).
2. Put source code in [fenced code blocks with syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting).
3. What do you expect to happen?
4. What happens instead?

**Comment by sonicno1** [comment]
from nicegui import ui, app

from fastapi import Request
from fastapi.responses import RedirectResponse
from starlette.middleware.sessions import SessionMiddleware

def dialogtest():
    dialog1.clear()
    with dialog1, ui.card().classes('absolute-center items-center'):
        ui.label("")
        with ui.row():
            ui.button("btn1", on_click=lambda: dialog1.submit('Yes'))
            ui.button("btn2", on_click=lambda: dialog1.submit('No'))
    dialog1.open()
    
@ui.page("/")
async def index(request: Request):
    global dialog1
    with ui.column():
        with ui.dialog() as dialog1, ui.card().classes('w-32 h-32 absolute-center items-center'):
            with ui.row():
                ui.button('Yes', on_click=lambda: dialog1.submit('Yes'))
                ui.button('No', on_click=lambda: dialog1.submit('No'))
        
        async def open_dialog():
            dialogtest()
            result = await dialog1
            if result == "Yes" :
                print("test")
            elif result == "No":
                print("test")

        navigation = ui.row()
        with navigation:
            ui.button('TestBtn', on_click=open_dialog, color='purple')
            
ui.run(port=80, favicon='', dark=True, reload=False)

**Comment by python-and-fiction** [comment]
It's not a bug of nicegui.It's you explosure `dialog1` to global,that makes the `dialog1` in the newest client page controled by former client page.
This is right:
```python3
from nicegui import ui
def dialogtest(dialog1):
        dialog1.clear()
        with dialog1, ui.card().classes('absolute-center items-center'):
            ui.label("")
            with ui.row():
                ui.button("yes", on_click=lambda: dialog1.submit('Yes'))
                ui.button("no", on_click=lambda: dialog1.submit('No'))
        dialog1.open()

@ui.page("/")
async def index():
    with ui.column():
        with ui.dialog() as dialog1, ui.card().classes('w-32 h-32 absolute-center items-center'):
            with ui.row():
                ui.button('Yes', on_click=lambda: dialog1.submit('Yes'))
                ui.button('No', on_click=lambda: dialog1.submit('No'))
        
        async def open_dialog():
            dialogtest(dialog1)
            result = await dialog1
            if result == "Yes" :
                print("yes")
            elif result == "No":
                print("no")

        navigation = ui.row()
        with navigation:
            ui.button('TestBtn', on_click=open_dialog, color='purple')
            
ui.run(port=80, favicon='', dark=True, reload=False)      
```

**Comment by sonicno1** [comment]
Thank you very much for your help @python-and-fiction ^_^

**Comment by python-and-fiction** [comment]
@sonicno1 
```talk is cheap, show me the code```
The clear code can save a lot of time for everyone.
And create a discussion plz if you are not sure that it is a bug of nicegui.
