### ISSUE TITLE
niceGUI + Echart    Pie charts or bar charts cannot be categorized by clicking Category

### ISSUE THREAD

**Issue by zhangguolin333** [zauberzeug/nicegui#3421]
### Description

from nicegui import ui
import json
import math

def create_new_page(page_name):
    @ui.page(page_name)
    def page():
        ui.label(f'You are on page: {page_name}')
        ui.button('Back to Chart', on_click=lambda: ui.open('/'))

pie_data = [
    {"value": 1048, "name": "Category A"},
    {"value": 735, "name": "Category B"},
    {"value": 580, "name": "Category C"},
    {"value": 484, "name": "Category D"},
    {"value": 300, "name": "Category E"}
]

pie_chart_options = {
    "title": {
        "text": "Example Pie Chart",
        "left": "center"
    },
    "tooltip": {
        "trigger": "item"
    },
    "legend": {
        "orient": "vertical",
        "left": "left"
    },
    "series": [
        {
            "name": "Example Data",
            "type": "pie",
            "radius": "50%",
            "data": pie_data,
            "emphasis": {
                "itemStyle": {
                    "shadowBlur": 10,
                    "shadowOffsetX": 0,
                    "shadowColor": "rgba(0, 0, 0, 0.5)"
                }
            }
        }
    ]
}

for item in pie_data:
    create_new_page(f'/{item["name"].lower().replace(" ", "_")}')

@ui.page('/')
def index():
    ui.label('Interactive Pie Chart with ECharts').style('font-size: 24px; font-weight: bold;')

    chart = ui.echart(options=pie_chart_options).style('width: 600px; height: 400px;')

    def handle_click(e):
        if hasattr(e, 'args') and isinstance(e.args, dict):
            args = e.args
            print(99999999999999, dir(args))
            x, y = args.get('offsetX', 0), args.get('offsetY', 0)
            center_x, center_y = 300, 200 
            angle = math.degrees(math.atan2(y - center_y, x - center_x))
            if angle < 0:
                angle += 360

            total = sum(item['value'] for item in pie_data)
            start_angle = 0
            for item in pie_data:
                end_angle = start_angle + (item['value'] / total * 360)
                if start_angle <= angle < end_angle:
                    category = item['name'].lower().replace(" ", "_")
                    ui.open(f'/{category}')
                    return
                start_angle = end_angle

            print(f"Click detected at ({x}, {y}), but no matching sector found.")
        else:
            print("Unexpected event structure:", e)

    chart.on('click', handle_click)

ui.run()

My original intention is to jump to the corresponding page by clicking on the pie chart data. I have tried many methods but failed to achieve this. The calculation of the proportion is not accurate (this is not what I want). There should be an accurate solution. Can anyone solve this problem for me? Thank you very much

**Comment by python-and-fiction** [comment]
Make sure it is really an issue (see [FAQs](https://github.com/zauberzeug/nicegui/wiki/FAQs)).
A lot of people will read your message.
Make it worth their time.

What are you trying to do?
1. If possible, give a [minimal reproducible code example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).
2. Put source code in [fenced code blocks with syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting).
3. What do you expect to happen?
4. What happens instead?

**Comment by python-and-fiction** [comment]
If you need a help.Please create a discussion instead of a issue.

**Comment by python-and-fiction** [comment]
There is no error.What is your expectation? What is the issue you founded?
![image](https://github.com/user-attachments/assets/4a0d211b-8a18-4137-9eef-eab4838291a6)
![image](https://github.com/user-attachments/assets/0ec6b4de-2a28-47fa-a1bb-09a0f6aea6b7)
