### ISSUE TITLE
Can't reference model object like Quasar did.

### ISSUE THREAD

**Issue by guyingbo** [zauberzeug/nicegui#3426]
### Description

Code like:
```python
ui.range(min=0, max=100, step=1).props('''label-always v-model="model" :left-label-value="model.min+'px'" ''')
```
does't work as expected ([Quasar QRange example](https://quasar.dev/vue-components/range#with-label)), I got:
`nicegui.js:151 Error while converting :left-label-value attribute to function: 
ReferenceError: model is not defined`
in javascript console.

How can I reference model object in this case?

**Comment by falkoschindler** [comment]
Hi @guyingbo,

NiceGUI doesn't use Quasar's `v-model` directives, but `model-value` and `update:modelValue`. Therefore using `v-model="model"` doesn't work ("model" is undefined).

But you can update the label in Python:

```py
ui.range(min=0, max=100, step=1, value={'min': 0, 'max': 100}).props('label-always') \
    .on_value_change(lambda e: e.sender.props(f'left-label-value={e.value["min"]}px'))
```

**Comment by guyingbo** [comment]
> Hi @guyingbo,
> 
> NiceGUI doesn't use Quasar's `v-model` directives, but `model-value` and `update:modelValue`. Therefore using `v-model="model"` doesn't work ("model" is undefined).
> 
> But you can update the label in Python:
> 
> ```python
> ui.range(min=0, max=100, step=1, value={'min': 0, 'max': 100}).props('label-always') \
>     .on_value_change(lambda e: e.sender.props(f'left-label-value={e.value["min"]}px'))
> ```

Thank you very much! This method works for me even better.
