### ISSUE TITLE
Clear method on data table does not work

### ISSUE THREAD

**Issue by markdkraft** [zauberzeug/nicegui#3429]
### Description

I am trying to re-write a table each time new data comes in. I do this by using a clear method on the ui.table. The method does not seem to function. I have had to revert to removing each row individually. Here is an example of a simple clear that does not clear the table as expected. This is on version 1.4.29 and 1.4.30.

```py
from nicegui import ui

def build_table():
    # Create a label and the table
    ui.label('Table Example')
    columns = [
                    {'name':'name', 'label':'Data Name', 'field':'name', 'sortable': True, 'align':'left'},
                    {'name':'value', 'label':'Value', 'field':'value', 'align':'left'},
                    {'name':'unit', 'label':'Units', 'field':'unit', 'align':'left'},
                ]
    rows = []
    table = ui.table(columns=columns, rows=rows, row_key='name')

    # Add some initial rows to the table
    table.add_rows({'name':'1 Entry', 'value':'Val1', 'unit':'Unit1'})
    table.add_rows({'name':'2 Entry', 'value':'Val2', 'unit':'Unit2'})
    table.add_rows({'name':'3 Entry', 'value':'Val3', 'unit':'Unit3'})

    # Define a function to clear the table
    def clear_table():
        table.clear()  # Clear all rows from the table
        table.update()

    # Create a button to clear the table
    ui.button('Clear Table', on_click=clear_table)

if __name__ == '__main__':
    build_table()
    ui.run(reload = False, host = '127.0.0.1', port = 80)
```

**Comment by rodja** [comment]
The `clear()` method is provided by Element which only clears the sub-elements which can be added via the `with` context manager: https://nicegui.io/documentation/table#table:~:text=clear()%20%2D%3E%20None,all%20child%20elements.
Have you tried setting `.rows` to an empty list?

**Comment by markdkraft** [comment]
That works perfectly! I missed that it was settable.

**Comment by falkoschindler** [comment]
Calling `table.rows.clear()` with a subsequent `table.update()` should work as well.
