### ISSUE TITLE
AttributeError: module 'secrets' has no attribute 'token_bytes'

### ISSUE THREAD

**Issue by athuler** [zauberzeug/nicegui#3435]
### Description

NiceGui will throw an `AttributeError: module 'secrets' has no attribute 'token_bytes'` upon page load whenever a file `secrets.py` file is present in the same directory.

[This](https://stackoverflow.com/questions/66846608/attributeerror-module-secrets-has-no-attribute-token-bytes) StackOverflow post is what led me to try removing the `secrets.py` file from the same directory, which made the exception go away.

There are some cases where I would like to run NiceGui with a `secrets.py` file present in the same directory, so a workaround would be greatly appreciated!

Full code below:

```python
from nicegui import app, ui
from datetime import datetime
import time
from random import randint
import threading

print("Top")

# Main Loop
@ui.refreshable
def date_ui() -> None:
	ui.label(f"hi: {randint(1,100)}")

def updateData() -> None:
	while shutDownEvent.is_set():
		print("Updating Data...")
		date_ui.refresh()
		time.sleep(1)

# Set Initial Data
date_ui()
print("Data Set")

# Set Up Shutdown Trigger
shutDownEvent = threading.Event()
shutDownEvent.set()

dataThread = threading.Thread(target = updateData, name="GUI Run")

# Start Thread
dataThread.start()
print("Starting UI")

# Join Thread
try:
	ui.run(
		show = False,
		reload = False
	)
except KeyboardInterrupt:
	print("Shutting Down...")
app.shutdown()
shutDownEvent.clear()
dataThread.join()
print("Shut Down")
```

**Comment by falkoschindler** [comment]
Hi @athuler,

As far as I can tell, this is a general problem in Python: If you add a file secret.py to your working directory, this takes precedence over the builtin "secret" module. If you add a file logging.py, your app will crash if it (or any imported library) uses the builtin "logging" module.

I think it is up to the user code to avoid this conflict. As a general rule, avoid naming your files the same as standard library modules. This applies not just to secret and logging, but to any Python standard library module (e.g., don't create files named os.py, sys.py, json.py, etc.).

> There are some cases where I would like to run NiceGui with a secrets.py file present in the same directory

That's tricky and probably beyond the scope of this forum. StackOverflow or some other Python-related platform might be a better place to ask.
