### ISSUE TITLE
Passing PUID/PGID `100` to nicegui docker results in "chown: invalid group: ‘appuser:appgroup’" errors in docker log

### ISSUE THREAD

**Issue by zan73** [zauberzeug/nicegui#3437]
### Description

As per title, getting chown: invalid group: ‘appuser:appgroup’ errors in docker log if PUID/PGID environment variables are passed to the docker.
Seems to be due to chown statements in https://github.com/zauberzeug/nicegui/blob/main/docker-entrypoint.sh

**Comment by rodja** [comment]
It works for me:

```bash
docker run --env PUID=1001 --env=PGID=1001 --rm -it zauberzeug/nicegui:1.4.35 id
```

**Comment by zan73** [comment]
I believe that the issue is caused by this statement:
if ! getent group "$PGID" >/dev/null; then
  groupadd -g "$PGID" appgroup
fi

If you pass a group id that already exists in the base image (eg. PGID=100) then the groupadd isn't executed, appgroup doesn't then exist as a group and the subsequent chown statements fail.

**Comment by rodja** [comment]
Ok. So the real issue is that you can not pass the root user/group id. Do you have an idea how to fix it? A pull request would be welcome.
