### ISSUE TITLE
Problem configuring ui.date()

### ISSUE THREAD

**Issue by bderkk** [zauberzeug/nicegui#346]
Hi! I've been trying to configure a bit the ui.date() component, for exemple changing the lenguage or the first day of the week. I've reading the Quasar documentation, but always I get an error. Could be, that is not yet implemented? 

thank you!

**Comment by rodja** [comment]
Could you provide some code as an example what you have tried?

**Comment by bderkk** [comment]
Yes of course! Here is an exemple, but I've been trying a lot of things actually. Sorry if it's a silly question...

````
ui.date(mask = 'DD-MM-YYYY' , locale='es', first_day_of_the_week=1, on_change=añadirfechas).props('range')
````

**Comment by falkoschindler** [comment]
The first day of the week can be set as a prop:

```py
ui.date(mask='DD-MM-YYYY').props("range first-day-of-week=1")
```

But I'm not sure how to set the locale. We possibly need to switch the [Quasar language pack](https://quasar.dev/options/quasar-language-packs) at runtime.

**Comment by bderkk** [comment]
Perfect! I'll keep trying, and thank you for you fast answer!

**Comment by falkoschindler** [comment]
I'll close this issue as resolved. For the broader topic of configuring the locale, I opened a new discussion #389.
