### ISSUE TITLE
Display issues when combining ui.dropdown_button and ui.badge

### ISSUE THREAD

**Issue by tjakobi** [zauberzeug/nicegui#3460]
### Description

Thank you for providing this excellent framework!

I tried to combine the  `ui.dropdown_button` and `ui.badge` elements and was expecting a behavior  similar to  that shown in the `ui.badge` documentation:  

![image](https://github.com/user-attachments/assets/02bd87dc-56e3-4ae3-ad55-50606593ddc0)
 

However, it seems the badge is instead placed onto the first item of the the ui.item list for the `ui.dropdown_button`. 

The minimal reproducible code example with a few variations of placing the badge:

Example 1:

```py
from nicegui import ui

with ui.dropdown_button("foo", auto_close=True, split=False):
    badge = ui.badge(5, color='red')

    ui.item("one", on_click=lambda: ui.notify('2'))
    ui.item("two", on_click=lambda: ui.notify('2'))
    ui.item("three", on_click=lambda: ui.notify('2'))

ui.run()

```

![image](https://github.com/user-attachments/assets/4e318f13-4144-4a1d-b30b-f350c426caba)

Example 2:

```py
from nicegui import ui

with ui.dropdown_button("foo", auto_close=True, split=False):

    # version 2

    with ui.badge(5, color='red'):

        ui.item("one", on_click=lambda: ui.notify('2'))
        ui.item("two", on_click=lambda: ui.notify('2'))
        ui.item("three", on_click=lambda: ui.notify('2'))

    ui.badge(5, color='red')

ui.run()

```

![image](https://github.com/user-attachments/assets/74fd5a92-d14d-4c69-a83a-2824d2f4d1dd)

Am I just using the badge incorrectly or is this an actual issue? 

I used nicegui v1.4.34 for the tests.

Thank you,

Tobias

**Comment by python-and-fiction** [comment]
We can emulate it with `button_group`.
```python3
from nicegui import ui

with ui.button_group():
    with ui.button():
        badge1 = ui.badge('1',color='red').props('floating')
        ui.markdown('FOO')
    with ui.button().props('dense padding="0px"'):
        with ui.dropdown_button('',auto_close=True).classes('h-full w-8').props('unelevated'):
            with ui.column():
                ui.item('Switch',on_click=lambda :badge1.set_visibility(False if badge1.visible else True))
        badge2 = ui.badge('1',color='red').props('floating')
        badge2.bind_visibility_from(badge1,'visible',lambda x:not x)

ui.run()
```
![image](https://github.com/user-attachments/assets/37f599f1-8cd9-48ae-9d76-a463ac243b70)
![image](https://github.com/user-attachments/assets/202c30ef-c430-4640-a98d-51efbcabb72d)

**Comment by falkoschindler** [comment]
Hi @tjakobi,

This is exactly how Quasar's QBtnDropdown and QBadge behave. Here is a plain Quasar example with a similar result:
```html
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/npm/quasar@2.16.8/dist/quasar.prod.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="q-app">
      <q-btn-dropdown auto-close label="foo">
        <q-badge>1</q-badge>
        <q-list>
          <q-item>
            <q-item-section>
              <q-item-label>Photos</q-item-label>
            </q-item-section>
          </q-item>
        </q-list>
      </q-btn-dropdown>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.prod.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/quasar@2.16.8/dist/quasar.umd.prod.js"></script>
    <script>
      const app = Vue.createApp({
        setup() {
          return {};
        },
      });
      app.use(Quasar);
      app.mount("#q-app");
    </script>
  </body>
</html>
```
<img width="101" alt="Screenshot 2024-08-09 at 16 22 20" src="https://github.com/user-attachments/assets/44c032a9-045b-4627-8169-866ad57e4b2b">

This is because the default slot of a dropdown button represents the dropdown menu, not the button itself.
But you can place a badge on the button of the dropdown button using the ["label" slot](https://quasar.dev/vue-components/button-dropdown):
```py
with ui.dropdown_button() as dropdown:
    ui.item('one')
    ui.item('two')
    ui.item('three')
with dropdown.add_slot('label'):
    ui.label('foo')
    ui.badge('5', color='red').props('floating')
```
<img width="113" alt="Screenshot 2024-08-09 at 16 28 25" src="https://github.com/user-attachments/assets/eb12f7b9-6769-4344-bce5-134278fa0655">

**Comment by tjakobi** [comment]
Thank you @falkoschindler  and @python-and-fiction, both solutions work flawlessly.
