### ISSUE TITLE
 self.scene.remove(line) fails with 'Line' object has no attribute 'descendants'

### ISSUE THREAD

**Issue by WolfgangFahl** [zauberzeug/nicegui#3471]
### Description

I am trying to release a new version of [nicescad](https://nicescad.bitplan.com/) and run into a regression. The toggle axes feature does not work any more.
<img width="562" alt="grafik" src="https://github.com/user-attachments/assets/afbc6c35-1e73-48d1-8043-1186d4e11720">
Switching the axes on works - but when trying to remove the lines i get:

```
'Line' object has no attribute 'descendants'
Traceback (most recent call last):
  File "/Users/wf/py-workspace/nicescad/nicescad/webserver.py", line 244, in toggle_axes
    self.axes_view.toggle_axes()
  File "/Users/wf/py-workspace/nicescad/nicescad/axes_helper.py", line 99, in toggle_axes
    self.scene.remove(line)
  File "/Users/wf/Library/Python/3.12/lib/python/site-packages/nicegui/element.py", line 575, in remove
    self.client.remove_elements(element.descendants(include_self=True))
                                ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Line' object has no attribute 'descendants'
```

what can i do about it?

**Comment by falkoschindler** [comment]
Hi @WolfgangFahl,

I guess a minimal example would look like this:
```py
with ui.scene() as scene:
    line = scene.line([0, 0, 0], [1, 1, 1])

ui.button('Remove line', on_click=lambda: scene.remove(line))
```

But `scene.remove()` expects an element, not a 3D object. It is meant to remove child elements, like in a `ui.row` or `ui.card`. Instead, you can use `delete` or `delete_objects` like this:
```py
ui.button('Remove box', on_click=box.delete)
ui.button('Remove box', on_click=lambda: scene.delete_objects(lambda obj: obj is box))
```
