### ISSUE TITLE
TailwindCSS响应式布局的异常 | TailwindCSS responsive layout exceptions

### ISSUE THREAD

**Issue by Yuerchu** [zauberzeug/nicegui#3474]
## English Version
 (I'm sorry, because my English is poor, so here is a machine translation)

In TailWindCSS, `<div class"{something}">` is displayed first for mobile layout (sm), then (md), up to (2xl), for example:
```html
<div class="mx-auto sm:invisible md:visible">
```
This should mean: Hide this div on small screens, show this div on md and above devices. This code would look like this in NiceGUI:
```python
ui.label('Hello World').classes('mx-auto sm:invisible md:visible')
```
But when I run the code that includes this, it only shows up on small screens. On screens md and above, the element disappears.

My source code is as follows:
```python
with ui.footer().classes('bg-transparent'):
        with ui.row().classes('mx-auto sm:hidden md:visible'):
            with ui.card().classes('mx-auto'):
                ui.label('Hello World').classes('text-center text-black')
            with ui.card().classes('mx-auto'):
                ui.label('Python + FastAPI').classes('text-center text-black')
            with ui.card().classes('mx-auto'):
                ui.label('NiceGUI').classes('text-center text-black')
```
Here's the (md) size browser window, and you can see that a few cards are hidden from the footer:
![image](https://github.com/user-attachments/assets/f1ad1c46-96fe-462d-ac4a-e39f655e507b)
As I continue to shrink the browser window, these three cards appear:
![image](https://github.com/user-attachments/assets/cd5ea053-8a9f-4db1-8d31-2ab81b36645b)

## 中文版
在TailWindCSS里，`<div class"{something}">` 优先是对移动布局(sm)显示的，其次是(md)，直到(2xl)，比如：
```html
<div class="mx-auto sm:invisible md:visible">
```

这样写的意思应该是：在小屏幕上隐藏此div，在md及以上的设备上显示此div。这段代码换成NiceGUI应该是这样写：
```python
ui.label('Hello World').classes('mx-auto sm:invisible md:visible')
```
但是当我运行包含这段代码的时候发现，只有在小屏幕上会显示这个元素，在md及以上尺寸的屏幕上，这个元素消失了。

我的源代码如下：
```python
with ui.footer().classes('bg-transparent'):
        with ui.row().classes('mx-auto sm:hidden md:visible'):
            with ui.card().classes('mx-auto'):
                ui.label('Hello World').classes('text-center text-black')
            with ui.card().classes('mx-auto'):
                ui.label('Python + FastAPI').classes('text-center text-black')
            with ui.card().classes('mx-auto'):
                ui.label('NiceGUI').classes('text-center text-black')
```
这是(md)尺寸的浏览器窗口，可以看到footer中的几个card元素被隐藏了：
![image](https://github.com/user-attachments/assets/f1ad1c46-96fe-462d-ac4a-e39f655e507b)
当我继续把浏览器窗口缩小，这三个card居然显示出来了：
![image](https://github.com/user-attachments/assets/cd5ea053-8a9f-4db1-8d31-2ab81b36645b)

**Comment by python-and-fiction** [comment]
```You can also use variant modifiers to target media queries like responsive breakpoints, dark mode, prefers-reduced-motion, and more. For example, use md:invisible to apply the invisible utility at only medium screen sizes and above.```
For this example,you can see the size of button changed when the size of window is greater than `sm\md\lg`.

```python3
from nicegui import ui

ui.button('react').classes('w-full sm:w-16 md:w-32 lg:w-64')

ui.run()
```
![image](https://github.com/user-attachments/assets/b6008ca2-552d-46f8-9726-3c2e26090e3c)
![image](https://github.com/user-attachments/assets/bb8fea49-a0e1-4a19-a5f4-8a601622d359)
![image](https://github.com/user-attachments/assets/46b43859-e8e8-4332-9334-bee2f43c52dc)
![image](https://github.com/user-attachments/assets/938bddf8-d883-448e-a9a7-253c04ee3b75)

**Comment by Yuerchu** [comment]
Thank you very much! But I still have a question to ask you: what if I want this control to be displayed only in (lg) size and hidden in (sm)?
When I asked chatGPT, he replied with this code, which is obviously invalid:
```python
from nicegui import ui

ui.button('this Components will be hidden on large screens').classes('w-full sm:w-16 md:w-32 lg:invisible')

ui.button('this Components will be hidden on small screens').classes('w-full sm:invisible md:visible lg:visible')

ui.run()
```
![image](https://github.com/user-attachments/assets/fc03988e-252f-47d8-8901-dd41674d9026)

**Comment by falkoschindler** [comment]
I think there's a misconception here. Let's look into this example: `.classes('sm:invisible md:visible')`

- "sm:invisible" means: on screens with a width of at least 640px there it should use the class "invisible".
- "md:visible" means: on screens with a width of at least 768px there it should use the class "visible".

This results in both classes "invisible" _and_ "visible" on large screens because they fulfil both conditions.

Here's an example how you can correctly use upper and lower limits for responsive design:
```py
ui.label('Red between 640px and 768px').classes('sm:max-md:bg-red-500')
ui.label('Green for more than 768px').classes('md:bg-green-500')
ui.label('Blue for less than 768px').classes('max-md:bg-blue-500')
```

**Comment by python-and-fiction** [comment]
```python3
from nicegui import ui

size = ui.select(['sm','md','lg'],value='sm',label='it is visible when size is greater than:').classes('w-full')

@ui.refreshable
def test():
    ui.button('test button').classes(f'collapse {size.value}:visible')

test()
size.on_value_change(test.refresh)

ui.run()
```
![image](https://github.com/user-attachments/assets/3227ca05-8db7-4c39-b11d-13ab21886698)

**Comment by Yuerchu** [comment]
非常

**Comment by Yuerchu** [comment]
非常感谢你们！Thanks!
