### ISSUE TITLE
table from_pandas frozen when column is list

### ISSUE THREAD

**Issue by dcslin** [zauberzeug/nicegui#3475]
### Description

reproduce:
```py
import pandas as pd
from nicegui import ui

df = pd.DataFrame([
    {'name': 'Alice', 'id': [1,3]},
    {'name': 'Bob', 'id': [1,2]},
])

ui.table.from_pandas(df).classes('max-h-40')

ui.run()
```

**Comment by falkoschindler** [comment]
Thanks for reporting this bug, @dcslin!
It seems to be very similar to #2744. Do you think we can close it as a duplicate?

**Comment by dcslin** [comment]
Thanks @falkoschindler so much for checking this and appreciate your work on this, marking as closed
