### ISSUE TITLE
on_value_change does not trigger if ui.set_visibility(False)

### ISSUE THREAD

**Issue by Noghpu** [zauberzeug/nicegui#3522]
### Description

I have several buttons that function as a sort of quick select and send different values to a ui.number. ui.number is usually not visible but visibility can be toggled with another button, in case the user needs a value that is not in the quick select.

Now I have the problem that ui.number.on_value_changed does not trigger when the number is not visible. The value does change though.

Code works like this:
```python
from nicegui import ui


def increase_number():
    number.set_value(number.value + 1)


def toggle_visibility():
    number.set_visibility(not number.visible)


number = ui.number(value=1)
number.on_value_change(lambda e: ui.notify(f"clicked {e.value}"))
ui.button("Increase number").on_click(increase_number)
ui.button("Toggle visibility").on_click(toggle_visibility)

ui.run()
```

is this behaviour intended?

**Comment by python-and-fiction** [comment]
yes,if you want element react events after it is invisible,you shoud do `element.ignores_events_when_hidden = False`.
```python3
from nicegui import ui

def increase_number():
    number.set_value(number.value + 1)


def toggle_visibility():
    number.set_visibility(not number.visible)


number = ui.number(value=1)
number.on_value_change(lambda e: ui.notify(f"clicked {e.value}"))
number.ignores_events_when_hidden = False
ui.button("Increase number").on_click(increase_number)
ui.button("Toggle visibility").on_click(toggle_visibility)

ui.run()
```

**Comment by falkoschindler** [comment]
Hi @Noghpu,

In PR #1030 we tried to prevent the user from triggering events on invisible UI elements by changing their appearance using developer tools in the browser. But it looks like we're blocking events in the wrong place. It should be possible to trigger change events on hidden elements programmatically or via binding, just not via user events. We'll look into it.
