### ISSUE TITLE
large images doesnt load 

### ISSUE THREAD

**Issue by iGoinbl** [zauberzeug/nicegui#3535]
### Description

 help with large generated images!

I have an image generation app everything works perfectly except when my generated image has larger than 10 mb size it isn't viewed in the ui.image component as it says trying to reconnect down when the image is down and trying to save and the image shows only when i refresh , BTW has nothing to do with generation time as i tried other images which can process for 2-3 mins but saved perfectly once they are done only if they dont have large size i use web sockets for communication but i think this problem has to do with how nicgui handles things. also this happens with normal ui.upload so i dont think this has to do with websockets or the connection

**Comment by python-and-fiction** [comment]
Try this:
https://nicegui.io/documentation/upload#uploading_large_files

**Comment by falkoschindler** [comment]
Hi @iGoinbl, please share a minimal reproducible code example!
https://github.com/zauberzeug/nicegui/wiki/FAQs#why-is-it-important-to-provide-a-minimal-reproducible-example

**Comment by iGoinbl** [comment]
can't we control the timeout of nicegui ? even if we have async functionality i think controlling the time out of nicegui would be the best thing in the world especially if i want to build a desktop/offline app because sometimes when i try to load a large image this message pops up because the file is like 20mb so the time it gets loaded to the ui.image in the interface itself takes time and the only solution was that i optimised a version of my image into webp with max dimensions so the load time in the ui is not that large , 
JUST A QUESTION : can't i make the task of loading the image to the interface and i mean not reading the image file i mean the task when the image is processed and ready to be displayed in the interface run async becuase i think that is the main problem or just increasing interface timeout  ?

async def handle_image_upload(e: events.UploadEventArguments):
    global uploaded_image_base64, uploaded_img

    original_image_data = e.content.read()
    
    uploaded_image_base64 = base64.b64encode(original_image_data).decode('utf-8')
    
    # Save the original uploaded file
    img_filename = f"uploaded_image_{int(time.time())}.png"
    img_path = os.path.join(static_image_dir, img_filename)

    async with aiofiles.open(img_path, 'wb') as file:
        await file.write(original_image_data)
    
    # Create optimized WebP version for viewing
    img = Image.open(io.BytesIO(original_image_data))
    
    # Resize image if it exceeds maximum dimensions
    if img.width > MAX_WIDTH or img.height > MAX_HEIGHT:
        img = resize_image(img, MAX_WIDTH, MAX_HEIGHT)
    
    webp_filename = f"uploaded_image_{int(time.time())}.webp"
    webp_path = os.path.join(static_image_dir, webp_filename)
    
    # Save as WebP with specified quality
    img.save(webp_path, 'WEBP', quality=WEBP_QUALITY)
    
    # Update the UI with the WebP version
    uploaded_img.source = f"/static/images/{webp_filename}"
    uploaded_img.update()

**Comment by rodja** [comment]
You can change the [timeout until reconnect already](https://nicegui.io/documentation/run#ui_run:~:text=more%20CPU%20friendly)-,reconnect_timeout%3A,-maximum%20time%20the). But in the code you posted there are many time consuming things not async: reading, encoding, decoding, opening image from bytes, resizing and saving must all be async. Have you read [our FAQ](https://github.com/zauberzeug/nicegui/wiki/FAQs#why-is-my-long-running-function-blocking-ui-updates)? Especially with the `slow_callback_duration` debug-setting you can identify these kinds of issues.
