### ISSUE TITLE
auto_close = False does not work with context menu

### ISSUE THREAD

**Issue by gavinpotter** [zauberzeug/nicegui#3539]
### Description

Somewhere between 1.4.17 and the latest version, the auto_close = False option on the context menu has stopped working.  You can see that the behaviour does not work on the nicegui documentation website example where the reset menu item has auto_close = False but it does close the menu when pressed.

**Comment by falkoschindler** [comment]
Thank for reporting this bug, @gavinpotter!
When fixing issue #2894 (2a46e2455fb3b8185dbe0f3a65c6c9f07b61b41b) which we introduced with PR #2855, we forgot to remove the "auto-close" prop for `ui.context_menu`. I fixed it and added a corresponding pytest.
