### ISSUE TITLE
Launching NiceGUI app as an executable with PyInstaller

### ISSUE THREAD

**Issue by JS-Aibel** [zauberzeug/nicegui#355]
When trying to run an executable created with PyInstaller of a simple NiceGui Python script, the following error message occurs:
```
File "starlette\staticfiles.py", line 55, in __init__
\static' does not exist
```

Maybe as a simpler implementation then having a desktop wrapper like discussed here https://github.com/zauberzeug/nicegui/discussions/89. Could it be possible to run an executable made with PyInstaller that starts up NiceGui the same way it starts when I run `python filename.py`? This way the user does not need to have Python installed to run the NiceGui app/script.

**test.py**
```
from nicegui import ui

ui.label('some label')

ui.run()
```

**Creating an executable from terminal**
`python -m PyInstaller test.py`

**Comment by rodja** [comment]
Thats a great suggestion. We would really much like to support PyInstaller. Anyone volunteering to look into this issue? Seems we need to tell PyInstaller to also provide [the `static` folder](https://github.com/zauberzeug/nicegui/tree/main/nicegui/static).

**Comment by SebastienDorgan** [comment]
It is quite possible and not that complex without modifying nicegui, I created a minimal example to illustrate the procedure.

Mininal nicegui ui, in ui.py:
```python
from nicegui import ui
ui.label('Hello from Pyinstaller')
ui.run(show=False, reload=False, title="PyInstaller Test")
```
Minimal build file , in build.py
```python
import nicegui
from pathlib import Path
import subprocess
static_dir = Path(nicegui.__file__).parent

script = \
f"""
pyinstaller --onefile ui.py --add-data="{static_dir}:nicegui"
"""
subprocess.call(script, shell=True)
``` 
You just have to run build.py to generate a working executable (tested in Linux only) in `dist/ui`

**Comment by falkoschindler** [comment]
Great! I can confirm it works on Mac OS as well.
`reload=False` seems to be important though.

**Comment by SebastienDorgan** [comment]
Yes, without reload, the executable produced opens a series of windows in the browser

**Comment by rodja** [comment]
Should we add this to the documentation? There is already some text about [Deployment in the README](https://github.com/zauberzeug/nicegui#deployment). But maybe this need to be more prominent?

**Comment by JS-Aibel** [comment]
That’s great!
I have not got the build.py script to run under Windows 10. Been trying with WSL and PowerShell.
Is it to do with the subprocess.call?

**Comment by falkoschindler** [comment]
Ok, we'll add a "Deployment" section to the documentation including Docker and PyInstaller.

**Comment by rodja** [comment]
@falkoschindler I created the "Deployment" section, transfered the infos about Docker and Hosting from the README to the website and added the documentation for PyInstaller. Ready for review.

**Comment by abulka** [comment]
@falkoschindler When building on Mac M1, I'm only getting a `myapp` file not a `myapp.app` that the Mac usually likes, though I certainly can generate an `.app` version by adding `--windowed` to the `build.py`.  

Though when I run it (either `./dist/myapp` or `./dist/myapp.app/Contents/MacOS/myapp`), I get
```
./dist/myapp
Traceback (most recent call last):
  File "nice02.py", line 1, in <module>
    from nicegui import ui
  File "/var/folders/1t/ycxw0mzn2hqg7krq3nzzmqwc0000gn/T/_MEIlNgGYY/nicegui/__init__.py", line 6, in <module>
    __version__ = importlib_metadata.version('nicegui')
  File "importlib/metadata/__init__.py", line 984, in version
  File "importlib/metadata/__init__.py", line 957, in distribution
  File "importlib/metadata/__init__.py", line 548, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for nicegui
[23789] Failed to execute script 'nice02' due to unhandled exception!
```

I think there needs to be more clarity about 
- pyinstaller windowed vs non windowed, 
- whether to run NiceGui in `native=True` mode or not. 

- I've tried all the permutations of the above, as well as these invocations
```python
# ui.run()
# ui.run(reload=False)
# ui.run(native=True)
ui.run(reload=False, native=True)
```
with the same error.  Perhaps I should raise another issue re this?

**Comment by rodja** [comment]
Thanks for reporting. We should track and analyse the error in a separate issue. The suggestions/addons to the docu look fine. Could you create a pull request?

**Comment by abulka** [comment]
I solved the Apple M1 pyinstaller problem, which was due to the wrong version of pyinstaller being picked up. I was using a venv and the pyinstaller being invoked was from the 'outer' python. I recommend therefore that the build script be changed to invoke pyinstaller in an arguably more robust way `python -m PyInstaller ...` viz:

```python
cmd = [
    'python',
    '-m',
    'PyInstaller',
    'main.py', # your main file with ui.run()
    '--name', 'myapp', # name of your app
    '--onefile',
    #'--windowed', # prevent console appearing, only use with ui.run(native=True, ...)
    '--add-data', f'{Path(nicegui.__file__).parent}{os.pathsep}nicegui'       
]
subprocess.call(cmd)
```

I've also discovered that whilst using the `--windowed` option works, it is dangerous since you can't see the console output and thus cannot stop the app with `ctrl-c` - so it remains running forever (till you track down and kill the process).

I'll update the documentation with all this info and submit a PR.

**Comment by rodja** [comment]
Happy to hear your problem is solved. Can't wait to integrate your pull-request. The `python -m PyInstaller` trick should defenitly be integrated.

> I've also discovered that whilst using the --windowed option works, it is dangerous since you can't see the console output and thus cannot stop the app with ctrl-c

Hm... does the program not stop for you if the window is closed?

**Comment by abulka** [comment]
> Hm... does the program not stop for you if the window is closed?

Yes if its a popup native window, not if its a browser window.

**Comment by frankenstein91** [comment]
hanging here

```
ERROR:    Traceback (most recent call last):
  File "starlette/routing.py", line 677, in lifespan
  File "starlette/routing.py", line 566, in __aenter__
  File "starlette/routing.py", line 656, in startup
  File "nicegui/nicegui.py", line 62, in handle_startup
    raise RuntimeError('\n\n'
RuntimeError: 

You must call ui.run() to start the server.
If ui.run() is behind a main guard
   if __name__ == "__main__":
remove the guard or replace it with
   if __name__ in {"__main__", "__mp_main__"}:
to allow for multiprocessing.

ERROR:    Application startup failed. Exiting.
```

**Comment by falkoschindler** [comment]
@frankenstein91 Please open a new Q&A discussion with more information about your problem, i.e. a minimum reproducible code example. Thanks!

**Comment by Knochi** [comment]
Tested today from within a virtual environment on windows 10 and worked perfectly well!

**Comment by DarakDuVal** [comment]
@falkoschindler you guys rock! (probably not the right thread, but hey) Started using Nicegui couple weeks ago and - as a backend dev never doing frontends before - can find my way fast and easy. Also thanks to your examples, snippets and great discussions here! Thanks! Was able to use PyInstaller also in my setup, combined with nssm to run and host a web UI as a Windows service!
