### ISSUE TITLE
color_picker.props don't propagate

### ISSUE THREAD

**Issue by zobac** [zauberzeug/nicegui#3571]
### Description

Hi there. I can't seem to set the properties on the color_picker (defined [here](https://quasar.dev/vue-components/color-picker#qcolor-api)). Specifically, Ultimately, I want to set a custom palette, hide both the header and footer, and set the default-view to "palette". However, I can't get any of the properties to take, even when trying them individually. Here's what I'm doing:

```py
from nicegui import ui

with ui.button(icon='colorize') as button:
    ui.color_picker(on_pick=lambda e: button.style(f'background-color:{e.color}!important')).props('default-view=palette no-header no-footer')

ui.run()

```

I've also tried it by only passing only `no-header`, `no-header-tabs`, `no-footer`, and `default-view=palette`, but none of them render properly. 

Am I doing something wrong?

**Comment by falkoschindler** [comment]
Hi @zobac,

The `ui.color_picker` is actually a menu with a QColor component nested inside. Therefore you can't apply props directly, but need to use the `q_color` attribute instead:
```py
with ui.button(icon='colorize') as button:
    picker = ui.color_picker(on_pick=lambda e: button.classes(f'!bg-[{e.color}]'))
    picker.q_color.props('default-view=palette')
```

We should definitely add a note and a demo to the documentation.

**Comment by zobac** [comment]
Fantastic! Thank you for the quick response. Could you help me with setting a custom palette? I'm trying

```
from nicegui import ui

with ui.button(icon='colorize') as button:
    picker = ui.color_picker(on_pick=lambda e: button.classes(f'!bg-[{e.color}]'))
    picker.q_color.props('default-view=palette no-header no-footer palette=[rgb(23,120,0), rgb(123,20,0)]')

ui.run()

```

and

```
from nicegui import ui

with ui.button(icon='colorize') as button:
    picker = ui.color_picker(on_pick=lambda e: button.classes(f'!bg-[{e.color}]'))
    picker.q_color.props('default-view=palette no-header no-footer palette=[ "#019A9D", "#D9B801", "#B2028A"]')

ui.run()
```

But I still get the default palatte.

**Comment by falkoschindler** [comment]
Sure, here is a way to define a custom palette:
```py
with ui.button(icon='colorize') as button:
    picker = ui.color_picker(on_pick=lambda e: button.classes(f'!bg-[{e.color}]'))
    picker.q_color.props('''default-view=palette no-header no-footer :palette="['rgb(23,120,0)', 'rgb(123,20,0)']"''')
```
Note that the leading colon `:` indicates a prop that needs to be converted from a string into a JavaScript object on the client. The double quotes enclose the whole JavaScript expression. And the single quotes represent strings inside of the JavaScript array.

You can also use hex color codes like this:
```py
with ui.button(icon='colorize') as button:
    picker = ui.color_picker(on_pick=lambda e: button.classes(f'!bg-[{e.color}]'))
    picker.q_color.props('''default-view=palette no-header no-footer :palette="['#019A9D', '#D9B801', '#B2028A']"''')
```

A slightly simpler way to create the prop definition from a list of colors can be to use the json module for serialization:
```py
with ui.button(icon='colorize') as button:
    picker = ui.color_picker(on_pick=lambda e: button.classes(f'!bg-[{e.color}]'))
    palette = ['#019A9D', '#D9B801', '#B2028A']
    picker.q_color.props(f'''default-view=palette no-header no-footer :palette='{json.dumps(palette)}' ''')
```
