### ISSUE TITLE
ui.page_title fails in native

### ISSUE THREAD

**Issue by MastSE** [zauberzeug/nicegui#3583]
### Description

Using:

`ui.page_title('My app name')`

When I simply run my application as a webpage (`ui.run()`), the page title updates just fine. When I run my application natively (using pywebview, `ui.run(native=True)`), the page title does not update. Instead, it shows the default 'NiceGUI'. I want to set the title of a native app, with a workaround if necessary.

Running Windows 10, Python 3.11.1.

**Comment by MastSE** [comment]
Based on https://nicegui.io/documentation/run I've decided to use `ui.run(native=True, title='My app name')` instead. Which seems to work.

This does not change that `ui.page_title('My app name')` should've worked here just the same. Or, if this is a known issue that can't be fixed, mentioned in the page_title docs https://nicegui.io/documentation/page_title.

**Comment by python-and-fiction** [comment]
For native window, it's a windowproxy, not a normal client. If you want to control native window's properties, you should manipulate `app.native.main_window`.
```python3
from nicegui import ui,app

@ui.page('/')
def index():
    ui.button('title',on_click=lambda :ui.page_title('test'))
    ui.button('title',on_click=lambda :app.native.main_window.set_title('test'))
    
ui.run(native=True)
```

**Comment by rodja** [comment]
Thanks @python-and-fiction. Still @MastSE is right. `ui.page_title` should also work in native mode. Anyone up to a simple pull request which calls `app.native.main_window.set_title` in `ui.page_title`?
