### ISSUE TITLE
Missing documentation of align_items parameter in row/column/card

### ISSUE THREAD

**Issue by frankhuurman** [zauberzeug/nicegui#3602]
### Description

I noticed that in release 1.4.27 the align_items parameter got added to **ui.row**, **ui.column** and **ui.card** and wanted to see how this works but on the documentation pages of these elements(https://nicegui.io/documentation/column for exampe) I can only find:

![image](https://github.com/user-attachments/assets/5f1a6342-f718-4047-a478-bb504a929beb)

So I only know the default value is None but I don't know which value(or type) I could use to align the items(e.g. horizontal/vertical/center/left/right?). I couldn't find it on the rest of the documentation page either.

Can't wait to try it out :)

**Comment by frankhuurman** [comment]
Found out that "center" works as a value :)

**Comment by falkoschindler** [comment]
The `align_items` is type-annotated like this:
```py
align_items: Optional[Literal['start', 'end', 'center', 'baseline', 'stretch']] = None,
```
We tend to expect the users to use modern IDEs with type hints. But I guess we can duplicate the possible values in the docstring

**Comment by frankhuurman** [comment]
@falkoschindler 
I use VS Code but didn't point the editor to my new venv yet which is why I didn't see the suggestions.
But I did have the expectation of finding possible values in the online documentation, not sure if that's just me.
