### ISSUE TITLE
ui.chat_message does not change via dark/light mode

### ISSUE THREAD

**Issue by cleesmith** [zauberzeug/nicegui#3608]
### Description

Is it possible to have ui.chat_message honor the dark/light mode setting? 

As in, black text on a color when in light mode, and white text on a color when in dark mode.
It seems like many elements work this way by default, but ui.chat_message is noticeably different.

**Comment by python-and-fiction** [comment]
```python3
dark_mode = ui.dark_mode()

chat = ui.chat_message('test')

def refresh_chat():
    chat._props.update({'text-color':'white' if dark_mode.value else 'black','bg-color':'blue' if dark_mode.value else 'green'})
    chat.update()
switch = ui.switch('Dark Mode',on_change=lambda :(dark_mode.set_value(switch.value),refresh_chat()))
```
![image](https://github.com/user-attachments/assets/8baf4899-5721-4fc8-9ae5-fbe5cb913ecd)

**Comment by falkoschindler** [comment]
@cleesmith I don't think switching the text color would make sense, because the message background color doesn't change:
```py
ui.switch('Dark Mode').bind_value(ui.dark_mode())
ui.chat_message('test')
```
![Screenshot 2024-08-27 at 13 54 58](https://github.com/user-attachments/assets/8088eafa-f904-4759-97a2-429f473f5ee7)

> It seems like many elements work this way by default, but ui.chat_message is noticeably different.

Do you have an example for such elements?

**Comment by cleesmith** [comment]
I will give that a try in the following typical chat with human/AI:

'''
me_message = ui.chat_message(sent=True, stamp=timestamp)
me_message.clear()
with me_message:
    ui.html(f"<pre style='white-space: pre-wrap; user-select: text;'> \nME:\n{question}</pre>")

. . . 

response_message = ui.chat_message(sent=False, stamp=timestamp)
ui.html(f"<pre style='white-space: pre-wrap; user-select: text;'> \nAI:\n{response}</pre>")
'''

Thanks, to both!
