### ISSUE TITLE
Potential memory leak in ui.table

### ISSUE THREAD

**Issue by zan73** [zauberzeug/nicegui#3618]
### Description

I use a ui.table populated with a dataframe.to_dict('records'). The dataframe usually initially has 100 - 200 rows of data.
I modify the original dataframe by filtering based on ui controls (switches, dropdowns, etc) which are populated with the unique values from various columns of the dataframe, and then set the ui.table rows to the filtered dataframe.
As a secondary filter, I have enabled the RowClick event on the table and clicking a row in the table filters all records in the dataframe and hence ui.table, where the records have the same "Title".
This works most of the time, but occasionally when clicking the table row, even though the dataframe is correctly filtered, setting the ui.table rows to the filtered dataframe appears to retain some of the rows that should now be filtered - I am assuming this is a memory leak but I don't have the tech skills to confirm.
I have a working page visible on the internet which highlights the issue, but would prefer not to publish it here - I can provide it to a dev if they reach me directly.

**Comment by falkoschindler** [comment]
Hi @zan73,
I understand that it might be hard to boil it down to a few lines of code. Nonetheless, can you, please, try to create a minimum reproducible code example? This would allow us and the community to help more efficiently. Thanks!
[Why is it important to provide a minimal reproducible example?](https://github.com/zauberzeug/nicegui/wiki/FAQs#why-is-it-important-to-provide-a-minimal-reproducible-example)

**Comment by falkoschindler** [comment]
I'll close this issue due to inactivity. Without seeing any code there's not much we can do.
Feel free to re-open it once you have more information for us.

**Comment by zan73** [comment]
For anyone experiencing this issue, check whether your source dataframe having duplicate records. Once I removed the duplicates from the dataframe, this issue of filtered records still being present in the ui.table (even when totally different filters are applied) is resolved.
