### ISSUE TITLE
Memory leak of (one-shot) timers

### ISSUE THREAD

**Issue by fwerner** [zauberzeug/nicegui#3626]
### Description

Hey 👋 

The memory usage seems to keep growing indefinitely when creating many one-shot timers:

```py
from nicegui import ui

async def update():
    ui.timer(1e-3, update, once=True)

ui.timer(0, update, once=True)
ui.run()
```

I've checked with the `MemoryMonitor` from another issue and it looks like the `Timer`s are not cleaned up. Keeping track of the `Timer` instance (`timer`) and calling `timer.remove(timer)` in its callback is a workaround:

```py
from nicegui import ui

async def update():
    global timer
    timer.remove(timer)
    timer = ui.timer(1e-4, update, once=True)

timer = ui.timer(0, update, once=True)
ui.run()
```

I would expect that a one-shot timer cleans up after having fired, but perhaps I am misusing it here?

**Comment by rodja** [comment]
Wow. Thank you so much @fwerner! I created #3647 to fix it.

**Comment by fwerner** [comment]
> Wow. Thank you so much @fwerner! I created #3647 to fix it.

Thank you Rodja for your swift response!
