### ISSUE TITLE
pytest requires non-installed package plotly

### ISSUE THREAD

**Issue by Aluriak** [zauberzeug/nicegui#3629]
### Description

I cloned the repository (main branch), create and entered into a venv, then ran `poetry install`. Everything is ok. I then ran `pytest` (as per [the doc](https://github.com/zauberzeug/nicegui/blob/main/CONTRIBUTING.md#running-tests)), and got the following error, *preventing all tests to be run* :

```
ImportError while importing test module '/home/aluriak/nicegui/tests/test_plotly.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_plotly.py:2: in <module>
    import plotly.graph_objects as go
E   ModuleNotFoundError: No module named 'plotly'
```

It was fixed by installing explicitely plotly with `pip install plotly`. Unless i failed something, i think it may be undesirable behavior, and that missing import should not prevent to run the tests. Feel free to close if it's not relevant.

**Comment by rodja** [comment]
plotly is an optional dependency of nicegui because you do not require it for quite a lot of use cases and it's quite big to install. Of course, to run the whole test suite **all** optional dependencies must be installed. I'm not sure how we could improve the behaviour...

**Comment by Aluriak** [comment]
Technicaly speaking, we could deselect the tests if the library can't be imported. Not complex (pytest decorator + import at function level) but maybe not worth the hassle.

I used poetry, while documentation specifies the use of `pip install -e .` instead (expliciting that all deps are to be installed that way), i guess this is a non-issue. Sorry.
