### ISSUE TITLE
Drawers behave weirdly since they are derived from ValueElement in #308

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#367]
In #308 we derived `ui.left_drawer` and `ui.right_drawer` from `ValueElement` in order to allow setting their initial state. As it turns out, this causes weird mobile behavior:

- On small screens Quasar's drawers are initially hidden. But the default `value=True` overwrites this automation and always shows the drawer, even on small screens.
- A workaround might be to set the initial value to `None` and to re-activate the prop `show-if-above` to automatically show the drawer above a certain media query width. But this triggers a value change on clients with a large screen right after loading the HTML, when the socket is not yet connected. The JavaScript console shows an error and the `value` on the server is not updated. This causes the next `toggle()` call being uneffective.

Switching to a default value of `None` and setting `show-if-above` in this case only seems promising. But we have to find out how to inform the server about a possible automatic value change.

Or we ditch the `ValueElement` approach and send the `value` and other props only one-way from server to client. But this wouldn't allow providing a `toggle()` method, since the server does not know the current `value`.

**Comment by falkoschindler** [comment]
> Or we ditch the ValueElement approach and send the value and other props only one-way from server to client. But this wouldn't allow providing a toggle() method, since the server does not know the current value.

I just noticed there is a [client-side `toggle()` method](https://quasar.dev/layout/drawer) we could use.

**Comment by falkoschindler** [comment]
@rodja Removing the inheritance from `ValueElement` I found a solution I'm pretty pleased with. If you agree, we could release version 1.1.7 shortly before users start to rely on drawers being `ValueElements` with a bindable `value` property.

**Comment by rodja** [comment]
Sure. Releasing 1.1.7 quickly would be good. Go ahead.
