### ISSUE TITLE
Unable to hide the notification with set_visibility

### ISSUE THREAD

**Issue by canyone2015** [zauberzeug/nicegui#3670]
### Description

**Description:**

It's not possible to hide the notification by calling the `set_visibility` function.
Goal: don't allocate extra memory to create new notifications, especially those that are shown very often.
If the tab with the web page is in the background, at some point the notifications stop dismissing.
After many undismissed notifications have accumulated, the only way out is a long web page recovery.

**Code Examples:**

Non-Working Example:
```python3
from nicegui import ui


def create_notification():
    notification = ui.notification(timeout=None)
    notification.message = 'Message...'
    notification.spinner = True
    notification.set_visibility(False)


def main():
    print("Starting...")
    ui.timer(0, create_notification, once=True)
    ui.run(dark=False, language='en-US',
           reload=False, endpoint_documentation='none',
           show_welcome_message=False)


if __name__ in {"__main__", "__mp_main__"}:
    main()

```

**Expected result:**

The notification is hidden.

Working Example (every 3 seconds the notification appears and disappears; but there is no hiding effect when the page is reloaded):
```python3
from nicegui import ui


def show_hide_notification(notification_id=None):
    if notification_id is None:
        notification = ui.notification(timeout=None)
        notification.message = 'Message...'
        notification.spinner = True
        notification_id = notification.id
    ui.run_javascript(f"""
        let data_id = "nicegui-dialog-{notification_id}";
        var el = document.querySelector('[data-id="' + data_id + '"]');
        el.style.display = el.style.display === 'none' ? '' : 'none';
    """)
    ui.timer(3, lambda *_: show_hide_notification(notification_id), once=True)


def main():
    print("Starting...")
    ui.timer(3, show_hide_notification, once=True)
    ui.run(dark=False, language='en-US',
           reload=False, endpoint_documentation='none',
           show_welcome_message=False)


if __name__ in {"__main__", "__mp_main__"}:
    main()

```

**Environment:**
- NiceGUI Version: 2.0.1
- Python Version: 3.11
- OS: Windows 11

**Comment by falkoschindler** [comment]
Hi @canyone2015,

You're right, `ui.notification` doesn't implement `set_visibility` and shouldn't ignore it silently. We either should raise a `NotImplemented` exception or somehow implement this method. But because a Quasar notification behaves quite differently than a regular UI element, it is quite tricky to show and hide. There's a "classes" attribute in the "options" prop which we could use to add and remove the "hidden" class:
```py
n = ui.notification('Message...', timeout=None, spinner=True)

def hide():
    n.props['options']['classes'] = 'hidden'
    n.update()

def show():
    n.props['options']['classes'] = ''
    n.update()

ui.button('Hide', on_click=hide)
ui.button('Show', on_click=show)
```
But the animation looks rather weird.

> Goal: don't allocate extra memory to create new notifications, especially those that are shown very often.

Notifications are removed from memory after they disappear. So I'd assume you can simply create new notifications every time and don't have to care about keeping them alive.
