### ISSUE TITLE
ui.download silently replaces colons with underscores

### ISSUE THREAD

**Issue by marcuslimdw** [zauberzeug/nicegui#3672]
### Description

**What I did:**

```py
from nicegui import ui

@ui.page("/")
def page():
    ui.download(b"", filename="a:colon.txt")

ui.run()
```

**What I expected:**

I download a file named "a:colon.txt"

**What I got:** 

I downloaded a file named "a_colon.txt".

**Comment by python-and-fiction** [comment]
actually, filename is not legal on Windows.

**Comment by marcuslimdw** [comment]
I'm not on Windows.

**Comment by marcuslimdw** [comment]
I'm not on Windows, but on Mac. Nevertheless, you're right that this is probably a browser/OS thing, and not something NiceGUI can fix directly.

**Comment by marcuslimdw** [comment]
I'm not on Windows, but on Mac. Nevertheless, you're right that this is probably a browser/OS thing, and not something NiceGUI can fix directly.
