### ISSUE TITLE
Frequent unknown error message (sw.js not found)

### ISSUE THREAD

**Issue by MLaurenceFournier** [zauberzeug/nicegui#3674]
When using nicegui, this message often gets logged on stderr (according to pycharm coloring):
`http://localhost:8080/sw.js not found`
I don't know what it means, but it doesn't seem to impact anything. Is it important? How can I prevent it?

**system info:**
- windows 10
- conda 23.7.4
- python 3.10.12
- nicegui 1.4.26

**Comment by rodja** [comment]
There seems to be a browser or other client running which requests `sw.js` on `localhost:8080`. It has nothing to do with NiceGUI.
