### ISSUE TITLE
Native mode using doc example only shows a blank window

### ISSUE THREAD

**Issue by terremoth** [zauberzeug/nicegui#3675]
### Description

The image shows itself the problem

![image](https://github.com/user-attachments/assets/9cd797c4-3136-4b0c-8536-388f74dec217)

Python version being used: 3.12
Windows 10 22H2 updated, 32Gb RAM
Direct X 12 (Idk if that matters)

I had to install `pywebview` in order to use the app as native desktop app, as the nicegui itself asked to do this:  

![image](https://github.com/user-attachments/assets/1d7170c4-b61a-4ac9-8626-09fc830221c5)

After running the application and showed the blank screen, this was the terminal output:  

![image](https://github.com/user-attachments/assets/ed76a980-6d45-4f52-9451-8af71ddddecc)

So, probably there is a bug out there since the expected result was to show a label and a button on screen. Thanks.

**Comment by terremoth** [comment]
I realized with only webview, it doesn't work either, same result with blank screen:

![image](https://github.com/user-attachments/assets/b05ccae7-63b4-403c-8021-ffb147de9df1)

I installed `pythonnet` and `cefpython` as the pywebview doc suggested, but no success at all too.  
I googled and I saw some people having this same problem 😐

**Comment by canyone2015** [comment]
Duplicate:
https://github.com/zauberzeug/nicegui/issues/2751
