### ISSUE TITLE
cannot set padding and margin 0 for `ui.scroll_area()`

### ISSUE THREAD

**Issue by h0uter** [zauberzeug/nicegui#3677]
### Description

1. Goal: set padding in scroll area to zero
2. Expectations: I expect the children of a scroll area to not leave any gaps when I set their classes `"w-full"`.
3. Instead: I see gaps

minimal example:

```py
from nicegui import context, ui

context.client.content.classes("p-0")

with ui.scroll_area().classes("w-1/2 bg-blue-100"):
    ui.card().classes("w-full")
    ui.card().classes("w-full")

with ui.scroll_area().classes("w-1/2 bg-red-100 m-0 p-0"):
    ui.card().classes("w-full")
    ui.card().classes("w-full")

with ui.scroll_area().classes("w-1/2 bg-green-100 gap-0"):
    ui.card().classes("w-full")
    ui.card().classes("w-full")


ui.run()
```

![image](https://github.com/user-attachments/assets/f927a271-6a63-4099-8ea1-f56a5eda57e6)
<img width="1360" alt="image" src="https://github.com/user-attachments/assets/ffc34ebf-50d3-4b0a-bd1d-0c2bbbe2150a">

Perhaps this has to do with the  separate  `q-scrollarea`, `q-scrollarea_content` and `q-scrollarea_container` divs.

**Comment by falkoschindler** [comment]
Hi @h0uter,

You're right, the scroll area content is a nested element and therefore not directly affected by the container classes. But there's a ["content-style" prop](https://quasar.dev/vue-components/scroll-area) you can use:

```py
with ui.scroll_area().classes('w-80 border').props('content-style="padding: 0"'):
    ui.label('This spans the full width').classes('w-full bg-blue-200')
```
![Screenshot 2024-09-05 at 09 36 07](https://github.com/user-attachments/assets/592efcd4-e5d5-4dfd-9dbe-75a1c94e9a62)

**Comment by h0uter** [comment]
Thanks for tip!

For future reference, note that you might also want to set: `.props('content-style="padding: 0; gap: 0" content-active-style="padding: 0; gap: 0"')` to eliminate the vertical gap and apply it also when the scroll area starts to overflow.
