### ISSUE TITLE
Add component / example to docs for loading spinners

### ISSUE THREAD

**Issue by rbeeli** [zauberzeug/nicegui#368]
To inform users about long running processes, loading spinners can help.
I have not seen any examples of how to use them in the docs, nor is there a native component in nicegui.

Could this component be added as well? Should be fairly easy as it is a basic component.

[https://quasar.dev/vue-components/spinners](https://quasar.dev/vue-components/spinners)

**Comment by falkoschindler** [comment]
Great idea! In [1355cc1](https://github.com/zauberzeug/nicegui/commit/1355cc14654b6b03b30219da3ff41591fb421c16) I introduced `ui.spinner`, including pytest and reference example.
