### ISSUE TITLE
CSS property on dialog causes visual glitch when dialog is closed.

### ISSUE THREAD

**Issue by kulvind3r** [zauberzeug/nicegui#3696]
### Description

When applying the css property of `style("width: 50%")` to a `ui.dialog() as ui.card()` object. The property does not work correctly. This causes a glitch to happen when the dialog is closed.

It seems like instead of being applied to the dialog, the property applies to the dark overlay created behind the card for the brief moment when the dialog is closed. 

If your remove the style property , everything works fine.

### Code to reproduce.

```python
with ui.dialog().style("width: 50%") as addCategoryDialog, ui.card():
        addCategoryDialog.props('flat bordered')
        ui.input(label = "Title", placeholder= "Title for your category").classes('w-full')
        with ui.row():
            ui.label("Nest Under").classes('text-base font-semi-bold').style("margin-top: 10px")
            with ui.list().props('bordered separator'):
                ui.item("Programming")
                ui.item("Infrastrucutre Engineering")
                ui.item("OOP")
                ui.item("Design Patterns")
                ui.item("Python")
        with ui.row().classes('w-full justify-center'):
            ui.button("Add")
            ui.element('div').style("width: 50px;")
            ui.button("Cancel", on_click=addCategoryDialog.close)
```

### GIF demonstrating the glitch.

![Weird Flashing when closing Card](https://github.com/user-attachments/assets/fc2876ca-b641-4e22-8fb2-959461a999b8)

**Comment by falkoschindler** [comment]
Hi @kulvind3r,

Styling the `ui.dialog` will indeed affect the overlay and not the card.
What are you trying to achieve? To set the width of the card to 50% (of the screen), you can use these Tailwind classes:
```py
ui.card().classes('!max-w-full w-[50vw]')
```
or these CSS settings:
```py
ui.card().style('max-width: 100% !important; width: 50vw')
```
Setting the maximum width to some large value overwrites Quasar's default max width for dialog contents of 560px. And "50vw" means "50 percent of the width of the view port".

**Comment by kulvind3r** [comment]
Thanks for the prompt reply. And yes, i was trying to size the card to 50% of the screen, but since then i had removed the style, and the UI still looked good without card being large sized. I will use your provided solution if i decide to increase dialog size in future.

But i just wished to report the behavior in case this might be a genuine bug. Since the overlay renders full screen and the width style only kicks in when dialog is closed, it seemed like this might still qualify for unexpected behavior.

You can close the issue if this is not a bug.

and thanks for the great library.
