### ISSUE TITLE
when the data of list  includes the same name， click sort  field  twice or more ，the data shows in web will increase 

### ISSUE THREAD

**Issue by JumpWill** [zauberzeug/nicegui#3719]
### Description

this is an [offical demo](https://nicegui.io/documentation/section_data_elements#table)，
I just duplicated the last row:

```python
from nicegui import ui

columns = [
    {'name': 'name', 'label': 'Name', 'field': 'name', 'required': True, 'align': 'left'},
    {'name': 'age', 'label': 'Age', 'field': 'age', 'sortable': True},
]
rows = [
    {'name': 'Alice', 'age': 18},
    {'name': 'Bob', 'age': 21},
    {'name': 'Carol'},
    {'name': 'Carol'},
]
ui.table(columns=columns, rows=rows, row_key='name')

ui.run()
```
if i click age in web ui  repeatedly，there will be more and more data.

**Comment by rodja** [comment]
Wow, thanks for bringing this up @JumpWill. I can reproduce it and could write a test that fails:

```py
def test_sorting(screen: Screen):
    table = ui.table(columns=[
        {'name': 'name', 'label': 'Name', 'field': 'name', 'required': True, 'align': 'left'},
        {'name': 'age', 'label': 'Age', 'field': 'age', 'sortable': True},
    ],
        rows=[
        {'name': 'Alice', 'age': 18},
        {'name': 'Bob', 'age': 21},
        {'name': 'Carol'},
        {'name': 'Carol'},
    ], row_key='name')

    screen.open('/')
    assert len(screen.find_all('Carol')) == 2
    screen.click('Age')
    screen.wait(0.1)
    assert len(table.rows) == 4
    assert len(screen.find_all('Carol')) == 2
```

The interesting part is that `assert len(table.rows) == 4` still passes. So it looks like some issue with Vue...

**Comment by JumpWill** [comment]
@rodja  You did more than I did. You saw something deeper 👍

**Comment by falkoschindler** [comment]
This is basically the same mistake like in #3692: `row_key` needs to be set to a column name that contains unique values. Otherwise Quasar messes up the table rows.

> row_key: name of the column containing unique data identifying the row (default: "id")
