### ISSUE TITLE
Some UI elements do not follow the style of their parents

### ISSUE THREAD

**Issue by pascalzauberzeug** [zauberzeug/nicegui#3723]
### Description

I found that ui.select doesn't follow the style of it's parent element. I don't know whether this is a bug or intended, but it's bothering me.
I extracted an example and found that it affects multiple elements and setting the styles directly doesn't work either

### Example
```python
from nicegui import ui

with ui.row().classes('items-center'):
    version_select = ui.select(['123', '123', '123'], label='Test Text').style('min-width: 140px;')

with ui.card().style('background-color: #3E63A6; color: white;'):
    with ui.column().classes('items-center'):
        ui.label('123')
        ui.select(['123', '123', '123'], label='Test Text').style('min-width: 140px;')
        ui.select(['123', '123', '123'], label='Test Text').style(
            'min-width: 140px;color: white;').props('color=white')
        ui.checkbox('check me')
        ui.input()

ui.run()
```

![Screenshot 2024-09-13 at 16 14 33](https://github.com/user-attachments/assets/31bb8c10-483c-4b18-9a70-b625d01251a5)

**Comment by python-and-fiction** [comment]
```python3
with ui.card().style('background-color: #3E63A6; color: white;'):
        ui.select(['123', '123', '123'], label='Test Text').props('label-color=white').classes('w-64')
```
![image](https://github.com/user-attachments/assets/397e6441-9ed9-4bd3-83dc-cfc37cf0b79c)

**Comment by rodja** [comment]
Most of our elements are Quasar Framework components. Quasar encapsulated styles to ensure consistent behavior and appearance across different parts of an application. This encapsulation means that they do not necessarily inherit the CSS color property from parent elements. So the behaviour is something NiceGUI inherited from Quasar.
