### ISSUE TITLE
Compatibility issue with old 0.9 version

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#374]
Version 0.9.26 of NiceGUI requires cryptography==38.0.3, however, on Debian Buster (oldstable) there's only 37.0.4. I know 38.0.2 had regression in openSSL, but could 37.0.4 also be allowed? Or it's not simply done?

**Comment by falkoschindler** [comment]
See PR #375.

**Comment by rodja** [comment]
I'll prepare a new release soon.

**Comment by rodja** [comment]
I just published [v0.9.27](https://github.com/zauberzeug/nicegui/releases/tag/v0.9.27).

**Comment by rodja** [comment]
@me21 I just tested installing the 0.9.27 in a clean environment with this command:

```bash
docker run --rm -it python:3.11 pip install nicegui==0.9.27
```

But that fails with the error

    ERROR: Cannot install nicegui==0.9.27 because these package versions have conflicting dependencies.

Do you have an idea on how to resolve this?

**Comment by rodja** [comment]
Installation with 

    docker run --rm -it python:3.7 pip install nicegui==0.9.27

works fine, by the way.

**Comment by me21** [comment]
> Do you have an idea on how to resolve this?

Which dependencies are conflicting? I'll try installing it on my end.

**Comment by rodja** [comment]
```
The conflict is caused by:
    nicegui 0.9.27 depends on cryptography<38.0.0 and >=37.0.4; python_version ~= "3.7"
    nicegui 0.9.27 depends on cryptography<39.0.0 and >=38.0.3; python_version ~= "3.11.0"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Comment by rodja** [comment]
Thanks for the new pull request. [v0.9.28](https://github.com/zauberzeug/nicegui/releases/tag/v0.9.28) is working.

**Comment by falkoschindler** [comment]
What about the GitHub action being red?
https://github.com/zauberzeug/nicegui/actions/runs/4224756571

**Comment by me21** [comment]
It seems to be an exception inside matplotlib package, likely not related to the change. A similar issue - https://github.com/enthought/mayavi/issues/1000 - turned out to be package manager bug.
