### ISSUE TITLE
Expected ASGI message 'websocket.accept' or 'websocket.close', but got 'http.response.start'.

### ISSUE THREAD

**Issue by chandanch** [zauberzeug/nicegui#3740]
### Description

RuntimeError: Expected ASGI message 'websocket.accept' or 'websocket.close', but got 'http.response.start'.

**Comment by python-and-fiction** [comment]
plz give a [minimal reproducible code example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).
Provide more info about version and environment.
