### ISSUE TITLE
Download of medium and large files

### ISSUE THREAD

**Issue by ReimarW** [zauberzeug/nicegui#3756]
### Description

I recently started using NiceGUI and I love it. So easy to use and yet so powerful, great job!
My problem: My WebApp includes a download button for data export. The file size varies from few MB up to 10 GB.
Everything is fine for files up to 50MB. For file sizes from 50 MB to 500 MB there is an increasingly noticeable
freeze of the event loop before the download starts. For files >= 1 GB, the event loop freezes and the download does
not start at all (no error message).

``` python
from nicegui import ui
import numpy as np


# succeeds with size = 5e8, fails with size = 1e9
def download_file(size):
    print("create bytes")
    arr = np.zeros(size, dtype="uint8")
    bytes_ = arr.tobytes()
    print("trigger download")
    ui.download(bytes_, "deleteme.dat")
    print("done")

size = int(5e8)

if {"__main__", "__mp_main__"}:
    ui.button("download", on_click=lambda: download_file(size))
    ui.button("alive?", on_click=lambda:ui.notify("alive!"))
    ui.run(show=False)
```

All three print messages, including "done" show up with no noticeable delay after the button is clicked. The button "alive" is used to check if the event loop is still alive. If you replace ``arr = np.zeros(size, dtype="uint8")`` by something CPU heavy, the problem gets significantly worse. As a minimal example, replace ``download_file`` with the following:

``` python
def task_cpu_bound(size):
    arr = np.zeros(size, dtype="uint8")
    t0 = time.time()
    while time.time() < t0 + 1.:
        arr = np.random.randint(0, 255, len(arr), dtype="uint8")
    bytes_ = arr.tobytes()
    return bytes_

# succeeds with size = 5e7, fails with size = 1e8
async def download_file(size):
        #bytes_ = await run.cpu_bound(task_cpu_bound, size)
        bytes_ = task_cpu_bound(size)
        ui.download(bytes_, "deleteme.dat")
        print("done")
```
Now, the maximum file size is only 50 MB. The attempt to download 100 MB fails with the same symptoms.
Exactly the same behavior using ``run.cpu_bound``.

I'm running my tests on a machine with 64 GB RAM. The server runs in WSL, the Browser on Windows on the same machine.

Any hint towards a workaround would be very welcome.

**Comment by rodja** [comment]
You should use FastAPI's streams instead of file objects: https://fastapi.tiangolo.com/advanced/custom-response/#using-streamingresponse-with-file-like-objects

**Comment by ReimarW** [comment]
You pointed the right direction. Thanks, rodja!
In case anyone else needs it, here is my solution:
``` python
from uuid import uuid1
from fastapi.responses import StreamingResponse
from nicegui import ui, app

CHUNK_SIZE = 1024*1024 # 1 MiB

#: {uuid: (file like or bytes, filename)}
files = {}

def download(data, filename="download"):
    uuid = str(uuid1())
    files[uuid] = (data, filename)
    ui.navigate.to(f"/download_streaming/{uuid}")

@app.get("/download_streaming/{uuid}")
def _download_streaming(uuid: str):
    data, filename = files.pop(uuid)

    def iter_file():
        with data:
            while True:
                chunk = data.read(CHUNK_SIZE)
                if chunk:
                    yield chunk
                else:
                    break

    def iter_bytes():
        for i in range(0, len(data), CHUNK_SIZE):
            yield data[i: i+CHUNK_SIZE]

    if hasattr(data, "read"):
        iter_data = iter_file
    else:
        iter_data = iter_bytes

    return StreamingResponse(iter_data(), headers={'Content-Disposition': f'attachment; filename="{filename}"'})
```
The function ``download`` allows the download of files of arbitrary size with a syntax similar to ``ui.download``.
