### ISSUE TITLE
ui.refreshable breaks when referencing element within 'with' keyword

### ISSUE THREAD

**Issue by SpyrexDE** [zauberzeug/nicegui#3760]
### Description

Example from https://nicegui.io/documentation/refreshable#local_scope_(variant_b) but with added 'with' reference as class variable.
```py
from datetime import datetime
from nicegui import ui

class Clock:
    def __init__(self, container):
        self.container = container
    @ui.refreshable
    def time(self):
        with self.container:
            ui.label(f'Time: {datetime.now()}')

@ui.page('/local_refreshable_b')
def demo():
    container = ui.chat_message('Clock', sent=True)
    clock = Clock(container)
    clock.time()
    ui.button('Refresh', on_click=clock.time.refresh)

ui.link('Open demo', demo)

ui.run()
```

Results in multiple elements being created instead of refreshed:
<img width="264" alt="image" src="https://github.com/user-attachments/assets/8427b34f-680e-48b2-bd1f-39b0f1a07922">

**Comment by python-and-fiction** [comment]
It looks like https://github.com/zauberzeug/nicegui/issues/3392

**Comment by python-and-fiction** [comment]
```python3
from datetime import datetime
from nicegui import ui

class Clock:
    def __init__(self, container):
        self.container = container
        with self.container:
            self.time()
    @ui.refreshable
    def time(self):
        ui.label(f'Time: {datetime.now()}')

@ui.page('/')
def demo():
    container = ui.chat_message('Clock', sent=True)
    clock = Clock(container)
    ui.button('Refresh', on_click=clock.time.refresh)

ui.run()
```
![image](https://github.com/user-attachments/assets/dd19cf64-5783-429b-b457-a66cd8d942e0)

**Comment by SpyrexDE** [comment]
> ```python3
> from datetime import datetime
> from nicegui import ui
> 
> class Clock:
>     def __init__(self, container):
>         self.container = container
>         with self.container:
>             self.time()
>     @ui.refreshable
>     def time(self):
>         ui.label(f'Time: {datetime.now()}')
> 
> @ui.page('/')
> def demo():
>     container = ui.chat_message('Clock', sent=True)
>     clock = Clock(container)
>     ui.button('Refresh', on_click=clock.time.refresh)
> 
> ui.run()
> ```
> ![image](https://github.com/user-attachments/assets/dd19cf64-5783-429b-b457-a66cd8d942e0)
> 
> 

In my usecase the container variable is set after the initialization of the object so your workaround won't work for me.

**Comment by python-and-fiction** [comment]
Only the element created within refreshable slot can be refreshed:
```python3
from nicegui import ui
from datetime import datetime

@ui.refreshable
def time1(container):
    with container:
        ui.label(datetime.now())

@ui.refreshable
def time2(container):
    with container():
        ui.label(datetime.now())

card1 =ui.card()

time1(card1)
time2(ui.card)

ui.button('refresh1',on_click=time1.refresh)
ui.button('refresh2',on_click=time2.refresh)

ui.run(native=True)
```
![image](https://github.com/user-attachments/assets/1b470e50-cc90-4e5d-aceb-8ecff60493da)

**Comment by python-and-fiction** [comment]
```python3
from nicegui import ui
from datetime import datetime

@ui.refreshable
def time1(container:ui.element):
    container.clear()
    with container:
        ui.label(datetime.now())

@ui.refreshable
def time2(container):
    with container():
        ui.label(datetime.now())

card1 =ui.card()

time1(card1)
time2(ui.card)

ui.button('refresh1',on_click=time1.refresh)
ui.button('refresh2',on_click=time2.refresh)

ui.run(native=True)
```

**Comment by SpyrexDE** [comment]
> Only the element created within refreshable element can be refreshed:

It makes sense, but is a bit limiting. Is there no way this functionality could be added?

**Comment by falkoschindler** [comment]
@SpyrexDE `ui.refreshable` is meant to manage its own container, which is created in the context where the decorated function or method is called. With `with self.container` you're switching into another context, which is not managed by `ui.refreshable`.

To avoid accumulating elements in `self.container`, you can simply call `self.container.clear()` before adding new elements. This also makes the use of `ui.refreshable` a bit unnecessary. Simply rename `time()` to something like `update_container()` and manage it yourself.
