### ISSUE TITLE
no UDP connection next to nicegui possible

### ISSUE THREAD

**Issue by nele8tx** [zauberzeug/nicegui#3776]
### Description

Hey there!
I tried to create an upd connection to a local host. The connection between server and client is indeed working **if** I am not using Nicegui. So I am able to create a regular Gui and also get data from my udp-connection (or use no gui at all and it all works just fine).  Therefore all my ports etc. are set correctly.

But as I change my gui to nice gui I get a timeout error and the windows error `[WinError 10048] Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden` 

```py
import asyncio
from nicegui import ui
from footer import create_footer, create_header
import os
import sys
import dsc.dev_dsc as dsc
from dsc import udp_communication as udpcom

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

udp_com = udpcom.UdpCom(target_ip='127.0.0.1')
dsc = dsc.Dsc(udp_com)

create_header()

async def ping_loop():
    while True:
        response = dsc.ping_dsc()
        print(response)
        await asyncio.sleep(2) 


ui.run(ping_loop())


ui.run()
```

Without `ui.run()` it is working just fine...

What can I do?

**Comment by rodja** [comment]
The issue arises because both `UdpCom` and `ui.run()` are set to use the same default port, which is 8080.
