### ISSUE TITLE
plotly.js improve performance and enhance integration

### ISSUE THREAD

**Issue by rbeeli** [zauberzeug/nicegui#380]
Thanks for the recent addition of the Plotly UI component, sure lots of people will use it extensively.

I think the current implementation is not optimal in terms of performance, and missing some features. It seems to me that NiceGUI is directly competing with R Shiny and Dash, and especially tailored for scientific/research visualization, dashboards etc. Hence, good integration of at least one chart library is crucial IMO.

Proposed changes:

1. Switch from Python's _json_ library to _orjson_. IMO it should be used everywhere by default as it is much faster and basically a drop-in replacement for the default _json_ library of Python.

3. Make plot definition validation optional, or even turn it off. Chart definitions can get large quickly, whether it's lots of annotations, shapes or traces, loading times can become a problem, especially in Python, as it is not the most efficient language. See `validate` parameter of the `to_json` method: `self.figure.to_json()`

5. Instead of using `json.loads` and `to_json`, which generates a JSON just to deserialize it immediately in `json.loads(self.figure.to_dict())`, consider the use of `self.figure.to_dict` directly. I have not verified whether they are functionally equal, but this would save computation time and memory, IMO worth it.

6. Allow for specification of `config` parameter of `Plotly.newPlot` method:
```Plotly.newPlot(graphDiv, data, layout, config)```
This is an important parameter, see: [https://plotly.com/javascript/configuration-options/](https://plotly.com/javascript/configuration-options/). Currently, only `data` and `layout` can be set.

7. Allow specification of Plotly chart without `go.Figure`, but instead directly providing Python-native `dict`s for `data`, `layout` and `config`. This is the most efficient way, as it circumvents validation, intermediate object creation and additional de-/serialization. `go.Figure` is certainly useful, but having support for dictionaries directly would be welcome, i.e. the `data`, `layout` and `config` parameters. This also benefits users coming from the JavaScript land, or just like the declarative creation of charts more than the OOP Python Plotly API.

8. Automatic resizing of charts if parent container size changes. This can be done using the `ResizeObserver` API/window resize event of browsers to watch for size changes. I would also add some simple throttling to not resize every millisecond, i.e. when the user resizes a window for performance reasons. Plotly charts can be resized by calling:  `Plotly.Plots.resize(plotlyInstance)`. I.e. something like this:
```
// register resize observer to auto-adjust plot size if parent container is resized
let obs = new ResizeObserver(entries => {
    if (isHidden(plotlyDiv)) return
    Plotly.Plots.resize(plotlyDiv)
})
obs.observe(plotlyDiv)
```
Of course, observer needs to be destroyed again, and throttling is missing (easy to add using `setTimeout`).

---

orjson:
- [X] use orjson in `client.build_response()`
- [X] use orjson in `element._parse_props()`
- [X] use orjson in plotly.py (not used explicitly, but implicitly because overwritten in `AsyncServer` of socket.io)
- [X] use orjson for `sio.emit` in outbox.py (overwritten in `AsyncServer` of socket.io)

plotly:
- [X] turn off plot definition validation
- [X] use `to_dict` instead of `to_json` and `json.loads`
- [X] allow specifying the `config` parameter for `newPlot`
- [X] allow calling `ui.plotly` with `data`, `layout`, and `config`
- [X] automatically resize `ui.plotly` element
- [X] fix styles of modebar (had large buttons with line-breaks)

**Comment by rodja** [comment]
Wonderful. Thats why we put so much effort in open-sourcing this lib. Your analysis and suggestions are spot on. Would you like to create a pull request. Or even better multiple ones? The steps you outlined seems to be quite disjunced.

**Comment by falkoschindler** [comment]
@rbeeli Your suggestions sound really awesome! It shows that I just started to work with plotly and don't know the library and its API very well. Just two remarks:

1\. Most of the time we pass dictionaries directly to `sio.emit`, so we don't explicitly use `json`. We need to check how to use `orjson` with FastAPI and SocketIO.

3\. Using `to_dict` directly didn't work because it contains non-serializable `ndarray`s. But maybe there is a better solution than taking the detour via `json.loads`.

**Comment by rbeeli** [comment]
@rodja I hope I find some time next week. In theory, the Plotly extensions apart from the global `orjson` switch should not take too much time.

@falkoschindler socket.io supports custom JSON serializers, see [https://python-socketio.readthedocs.io/en/latest/api.html#client-class](https://python-socketio.readthedocs.io/en/latest/api.html#client-class) parameter `json`. I think it's worth investigating it. `orjson` supports serialization of `ndarray`s, so that problem would be solved automatically:
```
>>> a = np.array([1.0,2.0,3.0])
>>> orjson.dumps(a, option=orjson.OPT_SERIALIZE_NUMPY).decode('utf-8')
'[1.0,2.0,3.0]'
```

NiceGUI should experience an immediate performance boost for almost all operations in the framework at almost no effort.

Adding custom middleware to FastAPI, or simply using `ORJSONResponse` in FastAPI should also be a rather simple change, see: [https://fastapi.tiangolo.com/advanced/custom-response/#orjsonresponse](https://fastapi.tiangolo.com/advanced/custom-response/#orjsonresponse)

**Comment by falkoschindler** [comment]
Ok, I added two task lists to the original post in order to track progress on this issue.

**Comment by rbeeli** [comment]
All discussed points have been implemented, see https://github.com/zauberzeug/nicegui/pull/437

**Comment by falkoschindler** [comment]
Hey, [fastapi-socketio](https://github.com/pyropy/fastapi-socketio) just published a new release supporting the kwargs @rbeeli used for integrating orjson. I'll re-open this issue just to remind me to remove our copy of `SocketManager`.

**Comment by rbeeli** [comment]
Nice! Change is easy, just remove the file and import it from the package, should work right away.
