### ISSUE TITLE
Native mode error on Windows

### ISSUE THREAD

**Issue by cgfxpy** [zauberzeug/nicegui#3813]
### Description

All applications made with NiceGui stopped working after refreshing the browser an error is triggered:
```
[pywebview] WebView2 initialization failed with exception:
  (0x8007139F): The group or resource is not in the right state to perform the required operation. (HRESULT exception: 0x8007139F)
   in System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   In Microsoft.Web.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d8.MoveNext()
--- End stack trace from the previous location where the exception occurred ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d26.MoveNext()
```

**Comment by falkoschindler** [comment]
Hi @cgfxpy,
_When_ did the applications stop working? How to reproduce the error? Does it even occur with a simple hello-world app?
Can you, please, try to create a minimum reproducible code example? This would allow us and the community to help more efficiently. Thanks!
[Why is it important to provide a minimal reproducible example?](https://github.com/zauberzeug/nicegui/wiki/FAQs#why-is-it-important-to-provide-a-minimal-reproducible-example)

**Comment by python-and-fiction** [comment]
@cgfxpy Have you tried pywebview's example?
```python3
import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/')
webview.start()
```
It seems that it is a problem of pywebview or your environment.

**Comment by cgfxpy** [comment]
Yes this example has the same behavior. 
I should add this error occurs when running in Pycharm and from freeze in pyinstaller when running from cmd this problem is not detected.

**Comment by rodja** [comment]
Ok. The error should be reported directly to pywebview. I'll close it here.
