### ISSUE TITLE
Issue running `nicegui` with multiprocessing on Windows

### ISSUE THREAD

**Issue by engineerjames** [zauberzeug/nicegui#3873]
### Summary 
I'm trying to get nicegui to run inside of a subprocess so that it can be easily managed (and terminated if necessary) as a Windows service.  The minimal code example below has been run on Windows 11, Python 3.11.9 with nicegui `1.4.30`.  I'm sure I'm doing something goofy...

### Expected behavior:
I expect things to run as normal when calling `ui.run` as a subprocess, and the UI to be hosted locally.

### Actual behavior:
A RuntimeError (as described in the code block).

```python
from multiprocessing import Process, freeze_support
from nicegui import ui

if __name__ in {"__main__", "__mp_main__"}:
    # Same error with or without the freeze_support() call (spawn.py:140 exception)
    # freeze_support()

    ui.label('Hello NiceGUI!')

    # Works by itself.
    # ui.run()

    # This exception happens if ran via a subprocess
    #   File "<path>\multiprocessing\spawn.py", line 140, in _check_not_importing_main
    #     raise RuntimeError('''
    # RuntimeError:
    #         An attempt has been made to start a new process before the
    #         current process has finished its bootstrapping phase.

    #         This probably means that you are not using fork to start your
    #         child processes and you have forgotten to use the proper idiom
    #         in the main module:

    #             if __name__ == '__main__':
    #                 freeze_support()
    #                 ...

    #         The "freeze_support()" line can be omitted if the program
    #         is not going to be frozen to produce an executable.

    #         To fix this issue, refer to the "Safe importing of main module"
    #         section in https://docs.python.org/3/library/multiprocessing.html
    p = Process(target=ui.run)
    p.start()
    p.join()

```
### Other things I've tried:
I've tried running it with and without freeze_support() and I get the same result, I've tried moving the process related calls outside of the `if __name__...` block.  I've tried moving the subprocess calls into a separate `main` function, etc.

**Comment by falkoschindler** [comment]
Hi @engineerjames,

Running NiceGUI in a subprocess might not be possible. We have never tried it ourselves.
You could, however, try calling `ui.run` with `reload=False` to avoid another process watching for file changes.

**Comment by engineerjames** [comment]
Thank you for the response! Ah, that's good to know--I did end up trying it with `reload=False` but with the same result.

I'll be honest I'm kind of a newb when it comes to debugging Python packages; are there any resources you could point me at that might help me investigate what the underlying issue might be?

**Comment by falkoschindler** [comment]
A workaround might be to run start a FastAPI app in a subprocess and attach NiceGUI to it:
```py
import multiprocessing
import uvicorn
from fastapi import FastAPI
from nicegui import ui

def run_server():
    app = FastAPI()
    ui.label('Hello NiceGUI!')
    ui.run_with(app)
    uvicorn.run(app)

if __name__ == '__main__':
    server_process = multiprocessing.Process(target=run_server)
    server_process.start()
    print('NiceGUI is running in a subprocess. Press Ctrl+C to stop.')
    try:
        server_process.join()
    except KeyboardInterrupt:
        print('Stopping the server...')
        server_process.terminate()
        server_process.join()
        print('Server stopped.')
```

I just don't get why it doesn't work with a simple `ui.run(reload=False)`...

**Comment by engineerjames** [comment]
@falkoschindler - This solution worked for me! I hadn't even thought to try it, so thank you.  It is odd the other approach won't work, but this will work just perfectly for what I need.  Thanks again.
