### ISSUE TITLE
Website shows Connection lost / trying to connect ... all the time

### ISSUE THREAD

**Issue by helmut-hoffer-von-ankershoffen** [zauberzeug/nicegui#3884]
### Description

Use demos embedded on homepage of https://nicegui.ui

After a few seconds <email:subject/> pops up.

**Comment by xaptronic** [comment]
Not sure - but I think this might be a question about the nicegui.io website itself, not about a particular nicegui code snippet.

If I understand the original post, I'll add that I frequently get hang-ups and long running spinners when browsing nicegui.io looking at various examples in the documentation, and will frequently see the connection lost dialog popup.

I had assumed maybe the server where this is hosted is on another continent from where I am.. but I have not looked into that at all. I am on a fibre optic line with high bandwidth etc. 

Happy to try anything to help diagnose or figure out what the issue might be.

**Comment by xaptronic** [comment]
I am located in the Ottawa area of Canada - I wouldn't describe where I am as remote...

**Comment by rodja** [comment]
Just to make sure we started another instance in Montreal. Does that improve your situation?

**Comment by xaptronic** [comment]
I just spent 10 mins or so browsing around as close to normal as I have been lately and things are seeming to be more response and I haven't seen a disconnect yet. I'll report back after some goes by and let you know if I still see any issues?
