### ISSUE TITLE
Unexpected Behavior

### ISSUE THREAD

**Issue by kwmartin** [zauberzeug/nicegui#3919]
### Description

Minimal Code:
```py
from nicegui import ui

def set_color(val):
  print(f"Color: {val}")

usr_typ_slct = ui.select(['One', 'Two', 'Three'], \
  value='One', on_change=lambda e : set_color(e.value), label='Color'). \
classes(' text-rose-600 w-[400px] p-20')

ui.run()
```
I am trying to control the padding, size, color etc. in the ui.select dropdown. It appears that .classes applies to the dropdown element, not the labels inside the drop down. No warnings are given. The width and the padding effect the dropdown, not the text inside of it. The text color doesn't seem to effect anything (i.e. the dropdown itself does not have any text, just the elements inside it - are they labels?) have text.

Finally, could someone tell me the best place to discuss/suggest improvements (i.e. is discourse better or is stackflow the place to go?). For example, every documentation element on the add_slot method is the same, but I can't find anywhere that explains slots that I can understand (my bad). It took me a long time to realize that Vue slots are completely different animals compared to Qt5 slots (I haven't been able to figure out Vue properly; again my bad; forget making custom Vue or Quasar elements or components). Also, many places use lines such as ```with ui.dialog() as self.dialog, ui.card():```. I have read everything I can find on python3 contexts, but I can't find any explanation regarding having two objects after "as". In this example, that is:  "self.dialog, ui.card()". My guess is self.dialog is the actual dialog, and ui.card() is the first element in the dialog, and it contains a group of labels?. This is a complete guess, as I can't find any explanation I can understand as how elements and slots are placed in python contexts,  especially for hierarchical components, and the fact I don't properly understand Vue (or Quasar). Finally, regarding dialogs which I have spent countless hours on, I have found a single example of using a python class to separate the dialog from opening it, but I can't find any examples of using a class for a dialog with the "await dialog" for opening it. Indeed, I have only found one example of awaiting a dialog, and I am continuously having nicegui hang on this as I can't see the dialog (i.e. it's going to some unknown slot and I can't trace where), so I can't click "Yes" or "No". I really think Nicegui might be a real good interface, but without being able to understand the documentation (mostly just one simple example, and no explanation for each feature), I'm spending man hours just doing trial and error. For example, as a workaround, I am using completely separate pages for what should be dialogs, along with ui.navigate.back(), but this is ugly. In my opinion, dialogs are the most critical component for dynamic pages. Ditto on understanding Nicegui route tables vs Fastapi (actually Starlette) route tables. Finally, I have no idea when lambda is needed in responding to events and when not (i.e. just a function, and how arguments are automatically supplied). Any help on the best approach to understanding and how to best use Nicegui with best practices would be appreciated. I dread having to put it in a docker container - which killed my firewall and TLS/SSL). I apologize for such a long "issue" and will use either discourse or stackflow in the future once someone tells me which one I should use.

**Comment by kwmartin** [comment]
Sorry, should have included:
```
def set_color(val):
  print(f"Color: {val}")
 ```

**Comment by falkoschindler** [comment]
> It appears that `.classes` applies to the dropdown element, not the labels inside the drop down.

Yes, that's right. You're calling `.classes` on the `ui.select` element, so it affects the `ui.select` element. [Quasar's QSelect](https://quasar.dev/vue-components/select) has "popup-content-class" and "popup-content-style" props for customizing the popup content. As a last resort, you can overwrite the "option" slot.

> the best place to discuss/suggest improvements

When you created this issue, you should have seen [this page](https://github.com/zauberzeug/nicegui/issues/new/choose):

<img width="877" alt="Screenshot 2024-10-24 at 17 51 47" src="https://github.com/user-attachments/assets/86411a89-dab1-40fb-8eae-dd526b3889e9">

If there's something wrong with the library, create an issue.
If you're asking for help or a new feature, create a discussion.
Discord and StackOverflow might be better to discuss with a broader audience.

> I can't find anywhere that explains slots

Let me cite from [here](https://github.com/zauberzeug/nicegui/discussions/1786#discussioncomment-7282380):

> Yes, NiceGUI is using the slot concept from Vue: Elements can have multiple slots, each possibly with a number of children. Most elements only have one slot, e.g. a `ui.card` (QCard) only has a default slot. But more complex elements like `ui.table` (QTable) can have more slots like "header", "body" and so on. If you nest NiceGUI elements via `with ui.row(): ...` you place new elements inside of the row's default slot. But if you use `with table.add_slot(...): ...`, you enter a different slot.
> 
> The slot stack helps NiceGUI to keep track of which slot is currently used for new elements. The `parent` field holds a reference to the its element. Whenever an element is entered via a `with` expression, its default slot is automatically entered as well (see `__enter__` in element.py).

Sure, this should be added to the documentation. Pull requests or suggestions for where to put it are very welcome.

> lines such as `with ui.dialog() as self.dialog, ui.card():`

This is a [Python feature](https://docs.python.org/3.1/reference/compound_stmts.html#with).
It is equivalent to
```py
with ui.dialog():
	with ui.card():
```

> regarding dialogs

I suggest you create a new Q&A discussion including a minimal reproducible example to show what you're trying to do and what doesn't work.

> I have no idea when lambda is needed

Again, please create a separate discussion including code examples which you need help with.

> I dread having to put it in a docker container

What does any of this have to do with Docker?

---

Let's close this issue. But feel free to open new discussions (Q&A, feature requests etc.) focussing on individual subjects. This makes it easier for us maintainers as well as for the community to follow, to help you and to improve the library. Thanks!
