### ISSUE TITLE
Interrupt a function called through run.io_bound()

### ISSUE THREAD

**Issue by gfrebello** [zauberzeug/nicegui#3929]
### Description

Say I have a code like this:
```py
from nicegui import ui, run
import time

def very_slow_function():
    time.sleep(100)
    print('Thank you for waiting!')

async def my_fun():
    await run.io_bound(very_slow_function)

ui.button('Run my_fun', on_click=my_fun)
ui.run()
```
I'd like the user to be able to abort the execution of `very_slow_function()` by clicking some other button if needed. Is there a simple way to accomplish this after the function has been called with `run.io_bound()`?

**Comment by rodja** [comment]
This is not strictly a NiceGUI question because `run.io_bound` is simply a wrapper around `run_in_executor`. And as far as I know, there isn't a clean way to forcefully terminate a thread in Python.
