### ISSUE TITLE
After opening in a local window, it displays blank content.

### ISSUE THREAD

**Issue by SyniLSN** [zauberzeug/nicegui#3934]
### Phenomenon
Display blank after running
### Description
I thought the program code was written incorrectly, so I used minimal functionality to reproduce the code, but the problem still occurred.
### Reproduce code
```py
from nicegui import ui
ui.label("page with custom title")
ui.run(native=True, window_size=(400, 300), fullscreen=False)
```
### System environment
python 3.11.9 64-bit, nicegui 2.5.0

**Comment by rodja** [comment]
Maybe pywebview is not correctly installed? See https://github.com/zauberzeug/nicegui/issues/2751.

**Comment by falkoschindler** [comment]
Without further information, there's not much we can do here. I'll close this issue for now.
