### ISSUE TITLE
Scoped slots are not passed to python described elements

### ISSUE THREAD

**Issue by zceemja** [zauberzeug/nicegui#3939]
### Description

This is on the same topic as #167 and #501. Here is the code to expand the idea (tested on nicegui 2.5.0):
```python
from nicegui import ui

columns = [
    {'name': 'id', 'label': 'ID', 'field': 'id'},
    {'name': 'name', 'label': 'Name', 'field': 'name'},
]
rows = [{'id': i, 'name': f'row-{i}'} for i in range(5)]

table = ui.table(columns=columns, rows=rows, row_key='id')
table.add_slot('body', r'''
<q-tr :props="props">
    <q-td key="id" :props="props">{{props.row.id}}</q-td>
</q-tr>''')

ui.run(prod_js=False)
```
And this works as expected. Props are passed down to `q-td` and is visible from vue debugging on browser:

![image](https://github.com/user-attachments/assets/d6c74b0b-6ed0-4bda-a179-2c62161d8788)

But this does not work when describing with body slot with python:
```python
...
table = ui.table(columns=columns, rows=rows, row_key='id')
with table.add_slot('body'):
    with table.row().props(':props=props'):
        with table.cell().props('key=id :props=props'):
            ...
...
```
![image](https://github.com/user-attachments/assets/ebad2af3-7b44-4bf1-bec7-cfe24446a083)
However there seems to be some disconnect (missing anonymous component?) between body slot and `QTr` and `props.row` are not accessible. 

Reason why I find this useful is that body description in python enables inserting custom vue components, and the only way I see to do it now is rewriting whole table with custom component as new combined component, which is a lot of duplicated boilerplate code.

**Comment by falkoschindler** [comment]
Hi @zceemja,

Currently there is - as far as I know - no way to use scoped slots without writing template strings. This problem is discussed in #3148 and addressed in PR #3261. Hopefully there will be a solution in the near future.

Since passing props like `.props(':props=props')` isn't expected to work, I'll close this issue.
