### ISSUE TITLE
Apache Echart not taking up container's height

### ISSUE THREAD

**Issue by EmilioGarCan** [zauberzeug/nicegui#3940]
### Description

I've tried recreating this [example chart](https://echarts.apache.org/examples/en/editor.html?c=gauge-simple) from Apache Echarts, however, when implementing it in NiceGUI, the gauge chart doesn't respond or adjust to its container's height or width, making the gauge chart appear like this:

![image](https://github.com/user-attachments/assets/9387e51d-4ce5-4883-82bc-e2155955cd7f)

Here is the minimal reproducible code:

```python
from nicegui import ui

@ui.page('/')
async def main_page():  
    with ui.row().classes('w-full h-96'): # The height of the row/container doesn't change the height of the chart
        optionsDict = {
            'tooltip': {
                'formatter': '{a} <br/>{b} : {c}%'
            },
            'series': [
                {
                'name': 'Pressure',
                'type': 'gauge',
                'progress': {
                    'show': True
                },
                'detail': {
                    'valueAnimation': True,
                    'formatter': '{value}'
                },
                'data': [
                    {
                    'value': 50,
                    'name': 'SCORE'
                    }
                ]
                }
            ]
        };
        echartGauge = ui.echart(options=optionsDict)

ui.run()
```

**Comment by falkoschindler** [comment]
Hi @EmilioGarCan,
By default `ui.echart` has a height of "16rem".
You can simply add `.classes('h-full')` to the element to have it fill the height of its parent container.
