### ISSUE TITLE
One small issue: Tailwind's flex-col doesn't work anymore

### ISSUE THREAD

**Issue by noontee0** [zauberzeug/nicegui#3955]
### Description

Flex-col is normal in version 1.4.3 * of Nicegui, but invalid in version 2.5.0

**Comment by falkoschindler** [comment]
Hi @noontee0,

It works for me:
```py
with ui.element().classes('flex flex-col'):
    ui.label('A')
    ui.label('B')
```

The container element is rendered as flexbox with direction "column". Why do you think it is not working?

In 2.0.0 we upgraded the Tailwind version. There might be edge cases that behave differently now.
