### ISSUE TITLE
touchmove, touchmove.prevent, touchstart events don't report X/Y coordinates for ui components

### ISSUE THREAD

**Issue by aabrodskiy** [zauberzeug/nicegui#3965]
### Description

While trying to implement mobile drag/drop behaviour, I ran into the fact that neither of touch events report ClientX/Y or pageX/Y into the GenericEventArguments structure, unlike the normal drag events. 
Is this a simple bug that's easy to fix, or is it some sort of limitation of the framework?

**Comment by aabrodskiy** [comment]
By trial and error I found that "pointer" group of events produces all Xs and Ys while moving, so ended up implementing those handlers and it works just fine.
```
      .on('pointerdown', lambda e, c=col: self.handle_drag_start(e, c))\
      .on('pointerup', lambda e, c=col: self.handle_drop(e, c))\
      .on('pointermove.prevent', throttle=0.2, handler=lambda e: self.handle_pointer_move_prevent(e)):
```

**Comment by falkoschindler** [comment]
Hi @aabrodskiy,

I'm not aware of a specific limitation for touch event arguments. Maybe you can share your code so that we can try to reproduce the problem more easily?

You mention you're implementing a mobile interface. Maybe it's a limitation of Safari. They don't seem to support touch events: https://developer.mozilla.org/en-US/docs/Web/API/Touch_events#browser_compatibility. So maybe pointer events are the better option anyway.

**Comment by falkoschindler** [comment]
This issue seems stale, so I'll close it for now. Feel free to re-open it with more information or even a code example.

**Comment by aabrodskiy** [comment]
Hi @falkoschindler , 
Apologies, I've let this slip away.. Maybe you are right and pointer events are the better option anyway, I've implemented with them and it works.
It does feel though more like a workaround as I have to calculate relative position of the dragged element over the background to imitate the "mouseover" part and highlight the background containers that can accept the dropping. Not ideal, but it seems there isn't a better solution.

This is my code now, if anyone comes across this issue and finds it any helpful. I deleted the parts where I tried the touch events, so unfortunately don't have those anymore to post for reproducing, sorry..
```python
    async def get_touch_target(self, event):
            self.final_y = event.args['clientY']
            index_diff = int((self.final_y - self.initial_y) / 24)
            siblings = event.sender.parent_slot.children
            new_index = self.initial_index + index_diff
            if new_index < 0:
                new_index = 0
            elif new_index >= len(siblings):
                new_index = len(siblings) - 1
            return self.column_order[new_index], siblings[new_index]

    async def reorder_columns(self, dragged_column: str, target_column: str):
        try:
            if dragged_column != target_column and dragged_column and target_column:
                # print(f"Reordering columns: {dragged_column} -> {target_column}")
                old_index = self.columns.index(dragged_column)
                new_index = self.columns.index(target_column)
                
                # Reorder the list
                self.columns.insert(new_index, self.columns.pop(old_index))

                self.render_column_list.refresh()
                await self.callback(self.columns)
                
        except Exception as e:
            print(f"Error reordering columns: {e}")
```
