### ISSUE TITLE
scene.point_cloud() doesn't parse the cloud properly

### ISSUE THREAD

**Issue by bhomaidan1990** [zauberzeug/nicegui#3971]
### Description

I want to visualize the [bunny point cloud](https://github.com/naucoin/VTKData/blob/master/Data/bunny.ply) using NiceGUI, here is the code that I'm using:
```py
import numpy as np
import open3d as o3d
from nicegui import ui

pcd_scene = ui.scene()

pcl_path = "bunny.ply"
cloud = o3d.io.read_point_cloud(pcl_path)
pts = np.asarray(cloud.points)
# o3d.visualization.draw_geometries([cloud])

pcd_scene.axes_helper()
pcd_scene.point_cloud(points=pts, point_size=0.1)

ui.run(show=False)
```
but as you can see the result is not OK, can you please tell me how I can fix that? thanks

![Screenshot from 2024-11-10 20-30-20](https://github.com/user-attachments/assets/1f1eefdf-dd10-42d0-a5ba-8dd9c8521e04)

**Comment by falkoschindler** [comment]
Hi @bhomaidan1990,

I think the bunny is alright. It just needs a smaller point size, maybe some color and can be scaled and turned up:
```py
cloud = o3d.io.read_point_cloud('/Users/falko/Downloads/bunny.ply')
pts = np.asarray(cloud.points)

with ui.scene() as scene:
    scene.point_cloud(pts, point_size=0.001).material('silver').scale(20).rotate(3.14 / 2, 0, 0)
```

<img width="397" alt="Screenshot 2024-11-11 at 07 18 07" src="https://github.com/user-attachments/assets/f2609b1d-6f6e-4a52-9220-c5482c16cf9e">

**Comment by bhomaidan1990** [comment]
@falkoschindler thanks
