### ISSUE TITLE
RuntimeError: app.storage.user needs a storage_secret passed in ui.run() with example

### ISSUE THREAD

**Issue by nhatnamt** [zauberzeug/nicegui#3972]
### Description

When using the example counting page visit in the documentation page, an exception is thrown (as per title). Similar behaviour when using app.storage.browser.

```py
from nicegui import app, ui

@ui.page('/')
def index():
    app.storage.user['count'] = app.storage.user.get('count', 0) + 1
    with ui.row():
       ui.label('your own page visits:')
       ui.label().bind_text_from(app.storage.user, 'count')

ui.run(storage_secret='private key to secure the browser session cookie')
```

**Comment by rodja** [comment]
Hello @nhatnamt. Are you sure you are using the exact code as shown above? It works for me...

**Comment by nhatnamt** [comment]
Hi @rodja, turns out my nicegui installation was corrupted somehow. Reinstalling the package fixes the issue.
