### ISSUE TITLE
Problems with nicegui 1.1.8

### ISSUE THREAD

**Issue by frwkl** [zauberzeug/nicegui#398]
Hello guys, thank you for the very nice work.
After i installed the new version of nicegui 1.1.8 and start my app, i got the following error:

from fastapi.dependencies.models import Dependant 
No module named 'fastapi.dependencies'

I never import this module in my code
After reinstall nicegui 1.1.6. the app works fine.
Where can i find the failure.
Thx in advance for help.

**Comment by rodja** [comment]
Thats strange. We upgraded to latest [FastAPI 0.92.0](https://github.com/tiangolo/fastapi/releases/tag/0.92.0) in our 1.1.8 release to apply a vulnerability bugfix in Starlette. Can you confirm that after installing the latest version of NiceGUI, you also have the latest FastAPI version installed? Does anyone else experience this issue?

**Comment by frwkl** [comment]
Ok. I see it that way too. Since I get different errors after several attempts. I will try it tomorrow with another machine and report the result to you.
Thank you for the quick answer.

**Comment by frwkl** [comment]
Good evening. I went the short route and recreated the virtual environment, installed nicegui 1.1.9 and everything is working again. Thanks for that.
