### ISSUE TITLE
Task exception was never retrieved nicegui 2.5.0

### ISSUE THREAD

**Issue by pumtechai** [zauberzeug/nicegui#3983]
### Description

```
Task exception was never retrieved
future: <Task finished name='Task-55' coro=<AsyncServer._handle_event_internal() done, defined at E:\my_projects\portfolio\venv\lib\site-packages\socketio\async_server.py:605> exception=TypeError('string indices must be integers')>
Traceback (most recent call last):
File "E:\my_projects\portfolio\venv\lib\site-packages\socketio\async_server.py", line 607, in _handle_event_internal
r = await server._trigger_event(data[0], namespace, sid, *data[1:])
File "E:\my_projects\portfolio\venv\lib\site-packages\socketio\async_server.py", line 634, in _trigger_event
ret = await handler(*args)
File "E:\my_projects\portfolio\venv\lib\site-packages\nicegui\nicegui.py", line 167, in _on_handshake
client = Client.instances.get(data['client_id'])
TypeError: string indices must be integers
```

**Comment by falkoschindler** [comment]
@pumtechai Please follow the instructions you have read when creating this issue:

> Make sure it is really an issue (see [FAQs](https://github.com/zauberzeug/nicegui/wiki/FAQs)).
> A lot of people will read your message.
> Make it worth their time.
> 
> 1. What are you trying to do?
>     If possible, give a [minimal reproducible code example](https://en.wikipedia.org/wiki/Minimal_reproducible_example).
>     Put source code in [fenced code blocks with syntax highlighting](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting).
> 2. What do you expect to happen?
> 3. What happens instead?
