### ISSUE TITLE
Button has non intended 1px background

### ISSUE THREAD

**Issue by phifuh** [zauberzeug/nicegui#4002]
### Description

There is a visible bug on buttons:

```python
ui.button('', icon='delete', color="bg-transparent").classes('size-px p-0 mr-4 hover:bg-transparent')
```

If you hover the button you still see a 1px vertical line even tho it should be transparant

![image](https://github.com/user-attachments/assets/34a105ba-849a-48a7-8d97-d88c8273230e)

**Comment by falkoschindler** [comment]
Hi @phifuh,

I think the 1px line is the remainder of the focus indicator which appears when hovering a button:

![Nov-18-2024 10-21-04](https://github.com/user-attachments/assets/4ef84f82-ea09-492e-aef7-eca4f59bbb40)

But I don't know how to disable it. It should be a Quasar problem, independent of NiceGUI. So you might find answers from the Quasar community.
