### ISSUE TITLE
html.tr element is missing

### ISSUE THREAD

**Issue by kleynjan** [zauberzeug/nicegui#4005]
### Description

No biggie, but it seems like this line is missing in html.py:
```python
tr = _create_html_element('tr')
```

So in a table constructed with the html module I still have to resort to:
```python
with html.table():
   with ui.element('tr):
      with html.td():
          ...
```

**Comment by falkoschindler** [comment]
Oh, thanks for spotting this, @kleynjan!
I wonder how this one got lost... Should be fixed by https://github.com/zauberzeug/nicegui/commit/1f78c863e7e2f3baaed03148ddc4e021f83eef97.
