### ISSUE TITLE
ui.number validation not working on load

### ISSUE THREAD

**Issue by kraftto** [zauberzeug/nicegui#4006]
### Description

I want to create a mandatory ui.number() input element via a validation rule:

```python
from nicegui import ui

ui.number(
    value=None,
    precision=0,
    format="%d",
    validation={"required": lambda x: x is not None},
).props("clearable")

ui.run(port=8888)
```

I expect the validation error to trigger on loading the element (as it is the case with `ui.input()`), but it only appears when I enter a number and then use the clear button.

Using nicegui v2.5.0.

**Comment by kraftto** [comment]
Btw, kudos for this project :)

**Comment by falkoschindler** [comment]
Hi @kraftto,

Validation is often not expected to run _after_ the user had the chance to enter something (like [here](https://quasar.dev/vue-components/input#example--basic)).
But you can simply trigger the validation explicitely:
```py
number = ui.number(precision=0, validation={"required": lambda x: x is not None})
number.validate()
```

**Comment by kraftto** [comment]
Thanks!
