### ISSUE TITLE
Search as you type example link is wrong

### ISSUE THREAD

**Issue by SebastienDorgan** [zauberzeug/nicegui#401]
Hi,

The link in the Home page, section Pick your solution/Search as you type is:
- https://github.com/zauberzeug/nicegui/tree/main/examples/search_as_you_type/ 

But should be:
- https://github.com/zauberzeug/nicegui/tree/main/examples/search-as-you-type/

**Comment by rodja** [comment]
Thanks @SebastienDorgan for pointing this our. Is fixed now.
