### ISSUE TITLE
Regression: Codemirror syntax highlight broken in 2.0+

### ISSUE THREAD

**Issue by JeppeKlitgaard** [zauberzeug/nicegui#4014]
### Description

After updating to 2.0+ (2.5 specifically), I have noticed that the codemirror syntax highlighting has stopped working. I thought it was something wrong on my end, but it appears to also be broken on the official nicegui documentation: [NiceGUI docs](https://nicegui.io/documentation/codemirror).

**Comment by falkoschindler** [comment]
Hi @JeppeKlitgaard,

It seems like some themes don't include syntax highlighting, like the default "basicLight". But it works for others like this:

```py
ui.codemirror('print(42)', language='Python', theme='vscodeLight')
```

![Screenshot 2024-11-20 at 15 25 52](https://github.com/user-attachments/assets/16fa7ffb-505b-47ca-99fa-c916963c49e5)

**Comment by JeppeKlitgaard** [comment]
Thank you so much for having a look! You're absolutely right, of course - apologies that I missed this.

I believe the default theme used to have syntax highlighting - maybe the new default should as well?

Either way, the problem has been solved - thank you for your support!
