### ISSUE TITLE
Editable table example not working properly

### ISSUE THREAD

**Issue by Zironics** [zauberzeug/nicegui#4029]
### Description

In the example for the editable table, there is the function rename that triggers when a column value is updated but it doesn't seem to be working correctly as I'm not getting the notification that the row has changed, i tried debugging but it seems like the function isn't being called at all.

**Comment by falkoschindler** [comment]
Hi @Zironics,

I can't reproduce any problem with this example. After changing a name I get a notification:
<img width="489" alt="Screenshot 2024-11-24 at 09 39 44" src="https://github.com/user-attachments/assets/35b71384-284c-44f5-b496-16fc21ba8720">

Maybe you can check with different browsers?

**Comment by Zironics** [comment]
i just tested again and it's also working for me now not sure what happened yesterday :sweat_smile:
