### ISSUE TITLE
Able to type to disabled Input element when using User Fixture in testing

### ISSUE THREAD

**Issue by randy-seng** [zauberzeug/nicegui#4080]
### Description

First up, thank you for creating and maintaining this great project! 

## Description
I am using the User Fixture to write UI tests. I am trying to simulate typing to a **disabled** `Input` element using the User Fixture. 

## Version Information
* Python 3.11.9
* nicegui==2.8.1
* pytest==8.3.2
* pytest-asyncio==0.24.0

## Minimum Reproducible Example

```python
import pytest
from nicegui import ui
from nicegui.testing import User

MARKER_INPUT = "marker-input"


def build_ui() -> None:
    @ui.page("/")
    def page() -> None:
        with ui.input(label="My Input") as input_element:
            input_element.disable()
            input_element.mark(MARKER_INPUT)


@pytest.fixture
async def my_user(user: User) -> User:
    build_ui()
    await user.open("/")
    return user


@pytest.mark.asyncio
async def test_type_to_disabled_input(my_user: User) -> None:
    my_user.find(marker=MARKER_INPUT).type("Hello World!")
    await my_user.should_not_see("Hello World!")

```

## Expected Result
I expect the **disabled** `ui.input` element's value not to be changed when using `UserInteraction.type`. 

## Actual Result
But `UserInteraction.type` changes the `ui.input` element's value although it is disabled.

**Comment by rodja** [comment]
Nice catch @randy-seng. It should be easy to add here:

https://github.com/zauberzeug/nicegui/blob/redis-storage/nicegui/testing/user_interaction.py#L62

Would you like to give it a try? We always look forward to see new contributions to the code base.

**Comment by randy-seng** [comment]
@rodja Thanks for the opportunity! I’d be happy to contribute and give this a try.
