### ISSUE TITLE
user fixture incompatible with httpx >= 0.28.0

### ISSUE THREAD

**Issue by jychp** [zauberzeug/nicegui#4094]
### Description

The requirements is defined as follow
`httpx >= 0.24.0`

In httpx versio >= 0.28.0, AsyncClient no longer accept the "app" parameter in `__init__` function.

Workarround: adding a constraint on max version (<=0.27.2)

Documentation: https://www.python-httpx.org/api/#asyncclient
![Screenshot from 2024-12-12 17-06-55](https://github.com/user-attachments/assets/9c1b0a0b-704e-409e-bee9-46a23060938c)

**Comment by falkoschindler** [comment]
Hi @jychp,

This should have been fixed with PR #4048 in version 2.8.0. What version are you using?
