### ISSUE TITLE
datetime vars in app.storage.user are str after app restart

### ISSUE THREAD

**Issue by kleynjan** [zauberzeug/nicegui#4152]
### Description

In general, app.storage.user seems to work reliably, also across application restarts. But there seems to be a (recent?) issue with the persistence of datetime in app.storage.

See code below. 

1. Click on "SET" button. 
2. Reload the page. 
3. Assert that the some_dt type is 'datetime.datetime'. 
4. Stop and restart the app. 
5. Reload the page if necessary: some_dt type is now 'str'. 
 
For contrast, the 'some_dict' dict is correctly persisted.

```python
from nicegui import ui, app
from datetime import datetime

@ui.page('/')
def index():
    def do_set():
        app.storage.user['some_dt'] = datetime.now()
        app.storage.user['some_dict'] = {'a': 1, 'b': 2}

    dt = app.storage.user.get('some_dt')
    ui.label(f"{dt=} type: {type(dt)}")
    d = app.storage.user.get('some_dict')
    ui.label(f"{d=} type: {type(d)}")

    ui.button("Set", on_click=do_set)

ui.run(storage_secret="abracadabra")
```
This is on NiceGUI 2.9.0

**Comment by frankvp11** [comment]
I wonder if it's because it saves it to JSON.
I forget where tbh, but NiceGUI stores the app.storage.* inside JSON files. I think what might be happening is that when it reads the user's storage from that JSON file, it reads it as a string (since JSON can't store datetime objects).

**Comment by rodja** [comment]
@frankvp11 that's right. By default, the persistence is stored inside the `.nicegui` directory in the project root folder. I suggest you only store a iso string and convert it back to `datetime` if you read it:

```py
@ui.page('/')
def index():
    def do_set():
        app.storage.user['some_dt'] = datetime.now().isoformat()

    dt_str = app.storage.user.get('some_dt')
    dt = datetime.fromisoformat(dt_str) if dt_str else None
    ui.label(f"{dt=} type: {type(dt)}")

    ui.button("Set", on_click=do_set)
```

We should switch to `orjson` to serialize the storage data. `orjson` can handle datetime objects natively and serialize them automatically. Who would like to provide a pull request?

**Comment by frankvp11** [comment]
Doesn't it already? Looking at nicegui's [json](https://github.com/zauberzeug/nicegui/blob/09f4c34049b37907174bfe3109aae4b834f80863/nicegui/json/orjson_wrapper.py) folder, it has a wrapper for orjson, just needs you to have it installed...
Besides that, I'm not sure where it would be getting serialized.

**Comment by frankvp11** [comment]
Also, it doesn't appear to be the case that orjson will automatically de-serialize into datetime objects. 
You can refer to [their docs](https://github.com/ijl/orjson?tab=readme-ov-file#deserialize), and try this snippet
```
from datetime import datetime

import orjson

json_bytes = (orjson.dumps(datetime.now()))
print(json_bytes)
print(orjson.loads(json_bytes))
```

**Comment by kleynjan** [comment]
Exactly @frankvp11, it seems I was "naive" (bad pun here) to expect datetime deserialization anyway.

As @rodja pointed out, it may be better to use str's rather than dt's - both going in and coming out. Not rely on any implicit datetime stuff. 

Anyhow, workarounds are easy enough. Thanks for helping out! Closing the issue.
