### ISSUE TITLE
Add SSL parameters to ui.run

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#421]
In https://github.com/zauberzeug/nicegui/discussions/387 We noticed that it's rather tricky to start NiceGUI with SSL key and certificate. We could easily add those parameters to `ui.run`.
But there are [so many more uvicorn parameters](https://github.com/encode/uvicorn/blob/188679ecbba2474395a35bbd84970126a6c5e7ca/uvicorn/main.py#L453-L500)... Should we simply forward arbitrary keyword arguments to uvicorn?

**Comment by falkoschindler** [comment]
I'm afraid there is currently no way to add a button to a 3D scene. But using click events you might be able to create a similar user interaction:

```py
from nicegui import events, ui

def handle_click(event: events.SceneClickEventArguments) -> None:
    ui.notify(f'{event.click_type} on {event.hits[0].object_name or event.hits[0].object_id}', flush=True)

with ui.scene(on_click=handle_click) as scene:
    scene.sphere().with_name('sphere')

ui.run()
```

The `SceneClickEventArguments` object contains information about click type (e.g. double click), mouse button and modifier keys. And the `hits` field contains a list of hit objects starting with the one closest to the camera. See https://threejs.org/docs/#api/en/core/Raycaster for more details.

**Comment by morningstarsabrina** [comment]
`Should we simply forward arbitrary keyword arguments to uvicorn?`
I think its a good idea however I presume that we will not have code autocompletion for thses parameters

**Comment by falkoschindler** [comment]
Ok, I added support for additional keyword arguments.
You're right, we don't have auto-completion for those. But I don't see how to get that without adding each parameter individually.

**Comment by morningstarsabrina** [comment]
👍
