### ISSUE TITLE
Add guide on how to develop/contribute to nicegui

### ISSUE THREAD

**Issue by rbeeli** [zauberzeug/nicegui#432]
I'm looking for a simple guide showing the most important commands and setup steps to develop/extend nicegui. Not how to use GitHub, but actually working inside the project. With various Docker files, poetry etc., it's a bit confusing for me. Also, how would I run the automated tests on Linux/Ubuntu? It only shows Mac in `tests/README.md`.

Simple guide, common use cases / commands would already help to quickly get started.

**Comment by rodja** [comment]
Thank you very much for this request. This was long overdue. I've just pushed a updates to [contributing.md](https://github.com/zauberzeug/nicegui/blob/main/CONTRIBUTING.md) and [tests/README.md](https://github.com/zauberzeug/nicegui/blob/main/tests/README.md). Please have a look and tell me what you think. Is anything missing? Where could it further be improved.

Also note that I have not tested the test setup instructions  for Linux and Windows. Would be great if someone from the community could verify it.

**Comment by rbeeli** [comment]
Thanks for the updates. Tried my first pull request, see: https://github.com/zauberzeug/nicegui/pull/436

Question, for the local dev scenario, you write "Python 3", whereas in the Docker case, you specifically limit to 3.7.
Must local development also use 3.7, or is it not at all an issue to use, e.g. Python 3.10?

Also, just running `python3 -m pip install -e .` does not install the dev-dependencies, e.g. `pytest`. What is the correct command there to also install the dev-dependencies?

**Comment by rodja** [comment]
> Must local development also use 3.7, or is it not at all an issue to use, e.g. Python 3.10?

No. We are developing mainly in 3.11. But this means we sometimes miss some incompatibilities with 3.7. But the GitHub Actions are uncovering it. Also we use the 3.7 docker in cases where we are not sure.

> Also, just running python3 -m pip install -e . does not install the dev-dependencies

True. We've just installed these by hand. Not "nice" but we use them everywhere so we mostly do not notice anymore. Maybe there is a way? Using poetry is also an option but that does not allow you to use the local modified directory as package in other projects...
