### ISSUE TITLE
Provide global exception handler

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#445]
In #289 we got the idea of providing an `app.on_exception` event which can be used for registering a custom exception handler, either for showing notifications, logging to a file or whatever.

**Comment by smojef** [comment]
Ideally, users would want an easy way of displaying exceptions.  Some ideas:
- A simple one-liner to show exceptions, like `app.on_exception(ui.exceptions_dialog)`.
- Maybe this behavior should even be the default, and we could revert to the previous behavior with `app.on_exception(None)`. 
- Further ideas about `ui.exceptions_dialog`: 
  - It could display the exception with meaningful info, like an expansible stack trace in `<pre>`.
  - It could handle fast repeating exceptions without filling the screen (unlike `ui.notify`).
  - It could even be a small warning icon popup, that when clicked shows the dialog exceptions details.
  - It could even mention "Developers can hide exceptions with `app.on_exception(None)`" for transition if required.
  - Looking at its source, users could customize and create their own dialog/handler if required.

**Comment by smojef** [comment]
Great! You are absolutely right.  The `app.on_exception` is the most important.  I can't wait to try it.  Thanks,

**Comment by groucho86** [comment]
Can someone please write up a small sample where ui.notify is used to show a raised Exception?

**Comment by falkoschindler** [comment]
@groucho86 

```py
from nicegui import app, ui

app.on_exception(ui.notify)
ui.button('Do something impossible', on_click=lambda: print(1 / 0))

ui.run()
```

**Comment by groucho86** [comment]
@falkoschindler thank you! That works beautifully, but I'm struggling with utilizing it with asyncio.

It could be useful to show error handling in some of the examples, eg. ffmpeg_extract_images, script_executor, etc.
