### ISSUE TITLE
Link examples don't work in Firefox

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#45]
This is probably related to #42. The examples which show how to navigate to different pages (https://nicegui.io/#link, https://nicegui.io/#page) don't work in Firefox, the page is simply reloaded. In Edge they work correctly.

**Comment by falkoschindler** [comment]
I think I found a more reliable solution. Using `window.onbeforeunload` we can when the client want's to change the location. Setting a flag `unloading` we can react (or *not* react) accordingly when the socket connection is closed.

https://github.com/zauberzeug/nicegui/commit/aa2b30cfc6fed7a41ac00398dfb967915a29a0f9

The fix will be available with the next release.
