### ISSUE TITLE
Unable to limit options in Date Input

### ISSUE THREAD

**Issue by kazaarun** [zauberzeug/nicegui#457]
I am trying to limit date options in the Date Input element by passing a list of acceptable dates, as required by the _options_ prop in [QDate](https://quasar.dev/vue-components/date#limiting-options). But this has no effect on the component. If I understand correctly from the source code, the _props_ function can only parse the string input to a `dict[str, str]`.
Would it be possible to allow _props_ to parse lists or are there other ways to limit date options?

Example code:
```py
from nicegui import ui

date_options = ['2023-01-01', '2023-01-12', '2023-01-17']

ui.date(value='2023-01-01').props(f"options={date_options}")

ui.run()
```

**Comment by falkoschindler** [comment]
Good question! As far as I can tell, there are multiple layers to the problem:

1. The argument `f"options={date_options}"` results in the string "options=['2023-01-01', '2023-01-12', '2023-01-17']" which is incorrectly parsed into the props dictionary. Values containing whitespace need to be wrapped in quotes: `f'options="{date_options}"'`.

2. This still converts the array into a string, but Quasar expects an array. We can workaround this limitation by setting the dictionary value directly:

    ```py
    d = ui.date(value='2023-01-01')
    d._props['options'] = ['2023-01-01', '2023-01-12', '2023-01-17']
    ```

3. But this still doesn't work and I haven't found out why. 🫤

**Comment by falkoschindler** [comment]
Oh hey, I found a solution! It turns out the dates have to be in YYYY/MM/DD format:

```py
d = ui.date(value='2023-01-01')
d._props['options'] = ['2023/01/01', '2023/01/12', '2023/01/17']
```

You can even use the `.prop()` method. Here the options are a list of strings wrapped in double quotes to guide the props parser:

```py
ui.date(value='2023-01-01').props('''options="['2023/01/01', '2023/01/12', '2023/01/17']"''')
```

Or using the `date_options` list from the original post:

```py
date_options = ['2023/01/01', '2023/01/12', '2023/01/17']
ui.date(value='2023-01-01').props(f'options="{date_options}"')
```
