### ISSUE TITLE
Using keyword arguments from Quasar's API in ui.notify() don't work

### ISSUE THREAD

**Issue by MrTLMWD** [zauberzeug/nicegui#458]
When running the following code:

```python
from nicegui import ui

ui.button(f"Press for notification",on_click=lambda:ui.notify(message="I'm an error-message!",type="negative",caption="Captions dont't work.",textcolor="warning"))

ui.run()
```

The notification is of type error with the correct message, but uses none of the optional arguments. The [documentation](https://nicegui.io/reference#notification) says, that you can pass all keyword arguments mentioned in [Quasar's API for notifications](https://quasar.dev/quasar-plugins/notify#notify-api). Am I missing something?

**Comment by falkoschindler** [comment]
Thanks a lot for reporting this issue, @MrTLMWD!

There was indeed a bug in `ui.notify` which should be fixed now in [64d9e7d](https://github.com/zauberzeug/nicegui/commit/64d9e7dbb2bb9df7e507c21caddf0768e60aa576).

Note: According to [the documentation](https://quasar.dev/quasar-plugins/notify) there is an uppercase "C" in `textColor`.
