### ISSUE TITLE
Optional parameter on_disconnect for Page

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#46]
According to https://nicegui.io/#page, it's possible to supply `on_connect` callback which fires when the page is opened. But there is no corresponding `on_disconnect` callback. JustPy (which NiceGUI is built on) has such option: https://justpy.io/reference/webpage/#on_disconnectself-websocketnone

Is it possible to add this feature to NiceGUI?

**Comment by me21** [comment]
It's possible to work around this by:

```
class MyPage(ui.page):
    def __init__(self,
                 route: str,
                 title: Optional[str] = None,
                 favicon: Optional[str] = None,
                 dark: Optional[bool] = ...,
                 classes: str = 'q-ma-md column items-start',
                 css: str = HtmlFormatter().get_style_defs('.codehilite'),
                 on_connect: Optional[Callable] = None,
                 on_disconnect: Optional[Callable] = None,
                 ):
        super(ManualTestPage, self).__init__(route, title, favicon, dark, classes, css, on_connect)
        self.on_disconnect_handler = on_disconnect

    async def on_disconnect(self, websocket=None):
        await super().on_disconnect(websocket)
        if self.on_disconnect_handler:
            self.on_disconnect_handler()
```

**Comment by falkoschindler** [comment]
Thanks for your suggestion (and your patience)!
I finally found the time to add the new argument to the NiceGUI page. For symmetry, I also introduced `ui.on_disconnect`, which collects page-independent handlers for whenever a client disconnects.
The feature will be available with the next release.

https://github.com/zauberzeug/nicegui/commit/30fb1e56d73dcdc6c42850810c784bacd28b7c59
