### ISSUE TITLE
ui.keyboard doesn't register input when focusing some UI-elements

### ISSUE THREAD

**Issue by MrTLMWD** [zauberzeug/nicegui#460]
Using the following code, I found an issue with some of the UI-elements combined with `ui.keyboard`:

```python
from nicegui import ui
from nicegui.events import KeyEventArguments

def handle_key(e: KeyEventArguments):
    if e.action.keydown and not e.action.repeat:
        ui.notify(f"{e.key} was just pressed!")

keyboard = ui.keyboard(on_key=handle_key)
ui.label("With focus on the following elements, ui.keyboard can't capture key events:")
ui.button('Just for focus',on_click=lambda: ui.notify('Clicked!'))
ui.input("Input field")
ui.toggle(['A','B','C'])
ui.select([1, 2, 3], value=1)

ui.label("With focus on these elements, ui.keyboard can capture key events:")
ui.radio(['A','B','C'])
ui.checkbox('Track key events',value=True).bind_value_to(keyboard, 'active')

ui.run()
```
If you use Tab / Shift+Tab to navigate between elements and you focus the above mentionend elements, `ui.keyboard` doesn't capture keyboard inputs anymore. It's more obvious, when pressing 'f' on each element (or on `ui.input`, something like Control or Shift).

I found this issue when clicking an button and then pressing 'Enter', resulting in clicking it again. I'm using `ui.keyboard` to capture the input of an barcode scanner without keeping focus on an input-field. The barcode scanner sends an 'Enter'-press after each successful scan. I don't need that feature of my barcode scanner for my use case, but as a work-around I would need to click anywhere on the website every time I clicked a button (or deactivate the feature on my barcode scanner, which I'm trying to figure out).

**Comment by falkoschindler** [comment]
Thanks for bringing this up, @MrTLMWD!
This is mainly due to a filter that ignores key events when certain elements are focussed:

https://github.com/zauberzeug/nicegui/blob/fbc878aa6ce9c43539d8d6a4ae670512bfe4deeb/nicegui/elements/keyboard.js#L5-L8

In our use cases we want to steer some robot using certain letter keys, but don't want to continue sending hardware commands when the user is typing in a text input field.

We should make this filter configurable and add some documentation, so that the behavior is more transparent.

**Comment by falkoschindler** [comment]
Commit [6632602](https://github.com/zauberzeug/nicegui/commit/66326029aa2955815917e388175647fbcf29534d) solves this issue by making the list of ignored elements configurable. To get all key events, even if a button or an input element is focussed, you can pass an empty list:

```py
keyboard = ui.keyboard(on_key=handle_key, ignore=[])
```
