### ISSUE TITLE
[OFFICIAL SITE] Strange Font

### ISSUE THREAD

**Issue by angelhdzmultimedia** [zauberzeug/nicegui#462]
![image](https://user-images.githubusercontent.com/10191085/223297317-1721fa45-7197-496c-93e6-1ee23a4eea35.png)

I solved it temporarily by modifying the CSS in the developers settings removing  all traces of "Fira Code" in font-family. But it's strange, because I have Fira Code installed in my Windows 11 and it doesn't look cursive.

**Comment by angelhdzmultimedia** [comment]
### Update

It's Fira Sans, not Fira Code.

I thought I solved it by installing all Fira Sans font family, but I still get that illegible cursive font.

**Comment by ItsCubeTime** [comment]
Certainly doesnt look like that for me. I would try with a different browser

**Comment by angelhdzmultimedia** [comment]
Yeah, An issue with Chrome. Working with Firefox.
![image](https://user-images.githubusercontent.com/10191085/223309497-419f9595-1e69-4976-a46d-a96e3616a429.png)

Now I'm really wondering what can be wrong because it's only happening with this website. 
I'll try clearing the cache. Thank  you!

**Comment by angelhdzmultimedia** [comment]
It's strange. Happening on Edge too.

![image](https://user-images.githubusercontent.com/10191085/223315335-bae23538-43ab-48e0-87c1-d07a192a6da5.png)

**Comment by rodja** [comment]
Could you open the developer console and have a look at the console output and network traffic. NiceGUI should serve the fira sans font:

<img width="1501" alt="Screen Shot 2023-03-07 at 05 24 13" src="https://user-images.githubusercontent.com/131391/223320490-f6c582cf-2ace-47b6-b025-66fb84fe9d58.png">

**Comment by angelhdzmultimedia** [comment]
> Could you open the developer console and have a look at the console output and network traffic. NiceGUI should serve the fira sans font:
> 
> <img alt="Screen Shot 2023-03-07 at 05 24 13" width="1501" src="https://user-images.githubusercontent.com/131391/223320490-f6c582cf-2ace-47b6-b025-66fb84fe9d58.png">

Thank you so much for your time and energy.

I get 3 fonts request, but not of them seems to be fira sans:

![image](https://user-images.githubusercontent.com/10191085/223443528-aca21be4-b7e4-4785-bd56-5cc4988ea9d7.png)

![image](https://user-images.githubusercontent.com/10191085/223443705-6d4ec6f6-c3fd-4ca4-8865-5a39c622c16e.png)

**Comment by angelhdzmultimedia** [comment]
![image](https://user-images.githubusercontent.com/10191085/223444322-956baf58-2dbb-4b2a-9474-ffd058fbe408.png)

**Comment by falkoschindler** [comment]
Very strange. The requests in your screenshot are Roboto fonts. It looks like the font definitions in style.css don't work: https://github.com/zauberzeug/nicegui/blob/fbc878aa6ce9c43539d8d6a4ae670512bfe4deeb/website/static/style.css#L116-L176

So the font family uses Roboto instead of Fira:
https://github.com/zauberzeug/nicegui/blob/fbc878aa6ce9c43539d8d6a4ae670512bfe4deeb/website/static/style.css#L6

But even the Roboto fallback should yield _such_ an odd font. I'm a bit lost.

**Comment by angelhdzmultimedia** [comment]
Incognito, no extensions, same issue...

![image](https://user-images.githubusercontent.com/10191085/223611347-ebbf1ed7-716a-4288-9782-12e2b7a533d1.png)

**Comment by rodja** [comment]
Could you paste the source code of `index.html` as it was received by the browser? This will be the response content of "nicegui.io" in the network debug section. I wonder how the browser comes up with this strange font names...

**Comment by falkoschindler** [comment]
@rodja The "strange" font names are defined in fonts.css and represent Roboto variants. For me it looks like "Fira" is not found and Roboto takes over.

**Comment by rodja** [comment]
Ah, I missed that. Thanks @falkoschindler. Asking ChatGPT here are two other things we should rule out:

1. The user may have a font substitution plugin installed: Some users may have a font substitution plugin installed, which replaces fonts on websites with a different font of their choosing. There is little you can do in this case other than to recommend that the user disables the plugin or adds your website to a whitelist.
2. The user may have a custom font setting in their browser: Some browsers allow users to set a custom font for all websites. In this case, the user may need to adjust their browser settings to ensure that your website displays the correct font.

**Comment by angelhdzmultimedia** [comment]
> Ah, I missed that. Thanks @falkoschindler. Asking ChatGPT here are two other things we should rule out:
> 
> 1. The user may have a font substitution plugin installed: Some users may have a font substitution plugin installed, which replaces fonts on websites with a different font of their choosing. There is little you can do in this case other than to recommend that the user disables the plugin or adds your website to a whitelist.
> 2. The user may have a custom font setting in their browser: Some browsers allow users to set a custom font for all websites. In this case, the user may need to adjust their browser settings to ensure that your website displays the correct font.

😂 nice to see other people using ChatGPT for things like this!!!

Thanks for your time and energy.

I tried pasting the page's source here, but Github freezes... let me see what I can do.

**Comment by angelhdzmultimedia** [comment]
Here it is! https://pastebin.com/bkBWPB5c

**Comment by angelhdzmultimedia** [comment]
I use Windows since Windows 98. Never I experienced an issue with a website loading the wrong fonts. 
It's interesting to know what's causing this.

Maybe it isn't too obvious, so I'm going to mention it, but of course I first checked if this was a browser related issue before submitting the issue here, by checking other websites. Also reset my internet DNS, and reconnected the Wireless connection to rule out internet related issues.

So I was about to reinstall Chrome fresh, until I decided to try in Microsoft Edge, and it's happening there to, but not in Firefox.

Firefox:
![image](https://user-images.githubusercontent.com/10191085/223756775-806d2aed-83dc-4618-a861-d380eed4289a.png)

Edge:
![image](https://user-images.githubusercontent.com/10191085/223756920-35d3440c-bfb7-49a3-8e7e-686fe454b822.png)

**Comment by angelhdzmultimedia** [comment]
For now I just execute this script in the Chrome console so I can continue exploring the website.

```ts
document.querySelectorAll('*').forEach(item => item.style.fontFamily = 'sans-serif')
```

**Comment by angelhdzmultimedia** [comment]
From all the sites that I navigate daily, as a designer, musician, geek, and programmer, 
i just found out a 2nd website showing cursive font:

![image](https://user-images.githubusercontent.com/10191085/224130470-27ac7216-a0dc-4885-a3e5-d38c55212c3b.png)


So... that can safely rule out a problem specific to nicegui.io.

Now to scratch my head about what the issue could be.

**Comment by rodja** [comment]
You could try to boil it down to the simples minimal html snipped which produces the problem...

**Comment by angelhdzmultimedia** [comment]
### SOLVED!!!

Thanks to this result https://www.hostround.com/one/knowledgebase/102/Chrome-is-showing-weird-fontor-hand-writing-fontor-script-font-on-some-websites.html, I finally solved it. It was an installed font family "Easy Street" breaking all this havoc, Thanks to everyone who cared, and invested time, and effort, into helping me find a solution.

(I thought about doing this, but I have tons of cursive fonts that scared me away of even attempting it).
