### ISSUE TITLE
`asyncio.create_subprocess_exec` does not work on windows

### ISSUE THREAD

**Issue by wielandb** [zauberzeug/nicegui#486]
Transferred from #454 

One example file uses asyncio and its `create_subprocess_exec` function. If run on windows, this function raises a `NotImplementedError`, because, as far as I can tell, it's not available on windows. 

It would be interesting to research if an alternative solution could be found to make the example file run on all platforms.

**Comment by spehj** [comment]
I also have this problem with [script executor example](https://github.com/zauberzeug/nicegui/tree/main/examples/script_executor). 

Error is:
`in _make_subprocess_transport
    raise NotImplementedError`

**Comment by spehj** [comment]
I found a workaround using this code in main.py of the `script executor` example:
`import subprocess
sync def run_command(command: str) -> None:
    '''Run a command in the background and display the output in the pre-created dialog.'''
    dialog.open()
    result.content = ''
    process = subprocess.Popen(
        command,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        cwd=os.path.dirname(os.path.abspath(__file__))
    )
    # NOTE we need to read the output in chunks, otherwise the process will block
    output = ''
    while True:
        new = process.stdout.read(4096)
        if not new:
            break
        output += new.decode()
        # NOTE the content of the markdown element is replaced every time we have new output
        result.content = f'```\n{output}\n```'
`

**Comment by rodja** [comment]
Thanks for the code, @spehj. Unfortunately neither the Popen call nor the stdout.read are async. That means the UI will block. This may not be noticeable to you but may have huge impact when you want to use the example in a production setting.
I'm still dumbfounded that the `create_subprocess_exec` from the Python standard library is not working on Windows.

**Comment by rodja** [comment]
I just found https://github.com/tiangolo/fastapi/issues/964 which says that Uvicorn, the ASGI webserver used by FastAPI/NiceGUI is picking the wrong event loop. Can anybody with Windows confirm that without FastAPI/NiceGUI the `create_subprocess_exec` is working?

**Comment by spehj** [comment]
Thanks, you're right @rodja, it's blocking but I couldn't find better solution.

I used this code to test if `create_subprocess_exec ` works on Windows:
```import asyncio

async def test_create_subprocess():
    process = await asyncio.create_subprocess_exec("ipconfig", stdout=asyncio.subprocess.PIPE)
    stdout, stderr = await process.communicate()
    print(stdout.decode())

asyncio.run(test_create_subprocess())
```

... and it works fine.

**Comment by rodja** [comment]
In the solution to https://github.com/encode/uvicorn/issues/1220 it seems that Uvicorn only changes the EventLoop if reload is activated. Can someone with Windows verify that the original example works as expected if you set `ui.run(reload=False)`?

**Comment by spehj** [comment]
@rodja I can confirm that with `ui.run(reload=False)` the original example works as expected.

**Comment by rodja** [comment]
Great. Then a quick fix for the example would be to use

```py
ui.run(reload=platform.system() != "Windows")
```

But maybe someone finds another, more sophisticated solution?

**Comment by LONGER3D** [comment]
`ui.run(reload=platform.system() != 'Windows')`
It works, thankyou

**Comment by SimonTechv** [comment]
Hi everyone, I ran into a similar problem, but without nicegui `asyncio.create_subprocess_exec` works on windows. Can you please explain what this is related to?

**Comment by djongepier** [comment]
Hi,

Using Windows (11 24H2) and I can confirm that with 'reload=True' it's giving me errors, with the workaround it's OK. So ui.run(reload=platform.system() != 'Windows') does fix the issue.

Does this need an upstream bugreport?

**Comment by the-xentropy** [comment]
FYI, there's a simple way to get this working on windows too by simply utilizing a new thread. It doesn't solve the original issue with asyncio itself, but I'm sure 95% of us just want to run something async ez-pz and don't care about the exact mechanism.

```py
async def run_process_async(binary_path: str, command_line_args: typing.List[str], working_directory: str) -> str:
    """Async run a process and return the standard output of said process."""
    
    full_command = [binary_path] + command_line_args
    
    def run():
        res = subprocess.run(full_command, check=False, cwd=working_directory, capture_output=True, text=True)
        if not res.returncode == 0:
            raise RuntimeError(f"Process invocation failed with return code {res.returncode}.\nStdout: {res.stdout}\nStderr: {res.stderr}")
        return res.stdout

    return await asyncio.to_thread(run)
```

run() can be any arbitrary python function, but it's better to keep this as self-contained as possible since it's multi-threading.
