### ISSUE TITLE
`ui.tabs` loses state when changing tabs; persistent tabs?

### ISSUE THREAD

**Issue by wwoods** [zauberzeug/nicegui#488]
There does not appear to be any mechanism for persistent tabs, where the content retains changes to, e.g., properties, when tabs are changed. ~~While one can work around this via the `on_change` handler for `ui.tab_panels`~~ (Workaround does not work), persistent tabs would reduce the amount of thinking the user needs when using tabs.

**Comment by wwoods** [comment]
This does not appear to affect expansion panels, but does affect `interactive_image`'s `src` property, and plotly graphs.

**Comment by rodja** [comment]
Sorry, I do not understand your problem yet. Could you provide example code with a description what you except and what currently happens.

**Comment by wwoods** [comment]
Here's a minimum-ish working example:

```python
from nicegui import ui

@ui.page('/')
async def issue(client):
    with ui.tabs() as tabs:
        ui.tab('A')
        ui.tab('B')

    img = None
    img_addr = 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Example_image.svg/600px-Example_image.svg.png?20120902142711'
    async def tab_change(evt):
        # Should fix it, does not.
        img.set_source(img_addr)

    with ui.tab_panels(tabs, value='A', on_change=tab_change):
        with ui.tab_panel('A'):
            img = ui.interactive_image('').style('width: 10rem; height: 10rem')
        with ui.tab_panel('B'):
            ui.label('Flipping here will clear image')

    await client.connected()
    img.set_source(img_addr)

ui.run(port=8081)

```

**Comment by falkoschindler** [comment]
Very interesting! Thanks for reporting this issue, @wwoods!

I boiled it further down to the following example:

```py
@ui.page('/')
async def page(client: Client):
    with ui.tabs() as tabs:
        ui.tab('A')
        ui.tab('B')
    with ui.tab_panels(tabs, value='A'):
        with ui.tab_panel('A'):
            img = ui.interactive_image()
        with ui.tab_panel('B'):
            ui.label('Flipping here will clear image')
    await client.connected()
    img.set_source('https://nicegui.io/logo.png')
```

Indeed, the interactive image does not keep the new source when switching tabs. I'll look into it.

**Comment by falkoschindler** [comment]
[6d97db6](https://github.com/zauberzeug/nicegui/commit/6d97db659cf80b99076b0fa1f145ae6a2e9d5561) should have fixed the problem. We did not call `super().on_source_change`, so the respective prop hasn't been set.

**Comment by rodja** [comment]
Interestingly, in #843 we discovered that the underlying [QTabPanel](https://quasar.dev/vue-components/tab-panels#qtabpanels-api) has a prop called `keep-alive`. With this prop the content is not dropped by Quasar every time the tab content is shown.

**Comment by wwoods** [comment]
> Interestingly, in #843 we discovered that the underlying [QTabPanel](https://quasar.dev/vue-components/tab-panels#qtabpanels-api) has a prop called `keep-alive`. With this prop the content is not dropped by Quasar every time the tab content is shown.

Wonderful! Should that property be the default? Or at least in the docs for `ui.tab_panels`?

**Comment by rodja** [comment]
Great thinking @wwoods. Making this the default behaviour in NiceGUI could simplify things. Whats your take, @falkoschindler?

**Comment by falkoschindler** [comment]
Ok, I finally looked into this issue again. I experimented with the following code:

```py
import numpy as np
import plotly.graph_objects as go
from nicegui import ui

with ui.tabs() as tabs:
    ui.tab('A')
    ui.tab('B')
with ui.tab_panels(tabs, value='A'):  # .props('keep-alive'):
    with ui.tab_panel('A'):
        plot = ui.plotly(go.Figure())
    ui.tab_panel('B')

ui.button('Add trace', on_click=lambda: (
    plot.figure.add_trace(go.Scatter(x=np.arange(10), y=np.random.random(10))),
    plot.update(),
))

ui.run()
```

Adding `.props('keep-alive')` definitely helps when switching back to tab A. But I noticed that it's still not perfect: When adding a trace while on tab B, it only becomes visible with the next update when pressing the button again (when back on tab A). So the potential for confusion remains. And keep-alive is meant to be used with care, as it increases memory consumption quite a bit.

So I'd suggest to add a remark about the keep-alive prop in the documentation, but keep the default behavior unchanged.

**Comment by falkoschindler** [comment]
We created issue #1017 for using the keep-alive prop by default.
