### ISSUE TITLE
Support for enums in dropdown selection control

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#49]
Consider:

```python3
class GaugeGas(enum.Enum):
    unknown = (0, 'Unknown')
    nitrogen = (1, 'Nitrogen')
    argon = (2, 'Argon')

    def __init__(self, code, display_name):
        self.code, self.display_name = code, display_name

    def __str__(self):
        return self.display_name


class Model:
    def __init__(self):
        self.gauge_1_gas = GaugeGas.nitrogen

model = Model()

# later...
ui.select(GaugeGas.__members__).bind_value(model, 'gauge_1_gas')
```

The list is displayed correctly, however, when I try to change the value, I get the following message in the log: `Problem with websocket in component update, ignoring`.

Made it work by
```python3
ui.select([str(g) for g in GaugeGas]).\
                        bind_value(model, 'gauge_1_gas',
                                   forward=lambda gas_name: (gas for gas in GaugeGas if str(gas) == gas_name).__next__(),
                                   backward=lambda gas: str(gas))
```
but maybe there's a simpler way?

**Comment by falkoschindler** [comment]
That's an interesting idea! I fiddled around a bit and tried to support lists, dicts *and* enums. But it is rather complicated to get it working. And the desired behavior doesn't seem to be completely obvious. E.g. should `on_change` yield the selected enum item or only its value? Similarly the bound model could contain an enum item, a name or a value.

Therefore, I looked into your workaround, simplified it a bit and would leave it here as a recipe for connecting enums with choice elements like radio, select and toggle:

```python3
from enum import Enum, auto
from nicegui import ui

class Choice(Enum):
    a = auto()
    b = auto()
    c = auto()

model = type('', (), {'x': Choice.a})

ui.select([option.name for option in Choice], on_change=lambda: print(model.x, flush=True)) \
    .bind_value(model, 'x',
                forward=lambda name: Choice[name],
                backward=lambda item: item.name)

ui.run(port=1234)
```

The `on_change` handler is just for showing the updated model values.
