### ISSUE TITLE
demjson dependance breaks install

### ISSUE THREAD

**Issue by vault1337** [zauberzeug/nicegui#5]
From Python 3.10, the dependent JSON package demjson fails to install.
Since stock JSON package exists and maintenance of dependent package is problematic (https://github.com/dmeranda/demjson/issues/40) changing from demjson to builtin JSON would be favorable.

**Comment by rodja** [comment]
Yes, this dependency should be removed. Unfortunately it comes from JustPy. So we can not do anything but wait for @elimintz to fix https://github.com/elimintz/justpy/issues/301.

**Comment by elimintz** [comment]
I need to find time to release a new version with this.  There is a demjson compatible package called demjson3 that solves this issue. If you want to fix it locally, change all `import demjson` lines to `import demjson3 as demjson`.
And you need to install demjson3.
The advantage of using demjson is that it can parse correctly javascript objects where the keys do not need to be between quotes.

**Comment by themerius** [comment]
it is also not installable with python 3.9.9, it will output this error:

    error in demjson setup command: use_2to3 is invalid.

on python 3.8 it is installable.

**Comment by rodja** [comment]
You can try downgrading setuptools to 57.4.0. This is what we do in our continuous testing script: 
https://github.com/zauberzeug/nicegui/blob/12f3918f61cb34fe5a271f30aa6944e108463979/.github/workflows/test.yml#L25

**Comment by themerius** [comment]
this workaround solves the issue. thanks! :)

**Comment by elimintz** [comment]
Version 0.2.3 of justpy which I released a few days ago should solve this problem. demjson was replaced with demjson3 so things should work fine now also without the workaround. Please let me know if this is not the case.

**Comment by rodja** [comment]
With release 0.7.6 we upgraded to JustPy 0.2.3. @elimintz thanks for fixing this dependency.
