### ISSUE TITLE
Cannot change session in button callback

### ISSUE THREAD

**Issue by Shmuma** [zauberzeug/nicegui#527]
Hi! 

I might be missing something, but for some reason, session is not preserved if I modify it inside the button callback.

This code shows "Storing" message in console, but `token` value is not preserved.
If I move session modification to the page function, everything works.

```py
from fastapi import FastAPI
from nicegui import ui
from starlette.requests import Request
from starlette.middleware.sessions import SessionMiddleware

app = FastAPI()
app.add_middleware(SessionMiddleware, secret_key="my_secret")


@ui.page("/path")
def view_path(request: Request):
    v = request.session.get("token")
    ui.label(f"Token: {v}")
    ui.button("Back", on_click=lambda: ui.open("/"))


@ui.page("/")
def view_root(request: Request):
    def do_click():
        request.session["token"] = "token_v"
        print(f"Storing: {request.session}")
        ui.open("/path")
    ui.label("Index page")
    ui.button("Push me", on_click=do_click)


ui.run_with(app)
```

**Comment by rodja** [comment]
Oh yes. Great you bring it up. That one also bit me once, but I have not documented it before. Here is what happens:

1. the SessionMiddleware provides the "session" property to the request before entering your page creator
2. after the page is created (eg. when the function is complete) the SessionMiddleware grabs the session property and encodes the data into the response to the browser
3. modifying the session property on button click happens after the response is long send; so it can not update the browser cookie anymore

You see, it's totally logical :-) But when working with NiceGUI you expect every state to be magically synced to the client. Unfortunately here you are not using any NiceGUI functionality but rather the underlying SessionMiddleware which does not know about the websocket ...

I just added a note to the authentication demo code which also references this issue:

https://github.com/zauberzeug/nicegui/blob/7143c148051934bb235e87380e1c051fcacbcc41/examples/authentication/main.py#L37-L39
