### ISSUE TITLE
Typo in static/templates/main.html prevents web page from appearing

### ISSUE THREAD

**Issue by me21** [zauberzeug/nicegui#53]
I had an error in Developer Console complaining about undefined symbol "False". When I looked at the place of the error, it was referring to static/templates/main.html, there was a line `unloading = False;`.
After I changed it to `unloading = false;` and also True to true in the next line, the web page started working again.

**Comment by falkoschindler** [comment]
Oh dear, mixing up Python and JavaScript...

It's fixed in https://github.com/zauberzeug/nicegui/commit/6037a257c3993a206a11a0baf1ac1c0677374ecb
