### ISSUE TITLE
Desktop Application

### ISSUE THREAD

**Issue by Sh1tters** [zauberzeug/nicegui#544]
Add an easy way for to integrate NiceGUI onto a Desktop application, instead of having to use a 3rd party like electron.

**Comment by falkoschindler** [comment]
It's already implemented: https://github.com/zauberzeug/nicegui/pull/519
See this discussion for further information: https://github.com/zauberzeug/nicegui/discussions/89

**Comment by rodja** [comment]
The release of 1.2 is immanent. Stay tuned :-)

**Comment by rodja** [comment]
We just published "Electron for Python": https://github.com/zauberzeug/nicegui/releases/tag/v1.2.0. Happy coding!

**Comment by Sh1tters** [comment]
> We just published "Electron for Python": https://github.com/zauberzeug/nicegui/releases/tag/v1.2.0. Happy coding!

Nice, thanks!
