### ISSUE TITLE
Implement support to be able to run on cloud server like Replit

### ISSUE THREAD

**Issue by then77** [zauberzeug/nicegui#548]
Due to how replit works by only allowing only web port outside the replit instance, the program wont work correctly. Is there any code improve especially for something like this or something else?

### Some Screenshot:
![Screenshot_20230318-182224_Chrome](https://user-images.githubusercontent.com/82355841/226102399-86dd3a06-fc31-42b2-840a-b20b3076f292.jpg)
![Screenshot_20230318-182330_Chrome](https://user-images.githubusercontent.com/82355841/226102403-a8a3fbc5-3232-4497-986f-459c685057f8.jpg)

**Comment by falkoschindler** [comment]
Thanks for reaching out, @then77!
There is already an issue about NiceGUI on Replit: https://github.com/zauberzeug/nicegui/issues/548. Maybe you can help us out over there?
I'll close this one as a duplicate.

**Comment by falkoschindler** [comment]
Sorry, the reference to the other discussion was wrong. I just fixed it.
