### ISSUE TITLE
How to add optional query parameters

### ISSUE THREAD

**Issue by JS-Aibel** [zauberzeug/nicegui#573]
Hi,

Is it possible to make the url parameters optional?
By using the code below one can get the query string from the url  `http://127.0.0.1:8080/?text=test`. This is also mentioned in https://github.com/zauberzeug/nicegui/discussions/507
```py
@ui.page('/')
def home(text: str):
    ui.label(text)
```

However, I can not go to the same url without setting the query parameter in the url. `http://127.0.0.1:8080/` gives the error: ` {"detail":[{"loc":["query","text"],"msg":"field required","type":"value_error.missing"}]}`.

I have tried setting the parameter to optional as shown below, but then I get an error from @ui.page('/') saying `“ValueError: non-default argument follows default argument”`.

```py
@ui.page('/')
def home(text: Optional[str] = 'NA'):
```

**Comment by rodja** [comment]
This was fixed in #418 which is part of the [1.1.10 release](https://github.com/zauberzeug/nicegui/releases/tag/v1.1.10).
