### ISSUE TITLE
.on Event for Element doesn't pass information to callback about sender

### ISSUE THREAD

**Issue by michelemoretti** [zauberzeug/nicegui#583]
I noticed a difference between how 
`ui.button("label",on_click=button_click)`
and 
`button2.on("click",button_click)`
pass information to the callback
In the first case the button object itself is sent as a sender attribute of an event handler object
In the second case only a dict with no information about the sender is sent to the callback as first and only argument.

Is this intended behaviour? 
It's making the dynamic generation of elements harder than it needs to be for me, unless I'm missing something
I'll attach a minimum snippet that exemplifies what I mean

```python
buttons = ["try", "this", "buttons"]

def button_click(e):
    print(f"button={e.sender.text}")
    #Here in the secondary buttons there's no trace of information about the sender

for button in buttons:
    button_obj = ui.button(button,on_click=button_click )
    button2 = ui.button(button+" secondary_event")
    button2 = button2.on("click",button_click)
```

Thank you for the help in advance and for this awesome tool!

**Comment by rodja** [comment]
Code is merged 🎉
