### ISSUE TITLE
Exception: close window in desktop mode on Windows

### ISSUE THREAD

**Issue by al-eax** [zauberzeug/nicegui#584]
### Description

`os.getpgid` is not supported on non unix systems, see pythons `/os/__init__.py`

![grafik](https://user-images.githubusercontent.com/2324292/226587476-29b90fac-dada-41b0-b1e2-b07b8d51b524.png)

### Exception log

```sh
Exception in thread Thread-1:
Traceback (most recent call last):
  File "[LOCAL_APPDATA]\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "[LOCAL_APPDATA]\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "env\lib\site-packages\nicegui\native_mode.py", line 27, in check_shutdown
    os.kill(os.getpgid(os.getpid()), signal.SIGTERM)
AttributeError: module 'os' has no attribute 'getpgid'
```
###  Environment
* Windows 10
* python 3.8
* nicegui 1.2.0

### quick fix in [`native_mode.py:26`](https://github.com/zauberzeug/nicegui/blob/bcd916905a93b3753bb434d2b76365b2a493f834/nicegui/native_mode.py#L26)

* Check for non unix operating system.
* Use `os._exit(os.EX_OK)` or `os.kill(os.getpid(), signal.SIGTERM)` instead.

```py
def check_shutdown() -> None:
    while True:
        if shutdown.is_set():
            if sys.platform != "win32":
                os.kill(os.getpgid(os.getpid()), signal.SIGTERM)
            else:
                os._exit(os.EX_OK) 
        time.sleep(0.1)
```

### clean fix

Another approach is to use `thread.interrupt_main(signum=signal.SIGKILL)` from the daemon thread to interrupt the main thread.
Main thread cloud handle this interrupt and use `sys.exit()` for clean tremination as described [here](https://superfastpython.com/interrupt-the-main-thread-in-python/).

How ever, im not a threading expert, what would you suggest?
Do you guys want me to create a pr?

**Comment by rodja** [comment]
Hey @al-eax, thanks for reporting this issue. Sounds like a serious issue which we should fix in the next release. A PR from your side would be much appreciated. Maybe you go for the clean fix without platform dependent code. That way everyone can better support and test it. We should minimize platform specific code as much as possible. I should have bee aware of `os.getpgid` not being Windows-compatible. Sorry for any inconviniences.

**Comment by al-eax** [comment]
@rodja what's the reason for having the threaded loop waiting for the event?
The `create_window` method blocks until the user closed the window. Afterwards the application terminates. In my opinion there is no need to kill the application when the event is triggered.

**Comment by falkoschindler** [comment]
The PR #602 introduces an error when running with `ui.run(native=True, reload=False)` and canceling with Ctrl-C (tested on MacOS):

```
ERROR:    Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/starlette/routing.py", line 674, in lifespan
    await receive()
  File "/opt/homebrew/lib/python3.10/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
  File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError
```

It can be fixed by adding `lifespan='off'` to the `uvicorn.Config` in `run.py`. But I'm not quite sure what it does and where it might break next...

**Comment by falkoschindler** [comment]
`lifespan='off'` breaks `app.on_startup` and `app.on_shutdown`. 🙄

**Comment by rodja** [comment]
Oh. @al-eax I really like the `_thread.interrup_main()` solution. But while on macOS we only see the error @falkoschindler posted above, on Windows pressing Ctrl-C kills the server but the window does not close.

We think it's because Ctrl-C is send to both processes (pywebview and uvicorn) and the pywebview signals the shutdown event on window closing which produces some kind of unwanted dubble-control-c effect.
