### ISSUE TITLE
Buttons nested inside ui.image or ui.interactive image unclickable

### ISSUE THREAD

**Issue by chook100** [zauberzeug/nicegui#597]
A button will be unable to click if it is nested inside a ui.image or ui.interactive image. Not sure if this is intended behavior or not. NiceGUI V1.2

**Comment by falkoschindler** [comment]
Thanks for reporting this, @chook100! That's very strange.
It seems to appear with 1.1.x versions as well, but I don't know why.

Here's a minimum reproduction. The button cannot be clicked:

```py
with ui.image('https://picsum.photos/id/377/640/360').classes('w-80 h-60'):
    ui.button('Click me!', on_click=lambda: ui.notify('Hi!'))
```

**Comment by falkoschindler** [comment]
Here is a reproduction using Vue and Quasar only:

```html
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/quasar@2.11.8/dist/quasar.prod.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="q-app">
      <q-img src="https://picsum.photos/id/377/640/360" style="width: 400px">
        <q-btn color="primary" @click="$q.notify('A!')">Button A</q-btn>
      </q-img>
      <q-btn color="primary" @click="$q.notify('B!')">Button B</q-btn>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.prod.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/quasar@2.11.8/dist/quasar.umd.prod.js"></script>
    <script>
      const app = Vue.createApp();
      app.use(Quasar);
      app.mount("#q-app");
    </script>
  </body>
</html>
```

The nested Button A cannot be pressed while Button B works as expected. So it doesn't seem to be a bug in NiceGUI, but rather a strange behavior of Quasar. Maybe we can find a related ticked over at https://github.com/quasarframework/quasar or at least find a workaround.

**Comment by falkoschindler** [comment]
I think the reason is that the image intercepts all mouse events within its area. To avoid that we can put both image and button into a common container and position the image absolutely. This way it doesn't impact the "flow" of the layout and simply stays behind the button:

```py
with ui.row():  # or any other container like `ui.element('div)`
    ui.image('https://picsum.photos/id/377/640/360').classes('w-80 h-60 absolute')
    ui.button('Click me!', on_click=lambda: ui.notify('Hi!'))
```
