### ISSUE TITLE
Window does not close when stopping native mode with Ctrl-C on Windows

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#604]
As already mentioned on #584, the native application does not terminate correctly with Ctrl-C on Windows.

**Comment by al-eax** [comment]
uvicorn has similar issues:
https://github.com/encode/uvicorn/issues/1872

**Comment by rodja** [comment]
We will wait a bit longer for the uvicorn issue to evlolve.

**Comment by falkoschindler** [comment]
@rodja Issue https://github.com/encode/uvicorn/issues/1872 is from Feb 21 and still tagged as "needs confirmation". Anyway, I'll tag our issue as "waiting" and move it to "Later". Feel free to revert.

**Comment by ItsCubeTime** [comment]
Hai, you can implement a fix for this yourself!
```py
if sys.platform == "win32":
    import win32api
    import os
    win32api.SetConsoleCtrlHandler(lambda a=None: os.kill(os.getpid(), 15)) # Enables ctrl+C to kill the terminal on Windows. 15 == signal.SIGTERM
```

**Comment by rodja** [comment]
@ItsCubeTime cool. Would you care to create a [pull request](https://github.com/zauberzeug/nicegui/blob/main/CONTRIBUTING.md#pull-requests) to close this bug?

**Comment by falkoschindler** [comment]
Looks like https://github.com/encode/uvicorn/issues/1872 has been closed based on PR https://github.com/encode/uvicorn/pull/1584 which was merged already on April 13. According to the milestone and the release notes, it should have been released on April 28 with [uvicorn 0.22.0](https://github.com/encode/uvicorn/releases/tag/0.22.0).

@al-eax and @ItsCubeTime, can you check if the issue is gone with uvicorn 0.22.0? Thanks!

**Comment by falkoschindler** [comment]
Nope, the problem remains with uvicorn 0.22.0 and NiceGUI 1.3.5 on Windows. 😕

**Comment by falkoschindler** [comment]
Looks like a pywebview issue:

The example from https://pywebview.flowrl.com/#hello-world has the same problem:
```py
import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/')
webview.start()
```

**Comment by miningmanna** [comment]
As far as I understand, pywebview needs to run in the main thread, therefore eating the SIGINT/SIGTERM signal.
In nicegui it is already running in a different process. The uvicorn server also exits when you press ctrl-c in the console.
From my (maybe limited) testing, it could be as simple to fix as setting the pywebview process to be a daemon process.

native_mode.py
` 
    process = mp.Process(target=open_window, args=args, daemon=True)
`

or have some kind of message one could send to the pywebview process, similar to how get_size and so on work, in order to cleanly terminate the process.

**Comment by falkoschindler** [comment]
@miningmanna Have you tried setting `daemon=True`? If it worked, a pull request would be very welcome. We just can't test it ourselves, since we have no Windows machine at hand.

**Comment by miningmanna** [comment]
@falkoschindler I tried it on a Windows 10 and Windows 11 machine. It works on both.
I will create a pull request.

**Comment by falkoschindler** [comment]
Amazing! The argument `daemon=False` has been added to the code in the very first commit regarding native mode: https://github.com/zauberzeug/nicegui/commit/c734cab195709edf757a155ff01eceb73be4ea10#diff-e16537d6af67de700fc23c3bd55c1eb27592a57962272242cb148bae23275af0. Somehow it was never questioned.

For a bit more context, this is how ChatGPT describes its function:

> The `multiprocessing.Process` with `daemon=False` means that the main program will wait for the `open_window` function to complete its execution in the separate process before the main program finishes.

So since the window process shouldn't run without the main process, setting `daemon=True` seems to be absolutely correct. 👍🏻
