### ISSUE TITLE
Possible new bug with stacking

### ISSUE THREAD

**Issue by DavidLeBonk** [zauberzeug/nicegui#605]
```py
with ui.row().style("height: 100%; width: 100%;"):
    ui.button("Prev", on_click=prevPage).style("height: 35%; width: 35%;")
    ui.label(f"{main.uiElements.searchTabC.page + 1}/{main.uiElements.searchTabC.maxPages}").style("height: 30%; width: 30%; font-size: 2em; text-align: center;")
    ui.button("Next", on_click=nextPage).style("height: 35%; width: 35%;") 
```
1.2.0: https://i.imgur.com/r44ZR6k.png
1.2.1: https://i.imgur.com/dxphafb.png
Same code different results

**Comment by falkoschindler** [comment]
If I understand correctly, you are referring to the wrapping elements in 1.2.1. That's exactly what we discussed here #595.
You asked "can I assume the behavior of wrapping will be enabled by default in future versions?" and I responded "Yes":
You https://github.com/zauberzeug/nicegui/issues/595#issuecomment-1478982499

The behavior in 1.2.1 should be exactly like in 1.1.x and is intended.

I'll close this issue for now. But, please, let me know if I misunderstood the intention of your post.

**Comment by DavidLeBonk** [comment]
This helped, sorry for the non-issue issue. Adding ```.classes('no-wrap')``` to the ui.row fixed it
