### ISSUE TITLE
Connection refused: native mode with pyside6 webview on linux

### ISSUE THREAD

**Issue by al-eax** [zauberzeug/nicegui#607]
I installed pyside6 to get pywebview running on my linux machine.
Im running a simple NiceGUI and use `native=True` option.

The pyside6 webview control tries to access the URL before uvicorns `run` method was called:

![image](https://user-images.githubusercontent.com/2324292/227050215-bcf5c821-8a4f-4466-b00a-25022dc93ef1.png)

## quick fix

a simple `time.sleep` in `native_mode.open_window` before `webview.start` helps to wait until the server is running.
How ever this is a bad idea because duration of uvicorns startup process can differ.

## clean fix

My idea was to wait until `globals.server.started` is set to True.

```py
def open_window(url: str, title: str, width: int, height: int, fullscreen: bool) -> None:
    webview.create_window(title, url=url, width=width, height=height, fullscreen=fullscreen)
    while not globals.server.started:
        time.sleep(0.1)
    webview.start(storage_path=tempfile.mkdtemp())
```

Therefor in `nicegui.run` the `native_mode.activate` method has to be called after the server instance was created and assigned to globals.

Uvicorn sets the `started` flag in `server.Server.startup:174` method.

Unfortunately the flag is always False when i check it and i don't know why.

**Comment by rodja** [comment]
> Unfortunately the flag is always False when i check it and i don't know why.

`open_window` is started in a new process 

https://github.com/zauberzeug/nicegui/blob/554b47af1bb9baf45367c5ff11b4a61cc5366390/nicegui/native_mode.py#L32

and `globals.server.started` is only updated on the main process. For communicating with the subprocess we need to introduce a `multiprocessing.Event()` or use a `multiprocessing.Pipe` (which enables bidirectional communication).

**Comment by rodja** [comment]
@al-eax I think with the integration of #625 we should have the tools in place to implement your initial idea of waiting for the server to start before calling `webview.start(...)`. It would be great if you could try it on your side...

**Comment by al-eax** [comment]
@rodja nice, I will have a look this evening.

**Comment by al-eax** [comment]
> @al-eax have you made progress already?

@rodja Im sorry, I was in vacation and didn't inform you. 
I will take care of the issue if you give me two more days.
