### ISSUE TITLE
Cannot nest items inside of ui.interactive_image

### ISSUE THREAD

**Issue by ThonAfterPy** [zauberzeug/nicegui#618]
Not sure if this is a bug or a limitation in how interactive_images are handled, but for some reason I am unable to get any sort of label/image/anything to show on an interactive limit.

```py
with ui.interactive_image("https://sgnl.ai/images/blog/SB0008--authorization-land.jpg"):
    ui.label("does not show")
```

**Comment by falkoschindler** [comment]
Thanks for reporting this, @ThonAfterPy!
I'm also not sure if we should consider this a bug. It seems similar to #597, where a nested button is visible but not clickable.
For now you can place the label on top of the interactive image as follows:

```py
with ui.row():  # or any other container like `ui.element('div)`
    ui.interactive_image("https://sgnl.ai/images/blog/SB0008--authorization-land.jpg")
    ui.label("does show").classes('absolute')
```
