### ISSUE TITLE
uvicorn_reload_includes does not always work

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#62]
I have a script test.py and a data file test.yaml next to it. When changing the YAML file, the automatic reload works with

```python
ui.run(uvicorn_reload_includes='*')
```

but  not with

```python
ui.run(uvicorn_reload_includes='*.py,*.yaml')
```

Triggering the reload by changing the Python file works in both cases.

**Comment by rodja** [comment]
I could still reproduce the issue with uvicorn 0.18.3 and latest watchfiles package.

**Comment by falkoschindler** [comment]
I finally understood the reason for this issue: For me it looked like the include and exclude arguments could be a comma-separated string:

> By default the following patterns are excluded: `.*, .py[cod], .sw.*, ~*.`

https://www.uvicorn.org/settings/#reloading-with-watchfiles

But according to the uvicorn source code they either have to be a single string (without ",") or a list of strings. So I added a conversion in `ui.run` to split the arguments.
