### ISSUE TITLE
Provide more recent Google Material Icons

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#63]
The following code should show two icons, a face and the more recent "masks" icon.

```python3
ui.icon('face')
ui.icon('masks')
```

But only the face is shown.
Apparently NiceGUI uses an old version of the icon font and could need an update.

**Comment by rodja** [comment]
Depends on #65 which depends on JustPy... so we need to wait.

**Comment by falkoschindler** [comment]
This issue is fix since NiceGUI 1.0.
