### ISSUE TITLE
Fonts are not found if NiceGUI is running behind a reverse proxy

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#64]
We have NiceGUI running at, e.g., https://devices.zauberzeug.com/robots/32/. But the network inspection shows that the app tries to load the following fonts, which all fail with HTTP error 404:

https://devices.zauberzeug.com/templates/local/robotofont/KFOmCnqEu92Fr1Mu4mxK.woff2
https://devices.zauberzeug.com/templates/local/materialdesignicons/iconfont/MaterialIcons-Regular.woff2
https://devices.zauberzeug.com/templates/local/materialdesignicons/iconfont/MaterialIcons-Regular.woff
https://devices.zauberzeug.com/templates/local/materialdesignicons/iconfont/MaterialIcons-Regular.ttf

Besides that, there are three fonts loaded from https://fonts.gstatic.com/. So there are probably multiple parts of NiceGUI requesting fonts from different sources.

**Comment by rodja** [comment]
The errors in loading the material icons have been fixed in the JustPy pull request https://github.com/elimintz/justpy/pull/459. Let's wait and see if this is applied upstream.

**Comment by rodja** [comment]
It was such a small change that I already released it in https://github.com/zauberzeug/nicegui/releases/tag/v0.8.8.
