### ISSUE TITLE
ui.mermaid does not interpret linebreaks

### ISSUE THREAD

**Issue by cedricWassenaar** [zauberzeug/nicegui#641]
Some mermaid diagrams require linebreaks to indicate the end of a command instead of `;`. Such as below:
```
requirementDiagram

requirement test_req {
id: 1
text: the test text.
risk: high
verifymethod: test
}
```

However, when strings with linebreaks (or multiline strings) are used as content for `ui.mermaid`, the linebreaks are replaced as spaces. This causes mermaid to fail rendering and throw the error `Expected NEWLINE after <command>`. 

Fortunately, for now I can use `ui.markdown` with mermaid as extra to solve this issue.

**Comment by falkoschindler** [comment]
Thanks for reporting this issue, @cedricWassenaar!

I think I could already fix it. Will be part of the next release. 👍

**Comment by falkoschindler** [comment]
Thanks for reporting this issue, @cedricWassenaar!

I think I could already fix it. Will be part of the next release. 👍
