### ISSUE TITLE
Simplify event protocol between server and client

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#644]
During a discussion about throttling button clicks with @pythonormen (#628) we noticed some confusion about the way the server communicates registered events to the client. In order to save bandwidth multiple registrations of the same event type are combined and, thus, have to agree upon throttle duration and the list of event arguments.

We think it would be better to communicate every single event registration independently. The increase in bandwidth should be neglectable, while simplifying the API and giving full control to the user.

**Comment by falkoschindler** [comment]
Branch [events](https://github.com/zauberzeug/nicegui/compare/events) contains the new, simplified implementation. Although I feel pretty confident it doesn't introduce regressions, a review certainly wouldn't hurt.

**Comment by rodja** [comment]
Looks good. I've just merged the code.
