### ISSUE TITLE
How to pass an argument to an async function with a ui.button

### ISSUE THREAD

**Issue by JS-Aibel** [zauberzeug/nicegui#647]
Hi,
When clicking the button 'Await a dialog' below the error message says:
```
RuntimeWarning: coroutine 'show' was never awaited 
```

How do I pass an argument to an async function when the call is made from an on_click event on a ui.button?

```
with ui.dialog() as dialog, ui.card():
    ui.label('Are you sure?')
    with ui.row():
        ui.button('Yes', on_click=lambda: dialog.submit('Yes'))
        ui.button('No', on_click=lambda: dialog.submit('No'))

async def show(text):
    result = await dialog
    ui.notify(f'{text} chose {result}')

ui.button('Await a dialog', on_click=lambda: show('test'))
```

The example is taken from https://nicegui.io/documentation#awaitable_dialog, the only differences are the parameter in the show method and the button's on_click method.

**Comment by JS-Aibel** [comment]
Found the answer here: https://github.com/zauberzeug/nicegui/discussions/348

**Comment by rodja** [comment]
Great you found the answer already. Would you like to create a pull-request which adds the demo to the documentation? See here for instructions: https://github.com/zauberzeug/nicegui/blob/main/CONTRIBUTING.md#additional-demos

**Comment by JS-Aibel** [comment]
> Great you found the answer already. Would you like to create a pull-request which adds the demo to the documentation? See here for instructions: https://github.com/zauberzeug/nicegui/blob/main/CONTRIBUTING.md#additional-demos

Yes, but I can’t seem to find a _documentation.py for the Awaitable dialog [more_documentation](https://github.com/zauberzeug/nicegui/tree/main/website/more_documentation).
On the other hand, I notice that functools.partial is mentioned here [async_event_handlers](https://nicegui.io/documentation#async_event_handlers), maybe it would be better to have an example of the use of partial there instead?

**Comment by rodja** [comment]
Good point @JS-Aibel. Maybe we should put all awaitable dialog demos into [dialog_documentation](https://github.com/zauberzeug/nicegui/blob/main/website/more_documentation/dialog_documentation.py). What do you think @falkoschindler.

**Comment by falkoschindler** [comment]
@rodja Done. 👍
