### ISSUE TITLE
Upgrade Quasar

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#65]
NiceGUI seems to be using Quasar 1.9.14 (according to the JavaScript console output).
The latest Quasar version is 2.7.7. It would be great to get at least 2.x.x.

**Comment by rodja** [comment]
If Quasar is updated in JustPy (see https://github.com/elimintz/justpy/issues/460) we would not have to maintain it here.

**Comment by falkoschindler** [comment]
See this discussion about JustPy's dependency on specific Vue and Quasar versions:
https://github.com/justpy-org/justpy/discussions/476

**Comment by falkoschindler** [comment]
This issue is fix since NiceGUI 1.0.
