### ISSUE TITLE
Cant change textarea line height

### ISSUE THREAD

**Issue by all4me7** [zauberzeug/nicegui#652]
Cant change textarea line height. I can change font size using quasar/tailwind classes or using css style, but line-height is still the same (even using line-height css style).
![image.png](https://user-images.githubusercontent.com/58729295/228195118-0f067208-6625-4bc3-b80a-396bf17fc434.png)

**Comment by dclause** [comment]
Hey ! 
I guess you are using `style` method with CSS. This won't work because under the hood, Quasar will replace your textarea with custom components. You have therefore to use the appropriate API from quasar which is the `input-style` property (see https://quasar.dev/vue-components/input)

Demo code: 
```
ui.textarea('not working').style('font-size:40px;line-height:40px;')
ui.textarea('working fine').props('input-style="font-size:40px;line-height:40px;"')
```

![image](https://user-images.githubusercontent.com/812055/228198379-9cc61d2d-eb1a-43da-b855-7b12cf4fb33e.png)

**Comment by all4me7** [comment]
Yep! Thank you so much! Works perfect.

**Comment by rodja** [comment]
@all4me7 that would make a nice demo in the documentation. We would love it if you could add it. Here are the instructions: https://github.com/zauberzeug/nicegui/blob/main/CONTRIBUTING.md#additional-demos

**Comment by rodja** [comment]
@all4me7 that looks strange. There seems to be multiple interweaved errors. Ensure you are using the latest version of Poetry and make sure your Python environment is clean and set up correctly. If you are using a virtual environment, try creating a new one and installing the dependencies again.

As written in the [CONTRIBUTING.md](https://github.com/zauberzeug/nicegui/blob/main/CONTRIBUTING.md#setup), we are not using `poetry install`. Have you tried [launching with docker](https://github.com/zauberzeug/nicegui/blob/main/CONTRIBUTING.md#alternative-docker)?

**Comment by all4me7** [comment]
@rodja Sorry i still have some problems with my machine. For now im unable to create thisn environment add anything to repo. But i will try on second machine soon. Thank you for your help

**Comment by rodja** [comment]
@all4me7 you could also try [the docker setup](https://github.com/zauberzeug/nicegui/blob/main/CONTRIBUTING.md#alternative-docker). It will encapsulate everything in a container so you do not need to worry about dependencies etc.
