### ISSUE TITLE
Tabs stop working

### ISSUE THREAD

**Issue by HilkopterBob** [zauberzeug/nicegui#653]
Hey, i have following code inside my mainpage:
```py
@ui.page('/')
def landng_page(request: Request) -> None:

    with ui.card().classes(" w-full") as card: #absolute-center w-full h-full
        with ui.tabs() as tabs:
            ui.tab('Presets', icon='description')
            ui.tab('Builder', icon='edit_document')
        
        with ui.tab_panels(tabs, value='Home').classes("w-full"):
            with ui.tab_panel('Home'):
                ui.label('This is the first tab')
            with ui.tab_panel('About'):
                ui.label('This is the second tab')

    # ~~~~~ Main Page running history Card  ~~~~~ #

    with ui.card().classes(" w-full") as card: #absolute-center w-full h-full
            with ui.tabs() as tabs:
                ui.tab('Home', icon='home')
                ui.tab('About', icon='info')
            
            with ui.tab_panels(tabs, value='Home').classes("w-full"):
                with ui.tab_panel('Home'):
                    ui.label('This is the first tab')
                with ui.tab_panel('About'):
                    ui.label('This is the second tab')

```
As you can see i have two seperate cards, with tabs inside both of them.
If i click on Builder (first tab, second option) all elements that should be inside the tab container disapear, if i go back to the first option (same tab, option one) the elements from the first tab disapear to.

the second tab view works perfectly.

![image](https://user-images.githubusercontent.com/117028104/228225289-8f7ddc9f-8e1d-440e-ac7d-ab88e822e89c.png)
freshly loaded ↑

![image](https://user-images.githubusercontent.com/117028104/228225591-6e398202-bc18-4a18-adcc-0c299a3080c5.png)
changed both to second tab ↑

![image](https://user-images.githubusercontent.com/117028104/228225699-2cb7f2de-b138-4cff-88e0-af970820032e.png)
changed both back to first tab ↑

i have already searched th quasar qTabs docs (https://quasar.dev/vue-components/tabs) and have found nothing...

**Comment by falkoschindler** [comment]
Make sure that the tab names match the panel names. You're mixing up "Presets" and "Builder" with "Home" and "About".

**Comment by HilkopterBob** [comment]
ah thank you!

**Comment by HilkopterBob** [comment]
ah thank you!
