### ISSUE TITLE
How to cite nicegui?

### ISSUE THREAD

**Issue by tjakobi** [zauberzeug/nicegui#660]
Thank you for your continued support of nicegui. I am currently preparing an academic paper for a software that employs nicegui for the web interface.

Of course, I would like to correctly cite nicegui and I was wondering if there is a preferred way of doing this?

There is now also direct support from GitHub to generate citations: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files 

Thank you!

**Comment by rodja** [comment]
Thank you for addressing the topic @tjakobi. We are thrilled you use NiceGUI in an academic paper. I just added a first citation file. With the next release we will get a DOI from Zenodo.

@falkoschindler could you add your ORCID?

**Comment by falkoschindler** [comment]
@rodja Done. 👍

**Comment by rodja** [comment]
We will close the issue as soon as the 1.2.3 release is through and we get the DOI + verified that auto-updating the citation with correct version number works.

**Comment by tjakobi** [comment]
Thank you!

**Comment by rodja** [comment]
Auto-update failed :-(
We'll try again in the next release!

**Comment by rodja** [comment]
Ok, after a few trails I've now a working GitHub Action in place. I tested it by updating in on every push. With the last commit I switched it to only run after a new release has been made. We can safely close the issue now.
