### ISSUE TITLE
Improve access to event arguments

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#672]
### Discussed in https://github.com/zauberzeug/nicegui/discussions/664

<div type='discussions-op-text'>

<sup>Originally posted by **bobanovo** March 29, 2023</sup>
Hi, 
I would like to ask for help. For `ui.table` I need to listen, on which row was clicked, and process the id of row in the rest of the code.
When I used `ui.table` (qtable), and `table.on('rowClick', callback_function)`, the function has only one parameter, which doesn't contain the id of the row, or data of specific row etc. What do I wrong?

```py
tbl1=ui.table(columns=columns_, rows=rows_, row_key='id', selection='single').props('')
print(tbl1.on('rowClick', lambda msg: print("> ",msg)))
```

and the output:
```
>  {'id': 4, 'type': 'rowClick', 'args': {'isTrusted': True, '_vts': 1680074011030}}
>  {'id': 4, 'type': 'rowClick', 'args': {'isTrusted': True, '_vts': 1680074011218}}
>  {'id': 4, 'type': 'rowClick', 'args': {'isTrusted': True, '_vts': 1680074011840}}
>  {'id': 4, 'type': 'rowClick', 'args': {'isTrusted': True, '_vts': 1680074012014}}
```

Thanks a lot, for your help.
Radek</div>

We need to find a way to include more than the first event argument (see `let handler = (e) => {` in index.html). This also affects the argument-filtering mechanism (the `args` parameter).

**Comment by rodja** [comment]
Code is merged 🎉
