### ISSUE TITLE
Make native window more configurable

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#674]
### Discussed in https://github.com/zauberzeug/nicegui/discussions/640

<div type='discussions-op-text'>

<sup>Originally posted by **rodja** March 27, 2023</sup>
@Skjolbir came up with this feature request in #576. There a many more parameters which could be passed in 

https://github.com/zauberzeug/nicegui/blob/9093c72331b55f988157a57ffe64ff464e2f640e/nicegui/native_mode.py#L17-L19

The first idea was to provide a `webview_args` parameter to `ui.run`. But that would further blow up the already long list of parameters. Also the `webview.create_window` has some parameters which would be helpful good to manipulate from the users.

Maybe it is better to introduce an `app.native` object which has properties like `create_window_args`, `webview_start_args` and an callback `on_webview_started` which provides the window instance from `create_window`. This could be used to add menus etc.</div>

---

We decided to implement an API like this:

```
app.native.start_args = { ... }
app.native.window_args = { ... }
...
ui.run(...)
```

**Comment by Skjolbir** [comment]
Wonderful, Bravo!

**Comment by falkoschindler** [comment]
@rodja Commit [cff6838](https://github.com/zauberzeug/nicegui/commit/cff68385ec643db7ec85da9425655cea9f8f2222) should be all it needs. Note that, as indicated in the documentation, I decided to let `app.native` arguments overrule `ui.run` arguments.

**Comment by rodja** [comment]
Great! I just added a link to the pywebview and had to modify the wording in the docs.
