### ISSUE TITLE
Unhandled exception when running executable with no console on Windows

### ISSUE THREAD

**Issue by spehj** [zauberzeug/nicegui#681]
When building an executable with pyinstaller on Windows, there is error: `Unhandled exception in script` and .exe doesn't work. 

`build.py` is:
```python
import os
import subprocess
from pathlib import Path
import nicegui

cmd = [
    'pyinstaller',
    'main.py', # your main file with ui.run()
    '--name', 'Test app', # name of your app
    '--onefile',
    '--windowed', # prevent console appearing, only use with ui.run(native=True, ...)
    '--add-data', f'{Path(nicegui.__file__).parent}{os.pathsep}nicegui'       
]
subprocess.call(cmd)
```

Error is: 
```powershell
Traceback (most recent call last):
  File "logging\__init__.py", line 1113, in emit
  File "tempfile.py", line 483, in func_wrapper
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 529, in <module>
  File "nicegui\run.py", line 122, in run
    globals.server.run()
  File "uvicorn\server.py", line 60, in run
  File "asyncio\runners.py", line 190, in run
  File "asyncio\runners.py", line 118, in run
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "uvicorn\server.py", line 77, in serve
  File "uvicorn\server.py", line 88, in startup
  File "uvicorn\lifespan\on.py", line 58, in startup
  File "logging\__init__.py", line 1518, in error
  File "logging\__init__.py", line 1634, in _log
  File "logging\__init__.py", line 1644, in handle
  File "logging\__init__.py", line 1706, in callHandlers
  File "logging\__init__.py", line 978, in handle
  File "logging\__init__.py", line 1118, in emit
  File "logging\__init__.py", line 1031, in handleError
  File "tempfile.py", line 483, in func_wrapper
TypeError: a bytes-like object is required, not 'str'
```
In `main.py` I use:
```python
ui.run(native=True, reload=False)
```

I get the same error for `'--windowed'` or `'--noconsole'`. If I comment out `'--windowed'` or `'--noconsole'` from `build` file, .exe file works.

**Comment by hditano** [comment]
Getting exactly the same error.

**Comment by edsase** [comment]
This is not Nicegui issue but is coming from uvicorn. You'd get the same error if you build a fastapi with pyinstaller and the `--windowed` flag. It seems uvicorn needs to send console log outputs and will not be able to do so if `--windowed` takes the console away. Solution is to divert stdout to a file. Add the following at the top of your main.py to get rid of this error:
```
import sys
sys.stdout = open('logs.txt', 'w') # divert stdout to logs.txt file
```

**Comment by executionunit** [comment]
@edsase is correct but it's an annoying issue. An alternative to creating a log file is to create a `nullwriter` output when in a PyInstaller bundle:

```python
import sys

# Are we running in a PyInstaller bundle
# https://pyinstaller.org/en/stable/runtime-information.html#run-time-information
if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
    class NullOutput(object):
        def write(self, string):
            pass

        def isatty(self):
            return False


    sys.stdout = NullOutput()
    sys.stderr = NullOutput()
```

before calling ui.run().

**Comment by clueple** [comment]
"me2",  I tried using 'auto-py-to-exe' to convert a very basic  nicegui app (only a ui.label('some text') and then ui.run(native=True, reload=False) to an exe on Windows 10 (in windowed-mode).  

It ended up with similar result as that of @hditano .

Gonna try creating a nullwriter output approach (see the bottom quote) by @executionunit .

Thanks for sharing.

> Getting exactly the same error.
> 
> ![image](https://user-images.githubusercontent.com/6069906/229363549-02d91660-7333-4195-89a9-6aca9c019a88.png)



> ```python
> import sys
> 
> # Are we running in a PyInstaller bundle
> # https://pyinstaller.org/en/stable/runtime-information.html#run-time-information
> if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
>     class NullOutput(object):
>         def write(self, string):
>             pass
> 
>         def isatty(self):
>             return False
> 
> 
>     sys.stdout = NullOutput()
>     sys.stderr = NullOutput()
> ```

**Comment by rodja** [comment]
Sounds like we should add this to the documentation. Anyone interested in creating a pull-request?

**Comment by clueple** [comment]
> Sounds like we should add this to the documentation. Anyone interested in creating a pull-request?

Just tried @executionunit 's approach (see below), but I still get the same error (packaging to exe with auto-py-to-exe, windowed-mode, one-directory, add folder = fastapi, unicorn, nicegui, webview)  .

Not sure if that's related to my own setting ( my httpx version is 0.13 while  the httpx comes along with nicegui is 0.24)
(also, my Win 10 laptop doesn't have node.js installed)


@executionunit  's approach:
import sys

# Are we running in a PyInstaller bundle
# https://pyinstaller.org/en/stable/runtime-information.html#run-time-information
if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
    class NullOutput(object):
        def write(self, string):
            pass

        def isatty(self):
            return False


    sys.stdout = NullOutput()
    sys.stderr = NullOutput()

**Comment by edsase** [comment]
You may try redirecting stdout to a log file as i suggested above.

**Comment by ymweagle** [comment]
I get the different error 
![image](https://user-images.githubusercontent.com/49975096/230309603-754311ac-be41-48aa-9936-deba16649c84.png)

divert stdout to logs.txt file
this error still exists

**Comment by edsase** [comment]
Your error seems unrelated to the original issue. Can you post the full error message text instead of a screenshot?

**Comment by ymweagle** [comment]
@edsase 

this is the full error message

Traceback (most recent call last):
  File "ui测试.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "nicegui\__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "nicegui\ui.py", line 62, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "nicegui\elements\upload.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "nicegui\nicegui.py", line 33, in <module>
  File "starlette\staticfiles.py", line 57, in __init__
RuntimeError: Directory 'C:\Users\ADMINI~1\AppData\Local\Temp\_MEI117682\nicegui\static' does not exist

**Comment by edsase** [comment]
This is likely be related to the issue solved [here](https://github.com/zauberzeug/nicegui/releases/tag/v1.2.6).  Please update your version of nicegui to the latest: `python -m pip install nicegui --upgrade`

**Comment by ymweagle** [comment]
@edsase 

Upgraded from 1.2.5 to 1.2.6

the new error
![image](https://user-images.githubusercontent.com/49975096/230332430-5fe7eac6-68d1-46c8-b0de-6cd89087b3be.png)

Here is the code:

from nicegui import ui
import sys
sys.stdout = open('logs.txt', 'w') # divert stdout to logs.txt file
ui.label('transparency')

ui.run()

**Comment by edsase** [comment]
Run like this: 
```
ui.run(reload=False, native=True)
```
If you still get errors, then I'd suggest you open a fresh issue.

**Comment by clueple** [comment]
> This is likely be related to the issue solved [here](https://github.com/zauberzeug/nicegui/releases/tag/v1.2.6). Please update your version of nicegui to the latest: `python -m pip install nicegui --upgrade`

Seems like it's about text handling.

Here's my testing result on a 64-bit Win10, no node.js installed:
1) Created an app with just the label object , ui.run(native=True, reload=False) ===> able to run the app
2) Created an app (note a) needing requests-html (for webscraping), same ui.run(native=True, reload=False ) ===> error message (note b)
3) Both (1) and (2) have the same code (to add a log text file) (note c)
4) Both (1) and (2) were packaged with auto-py-to-exe (note d)


**(note a)**
**This is my python code, filename=='testapp1.py'**

from nicegui import ui
from requests_html import HTMLSession

""" add a log file"""
import sys
sys.stdout = open('logs.txt', 'w') # divert stdout to logs.txt file


""" click events """
#function to scrape text when the button 's_btn' is clicked
def scrape(e):
    #initiate an html session, generate an html response, extract text based on css selector
    session = HTMLSession()
    #create response variable to return the html from the url specified in element, 'e_url'
    r = session.get(f"{e_url.value}").html
    #return text specified by the css selector (e.g. 'e_css')
    try:
        rc = r.find(f"{e_css.value}")
        result_txt = "\n".join([p.text for p in rc])
        result.set_value(result_txt)

    except:
        result.value = "Please enter correct url and type the css selector"
        

""" Add style for the elements with CSS  """
css_style1 = r"""
width: 100%;
height: 300px; 
padding: 12px 20px; 
box-sizing: border-box; 
border: 2px solid #ccc; 
border-radius: 25px; 
background-color: #f8f8f8; 
font-size: 16px; 
resize: none;
"""



""" elements """
#text area to enter url
e_url = ui.input(label='Web URL', placeholder = 'Enter url here')

#text area to enter css selector
e_css = ui.input(label='CSS Selector', placeholder = 'Enter css selector here')

#click button to scrape text based on the 'e_url' and 'e_css'
s_btn = ui.button("Scrape Text", on_click=scrape)

#create text area to store the scrape result
result = ui.textarea(label='Result', placeholder='Your result text should be here').style(css_style1)


""" run app """
ui.run(reload=False, native=True)


```


**(note b)**
```
Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
  File "tempfile.py", line 483, in func_wrapper
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testapp1.py", line 51, in <module>
  File "nicegui\run.py", line 121, in run
    globals.server.run()
  File "uvicorn\server.py", line 60, in run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 641, in run_until_complete
  File "uvicorn\server.py", line 77, in serve
  File "uvicorn\server.py", line 88, in startup
  File "uvicorn\lifespan\on.py", line 58, in startup
  File "logging\__init__.py", line 1497, in error
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "tempfile.py", line 483, in func_wrapper
TypeError: a bytes-like object is required, not 'str'

```



**(note c)**
```
""" add a log file"""
import sys
sys.stdout = open('logs.txt', 'w') # divert stdout to logs.txt file
```

**(note d)**
```
pyinstaller --noconfirm --onedir --windowed --add-data "G:/testenv/Lib/site-packages/nicegui;nicegui/" --add-data "G:/testenv/Lib/site-packages/requests;requests/"  "G:/app/testapp1.py"
```

**Comment by clueple** [comment]
> @clueple Can you further reduce your example (note a) so that we find out what is causing the error (despite setting a custom `sys.stdout`)? Besides that we should add the stdout trick to the documentation. But before that it would be great to find out what is still causing the problem with your app.

@falkoschindler , actually, the sys.stdout approach doesn't work for me.  and I figured out how to do that with the code below:

```
"""#dd the following codes BELOW 'ui.run(reload=False, native=True)' to ignore deprecated warnings """

import warnings

def fxn():
    warnings.warn("deprecated", DeprecationWarning)

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    fxn()

```
I've shot a video on how I **fix the unhandled exception error** while packing my test app on Windows through nicegui 1.2.6

https://www.youtube.com/watch?v=4eIotPSIMDM


The code below is my original code (with the exception error); feel free to try it out for practice:

```
from nicegui import ui
from deep_translator import GoogleTranslator as gt

"""css style for textarea"""
css_style1 = r"""
width: 100%;
height: 300px; 
padding: 12px 20px; 
box-sizing: border-box; 
border: 2px solid #ccc; 
border-radius: 25px; 
background-color: #f8f8f8; 
font-size: 16px; 
resize: none;
"""
src_txt = ui.input(label='Input Text', placeholder='Enter text here', on_change=lambda e: result.set_value(gt(source='auto', target='de').translate(e.value)))

result = ui.textarea(label="Result", placeholder="Your result text is here").style(css_style1)

ui.run(native=True, reload=False)


```

**Comment by falkoschindler** [comment]
Thanks @clueple! Glad to hear that you could fix the issue.
I added a note to the documentation pointing to this discussion.
I'll close it for now. Feel free to re-open it if you have more information we should consider.

**Comment by firai** [comment]
By the way, for anyone landing here from the docs, you can direct `stdout` to `os.devnull` instead of creating a dummy log file that might need to be cleaned up (see https://github.com/zauberzeug/nicegui/issues/719#issuecomment-1511199514).

In fact, this is directly written into the source for pywebview, which I understand is the engine for `native` mode, to deal with a similar issue due to bottle (see https://github.com/r0x0r/pywebview/issues/1044 and https://github.com/r0x0r/pywebview/pull/1086).

**Comment by clueple** [comment]
> For anyone landing here from the docs, you can direct `stdout` to `os.devnull` instead of creating a dummy log file that might need to be cleaned up (see [#719 (comment)](https://github.com/zauberzeug/nicegui/issues/719#issuecomment-1511199514)).
> 
> In fact, this is directly written into the source for pywebview, which I understand is the engine for `native` mode, to deal with a similar issue due to bottle (see [r0x0r/pywebview#1044](https://github.com/r0x0r/pywebview/issues/1044) and [r0x0r/pywebview#1086](https://github.com/r0x0r/pywebview/pull/1086)).

Thank for the hint, @firai.  The same problem is gone when updating Python to 3.11.3.  But still good to know it can be fixed with the pywebview approach.
