### ISSUE TITLE
Zooms in when writing text or using dropdown

### ISSUE THREAD

**Issue by ijoel92** [zauberzeug/nicegui#690]
https://user-images.githubusercontent.com/44055815/229279817-c077442d-8246-422d-a647-3d987faf4fa7.MOV

https://user-images.githubusercontent.com/44055815/229279868-84b80324-0b06-4751-92df-660aa4a55f3a.MOV

### Description

From the post on Reddit, I checked the website and when clicking on dropdowns and text boxes, it zooms on it which can be unintended.

**Comment by falkoschindler** [comment]
Strange. It doesn't happen on my phone (Android, OnePlus 5). What device do you have?

**Comment by ijoel92** [comment]
Sorry, forgot to add the device model. iPhone 12 Pro. iOS 16.3.1. Chrome version 111. 
Same happens within the Reddit and Safari browsers.

**Comment by dclause** [comment]
Maybe I am wrong but isn't it something done by the iPhone itself ?
https://support.apple.com/en-en/guide/iphone/iph3e2e367e/ios

**Comment by falkoschindler** [comment]
I also think this isn't a bug in NiceGUI, but a feature on iOS.

**Comment by rodja** [comment]
@ijoel92 does it also happen on other websites?

**Comment by rodja** [comment]
We are closing the issue for now. Feel free to reopen if you disagree. Thanks!
