### ISSUE TITLE
Building the FastAPI example using Pyinstaller

### ISSUE THREAD

**Issue by edsase** [zauberzeug/nicegui#691]
### Description

Hi, first of all thanks @zauberzeug-dev for this great library. 

I'm having issues building the fastapi example using Pyinstaller on windows. Here's my `main.py` where I tried to launch the server with uvicorn: 
```py
#!/usr/bin/env python3
import frontend
from fastapi import FastAPI
import uvicorn

app = FastAPI()

@app.get('/')
def read_root():
    return {'Hello': 'World'}

frontend.init(app)

uvicorn.run("main:app", host="127.0.0.1", port=5000, log_level="info")
```

My `build.py` is the same as in `/nicegui/tree/main/examples/fastapi/`.
I however get the following error: 
```
RuntimeError: asyncio.run() cannot be called from a running event loop
sys:1: RuntimeWarning: coroutine 'Server.serve' was never awaited
```

Can you help me with an example of how to do this correctly? Thanks.

**Comment by rodja** [comment]
Does it work without NiceGUI (eg. commenting out the `frontend.init(app)` line)?

**Comment by edsase** [comment]
> Does it work without NiceGUI (eg. commenting out the `frontend.init(app)` line)?

No, It doesn't. Produces the same error.

**Comment by rodja** [comment]
Ok, then it's maybe a good idea to file an issue in the PyInstaller GitHub project. Feel free to reference this issue here so the NiceGUI community can stay in the loop.

**Comment by edsase** [comment]
It's resolved now. Problem was indeed from Pyinstaller. I refactored my code to put the fastapi code in a new module called app, and main.py only having `uvicorn.run("app:app", host="127.0.0.1", port=5000, log_level="info")`, then added the argument `--hidden-import=app` in cmd for the pyinstaller build.
