### ISSUE TITLE
Allow returning a RedirectResponse from an async page function

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#693]
### Discussed in https://github.com/zauberzeug/nicegui/discussions/549

<div type='discussions-op-text'>

<sup>Originally posted by **espeoceka** March 18, 2023</sup>
Hey im not even sure its issue, i might be doing something wrong....

For example:

```py
@ui.page('/logout')
async def logout(request: Request) -> None:
    if await is_authenticated(request):
        await redis.expire(request.session["id"], 0)
        request.session['id'] = None
        return RedirectResponse('/login')
    else:
        return RedirectResponse('/')
```

It never redirect to anything, but when i remove async it works like intended. Any ideas how to sort this out ?

</div>

**Comment by HilkopterBob** [comment]
+1 a fix/workaround would be great!

**Comment by rodja** [comment]
Wow. That bug was really deep in our page logic. Quite easy to fix but I wonder how we could miss it so long. Now there are additional tests to ensure the behaviour does not break in the future.
