### ISSUE TITLE
FastAPI: value_error.missing

### ISSUE THREAD

**Issue by HilkopterBob** [zauberzeug/nicegui#694]
### Description

i get the error message: `{"detail":[{"loc":["query","session_info"],"msg":"field required","type":"value_error.missing"}]}`

with this code:
```py
@ui.page('/')
async def index_page(request: Request, session_info) -> None:
    with theme.frame('generic title'):
        await index.content(request, session_info)
```

i dont get it if i dont give session_info as arg. with this code:

```py
@ui.page('/')
async def index_page(request: Request) -> None:
    with theme.frame('generic title'):
        await index.content(request, session_info)
```

**Comment by falkoschindler** [comment]
I'm not sure what `session_info` is supposed to do. Is it some FastAPI magic I'm not aware of? I guess you need to type-annotate it at least. Otherwise FastAPI tries to find a "session_info" parameter in the path string.

**Comment by HilkopterBob** [comment]
> Otherwise FastAPI tries to find a "session_info" parameter in the path string.  

oh i guess thats the problem, i didnt know that it will try to find session_info in the path. 

---

session_info is used for auth:

```py
session_info: Dict[str, Dict] = {}
```

```py
async def content(request: Request, session_info) -> None:
    if await is_authenticated(request, session_info):
        return RedirectResponse('/login')
```

```py
async def is_authenticated(request: Request, session_info) -> bool:
    return session_info.get(request.session.get('id'), {}).get('authenticated', False)
```

**Comment by rodja** [comment]
Have you seen our [auth example](https://github.com/zauberzeug/nicegui/blob/main/examples/authentication/main.py), @HilkopterBob? There , `session_info` is a global dict which should be replaced with a database or similar for real world usage.

**Comment by HilkopterBob** [comment]
yes from there i got my first draft of a login system, i know i should replace it but for now is i just test this framework for my company i think its okay
