### ISSUE TITLE
ui.table is not responding to on_select event

### ISSUE THREAD

**Issue by abulka** [zauberzeug/nicegui#698]
### Description

1. Trying to click on a table row and have an event fire, telling me which row was clicked on.
```python
from nicegui import ui

columns = [
    {'name': 'name', 'label': 'Name', 'field': 'name', 'required': True, 'align': 'left'},
    {'name': 'age', 'label': 'Age', 'field': 'age', 'sortable': True},
]
rows = [
    {'name': 'Alice', 'age': 18},
    {'name': 'Bob', 'age': 21},
    {'name': 'Carol'},
]

ui.table(columns=columns, rows=rows, row_key='name', on_select=lambda e: ui.notify(e.value))

ui.run()
```
2. I expect a `ui.notify` popup to appear when I click on the table.
3. Nothing happens when I click on the table.

**Comment by falkoschindler** [comment]
By default `ui.table` has row selections disabled. You need to pass `selection='single'` or `selection='multiple'` as an argument to activate it.

If you wan't to get click events instead without the need for checkboxes, it is, unfortunately, currently not possible. There's a related discussion over here: https://github.com/zauberzeug/nicegui/discussions/664.

**Comment by abulka** [comment]
I see. I added `selection='single'` and changed the event property to `e.selection` viz.
```python
ui.table(columns=columns, rows=rows, row_key='name', selection='single', on_select=lambda e: ui.notify(e.selection))
```
and I am getting the event now - when I click on the checkbox. 

Its not the ideal interface I want, but it will get me by!

### Aside
I'm translating a wxPython application to NiceGUI and ideally want a multi column [list view](https://docs.wxpython.org/wx.ListCtrl.html) where the entire row is selected 
![image](https://user-images.githubusercontent.com/11467530/229386653-ff97440d-5d01-4e6f-8b67-881693d16bb0.png)

Actually looking at Quasar table, there is no demo of the entire line remaining selected after you click on it - so even if I had the event, I would still have to highlight the entire row somehow. The Quasar [List](https://v1.quasar.dev/vue-components/list-and-list-items) does have that row selection highlight behaviour (the second last example with the word "Menu" in it) but doesn't have multiple columns, nor is it implemented yet in NiceGUI.

**Comment by falkoschindler** [comment]
@abulka Interesting idea to use lists and list items for that purpose. Based on the example from https://github.com/zauberzeug/nicegui/discussions/512#discussioncomment-5314453 I came up with the following demo:

```py
with ui.element('q-list').props('bordered separator'):
    with ui.element('q-item').props('clickable').on('click', lambda: click(item1)) as item1:
        with ui.element('q-item-section'):
            ui.label('Hello World!')
    with ui.element('q-item').props('clickable').on('click', lambda: click(item2)) as item2:
        with ui.element('q-item-section').props('avatar'):
            ui.element('q-avatar').props('icon=bluetooth')
        with ui.element('q-item-section'):
            ui.label('Bluetooth')
    with ui.element('q-item').props('clickable').on('click', lambda: click(item3)) as item3:
        with ui.element('q-item-section').props('avatar'):
            ui.element('q-avatar').props('icon=wifi')
        with ui.element('q-item-section'):
            ui.label('WiFi')

def click(item: ui.element) -> None:
    item._props['active'] = not item._props.get('active', False)
    item.update()
```

As a next step I would certainly introduce `List` and `Item` classes to remove repetition. And setting the `active-class` prop would allow styling the items in "active" state.

**Comment by abulka** [comment]
Thanks for that code fragment. Didn't realise you could hack together any quasar element using `ui.element` - that's so liberating. 

I built on top of your code to get more columns, column borders, single select row highlighting and even a hacky way of finding the text of the item being clicked on. 

![image](https://user-images.githubusercontent.com/11467530/229693611-c28626c6-781c-4055-9bb7-f9768a0e5ecc.png)

![image](https://user-images.githubusercontent.com/11467530/229693649-87ab7442-c7cd-4e80-befd-5d143c288f5d.png)

Besides introducing proper NiceGui `List` and `Item` classes it would of course be nice to model the active row so that `bind_value` could be used, which would presumably provide a less hacky way of finding the data of the row being clicked.

I could perhaps have a go at implementing some of this, but would need a recipe of development steps to follow as I sense this is more complex than the ui.splitter I contributed. Pointing out other NiceGui elements that might be similar would also help. Whenever someone has the time to provide this info - that would be great. I don't mind if someone else more versed with NiceGui implements this, either.

## My enhanced example

```python
from nicegui import ui

def find_label(element):
    """
    Recursively search for a `Label` object in an element's children.
    Return `None` if not found.
    """
    if isinstance(element, ui.label):
        # Found the `Label` object
        return element

    # Check children recursively
    for child in element.default_slot.children:
        if isinstance(child, ui.element):
            label = find_label(child)
            if label is not None:
                return label

    # `Label` object not found
    return None

ui.add_head_html('''
<style>
.my-menu-link {
  color: white;
  background: #59aef2; /* blue */
}
</style>
''')
section_classes = 'w-40 border-l-2 border-gray-300 pl-5'

with ui.element('q-list').props('dense bordered separator'):
    with ui.element('q-item').props('clickable active-class="my-menu-link"').on('click', lambda: click(item1)) as item1:
        with ui.element('q-item-section').props('avatar'):
            ui.element('q-avatar').props('icon=home')
        with ui.element('q-item-section').classes(section_classes):
            ui.label('Hello World!')
        with ui.element('q-item-section').classes(section_classes):
            ui.label('WORLD!')
    with ui.element('q-item').props('clickable active-class="my-menu-link"').on('click', lambda: click(item2)) as item2:
        with ui.element('q-item-section').props('avatar'):
            ui.element('q-avatar').props('icon=bluetooth')
        with ui.element('q-item-section').classes(section_classes):
            ui.label('Bluetooth')
        with ui.element('q-item-section').classes(section_classes):
            ui.label('HA HA')
    with ui.element('q-item').props('clickable active-class="my-menu-link"').on('click', lambda: click(item3)) as item3:
        with ui.element('q-item-section').props('avatar'):
            ui.element('q-avatar').props('icon=wifi')
        # add a left border to the section and some padding
        with ui.element('q-item-section').classes(section_classes):
            ui.label('WiFi')
        with ui.element('q-item-section').classes(section_classes):
            ui.label('HO HOOOOOO')

def click(item: ui.element) -> None:
    # make all items inactive then activate the one clicked
    for _item in [item1, item2, item3]:
        _item._props['active'] = False
        _item.update()
    # activate the one clicked, not by toggling but by setting to True
    item._props['active'] = True
    item.update()

    # find the label in the item and print its text
    label = find_label(item)
    if label is not None:
        ui.notify(label.text)

ui.run()
```

**Comment by falkoschindler** [comment]
@abulka That looks awesome! I'd love to develop a better API for it. But at the moment I'm not sure what that API might even look like. But feel free to open a new discussion about this idea/feature request. Then we can discuss it more prominently with others and eventually start implementing it.

**Comment by abulka** [comment]
Ok, have started https://github.com/zauberzeug/nicegui/discussions/774
