### ISSUE TITLE
ui.page_sticky() does not work as expected

### ISSUE THREAD

**Issue by JS-Aibel** [zauberzeug/nicegui#710]
### Description

For the [page layout example](https://nicegui.io/documentation#page_layout), I want to have a container (variable) where I can keep the content of the “main view” bordering the header, footer, left and right drawers. When trying out the ui.page_sticky() the result is not like [the original example](https://nicegui.io/page_layout). See image below. Content all the way to the right. No scrolling available.

**Code**
```py
@ui.page('/')
async def page_layout():

    with ui.page_sticky() as mainView:
        ui.label('CONTENT')
        [ui.label(f'Line {i}') for i in range(100)]

    with ui.header(elevated=True).style('background-color: #3874c8').classes('items-center justify-between'):
        ui.label('HEADER')
        ui.button(on_click=lambda: right_drawer.toggle()).props('flat color=white icon=menu')
    with ui.left_drawer(top_corner=True, bottom_corner=True).style('background-color: #d7e3f4'):
        ui.label('LEFT DRAWER')
    with ui.right_drawer(fixed=False).style('background-color: #ebf1fa').props('bordered') as right_drawer:
        ui.label('RIGHT DRAWER')
    with ui.footer().style('background-color: #3874c8'):
        ui.label('FOOTER')
```

**Image** Showing only the top of the webpage.
![image](https://user-images.githubusercontent.com/100705556/229484735-0f7fc3dc-b2ec-4621-89a8-7a4622488ebd.png)

**Comment by falkoschindler** [comment]
Why do you expect `ui.page_sticky` to behave like the original example? Page sticky is for placing small UI elements like a floating button on top of the page content. See https://quasar.dev/layout/page-sticky.

**Comment by JS-Aibel** [comment]
Oh, my bad. 
From Quasar `"elements wrapped by this component will never overlap the layout header, footer or drawer(s), even if those are not configured to be fixed"` got me the impression that this was a container for the “content”.
 
I have had some problems where the content have exceeded the right drawer. I haven’t been able to reproduce the problem in a small example yet. But at least  Sticky pages is not the answer then 😊
