### ISSUE TITLE
not found error on inspect

### ISSUE THREAD

**Issue by HilkopterBob** [zauberzeug/nicegui#716]
### Description

hey, if i inspect my website with "inspect" tools of microsoft edge, i get following errors in my console:
```
http://localhost/_nicegui/1.2.4/static/socket.io.min.js.map not found
http://localhost/_nicegui/1.2.4/dependencies/3/highcharts-3d.js.map not found
http://localhost/_nicegui/1.2.4/dependencies/2/highcharts-more.js.map not found
http://localhost/_nicegui/1.2.4/dependencies/1/highcharts.js.map not found
http://localhost/_nicegui/1.2.4/dependencies/74/mermaid.min.js.map not found
```

the websites workes normal, imo.
as my website is quite big and i usually test with chrome where i cant inspect (company rule), i cannot say if this error is newly introduced by some element. 

System:
win11 prof. + Edge Version 111.0.1661.43

**Comment by HilkopterBob** [comment]
if i use a blank page:
```py
from nicegui import ui
ui.run()
```

i get the same errors

**Comment by HilkopterBob** [comment]
close because duplicate of issue #714

**Comment by falkoschindler** [comment]
@HilkopterBob No, that's not a duplicate of #714. In #714 _no_ static files are served. But you are describing a known issue that *.map files are not provided by NiceGUI.
Although it is not nice to see these warnings, it is nothing to worry about. They are only needed for debugging with the developer tools.
We are planning add these files in the future. Before that, we're improving the overall dependency management in https://github.com/zauberzeug/nicegui/pull/658.
