### ISSUE TITLE
ui.menu_item won’t open an ui.dialog()

### ISSUE THREAD

**Issue by JS-Aibel** [zauberzeug/nicegui#717]
### Description

Hi,

In the example below, when clicking **Help -> About**, the About dialog does not show. 
But if I click the **Help** button again, the About dialog pops up. 
Clicking the button “Open About” works as normal. 

I want the About dialog to pop up when I select About in the Help menu. The reason I place the ui.dialog() and dialog.open() in the function About() is that I want the dialog code to be in another file.
See code below.

```py
from nicegui import ui

def About():
    with ui.dialog() as dialog, ui.card():
        ui.label('About this app').classes('text-h6')
        ui.button('Close', on_click=dialog.close)
    dialog.open()

with ui.row().classes('w-full items-center'):
    result = ui.label().classes('mr-auto')
    with ui.button("Help", on_click=lambda: menu.open()):
        with ui.menu() as menu:
            ui.menu_item('About', lambda: About())

ui.button("Open About", on_click=About)

ui.run()
```

**Comment by falkoschindler** [comment]
Interesting question, @JS-Aibel!

I think you should split generating the dialog and opening it. You can do so by moving it into a class:

```py
class About:

    def __init__(self) -> None:
        with ui.dialog() as self.dialog, ui.card():
            ui.label('About this app').classes('text-h6')
            ui.button('Close', on_click=self.dialog.close)

    def open(self) -> None:
        self.dialog.open()

about = About()

with ui.row().classes('w-full items-center'):
    result = ui.label().classes('mr-auto')
    with ui.button("Help", on_click=lambda: menu.open()):
        with ui.menu() as menu:
            ui.menu_item('About', about.open)

ui.button("Open About", on_click=about.open)
```

Inheriting directly from `ui.dialog` you can even simplify it a bit, as you don't need to wrap the `open` method:

```py
class About(ui.dialog):
    def __init__(self) -> None:
        super().__init__()
        with self, ui.card():
            ui.label('About this app').classes('text-h6')
            ui.button('Close', on_click=self.close)

about = About()

with ui.row().classes('w-full items-center'):
    result = ui.label().classes('mr-auto')
    with ui.button("Help", on_click=lambda: menu.open()):
        with ui.menu() as menu:
            ui.menu_item('About', about.open)

ui.button("Open About", on_click=about.open)
```

**Comment by falkoschindler** [comment]
Oh, the actual reason why your code doesn't work: `About()` creates a new dialog _within the current context_. If it is triggered by a menu item, the context is the menu, i.e. the parent of the event sender. This is why you only see the dialog after opening the menu again.

But as indicated in my previous response, it might be better to create the dialog only once anyway.

**Comment by JS-Aibel** [comment]
Thank you for the help.
