### ISSUE TITLE
single page example navigation issue/bug

### ISSUE THREAD

**Issue by cj** [zauberzeug/nicegui#721]
### Description

When following the single page app example https://github.com/zauberzeug/nicegui/tree/main/examples/single_page_app, navigating affects other clients.

Here is a minimal repo that recreates the issue: https://github.com/cj/nicegui-single-page-app-router-issue 

![GIF Recording 2023-04-04 at 15 36 19](https://user-images.githubusercontent.com/1819/229915084-a09b81c1-af29-43a6-9dcf-50eb20f86f9f.gif)

**Comment by cj** [comment]
I came up with a possible solution; it fixes the issue, but there might be a better approach.

- https://github.com/cj/nicegui-single-page-app-router-issue/blob/possible-solution/app/ui/routes.py
- https://github.com/cj/nicegui-single-page-app-router-issue/blob/possible-solution/app/ui/__init__.py#L13-L14

**Comment by falkoschindler** [comment]
Thanks for spotting this bug and suggesting a fix, @cj!

It looks like moving [these lines](https://github.com/zauberzeug/nicegui/blob/4cd7d534de821764659863f8116b8eb2eb5458fb/examples/single_page_app/main.py#L6-L21) down into `main()` is all it takes. I think commit [425c209](https://github.com/zauberzeug/nicegui/commit/425c20901c79f8b2e8cb616c971ba370c74dc96f) fixes it.

**Comment by falkoschindler** [comment]
@rodja I just noticed that you can't navigate back more than once in the single page app example, independent of my change in [425c209](https://github.com/zauberzeug/nicegui/commit/425c20901c79f8b2e8cb616c971ba370c74dc96f). Should we file a new issue?

**Comment by falkoschindler** [comment]
Awesome, @cj! That works beautifully. 🙂
Just out of curiosity: Do you understand _why_ the condition is needed? I wonder where the redundant history entries come from and why they let you strand at the previous history entry.

**Comment by cj** [comment]
@falkoschindler I need to look into it further, but I'm pretty sure it's just a loop issue. Without the check history.pushState always gets called, and it will always be the page you are on, so hitting the back button will always be your current page as it's constantly pushed. I hope that made sense 😄

**Comment by falkoschindler** [comment]
Yeah, I guess I understand. Every time a page is opened, it is pushed to the history. This also happens when navigating back (caused by `ui.element('router_frame').on('open', ...)`), which pushes the popped page back to the stack.

**Comment by Salex406** [comment]
@cj Hi
I am testing the example
Is it ok that Back button doesn't work?
I mean, URL string changes when i press Back, but page content not refreshes
Any ways to fix? Unfortunately I don't know anything about JS

**Comment by falkoschindler** [comment]
@Salex406 Interesting, it seems like the Back button doesn't work to navigate back to the first page:
- When opening the app, clicking "Two" and "Back", the content still shows "Content Two".
- When opening the app, clicking "Two", "Three" and "Back", the content correctly shows "Content Two". Clicking "Back" again still shows "Content Two".

Let's create a new issue to tackle this bug.
