### ISSUE TITLE
pyright typing issues with on

### ISSUE THREAD

**Issue by cj** [zauberzeug/nicegui#722]
### Description

The is a pyright typing issue with `on`:
```
Pyright: Type of "on" is partially unknown
  Type of "on" is "(type: str, handler: ((...) -> Unknown) | None, args: List[str] | None = None, *, throttle: float = 0) -> Input" [reportUnknownMemberType]
```
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/1819/229917264-d8f0ee89-af8b-4e67-b27e-609e96731a45.png">

Minimal repo to re-create the issue https://github.com/cj/nicegui-typing-issues-with-on-

**Comment by rodja** [comment]
Thanks for sharing @cj. What IDE's have you tried? On which OS are you running?

**Comment by cj** [comment]
@rodja https://www.lunarvim.org/ (nvim) with pyright installed. `:LspInstall` then select pyright.

**Comment by falkoschindler** [comment]
@cj I'm not familiar with pyright. Do you have an idea about the cause? Is it maybe because the handler is only declared as `handler: Optional[Callable]` (without specifying the parameters and return value)?

**Comment by rodja** [comment]
I've set up a test environment with docker and installing pyright + nicegui yields no errors on your example repo:

```
/test/app# pyright .
No configuration file found.
pyproject.toml file found at /test.
Loading pyproject.toml file at /test/pyproject.toml
Pyproject file parse attempt 1 error: {"name":"TomlError","fromTOML":true,"wrapped":null,"line":35,"col":21,"pos":779}
Pyproject file parse attempt 2 error: {"name":"TomlError","fromTOML":true,"wrapped":null,"line":35,"col":21,"pos":779}
Pyproject file parse attempt 3 error: {"name":"TomlError","fromTOML":true,"wrapped":null,"line":35,"col":21,"pos":779}
Pyproject file parse attempt 4 error: {"name":"TomlError","fromTOML":true,"wrapped":null,"line":35,"col":21,"pos":779}
Pyproject file parse attempt 5 error: {"name":"TomlError","fromTOML":true,"wrapped":null,"line":35,"col":21,"pos":779}
Pyproject file parse attempt 6 error: {"name":"TomlError","fromTOML":true,"wrapped":null,"line":35,"col":21,"pos":779}
Config file "/test/pyproject.toml" could not be parsed. Verify that format is correct.
Assuming Python platform Linux
Searching for source files
Found 3 source files
pyright 1.1.302
0 errors, 0 warnings, 0 informations
Completed in 0.849sec
```

What does your output say?

**Comment by cj** [comment]
@rodja I fixed the example repo; there was an issue with the pyproject.toml, it has a duplicate `max-line-length`. If you pull the update, it should work as expected now. Sorry about that!

**Comment by falkoschindler** [comment]
I just reproduced the error by installing pyright (`brew install pyright`) and calling `pyright test.py` on
```py
# pyright: strict
from nicegui import ui

ui.input().on("keydown.enter", lambda: ui.notify('Send'))

ui.run()
```

VSCode also highlights pyright errors:
![Screenshot 2023-05-26 at 12 15 39](https://github.com/zauberzeug/nicegui/assets/5767091/2faecd13-493b-41fe-8f2c-49db2957d2ae)

**Comment by falkoschindler** [comment]
Ok, I replaced all plain `Callable` annotations with `Callable[..., Any]` (or more specific annotations in some cases). This resolves the original issue.

I also type-annotated `kwargs` to fix the error for `ui.notify` and `ui.run`.
