### ISSUE TITLE
Unknown error after packaging

### ISSUE THREAD

**Issue by ymweagle** [zauberzeug/nicegui#730]
### Description

python 3.11
nicegui 1.2.6
auto-py-to-exe 2.33.0

Run after packaging
![image](https://user-images.githubusercontent.com/49975096/230557116-9d57d399-c2f1-47f7-8f8e-1274f48b9d38.png)

code show as below
```py
from nicegui import ui
import sys
sys.stdout = open('logs.txt', 'w') # divert stdout to logs.txt file
ui.label('transparency')

ui.run(reload=False, native=True)
```

**Comment by rodja** [comment]
We have not tested with auto-py-to-exe and do not now which options need to be set to make it work. Why do not [use PyInstaller](https://nicegui.io/documentation#package_for_installation) instead?

**Comment by ymweagle** [comment]
Change to Pyinstaller packaging, error still exists

**Comment by ymweagle** [comment]
> ### Description
> python 3.11 nicegui 1.2.6 auto-py-to-exe 2.33.0
> 
> Run after packaging ![image](https://user-images.githubusercontent.com/49975096/230557116-9d57d399-c2f1-47f7-8f8e-1274f48b9d38.png)
> 
> code show as below
> 
> from nicegui import ui import sys sys.stdout = open('logs.txt', 'w') # divert stdout to logs.txt file ui.label('transparency')
> 
> ui.run(reload=False, native=True)

this is the new error
![image](https://user-images.githubusercontent.com/49975096/230814812-db7ce534-3075-44c6-80b8-e2514b0291cd.png)

**Comment by rodja** [comment]
Could you provide the output of the script (eg. log.txt)? What happens if you start the code directly (not packaged)? And what is the outcome if you remove the log redirection?

**Comment by falkoschindler** [comment]
I'll close this issue due to inactivity. Please feel free to re-open it once there is new information.
