### ISSUE TITLE
ui.input with mask overwrites chars and makes them undeletable

### ISSUE THREAD

**Issue by phoskee** [zauberzeug/nicegui#731]
### Description

```py
from nicegui import ui

INPUT_CODE = ui.input(placeholder='CODE').props('rounded outlined autofocus input-class=mx-3 mask="AAAAAA##A##A###A"')

ui.run()
```
![bug-nicegui-input](https://user-images.githubusercontent.com/125825348/230563932-d83370f7-dd71-4eb0-b6bc-2b55ea776d83.gif)

**Comment by falkoschindler** [comment]
Minimal reproduction:

```py
ui.input().props('mask="AAA###"')
```

Typing "abc123" yields "ABC123" (correct).
Pressing backspace 6 times yields "B" with strange intermediate values.

**Comment by falkoschindler** [comment]
@phoskee That's great news! Then we should upgrade from 2.11.8 to 2.11.9.
