### ISSUE TITLE
format is not applied to number element 

### ISSUE THREAD

**Issue by tmichela** [zauberzeug/nicegui#736]
### Description

The formatting is applied to the default value when starting the app, but not for updated values by the user. The correct formatting is only applied once the page is reloaded.

Example:

```python
from nicegui import ui

ui.number('num', 1234, format='%06d')
ui.run()
```

![nicegui-number-bug-report](https://user-images.githubusercontent.com/32831491/230791084-7175a83e-ac42-43cf-a39c-2b0db999b631.gif)

**Comment by falkoschindler** [comment]
Thanks for reporting this bug, @tmichela!

It looks like the fix from https://github.com/zauberzeug/nicegui/issues/287 introduced this issue by not sending the updated value back to the client.

**Comment by falkoschindler** [comment]
A simple fix might be to send an update on blur:

```py
class Number(ValueElement):
    ...
    def __init__(self, ...) -> None:
        ...
        self.on('blur', self.update)
```
