### ISSUE TITLE
docker image fails; missing docutils

### ISSUE THREAD

**Issue by Paradoxdruid** [zauberzeug/nicegui#739]
### Description

I pulled the current docker image with `docker pull zauberzeug/nicegui`.

Then, I ran `docker run --rm zauberzeug/nicegui`, and encountered this error:

```
Traceback (most recent call last):
  File "/app/main.py", line 22, in <module>
    from website import documentation, example_card, svg
  File "/app/website/documentation.py", line 6, in <module>
    from .documentation_tools import element_demo, heading, intro_demo, load_demo, subheading, text_demo
  File "/app/website/documentation_tools.py", line 6, in <module>
    import docutils.core
ModuleNotFoundError: No module named 'docutils'
```

It appears the docker image is missing some needed dependencies to run.

**Comment by rodja** [comment]
Wow. Thanks for reporting @Paradoxdruid. I cant believe we missed that. Will be fixed with next release 1.2.7. I also added a verification step to GitHub Actions which ensure the container starts as expected.
