### ISSUE TITLE
Drag and Drop ?

### ISSUE THREAD

**Issue by GlennoFromOZ** [zauberzeug/nicegui#75]
Is it possible to have a Drag and Drop option ? Would be great to be able to drop something like a CSV and be able to process it.

Thanks!

**Comment by falkoschindler** [comment]
You can already drop a file on `ui.upload`. You can try the following example. Dropping a file onto the input field should show its filename. Hitting "Upload" should print the file content onto the console (besides other event information).

```python
from nicegui import ui

ui.upload(on_upload=lambda *args: print(*args, flush=True))

ui.run(port=1234)
```
