### ISSUE TITLE
Send "leading" and "trailing" events when throttling

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#751]
### Description

On Discord we noticed that the current event throttling implements a "leading" throttle. This is good for getting the first event immediately without additional latency. But often you are interested in the last event as well, even if it is slightly delayed, e.g. when moving a slider to its final position.

> [...] in your case it's more a question of how exactly you want to throttle. Check this diagram: https://dev.to/rxjs/debounce-vs-throttle-vs-audit-vs-sample-difference-you-should-know-1f21. The current implementation seems to be "throttle leading" while you're looking for "throttle trailing". There are certainly applications for both. "leading" might feel like less latency, but - you're right - doesn't capture the last event.
As we're planning to improve on the whole event subscription (#685, #672, #583), it might be a good opportunity to think about the throttling.

- [x] By default we should send leading _and_ trailing events.
- [x] Maybe we can also allow the user to define which events to get, either leading, trailing or both.

**Comment by pythonwood** [comment]
sorry but the function throttle(callback, time, leading, trailing, id) in <script> is not rigth, isn`t  it?
[commit is here
](https://github.com/zauberzeug/nicegui/commit/050767966d6b79ae100cf9188fde0f71e6146057)
```
      function throttle(callback, time, leading, trailing, id) {
        if (time <= 0) {
          // execute callback immediately and return
          callback();
          return;
        }
        if (waitingCallbacks.has(id)) {
          if (trailing) {
            // update trailing callback
            waitingCallbacks.set(id, callback);
          }
        } else {
          if (leading) {
            // execute leading callback and set timeout to block more leading callbacks
            callback();
            waitingCallbacks.set(id, null);
          }
          else if (trailing) {
            // set trailing callback and set timeout to execute it
            waitingCallbacks.set(id, callback);
          }
          if (leading || trailing) {
            // set timeout to remove block and to execute trailing callback
            setTimeout(() => {
              const trailingCallback = waitingCallbacks.get(id);
              if (trailingCallback) trailingCallback();
              waitingCallbacks.delete(id)
            }, 1000 * time);
          }
        }
      }
```

**Comment by falkoschindler** [comment]
@pythonwood What is wrong with it?

**Comment by pythonwood** [comment]
> @pythonwood What is wrong with it?

add 4 line in index.html <scriptp> for input debuging.  
```
            const emitter = () => window.socket.emit("event", data);
            if (element.tag == "nicegui-input"){ // element.component.name == "input"
              event.throttle = 2.5; event.leading_events = false; 
            }
            console.log(event_name, event.throttle, event.leading_events, event.trailing_events, event.listener_id);
            throttle(emitter, event.throttle, event.leading_events, event.trailing_events, event.listener_id);
```
wants it to be trailling but after booting examples/chat for test, it do not work.

**Comment by pythonwood** [comment]
do you agree?  
and I fix for myself now. how about I post it as a pr ? 
```
      const waitingCallbacks = new Map();
      function throttle(callback, time, leading, trailing, id) {
        if (time <= 0) {
          // execute callback immediately and return
          callback();
          return;
        }
        // below: if time > 0
        if (leading) {
          if (!waitingCallbacks.has(id) || Date.now() > waitingCallbacks.get(id) + 1000 * time) {
            callback();
          }
          waitingCallbacks.set(id, Date.now());
          return;
        }
        // below: if time > 0 and not leading
        clearTimeout(waitingCallbacks.get(id)??null);
        waitingCallbacks.set(id, 
          setTimeout(() => { 
            callback(); 
          }, 1000 * time)
        ); 
      }
```

**Comment by falkoschindler** [comment]
@pythonwood Sorry, I still don't understand the problem. But feel free to post a new issue or a pull request. Please include a minimum reproducible code example, a description of what you expect to happen, what is happening instead and how you fixed it. Thanks!

**Comment by pythonwood** [comment]
I improve mycode now. new issuse and pr are coming.  
[Debouncing and Throttling Explained Through Examples
](https://css-tricks.com/debouncing-throttling-explained-examples/)
```
      function throttle(callback, time, leading, trailing, id) {
        if (time <= 0) {
          // execute callback immediately and return
          callback();
          return;
        }
        // below: if time > 0
        if (leading) {
          if (!waitingCallbacks.has(id) || Date.now() >= waitingCallbacks.get(id) + 1000 * time) {
            waitingCallbacks.set(id, Date.now());
            callback();
          } else if (!trailing)  // sure now: id in Map and waited time < need time
            waitingCallbacks.set(id, Date.now());
          return;
        }
        // below: if time > 0 and not leading
        clearTimeout(waitingCallbacks.get(id)??null);
        waitingCallbacks.set(id, 
          setTimeout(() => { 
            callback(); 
          }, 1000 * time)
        ); 
      }
```
