### ISSUE TITLE
user A's input value would display on user B's page automatically

### ISSUE THREAD

**Issue by CocoaRush** [zauberzeug/nicegui#759]
### Description

when I bind the value using ui.input().bind_value(xxx, 'yyy')

the the value get share automatically from one user to all the other, am I doing something wrong or this is the designed feature?

which means, if user A input something, user B/C/D... will all see the input if they are on the same page.

**Comment by falkoschindler** [comment]
Hi @CocoaRush! This isn't a bug, but a feature. 😉 
Have a look at https://github.com/zauberzeug/nicegui/discussions/461, https://github.com/zauberzeug/nicegui/discussions/491 and [the documentation on the auto-index page](https://nicegui.io/documentation#auto-index_page) for more information.
