### ISSUE TITLE
example app fails on Rpi2B running dietpi

### ISSUE THREAD

**Issue by linxcow** [zauberzeug/nicegui#769]
### Description

Tried to install on my RPI 2B running dietpi Install went fine , running a demo app failed

  ImportError: libcblas.so.3: cannot open shared object file: No such file or directory

Fix attempt :

 sudo apt-get install libcblas-dev => Package libcblas-dev is not available

Could not find requirements for running nicegui

**Comment by rodja** [comment]
Thanks for reporting the issue. Does 

    sudo apt-get install libatlas-base-dev

work for you?

**Comment by linxcow** [comment]
Yes , this worked , but i gave up after having to find & fullfill numerous other dependencies but still not working.

**Comment by rodja** [comment]
Yes, some of the NiceGUI dependencies require system-level dependencies that must be installed through your OS package manager. That can be quite cumbersome -- especially if you aim for a very stripped down os (like dietpi). Most often the best approach would be to just use a docker container. That way, all dependencies are already packaged inside the image.

Would you like to give it another try with 

    docker run -it --rm -p 8888:8080  -v "$PWD":/app zauberzeug/nicegui

run in a directory which contains a `main.py` with some NiceGUI code? The page should then be reachable via http://localhost:8888.

**Comment by linxcow** [comment]
I think the pi 2 may be a little limited to run docker apps , but thx for the suggestion

**Comment by rodja** [comment]
I'm sorry. So you give up? Would you like to close the issue?

**Comment by falkoschindler** [comment]
I'll close this thread due to inactivity. Please feel free to re-open it if you're still looking for a solution.
