### ISSUE TITLE
ui.markdown has no table support and or is missing extra features

### ISSUE THREAD

**Issue by TKaluza** [zauberzeug/nicegui#77]
in the markdown class the library markdown2 is used. For encoding different styles extras are needed, see [wiki markdown2](https://github.com/trentm/python-markdown2/wiki/Extras)

https://github.com/zauberzeug/nicegui/blob/30010cd6a12142deff62ada34bf511750cc494ed/nicegui/elements/markdown.py#L20
For example:
```python
html = markdown2.markdown(content, extras=["fenced-code-blocks", "tables"])
```
Why not add additional options (or at least `tables`)? :smile:

**Comment by falkoschindler** [comment]
Good idea! I made the list of extensions configurable and added "tables" by default: https://github.com/zauberzeug/nicegui/commit/686ce6a7cd22d37c15f6781232183a4be5f1aa00

**Comment by rodja** [comment]
I just released https://github.com/zauberzeug/nicegui/releases/tag/v0.8.10 with this feature. Great work!
