### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by YasTouchedMySpaggett** [zauberzeug/nicegui#793]
### Description

Hello,
I generate a pdf file with my code and open it on another tab but i could not find that on the docs, so instead im trying to download the file with the code from the documentation

```py
from nicegui import ui

ui.button('NiceGUI Logo', on_click=lambda: ui.download('https://nicegui.io/logo.png'))

ui.run()
```

but i get this error instead of a download prompt

`AttributeError: module 'nicegui.ui' has no attribute 'download'`

for context, this is my code around the command
` ui.button('Εκτυπωση', on_click=lambda: (printer(label1.text)))`

which then goes to make the pdf and
`page.cell(0, 0, printLabel1.text)
 page.output('C:/Users/user/dir/code/tuto1.pdf', 'F')
 ui.download('C:/Users/user/dir/code/tuto1.pdf')`

First of all, how do i fix this error, and second, is there a way to open the pdf on another page after all?

**Comment by rodja** [comment]
Do you have the latest NiceGUI version?

**Comment by YasTouchedMySpaggett** [comment]
> Do you have the latest NiceGUI version?

nicegui in c:\users\user\appdata\local\programs\python\python311\lib\site-packages **(1.2.6)**

i believe yes?

**Comment by rodja** [comment]
`ui.download` was introduced in [1.2.7](https://github.com/zauberzeug/nicegui/releases/tag/v1.2.7). Latest is 1.2.8.

**Comment by YasTouchedMySpaggett** [comment]
Oh, well that makes sense, haha.

Thank you a lot

**Comment by YasTouchedMySpaggett** [comment]
I upgraded and i no longer have the error, though pushing the button doesnt do anything : (

**Comment by falkoschindler** [comment]
Strange. Do you see any Python exception or output on the JavaScript developer console when pushing the button?

**Comment by YasTouchedMySpaggett** [comment]
nope : ((

**Comment by YasTouchedMySpaggett** [comment]
i also have tabs, maybe its that?

`with ui.tabs() as tabs:
    ui.tab('Home', icon='home')
    ui.tab('Statistics', icon='info')
with ui.tab_panels(tabs, value='Home').style('width: 65%'):`

**Comment by falkoschindler** [comment]
I'll close this issue due to inactivity. Please feel free to re-open it if there is new information about the problem.
