### ISSUE TITLE
Blockquotes not styled

### ISSUE THREAD

**Issue by atomicrichard** [zauberzeug/nicegui#820]
### Description

I am trying to render a styled blockquote in Markdown.

Minimal reproducible code example:

```py
from nicegui import ui

ui.markdown("Normal")
ui.markdown("> Quoted")

ui.run()
```

2. Expected behavior: "Quoted" is wrapped in `<blockquote>` and styled.
3. Actual behavior: "Quoted" is wrapped in `<blockquote>`, but no styles are applied.

Edit: workaround:

```py
ui.html("""
<style>
blockquote {
  background: #f9f9f9;
  border-left: 10px solid #ccc;
  margin: 1.5em 10px;
  padding: 0.5em 10px;
  quotes: "\201C""\201D""\2018""\2019";
  font-style: italic;
}
</style>
""")
```

**Comment by falkoschindler** [comment]
Thanks for reporting this bug, @atomicrichard!
Tailwind seems to remove all styling for the blockquote tag. Running with `ui.run(..., tailwind=False)` at least indents the quote a little.
I'm not sure how to fix it though. Simply styling _all_ blockquotes (i.e. partly reverting Tailwind's CSS reset) might have unwanted side effects. But maybe we can add the style to nicegui.css using a selector that only matches blockquotes in markdown elements.
