### ISSUE TITLE
New event registrations are not sent to the client

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#834]
### Description

The discussion #823 revealed a flaw in the generic event registration method `.on()`. When called later (after the element has already been sent to the client), the updated list of event listeners is not sent to the client.

Consider this simply example:
```py
label = ui.label('Click me maybe')
ui.button('Make label clickable', on_click=lambda: label.on('click', lambda: ui.notify('clicked!')))
ui.button('Update label', on_click=lambda: label.update())
```
The "Make label clickable" button should register a click event handler on the label. But only after triggering an "Update label" the label is actually clickable.

I think we should simply add an an `update()` at the end of `on()`.

**Comment by rodja** [comment]
I agree
