### ISSUE TITLE
Default URL does not work in WSL (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by ChrisJefferson** [zauberzeug/nicegui#855]
### Description

If I run the most minimal example in WSL in Windows, I get the following output:

```
>>> from nicegui import ui
>>> ui.label('Hi')
<nicegui.elements.label.Label object at 0x7f3c14f139a0>
>>> ui.run()
WARNING:root:auto-reloading is only supported when running from a file
NiceGUI ready to go on http://0.0.0.0:8080
```

The URL `http://0.0.0.0:8080` does not work if I put it in a windows browser. However, the URL `http://localhost:8080` does work fine. So does `http://127.0.0.1:8080/`

I'm not totally clear on the difference between `0.0.0.0` vs `localhost` vs `127.0.0.1`, so I'm not sure why `0.0.0.0` was chosen, and if changing the default to `localhost` or `127.0.0.1` might break something else?

**Comment by rodja** [comment]
Thanks for spotting this @ChrisJefferson! Looks like this bug got introduced in cf6c150c6. Anyone interested in creating a pull-request for this?

**Comment by falkoschindler** [comment]
@rodja Can you, please, add a link to the commit? I can't find it. 🤔

**Comment by falkoschindler** [comment]
Is the message "NiceGUI ready to go on http://0.0.0.0:8080" really incorrect? It correctly says where the server is listening. You can reach it via localhost (or 127.0.0.1) or from other machines in the local network using the IP of the host machine.

In contrast, would it be running on http://127.0.0.1:8080 you couldn't reach it from the local network but only from the host itself.

Maybe I'm missing something. But it looks like we need to clarify the actual purpose of this message.

**Comment by rodja** [comment]
>  it looks like we need to clarify the actual purpose of this message

True. I think the main purpose of the message is that you can click on it to open a browser tab. That does not work on all operating systems with 0.0.0.0. After digging deeper I don't think it is not a regression. We implemented a mapping from 0.0.0.0 to localhost [for the `show` parameter](https://github.com/zauberzeug/nicegui/blob/main/nicegui/helpers.py#L80). I mixed these two up.

And you are right, technically we are opening on 0.0.0.0 which means "listen on all interfaces". This also allows remote browsers to connect. Maybe we should write it more explicitly. Something like

    NiceGUI ready to go on http://localhost:8080 and other network interfaces

**Comment by falkoschindler** [comment]
New idea:

Instead of
```
NiceGUI ready to go on http://0.0.0.0:1234
```

we write
```
NiceGUI ready to go on http://localhost:1234, http://192.168.1.42:1234, and http://192.168.42.150:1234
```

Port 80 will be omitted.

**Comment by falkoschindler** [comment]
In [83203d6](https://github.com/zauberzeug/nicegui/commit/83203d6bd7e2f2f7e45962e79480e132d46879b8) I accidentally used `removesuffix` which is only available in Python 3.9. Apart from that this issue is resolved.
@rodja What do you think?

**Comment by rodja** [comment]
@falkoschindler I get

```
ips += set(ip for _, _, _, _, (ip, _) in socket.getaddrinfo(socket.gethostname(), None))

ValueError: too many values to unpack (expected 2)
```

The list from `socket.getaddrinfo` looks like this:

- `(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('::1', 0, 0, 0))`
- `(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0))`
- `(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('fe80::1', 0, 0, 1))`
- `(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('fe80::1', 0, 0, 1))`
- `(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))`
- `(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('127.0.0.1', 0))`
- `(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.1.165', 0))`
- `(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('192.168.1.165', 0))`
- `(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('fe80::cc30:c3ff:fee6:ff18', 0, 0, 6))`
- `(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('fe80::cc30:c3ff:fee6:ff1a', 0, 0, 5))`
- `(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('fe80::cc30:c3ff:fee6:ff19', 0, 0, 4))`
- `(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('fe80::cc30:c3ff:fee6:ff18', 0, 0, 6))`
- `(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('fe80::cc30:c3ff:fee6:ff1a', 0, 0, 5))`
- `(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('fe80::cc30:c3ff:fee6:ff19', 0, 0, 4))`
- `(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('fe80::1497:8bc2:ad63:c6ca', 0, 0, 14))`
- `(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('fe80::1497:8bc2:ad63:c6ca', 0, 0, 14))`

**Comment by falkoschindler** [comment]
Oh! I didn't consider IP6. I'll fix it.

**Comment by falkoschindler** [comment]
[7219baf](https://github.com/zauberzeug/nicegui/commit/7219baf2445627d17949e8278e18c19f7af51410) should have fixed it.
