### ISSUE TITLE
Chat message(s) repeated

### ISSUE THREAD

**Issue by markbaumgarten** [zauberzeug/nicegui#863]
### Description

Using the recently updated chat message example I have found that when a second user starts a session, the message(s) from the first user are repeated.

1) Start a session in one tab. Enter a message.
2) Start a second session in a new tab. Enter a message.

Notice how first users messages appears twice:

![message_repeated](https://user-images.githubusercontent.com/2726762/235247672-e196b629-59a0-412c-bd95-27cbb800a034.png)

I suspect the refreshable stuff to be the source of the error.....

Thanks for the nice updates to the chat message example by the way.

**Comment by rodja** [comment]
Wow. Thanks for spotting this @markbaumgarten. Much appreciated. Finding the issue took me all morning. But it was worth it. Here a minimal reproduction:

```py
@ui.refreshable
async def my_content() -> None:
    ui.label('refreshed')

@ui.page('/')
async def index():
    with ui.column():  # this makes the bug visible
        await my_content()
    ui.button('Refresh', on_click=my_content.refresh)
```

To make the refreshable function awaitable, we just returned the result in 

https://github.com/zauberzeug/nicegui/blob/9a93b77bb9d642fd7db37d5ed0c5f2a6aa2effbc/nicegui/functions/refreshable.py#L33

But that made the refreshable function execute in the outside container (`ui.column` in the reproduction) and not the internal container managed by `@ui.refershable`.

**Comment by markbaumgarten** [comment]
Wow. You guys dont rest much.... Thanks a million @rodja . I believe a lot of my future work will be based upon NiceGUI. I think NiceGUI contains just the right mix of components.
