### ISSUE TITLE
dynamic vue props are not supported

### ISSUE THREAD

**Issue by duane-impulse** [zauberzeug/nicegui#893]
### Description

**Initial Problem:** 

NiceGUI doesn't appear to support defining dynamic Vue props (assigned using either v-bind: or : before the prop key). Initial goal for the purposes of demonstrating this is to limit the valid date selections on a date component to be on or before May 15th 2023 using the options prop, similar to examples given in the interactive widget at the top of the Quasar QDate API documentation.

[https://quasar.dev/vue-components/date/](https://quasar.dev/vue-components/date/)

**Example case:**

```python
from nicegui import ui

# goal is to allow selecting any date prior or equal to May 15 2023
# based on the Quasar QDate API documentation

ui.date().props(''' :options="date => date <= '2023/05/15'" ''')
# actual result is only May 15 2023 selectable

ui.run()
```

**Result:**
![picture1](https://user-images.githubusercontent.com/125305042/236291008-d5940a58-f805-40ce-85a6-b94207db38f7.png)

So we don’t get the expected result - we can only select May 15th 2023, not any prior dates. Digging into why this might be, I believe I’ve come to understand the difference between setting Vue props like “options=” versus “:options=”. The former will evaluate as a string while the latter will evaluate as JavaScript. 

[https://vuejs.org/guide/components/props.html#props-declaration](https://vuejs.org/guide/components/props.html#props-declaration)

Let’s demonstrate this behavior in codepen, without NiceGUI.

[https://codepen.io/pen?template=dygJbNq](https://codepen.io/pen?template=dygJbNq)

The first case should be (at least as far as the defined props are concerned) identical to our attempt in NiceGUI, but the result is different. We get the intend behavior of allowing any date before or equal to May 15 2023!

In the second case, we can demonstrate instead evaluating the options prop as a string. This shows the same behavior as NiceGUI – only May 15 2023 is selectable. So this indicates that NiceGUI is indeed evaluating the prop as a string. I'm not sure exactly how this behavior works behind the scenes, but I'd guess something like it just searches the string for matches of the default date mask. (Tangent: while investigating this, it appears the default Quasar mask uses slashes, but the default in NiceGUI uses hyphens?)

Investigating this behavior in NiceGUI leads to [element.py (line 21).](https://github.com/zauberzeug/nicegui/blob/865a8eba1e1818ad6a64dde3c1af5e720ea5d332/nicegui/element.py#L21).

The regex results in dropping the colon in “:options” and instead just matching “options”. So this would seem to completely explain the behavior! Let’s update it to preserve the colon.

```diff
- PROPS_PATTERN = re.compile(r'([\w\-]+)(?:=(?:("[^"\\]*(?:\\.[^"\\]*)*")|([\w\-.%:\/]+)))?(?:$|\s)')
+ PROPS_PATTERN = re.compile(r'([:\w\-]+)(?:=(?:("[^"\\]*(?:\\.[^"\\]*)*")|([\w\-.%:\/]+)))?(?:$|\s)')
```

Now that we’ve “fixed” that, let’s try to replicate the codepen in NiceGUI.

```python
from nicegui import ui
import re

# goal is to allow selecting any date prior or equal to May 15 2023

should_work = ui.date().props(''' :options="date => date <= '2023/05/15'" ''')
# actual result is every date is selectable

shouldnt_work = ui.date().props(''' options="date => date <= '2023/05/15'" ''')
# actual result is only may 15 2023 is selectable

ui.run()
```

**Result:**

![Picture2](https://user-images.githubusercontent.com/125305042/236292395-ebf0e4ae-1e56-4a26-a0c4-5fc0b2ab66c3.png)

We do see in the second case that treating options as a string works as we would expect, identical to the previous behavior. Unfortunately, the first case which we hoped would work is still not as intended. The behavior **_is_** altered, but now every date is selectable **including** those after May 15 2023 which may indicate the options prop did nothing. Inspecting the page, we can verify the entire ":options" key now makes it to the client, but it appears that during _some_ parsing _somewhere_ the colon may be preventing it from being properly treated as a prop.

**Comment by falkoschindler** [comment]
@duane-impulse Thanks for this interesting analysis!

A quick thought about the `PROPS_PATTERN`: You can take a shortcut and write to the `_props` dictionary directly. So if setting the `:options` prop works, we can fix the parser later.
```py
d = ui.date()
d._props[':options'] = "date => date <= '2023/05/15'"
```

I think the core problem is that we'd need to evaluate such props on the client, i.e. converting it from a string into a function. Currently that's a known limitation. But why not adding such a conversion to index.html? A leading colon should be a clear indicator for a JavaScript expression that needs to get evaluated.

**Comment by falkoschindler** [comment]
I drafted a PR #896 to experiment with a possible implementation. @duane-impulse Would you like to try it out?
Evaluating strings is always a bit risky. But I guess it's ok because the Python code controls these props.
