### ISSUE TITLE
element.move() does not work as expected in some cases

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#898]
### Description

There seems to be a bug in `element.move`. When the enter key is pressed, the following demo should move the input field to another container and create a new input field in the first one. But this only works once:

```py
def create_new_input():
    with section1:
        input = ui.input()
        input.on('keydown.enter', lambda: add_item(input))

def add_item(element: ui.element):
    element.move(section2)
    create_new_input()

section1 = ui.card()
section2 = ui.card()
create_new_input()
```

**Comment by falkoschindler** [comment]
Adding a delay helps:
```py
def create_new_input():
    with section1:
        input = ui.input()
        input.on('keydown.enter', partial(add_item, input))

async def add_item(element: ui.element):
    element.move(section2)
    await asyncio.sleep(0.1)
    create_new_input()

section1 = ui.card()
section2 = ui.card()
create_new_input()
```

Of course, this is no solution. But maybe it helps understanding the problem.

**Comment by falkoschindler** [comment]
Oh, Vue's in-place patching seems to cause this issue. See https://github.com/zauberzeug/nicegui/issues/600 for a related bug. This means setting some unique property like
```py
self._props['key'] = self.id
```
in the `ui.input` or `ui.element` initializer fixes the problem.

I tend to move this line into the base class `ui.element`, because Vue's in-place patching keeps causing isseus like this.

**Comment by rodja** [comment]
I'm in favour for this. Can derived elements which handle replacement correctly still remove the key prop? I think @dclause wrote somewhere that it stops certain Vue optimizations...

**Comment by falkoschindler** [comment]
I'm not sure there is any element that is guaranteed to always behave correctly. When _replacing_ elements (#600), it only affected custom elements. But this time it affects a raw QInput.

I'm not even sure if Vue's performance optimization actually helps us. And if it does, the impact might be negligible, since our bottleneck is the websocket connection, not the rendering engine.

Long story short: I don't know Vue well enough to really understand the implications. But preventing any in-place patching seems reasonable and more stable.
