### ISSUE TITLE
Provide more complex examples

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#90]
We should create an `examples` folder with separate subfolders for each example.

Task list:
- [x] Map with live coordinates
- [x] Custom component class
- [x] Custom page class
- [x] remove obsolete `examples.py`
- [x] move `custom_example` into example folder

**Comment by rodja** [comment]
I just pushed the map example. This also shows how to encapsulate an javascript library (here [leaflet](https://leafletjs.com/)).
