### ISSUE TITLE
Duplicate content when creating a ui.log element while client is already connected

### ISSUE THREAD

**Issue by falkoschindler** [zauberzeug/nicegui#906]
### Description

The button in the following example should replace the `ui.log` ("A") with a new one ("B").

```py
with ui.row() as container:
    ui.log().push('A')

def replace():
    container.clear()
    with container:
        ui.log().push('B')

ui.button('Replace', on_click=replace)
```

Strangely, the resulting log contains two lines "B".

This bug already occurs back in version 1.2.7 when we first introduced the element replacement tests.

**Comment by falkoschindler** [comment]
Minimal reproduction:

```py
ui.button('Log', on_click=lambda: ui.log().push('Hi!'))
```

It looks like the problem occurs whenever a `ui.log` is created while the client is already connected.

**Comment by falkoschindler** [comment]
I managed to fix this bug by keeping track of the total number of lines sent to the client. If the number already matches, the push method exits early. It's not the most elegant we ever implemented, but it does the job.

https://github.com/zauberzeug/nicegui/tree/log-bug

@rodja Would you like to have a look?

**Comment by rodja** [comment]
@falkoschindler looks good. Let's merge it into main.
