### ISSUE TITLE
Incorrect type hint for `set_visibility()` method

### ISSUE THREAD

**Issue by jonathanunderwood** [zauberzeug/nicegui#911]
### Description

The `set_visibility()` method [here](https://github.com/zauberzeug/nicegui/blob/7deff0c433ca54d06bd857af7416e9583ccac6ca/nicegui/elements/mixins/visibility.py#L73) has the following definition:

```
    def set_visibility(self, visible: str) -> None:
        """Set the visibility of this element.

        :param visible: Whether the element should be visible.
        """
        self.visible = visible
```
but it looks like the `visible` attribute is a boolean. So, I think the type hint of `str` is incorrect?

**Comment by rodja** [comment]
Thanks for reporting @jonathanunderwood. Will be part of next release.
