### ISSUE TITLE
Trailing semicolon in function style() raises ValueError on dict update

### ISSUE THREAD

**Issue by hroemer** [zauberzeug/nicegui#93]
Update version `0.9.0` on existing code with calls to`style()` now raises:

`ValueError: dictionary update sequence element #2 has length 1; 2 is required`

```python
def str_to_dict(s: Optional[str]) -> Dict[str, str]:
    return dict((word.strip() for word in part.split(':')) for part in s.split(';')) if s else {}
```
[element.py#L72:L73](https://github.com/zauberzeug/nicegui/blob/ca2820666fb9faa0fe8d196827f986e5d031240c/nicegui/elements/element.py#L72:L73)

# Repro

```python
from nicegui import ui

btn = ui.button('Click me!', on_click=lambda: ui.notify(f'You clicked me!'))
btn.style(add='text-decoration: underline; text-transform: uppercase;')

ui.run()
```

**Comment by falkoschindler** [comment]
Thanks for pointing this out!
Should be fixed in https://github.com/zauberzeug/nicegui/commit/b54f827cefc1dadf56864ed5e0b181455bf8ab57
