### ISSUE TITLE
Chat app issue on mobile

### ISSUE THREAD

**Issue by markbaumgarten** [zauberzeug/nicegui#935]
### Description

I have tried to deploy my own slightly modified version of the chat example on a public facing VPS.

The app works fine on a normal laptop, but on my android+chrome cell phone I get the following occasional behavior(it requires patience to reproduce):

After using the app on my mobile phone I let my phone go into "Lock screen" mode. I then return to the browser tab in Chrome and occasionally:

1) Chrome says ERR_CONNECTION_TIMED_OUT

2) Upon first and second reload(I drag my finger from top to bottom of the UI): I get  blank white page. On third reload, the page loads fine.

I believe this has to do with the inner workings of android/cell phones and the way a phone tries to reduce power consumption by closing idle connections, but this is just a hunch of mine.

Did anyone other than me see this behavior - or does anyone have an idea how to resolve this?

Thanks

**Comment by rodja** [comment]
Does it only happen with the chat app? Or can you also reproduce the behaviour with https://nicegui.io itself?

**Comment by markbaumgarten** [comment]
Hmmmmm. Tried to leave nicegui.io on my chrome tab open, left my phone for
a few hours, then returned and briefly noticed the same connection timeout.
But nicegui.io does seem to recover faster (only .5 second)  than my own
test page.

**Comment by markbaumgarten** [comment]
Occasionally I see Facebook Messenger serving me a blank page as well....I
wonder if this is related.

Maybe it is just my phone?

**Comment by rodja** [comment]
Maybe the behaviour can be fixed by using the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) to detect when the page becomes visible again and refresh the content if needed?

**Comment by markbaumgarten** [comment]
Hmmmm - could you provide an example? Struggling to see how to call python from javascript as you can probably tell from this poor example...:

```
ui.run_javascript('document.addEventListener("visibilitychange", () => {
  if (document.hidden) {
     // Nothing
 } else {
    await chat_messages();
  }
});', respond=False)
```

How can I subscribe to this event from python?

**Comment by rodja** [comment]
I think you'll need a custom component. With that you can emit events from js to Python like done here:

https://github.com/zauberzeug/nicegui/blob/1aac7c09f1d7c68d0c34f8e53c3a206ec89d29f8/examples/custom_vue_component/counter.js#L14

**Comment by falkoschindler** [comment]
@markbaumgarten I recently found out how to emit events in JavaScript - no custom Vue component required:

```py
l = ui.label('Hello').on('clickclack', lambda: ui.notify('World!'))

ui.button('Click me', on_click=partial(ui.run_javascript, f'''
    getElement({l.id}).dispatchEvent(new CustomEvent("clickclack"));
'''))
```

Maybe this approach helps with handling the "visibilitychange" event.

**Comment by markbaumgarten** [comment]
Nice....I was about to create a merge request like this example...see below, but wanted to tie this to a refreshable element...

How would you go about this (using your example) without creating any new elements?


```
commit 4dec816cf9404545d9436beee4adb02f18de07fc
Author: Your Name <mark.baumgarten@gmail.com>
Date:   Thu Jun 1 19:56:56 2023 +0200

    Adding page visibility example

diff --git a/examples/page_visibility_reload/main.py b/examples/page_visibility_reload/main.py
new file mode 100755
index 00000000..6f99179e
--- /dev/null
+++ b/examples/page_visibility_reload/main.py
@@ -0,0 +1,14 @@
+#!/usr/bin/env python3
+from pagevisibility import AutoReloader
+from nicegui import ui
+
+ui.markdown('''
+#### Emit from javascript to python using visibility of page!
+
+Try to change tab or minimize the browser window...
+
+Notice how we can call a python function from javascript using $emit()...
+''')
+autoreloader = AutoReloader('Not needed, just javascript...', on_change=lambda msg: ui.notify(f'The value changed to {msg["args"]}.'))
+
+ui.run(port=1234)
diff --git a/examples/page_visibility_reload/pagevisibility.js b/examples/page_visibility_reload/pagevisibility.js
new file mode 100644
index 00000000..69ca9443
--- /dev/null
+++ b/examples/page_visibility_reload/pagevisibility.js
@@ -0,0 +1,18 @@
+export default {
+  created () {
+    document.addEventListener('visibilitychange', this.handle_visibility, false)
+  },
+  data() {
+    return {
+      value: 0,
+    };
+  },
+  methods: {
+    handle_visibility() {
+      if (document.visibilityState === "visible") {
+        this.value += 1;
+        this.$emit("change", this.value);
+      }
+    }
+  }
+};
diff --git a/examples/page_visibility_reload/pagevisibility.py b/examples/page_visibility_reload/pagevisibility.py
new file mode 100644
index 00000000..0df981d8
--- /dev/null
+++ b/examples/page_visibility_reload/pagevisibility.py
@@ -0,0 +1,14 @@
+from typing import Callable, Optional
+
+from nicegui.dependencies import register_component
+from nicegui.element import Element
+
+register_component('pagevisibility', __file__, 'pagevisibility.js')
+
+
+class AutoReloader(Element):
+
+    def __init__(self, title: str, *, on_change: Optional[Callable] = None) -> None:
+        super().__init__('pagevisibility')
+        self._props['title'] = title
+        self.on('change', on_change)
´´´

**Comment by markbaumgarten** [comment]
I think I have got my problem(s) solved.

I actually had two problems: 

1) chat_messages was potentially "stale"
2) client connection timeout (on phone only)

To solve 1) I did this:

To ensure that the user gets a current view of the chat messages when switching back to the browser tab I have applied the following to my code:

```
....
from pagevisibility import AutoReloader

....other code here....left out....

# in my chat_messages def I added this line(see AutoReloader from my merge request):
AutoReloader('Not needed, just javascript...', on_change=lambda: chat_messages.refresh())
```

To solve 2) I did this:

The other part of my problem was that the client was timing out, so I increased the client timeout as well:

```
await client.connected(timeout=6.0)
```

Thanks for your kind feedback and support!
