### ISSUE TITLE
App ends in restart loop when packed with ProcessPoolExecuter and PyInstaller

### ISSUE THREAD

**Issue by JoJoPuppe** [zauberzeug/nicegui#945]
### Description

I wrote a app with heavy ffmpeg background computation. i used the Progressbar Snipped from examples to track the progress. everything is fine and works as expected. but after packing with pyinstaller i end up in a restart loop.

**system: Mac with M2 chip
nicegui: 1.2.14**

this is the minimal code to replicate.

```python
from nicegui import app, events, ui
from concurrent.futures import ProcessPoolExecutor

pool = ProcessPoolExecutor()

ui.label("hello")

app.on_shutdown(pool.shutdown)
ui.run(reload=False)
```

```python
# pyinstaller script

import os
import subprocess
from pathlib import Path
import nicegui

cmd = [
    'python3',
    '-m', 'PyInstaller',
    'test_nice.py',
    '--name', 'test_07', 
    '--add-data', f'{Path(nicegui.__file__).parent}:nicegui',
]
subprocess.call(cmd)
```

```error
/dist/test_07/test_07 ; exit;
NiceGUI ready to go on http://localhost:8080, and http://10.48.24.114:8080
NiceGUI ready to go on http://localhost:8080, and http://10.48.24.114:8080
ERROR:    [Errno 48] error while attempting to bind on address ('0.0.0.0', 8080): address already in use
NiceGUI ready to go on http://localhost:8080, and http://10.48.24.114:8080
ERROR:    [Errno 48] error while attempting to bind on address ('0.0.0.0', 8080): address already in use
NiceGUI ready to go on http://localhost:8080, and http://10.48.24.114:8080
ERROR:    [Errno 48] error while attempting to bind on address ('0.0.0.0', 8080): address already in use
NiceGUI ready to go on http://localhost:8080, and http://10.48.24.114:8080
ERROR:    [Errno 48] error while attempting to bind on address ('0.0.0.0', 8080): address already in use
NiceGUI ready to go on http://localhost:8080, and http://10.48.24.114:8080
```

if i set the native flag i get the ui but cant use any inputs. i think in the background the same problem is happening.

**Comment by JoJoPuppe** [comment]
I tested the same code on my Ubuntu machine.
everything works fine.
Seems to be an issue with the Apple M2 chip and how pyinstaller handles the multiprocessing.
:(

**Comment by CatamountJack** [comment]
I verified the above code is working on Windows as well.

This may be entirely unrelated since it appears to be a Mac-only issue, but as a shot in the dark from StackOverflow...  [https://stackoverflow.com/questions/72551679/pyinstaller-with-concurrent-futures-executing-function-call-on-every-process-sta](https://stackoverflow.com/questions/72551679/pyinstaller-with-concurrent-futures-executing-function-call-on-every-process-sta)

**Comment by JoJoPuppe** [comment]
Thanks for the heads up @CatamountJack 
i read in other issue reports and there was already an issue that got fixed with `multiprocessing.freeze_support()`

but the call might be too late to work for apple chipsets. i modiefied the code like this:

```python
def main():
    pool = ProcessPoolExecutor()

    ui.label("hello")
    ui.input(label="test", placeholder="hellooooo")

    app.on_shutdown(pool.shutdown)
    ui.run(reload=False, native=False)


if __name__ == "__main__":
    multiprocessing.freeze_support()
    main()
```
this works as expected! yay!
but!, when i change *native* to true and build again. it still fixes the spawning of unlimited processes, but i cant use any input fields. as soon as i start typing the window changes focus to the previous window and sends the characters there.

not having native support right know is good enough. but would be nice to have it working in the future.

**Comment by JoJoPuppe** [comment]
it seems to work now with M2 chipset.
i changed the "__main__" guard to:

```python
if __name__ == "__main__":
    freeze_support()
    pool = ProcessPoolExecutor()
    app.add_static_files('/projects', 'projects')
    app.on_shutdown(pool.shutdown)
    ui.run(reload=False, native=False)
```
thanks again for the help. can be closed.
