### ISSUE TITLE
Startup is noticeably slower than webview

### ISSUE THREAD

**Issue by mardukbp** [zauberzeug/nicegui#972]
### Description

Given this minimal app using webview

```python
import webview

webview.create_window('Hello world', html='Hello webview!')

webview.start()
```

and this minimal app using NiceGUI

```python
from nicegui import ui

ui.label('Hello NiceGUI!')

ui.run(window_size=(800, 600))
``` 

the webview app starts in a couple seconds, whereas with NiceGUI it takes around four seconds to get the message "NiceGUI ready to go on http://localhost:8000" and then a couple seconds to see a window.

This noticeable lag is not expected for such a simple desktop app.

This is on Windows 10 64-bit using Python 3.8.10 64-bit, nicegui 1.2.15 and pywebview 4.1.

**Comment by rodja** [comment]
Well... we have not yet done a lot of startup-time optimizations. There may be some hidden gems. Would you like to help us further with the performance investigation/improvements? In general it does not surprise me that starting a webview with static html is faster than starting a webserver, generating html/js and loading it. But profiling could uncover possible ways to improve it.

**Comment by mardukbp** [comment]
> In general it does not surprise me that starting a webview with static html is faster than starting a webserver, generating html/js and loading it.

I did an experiment with a Django project and webview. First Django is executed in a background thread and meanwhile webview creates the window. The startup time is a couple seconds. And I am using JS libraries to alter the rendered HTML in-place, not static HTML.

I did not take a look at the code of NiceGUI, but if this is not how it starts, this could be an easy way to improve the startup time.

**Comment by rodja** [comment]
Window creation is already done in a separate process. As you wrote Django takes a couple of seconds. Same with FastAPI/NiceGUI. I suggest you use a profiler to find out where the time is spend...

**Comment by rodja** [comment]
@mardukbp I'll close the issue for now. That does not mean we are not keen to improve startup performance. But I think it's better suited as a vague "Feature Request" or a concrete pull request which shows a way to improve startup performance.

**Comment by mardukbp** [comment]
I did some profiling with viztracer on Fedora 38 64-bit with 6 cores, 32 GB of RAM and an SSD.

### Importing Matplotlib

```
MATPLOTLIB=true viztracer --min_duration 10ms --log_async main.py
```

![image](https://github.com/zauberzeug/nicegui/assets/1140106/c399e443-0ff1-44c3-9b23-ce19427f1fe7)

It takes around one second until the second process starts.

### Disabling Matplotlib 

```
MATPLOTLIB=false viztracer --min_duration 10ms --log_async main.py
```

![image](https://github.com/zauberzeug/nicegui/assets/1140106/b14bdbe2-186d-421d-a7e7-7856fd5c8e14)

Apparently the second process spends a lot of time sleeping.

I hope this information helps.
