### ISSUE TITLE
Date switching bug/unexpected behaviour

### ISSUE THREAD

**Issue by DavidLeBonk** [zauberzeug/nicegui#976]
### Description

When I set a date in and press get date it works fine
however when I change month/year 
it deselects the day however it retains previous value

Expected behavior:

When month is changed if day does not exist in the new month it rounds down to nearest valid day
if it is available in that month it retains the selected day
and also updates the value

Minimal reproducible code example:
```py
from nicegui import ui

dateTime = ui.date()
ui.button("Get date", on_click=lambda : {ui.notify(dateTime.value)})

ui.run(dark=True)
```

Also reported in discord here:
https://discord.com/channels/1089836369431498784/1113992737419710495

**Comment by falkoschindler** [comment]
Thanks for bringing this up, @DavidLeBonk.
However, I think this is expected behavior. Switching the displayed month does not change the date. Therefore the date value remains unchanged, independent on whether the day would exist in the currently visible month or not.
Differently put: You can't select the day independent of the month and year or vice versa. Only once you click on a new date, the date value is set to the new day, month and year.

See this pure Quasar example for comparison:
```html
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Material+Icons" rel="stylesheet" type="text/css" />
    <link href="https://cdn.jsdelivr.net/npm/quasar@2.12.0/dist/quasar.css" rel="stylesheet" type="text/css" />
  </head>
  <body>
    <div id="q-app">
      <q-date v-model="date"></q-date>
      <p>Selected Date: {{ date }}</p>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/vue@3/dist/vue.global.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/quasar@2.12.0/dist/quasar.umd.js"></script>
    <script>
      const app = Vue.createApp({
        setup() {
          return { date: Vue.ref("2019/02/01") };
        },
      });
      app.use(Quasar);
      app.mount("#q-app");
    </script>
  </body>
</html>
```

Switching the month or year does _not_ change the date.

**Comment by DavidLeBonk** [comment]
ah thank you very much, would it be possible as a user to develop a custom prop that has this change?

**Comment by falkoschindler** [comment]
Fortunately, Quasar's [QDate](https://quasar.dev/vue-components/date) component provides a "navigation" event we can use to update the date value ourselves:

```py
import calendar
from datetime import datetime
from nicegui import ui

def handle_navigation(msg: dict) -> None:
    if date.value is None:
        return
    old_date = datetime.strptime(date.value, '%Y-%m-%d')
    year = int(msg['args']['year'])
    month = int(msg['args']['month'])
    _, max_day = calendar.monthrange(year, month)
    day = min(old_date.day, max_day)
    new_date = datetime(year=year, month=month, day=day)
    date.value = new_date.strftime('%Y-%m-%d')

date = ui.date().on('navigation', handle_navigation)

ui.run()
```
